export const IMMUTABLE_MODULE_MANIFEST = [
  "LOCK_M0_FOUNDATION",
  "LOCK_M1_MENU_INGESTION",
  "LOCK_M2_BUSINESS_RULES",
  "LOCK_M3_INTENT_ENTITY",
  "LOCK_M4_SESSION_MEMORY",
  "LOCK_M5_STATE_MACHINE",
  "LOCK_M6_CART_ENGINE",
  "LOCK_M7_ORDER_ORCHESTRATION",
  "LOCK_M8_RESERVATION_ENGINE",
  "LOCK_M9_POS_BRIDGE",
  "LOCK_M10_CHANNEL_ADAPTERS",
  "LOCK_M11_HUMAN_ESCALATION",
  "LOCK_M12_OBSERVABILITY_SECURITY",
] as const;

export type ImmutableModuleLock = (typeof IMMUTABLE_MODULE_MANIFEST)[number];
