import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const aiAutomation: SystemConfig = {
  name: t5("AutomateAI", "AutomateAI", "AutomateAI", "AutomateAI", "AutomateAI"),
  subtitle: t5("Automatización con IA", "AI Automation", "Automatisation par IA", "KI-Automatisierung", "Automazione con IA"),
  brandColor: "#8b5cf6",
  icon: "🤖",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Main Dashboard", "Tableau Principal", "Hauptübersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Workflows Activos", "Active Workflows", "Workflows Actifs", "Aktive Workflows", "Workflow Attivi"), value: "34", change: "+6", trend: "up" },
        { label: t5("Ejecuciones Hoy", "Executions Today", "Exécutions Aujourd'hui", "Ausführungen Heute", "Esecuzioni Oggi"), value: "1.247", change: "+189", trend: "up" },
        { label: t5("Tasa de Éxito", "Success Rate", "Taux de Réussite", "Erfolgsquote", "Tasso di Successo"), value: "98.7%", change: "+0.3%", trend: "up" },
        { label: t5("Tiempo Ahorrado", "Time Saved", "Temps Économisé", "Eingesparte Zeit", "Tempo Risparmiato"), value: "142h", change: "+18h", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "workflow", label: "Workflow", type: "text" },
          { key: "tipo", label: "Trigger", type: "badge", badgeColors: { "Webhook": "blue", "Cron": "purple", "Evento": "green", "Manual": "gray" } },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Éxito": "green", "Error": "red", "Ejecutando": "blue" } },
        ],
        rows: [
          { actividad: "Sync CRM → Email Marketing", workflow: "Lead Nurturing Auto", tipo: "Webhook", fecha: "2026-03-07", estado: "Éxito" },
          { actividad: "Generación reporte semanal", workflow: "Weekly Report AI", tipo: "Cron", fecha: "2026-03-07", estado: "Ejecutando" },
          { actividad: "Clasificación tickets soporte", workflow: "AI Ticket Router", tipo: "Evento", fecha: "2026-03-07", estado: "Éxito" },
          { actividad: "Backup base de datos", workflow: "DB Backup Nightly", tipo: "Cron", fecha: "2026-03-06", estado: "Éxito" },
          { actividad: "Envío notificaciones push", workflow: "User Alert System", tipo: "Evento", fecha: "2026-03-06", estado: "Error" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...", "Search recent activity...", "Rechercher une activité récente...", "Letzte Aktivität suchen...", "Cerca attività recente..."),
      },
    },
    {
      id: "workflows",
      label: "Workflows",
      icon: "zap",
      kpis: [
        { label: "Total Workflows", value: "56", change: "+8", trend: "up" },
        { label: t5("Activos", "Active", "Actifs", "Aktiv", "Attivi"), value: "34", change: "+6", trend: "up" },
        { label: t5("Ejecuciones/Día", "Executions/Day", "Exécutions/Jour", "Ausführungen/Tag", "Esecuzioni/Giorno"), value: "1.247", change: "+15%", trend: "up" },
        { label: "Error Rate", value: "1.3%", change: "-0.3%", trend: "down" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "text" },
          { key: "descripcion", label: t5("Descripción", "Description", "Description", "Beschreibung", "Descrizione"), type: "text" },
          { key: "trigger", label: "Trigger", type: "badge", badgeColors: { "Webhook": "blue", "Cron": "purple", "Evento": "green", "Manual": "gray" } },
          { key: "ejecuciones", label: t5("Ejecuciones", "Executions", "Exécutions", "Ausführungen", "Esecuzioni"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activo": "green", "Pausado": "yellow", "Borrador": "gray", "Error": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Lead Nurturing Auto", descripcion: "Sync leads CRM → secuencia email", trigger: "Webhook", ejecuciones: "4.521", estado: "Activo" },
          { nombre: "AI Ticket Router", descripcion: "Clasifica y asigna tickets con IA", trigger: "Evento", ejecuciones: "12.340", estado: "Activo" },
          { nombre: "Weekly Report AI", descripcion: "Genera reportes semanales con GPT", trigger: "Cron", ejecuciones: "52", estado: "Activo" },
          { nombre: "DB Backup Nightly", descripcion: "Backup automático de BD cada noche", trigger: "Cron", ejecuciones: "365", estado: "Activo" },
          { nombre: "User Alert System", descripcion: "Notificaciones push según eventos", trigger: "Evento", ejecuciones: "8.900", estado: "Error" },
          { nombre: "Invoice Generator", descripcion: "Genera facturas automáticas mensual", trigger: "Cron", ejecuciones: "0", estado: "Borrador" },
        ],
        searchPlaceholder: t5("Buscar workflow...", "Search workflow...", "Rechercher un workflow...", "Workflow suchen...", "Cerca workflow..."),
      },
      modal: {
        title: t5("Nuevo Workflow", "New Workflow", "Nouveau Workflow", "Neuer Workflow", "Nuovo Workflow"),
        fields: [
          { name: "nombre", label: t5("Nombre del Workflow", "Workflow Name", "Nom du Workflow", "Workflow-Name", "Nome del Workflow"), type: "text", required: true, placeholder: t5("Ej: Lead Nurturing Auto", "E.g.: Lead Nurturing Auto", "Ex : Lead Nurturing Auto", "Z.B.: Lead Nurturing Auto", "Es.: Lead Nurturing Auto") },
          { name: "descripcion", label: t5("Descripción", "Description", "Description", "Beschreibung", "Descrizione"), type: "textarea", required: true, placeholder: t5("¿Qué hace este workflow?", "What does this workflow do?", "Que fait ce workflow ?", "Was macht dieser Workflow?", "Cosa fa questo workflow?") },
          { name: "trigger", label: t5("Tipo de Trigger", "Trigger Type", "Type de Trigger", "Trigger-Typ", "Tipo di Trigger"), type: "select", required: true, options: [
            { value: "webhook", label: "Webhook" },
            { value: "cron", label: t5("Cron (Programado)", "Cron (Scheduled)", "Cron (Programmé)", "Cron (Geplant)", "Cron (Programmato)") },
            { value: "evento", label: t5("Evento", "Event", "Événement", "Ereignis", "Evento") },
            { value: "manual", label: t5("Manual", "Manual", "Manuel", "Manuell", "Manuale") },
          ]},
          { name: "modelo_ia", label: t5("Modelo IA", "AI Model", "Modèle IA", "KI-Modell", "Modello IA"), type: "select", options: [
            { value: "gpt4", label: "GPT-4o" },
            { value: "claude", label: "Claude 3.5 Sonnet" },
            { value: "gemini", label: "Gemini Pro" },
            { value: "ninguno", label: t5("Sin IA", "No AI", "Sans IA", "Ohne KI", "Senza IA") },
          ]},
          { name: "activar", label: t5("Activar inmediatamente", "Activate immediately", "Activer immédiatement", "Sofort aktivieren", "Attivare immediatamente"), type: "checkbox" },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "" },
        { id: "activos", label: t5("Activos", "Active", "Actifs", "Aktiv", "Attivi"), filterField: "estado", filterValue: "Activo" },
        { id: "pausados", label: t5("Pausados", "Paused", "En Pause", "Pausiert", "In Pausa"), filterField: "estado", filterValue: "Pausado" },
        { id: "borradores", label: t5("Borradores", "Drafts", "Brouillons", "Entwürfe", "Bozze"), filterField: "estado", filterValue: "Borrador" },
        { id: "errores", label: t5("Con Errores", "With Errors", "Avec Erreurs", "Mit Fehlern", "Con Errori"), filterField: "estado", filterValue: "Error" },
      ],
    },
    {
      id: "triggers",
      label: "Triggers",
      icon: "bell",
      kpis: [
        { label: "Total Triggers", value: "78", change: "+12", trend: "up" },
        { label: t5("Webhooks Activos", "Active Webhooks", "Webhooks Actifs", "Aktive Webhooks", "Webhook Attivi"), value: "23", change: "+4", trend: "up" },
        { label: "Cron Jobs", value: "18", change: "+2", trend: "up" },
        { label: t5("Disparos/Hora", "Fires/Hour", "Déclenchements/Heure", "Auslösungen/Stunde", "Attivazioni/Ora"), value: "342", change: "+28", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre del Trigger", "Trigger Name", "Nom du Trigger", "Trigger-Name", "Nome del Trigger"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { "Webhook": "blue", "Cron": "purple", "Evento": "green", "Manual": "gray" } },
          { key: "workflow", label: t5("Workflow Asociado", "Associated Workflow", "Workflow Associé", "Zugeordneter Workflow", "Workflow Associato"), type: "text" },
          { key: "frecuencia", label: t5("Frecuencia / Endpoint", "Frequency / Endpoint", "Fréquence / Endpoint", "Frequenz / Endpoint", "Frequenza / Endpoint"), type: "text" },
          { key: "ultimo_disparo", label: t5("Último Disparo", "Last Fired", "Dernier Déclenchement", "Letzter Auslöser", "Ultimo Attivazione"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activo": "green", "Inactivo": "gray", "Error": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Webhook CRM Nuevos Leads", tipo: "Webhook", workflow: "Lead Nurturing Auto", frecuencia: "/api/hooks/crm-lead", ultimo_disparo: "2026-03-07", estado: "Activo" },
          { nombre: "Cron Backup Nocturno", tipo: "Cron", workflow: "DB Backup Nightly", frecuencia: "0 2 * * *", ultimo_disparo: "2026-03-07", estado: "Activo" },
          { nombre: "Evento Ticket Creado", tipo: "Evento", workflow: "AI Ticket Router", frecuencia: "ticket.created", ultimo_disparo: "2026-03-07", estado: "Activo" },
          { nombre: "Cron Reporte Semanal", tipo: "Cron", workflow: "Weekly Report AI", frecuencia: "0 8 * * 1", ultimo_disparo: "2026-03-03", estado: "Activo" },
          { nombre: "Evento Pago Recibido", tipo: "Evento", workflow: "User Alert System", frecuencia: "payment.received", ultimo_disparo: "2026-03-06", estado: "Error" },
        ],
        searchPlaceholder: t5("Buscar trigger...", "Search trigger...", "Rechercher un trigger...", "Trigger suchen...", "Cerca trigger..."),
      },
      modal: {
        title: t5("Nuevo Trigger", "New Trigger", "Nouveau Trigger", "Neuer Trigger", "Nuovo Trigger"),
        fields: [
          { name: "nombre", label: t5("Nombre del Trigger", "Trigger Name", "Nom du Trigger", "Trigger-Name", "Nome del Trigger"), type: "text", required: true, placeholder: t5("Nombre descriptivo", "Descriptive name", "Nom descriptif", "Beschreibender Name", "Nome descrittivo") },
          { name: "tipo", label: t5("Tipo de Trigger", "Trigger Type", "Type de Trigger", "Trigger-Typ", "Tipo di Trigger"), type: "select", required: true, options: [
            { value: "webhook", label: "Webhook" },
            { value: "cron", label: t5("Cron (Programado)", "Cron (Scheduled)", "Cron (Programmé)", "Cron (Geplant)", "Cron (Programmato)") },
            { value: "evento", label: t5("Evento", "Event", "Événement", "Ereignis", "Evento") },
            { value: "manual", label: t5("Manual", "Manual", "Manuel", "Manuell", "Manuale") },
          ]},
          { name: "workflow", label: t5("Workflow Asociado", "Associated Workflow", "Workflow Associé", "Zugeordneter Workflow", "Workflow Associato"), type: "text", required: true, placeholder: t5("Nombre del workflow", "Workflow name", "Nom du workflow", "Workflow-Name", "Nome del workflow") },
          { name: "configuracion", label: t5("Configuración", "Configuration", "Configuration", "Konfiguration", "Configurazione"), type: "textarea", required: true, placeholder: t5("URL del webhook, expresión cron, o nombre del evento...", "Webhook URL, cron expression, or event name...", "URL du webhook, expression cron, ou nom de l'événement...", "Webhook-URL, Cron-Ausdruck oder Ereignisname...", "URL del webhook, espressione cron o nome dell'evento...") },
          { name: "activar", label: t5("Activar inmediatamente", "Activate immediately", "Activer immédiatement", "Sofort aktivieren", "Attivare immediatamente"), type: "checkbox" },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "tipo", filterValue: "" },
        { id: "webhooks", label: "Webhooks", filterField: "tipo", filterValue: "Webhook" },
        { id: "cron", label: "Cron", filterField: "tipo", filterValue: "Cron" },
        { id: "eventos", label: t5("Eventos", "Events", "Événements", "Ereignisse", "Eventi"), filterField: "tipo", filterValue: "Evento" },
        { id: "manuales", label: t5("Manuales", "Manual", "Manuels", "Manuell", "Manuali"), filterField: "tipo", filterValue: "Manual" },
      ],
    },
    {
      id: "agents",
      label: t5("Agentes IA", "AI Agents", "Agents IA", "KI-Agenten", "Agenti IA"),
      icon: "code",
      kpis: [
        { label: t5("Agentes Activos", "Active Agents", "Agents Actifs", "Aktive Agenten", "Agenti Attivi"), value: "8", change: "+2", trend: "up" },
        { label: t5("Tareas Completadas", "Completed Tasks", "Tâches Terminées", "Abgeschlossene Aufgaben", "Attività Completate"), value: "4.567", change: "+342", trend: "up" },
        { label: t5("Precisión Media", "Average Accuracy", "Précision Moyenne", "Durchschnittliche Genauigkeit", "Precisione Media"), value: "96.2%", change: "+1.1%", trend: "up" },
        { label: t5("Tokens Consumidos", "Tokens Consumed", "Tokens Consommés", "Verbrauchte Token", "Token Consumati"), value: "2.4M", change: "+18%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Agente", "Agent", "Agent", "Agent", "Agente"), type: "text" },
          { key: "modelo", label: t5("Modelo IA", "AI Model", "Modèle IA", "KI-Modell", "Modello IA"), type: "badge", badgeColors: { "GPT-4o": "green", "Claude 3.5": "purple", "Gemini Pro": "blue", "Custom": "orange" } },
          { key: "proposito", label: t5("Propósito", "Purpose", "Objectif", "Zweck", "Scopo"), type: "text" },
          { key: "tareas_dia", label: t5("Tareas/Día", "Tasks/Day", "Tâches/Jour", "Aufgaben/Tag", "Attività/Giorno"), type: "text" },
          { key: "precision", label: t5("Precisión", "Accuracy", "Précision", "Genauigkeit", "Precisione"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activo": "green", "Entrenando": "yellow", "Inactivo": "gray", "Error": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Clasificador de Tickets", modelo: "Claude 3.5", proposito: "Clasifica y prioriza tickets de soporte", tareas_dia: 234, precision: "97.8%", estado: "Activo" },
          { nombre: "Generador de Informes", modelo: "GPT-4o", proposito: "Crea informes ejecutivos semanales", tareas_dia: 12, precision: "95.4%", estado: "Activo" },
          { nombre: "Asistente de Ventas", modelo: "GPT-4o", proposito: "Responde consultas de pre-venta", tareas_dia: 89, precision: "93.1%", estado: "Activo" },
          { nombre: "Extractor de Datos", modelo: "Gemini Pro", proposito: "Extrae datos de PDFs y facturas", tareas_dia: 156, precision: "98.2%", estado: "Activo" },
          { nombre: "Moderador de Contenido", modelo: "Claude 3.5", proposito: "Modera reseñas y comentarios", tareas_dia: 67, precision: "96.5%", estado: "Entrenando" },
        ],
        searchPlaceholder: t5("Buscar agente IA...", "Search AI agent...", "Rechercher un agent IA...", "KI-Agent suchen...", "Cerca agente IA..."),
      },
      modal: {
        title: t5("Nuevo Agente IA", "New AI Agent", "Nouvel Agent IA", "Neuer KI-Agent", "Nuovo Agente IA"),
        fields: [
          { name: "nombre", label: t5("Nombre del Agente", "Agent Name", "Nom de l'Agent", "Agentenname", "Nome dell'Agente"), type: "text", required: true, placeholder: t5("Ej: Clasificador de Tickets", "E.g.: Ticket Classifier", "Ex : Classifieur de Tickets", "Z.B.: Ticket-Klassifizierer", "Es.: Classificatore di Ticket") },
          { name: "modelo", label: t5("Modelo IA", "AI Model", "Modèle IA", "KI-Modell", "Modello IA"), type: "select", required: true, options: [
            { value: "gpt4o", label: "GPT-4o" },
            { value: "claude35", label: "Claude 3.5 Sonnet" },
            { value: "gemini", label: "Gemini Pro" },
            { value: "custom", label: t5("Modelo Custom", "Custom Model", "Modèle Custom", "Benutzerdefiniertes Modell", "Modello Custom") },
          ]},
          { name: "proposito", label: t5("Propósito", "Purpose", "Objectif", "Zweck", "Scopo"), type: "textarea", required: true, placeholder: t5("¿Qué hace este agente?", "What does this agent do?", "Que fait cet agent ?", "Was macht dieser Agent?", "Cosa fa questo agente?") },
          { name: "prompt_sistema", label: t5("Prompt del Sistema", "System Prompt", "Prompt Système", "System-Prompt", "Prompt di Sistema"), type: "textarea", required: true, placeholder: t5("Instrucciones para el agente IA...", "Instructions for the AI agent...", "Instructions pour l'agent IA...", "Anweisungen für den KI-Agenten...", "Istruzioni per l'agente IA...") },
          { name: "temperatura", label: t5("Temperatura (0-1)", "Temperature (0-1)", "Température (0-1)", "Temperatur (0-1)", "Temperatura (0-1)"), type: "number", placeholder: "0.3" },
          { name: "activar", label: t5("Activar inmediatamente", "Activate immediately", "Activer immédiatement", "Sofort aktivieren", "Attivare immediatamente"), type: "checkbox" },
        ],
      },
    },
    {
      id: "integrations",
      label: t5("Integraciones", "Integrations", "Intégrations", "Integrationen", "Integrazioni"),
      icon: "link",
      kpis: [
        { label: t5("Integraciones Activas", "Active Integrations", "Intégrations Actives", "Aktive Integrationen", "Integrazioni Attive"), value: "18", change: "+3", trend: "up" },
        { label: t5("Llamadas API/Día", "API Calls/Day", "Appels API/Jour", "API-Aufrufe/Tag", "Chiamate API/Giorno"), value: "45.600", change: "+12%", trend: "up" },
        { label: t5("Uptime Conexiones", "Connection Uptime", "Disponibilité Connexions", "Verbindungsverfügbarkeit", "Uptime Connessioni"), value: "99.8%", change: "+0.1%", trend: "up" },
        { label: t5("Errores (24h)", "Errors (24h)", "Erreurs (24h)", "Fehler (24h)", "Errori (24h)"), value: "12", change: "-5", trend: "down" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Servicio", "Service", "Service", "Dienst", "Servizio"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { "CRM": "blue", "Email": "green", "Storage": "purple", "Analytics": "orange", "Payment": "indigo" } },
          { key: "llamadas_dia", label: t5("Llamadas/Día", "Calls/Day", "Appels/Jour", "Aufrufe/Tag", "Chiamate/Giorno"), type: "text" },
          { key: "ultima_sync", label: t5("Última Sync", "Last Sync", "Dernière Sync", "Letzte Sync", "Ultima Sync"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Conectado": "green", "Desconectado": "red", "Limitado": "yellow" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Salesforce CRM", tipo: "CRM", llamadas_dia: "12.400", ultima_sync: "2026-03-07", estado: "Conectado" },
          { nombre: "SendGrid Email", tipo: "Email", llamadas_dia: "8.900", ultima_sync: "2026-03-07", estado: "Conectado" },
          { nombre: "Google Cloud Storage", tipo: "Storage", llamadas_dia: "3.400", ultima_sync: "2026-03-07", estado: "Conectado" },
          { nombre: "Mixpanel Analytics", tipo: "Analytics", llamadas_dia: "5.600", ultima_sync: "2026-03-07", estado: "Conectado" },
          { nombre: "Stripe Payments", tipo: "Payment", llamadas_dia: "1.200", ultima_sync: "2026-03-06", estado: "Limitado" },
        ],
        searchPlaceholder: t5("Buscar integración...", "Search integration...", "Rechercher une intégration...", "Integration suchen...", "Cerca integrazione..."),
      },
      modal: {
        title: t5("Nueva Integración", "New Integration", "Nouvelle Intégration", "Neue Integration", "Nuova Integrazione"),
        fields: [
          { name: "servicio", label: t5("Servicio", "Service", "Service", "Dienst", "Servizio"), type: "text", required: true, placeholder: t5("Nombre del servicio", "Service name", "Nom du service", "Name des Dienstes", "Nome del servizio") },
          { name: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "select", required: true, options: [
            { value: "crm", label: "CRM" },
            { value: "email", label: "Email" },
            { value: "storage", label: "Storage" },
            { value: "analytics", label: "Analytics" },
            { value: "payment", label: "Payment" },
          ]},
          { name: "api_key", label: "API Key", type: "text", required: true, placeholder: t5("Clave de API del servicio", "Service API key", "Clé API du service", "API-Schlüssel des Dienstes", "Chiave API del servizio") },
          { name: "endpoint", label: "Endpoint Base", type: "text", placeholder: "https://api.servicio.com/v1" },
          { name: "activar", label: t5("Activar inmediatamente", "Activate immediately", "Activer immédiatement", "Sofort aktivieren", "Attivare immediatamente"), type: "checkbox" },
        ],
      },
    },
    {
      id: "logs",
      label: "Logs",
      icon: "file",
      kpis: [
        { label: t5("Eventos Hoy", "Events Today", "Événements Aujourd'hui", "Ereignisse Heute", "Eventi Oggi"), value: "24.567", change: "+3.200", trend: "up" },
        { label: t5("Errores (24h)", "Errors (24h)", "Erreurs (24h)", "Fehler (24h)", "Errori (24h)"), value: "34", change: "-8", trend: "down" },
        { label: "Warnings (24h)", value: "89", change: "+12", trend: "up" },
        { label: t5("Almacenamiento Logs", "Log Storage", "Stockage Logs", "Log-Speicher", "Spazio Log"), value: "4.2 GB", change: "+0.3 GB", trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "timestamp", label: "Timestamp", type: "text" },
          { key: "workflow", label: "Workflow", type: "text" },
          { key: "nivel", label: t5("Nivel", "Level", "Niveau", "Stufe", "Livello"), type: "badge", badgeColors: { "INFO": "blue", "WARN": "yellow", "ERROR": "red", "DEBUG": "gray" } },
          { key: "mensaje", label: t5("Mensaje", "Message", "Message", "Nachricht", "Messaggio"), type: "text" },
          { key: "duracion", label: t5("Duración", "Duration", "Durée", "Dauer", "Durata"), type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { timestamp: "2026-03-07 14:32:18", workflow: "AI Ticket Router", nivel: "INFO", mensaje: "Ticket #1252 clasificado como Crítico → Agente L2", duracion: "1.2s" },
          { timestamp: "2026-03-07 14:30:05", workflow: "Lead Nurturing Auto", nivel: "INFO", mensaje: "12 leads sincronizados con secuencia email", duracion: "3.4s" },
          { timestamp: "2026-03-07 14:28:42", workflow: "User Alert System", nivel: "ERROR", mensaje: "Timeout al enviar push notification - Firebase 503", duracion: "30.0s" },
          { timestamp: "2026-03-07 14:25:11", workflow: "Weekly Report AI", nivel: "WARN", mensaje: "Token limit cercano (3.800/4.096) en generación", duracion: "12.8s" },
          { timestamp: "2026-03-07 14:20:00", workflow: "DB Backup Nightly", nivel: "INFO", mensaje: "Backup completado: 2.4GB comprimido a 890MB", duracion: "45.2s" },
          { timestamp: "2026-03-07 14:15:33", workflow: "Extractor de Datos", nivel: "DEBUG", mensaje: "PDF procesado: factura_2026_0089.pdf - 23 campos", duracion: "2.1s" },
        ],
        searchPlaceholder: t5("Buscar en logs...", "Search logs...", "Rechercher dans les logs...", "In Logs suchen...", "Cerca nei log..."),
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Plataformas de Automatización", "Automation Platforms", "Plateformes d'Automatisation", "Automatisierungsplattformen", "Piattaforme di Automazione"),
        icon: "building",
        kpis: [
          { label: t5("Total Plataformas", "Total Platforms", "Total Plateformes", "Plattformen Gesamt", "Piattaforme Totali"), value: "19", change: "+3", trend: "up" },
          { label: t5("Activas", "Active", "Actives", "Aktiv", "Attive"), value: "17", change: "+2", trend: "up" },
          { label: t5("Workflows Totales", "Total Workflows", "Workflows Totaux", "Workflows Gesamt", "Workflow Totali"), value: "890", change: "+67", trend: "up" },
          { label: "MRR", value: "€28.500", change: "+24%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Plataforma", "Platform", "Plateforme", "Plattform", "Piattaforma"), type: "text" },
            { key: "plan", label: "Plan", type: "badge", badgeColors: { "Starter": "gray", "Business": "blue", "Enterprise": "purple" } },
            { key: "workflows", label: "Workflows", type: "text" },
            { key: "ejecuciones_mes", label: t5("Ejecuciones/Mes", "Executions/Month", "Exécutions/Mois", "Ausführungen/Monat", "Esecuzioni/Mese"), type: "text" },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activo": "green", "Trial": "yellow", "Suspendido": "red" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "AutomatizaYA Corp", plan: "Enterprise", workflows: 156, ejecuciones_mes: "245.000", estado: "Activo" },
            { nombre: "FlowMaster España", plan: "Business", workflows: 78, ejecuciones_mes: "89.000", estado: "Activo" },
            { nombre: "DataPipeline Pro", plan: "Business", workflows: 45, ejecuciones_mes: "56.000", estado: "Activo" },
            { nombre: "SmartOps Startup", plan: "Starter", workflows: 12, ejecuciones_mes: "8.900", estado: "Trial" },
            { nombre: "IntegrationHub EU", plan: "Enterprise", workflows: 234, ejecuciones_mes: "412.000", estado: "Activo" },
          ],
          searchPlaceholder: t5("Buscar plataforma...", "Search platform...", "Rechercher une plateforme...", "Plattform suchen...", "Cerca piattaforma..."),
        },
        modal: {
          title: t5("Nueva Plataforma", "New Platform", "Nouvelle Plateforme", "Neue Plattform", "Nuova Piattaforma"),
          fields: [
            { name: "nombre", label: t5("Nombre de la Plataforma", "Platform Name", "Nom de la Plateforme", "Plattformname", "Nome della Piattaforma"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "plan", label: "Plan", type: "select", required: true, options: [
              { value: "starter", label: "Starter" },
              { value: "business", label: "Business" },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "email_admin", label: t5("Email Administrador", "Admin Email", "Email Administrateur", "Admin-E-Mail", "Email Amministratore"), type: "email", required: true, placeholder: "admin@plataforma.com" },
            { name: "max_workflows", label: t5("Máx. Workflows", "Max Workflows", "Max. Workflows", "Max. Workflows", "Max. Workflow"), type: "number", placeholder: "50" },
          ],
        },
      },
    ],
  },
};
