import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const catering: SystemConfig = {
  name: t5("CaterPlan", "CaterPlan", "CaterPlan", "CaterPlan", "CaterPlan"),
  subtitle: t5("Gestión de Catering", "Catering Management", "Gestion de Traiteur", "Catering-Verwaltung", "Gestione Catering"),
  brandColor: "#ca8a04",
  icon: "🍽️",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Übersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Eventos este Mes", "Events This Month", "Événements ce Mois", "Events diesen Monat", "Eventi questo Mese"), value: "34", change: "+6", trend: "up" },
        { label: t5("Ingresos Mensuales", "Monthly Revenue", "Revenus Mensuels", "Monatsumsatz", "Ricavi Mensili"), value: "€92.400", change: "+18.5%", trend: "up" },
        { label: t5("Presupuestos Pendientes", "Pending Quotes", "Devis en Attente", "Ausstehende Angebote", "Preventivi in Attesa"), value: "12", change: "+3", trend: "up" },
        { label: t5("Satisfacción Clientes", "Customer Satisfaction", "Satisfaction Clients", "Kundenzufriedenheit", "Soddisfazione Clienti"), value: "4.8/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Confirmado: "green", "Nuevo presupuesto": "blue", Completado: "purple", Cancelado: "red" } },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
        ],
        rows: [
          { actividad: "Evento confirmado", evento: "Boda García-López", cliente: "Ana García", estado: "Confirmado", fecha: "2026-03-15" },
          { actividad: "Presupuesto enviado", evento: "Gala Corporativa TechCo", cliente: "TechCo S.L.", estado: "Nuevo presupuesto", fecha: "2026-03-07" },
          { actividad: "Evento completado", evento: "Cumpleaños Privado", cliente: "Roberto Díaz", estado: "Completado", fecha: "2026-03-06" },
          { actividad: "Nuevo presupuesto", evento: "Cena Benéfica", cliente: "Fundación Vida", estado: "Nuevo presupuesto", fecha: "2026-03-07" },
          { actividad: "Evento cancelado", evento: "Brunch Empresarial", cliente: "MedCorp", estado: "Cancelado", fecha: "2026-03-04" },
        ],
        searchPlaceholder: t5("Buscar actividad...", "Search activity...", "Rechercher activité...", "Aktivität suchen...", "Cerca attività..."),
      },
    },
    {
      id: "events",
      label: t5("Eventos", "Events", "Événements", "Events", "Eventi"),
      icon: "calendar",
      kpis: [
        { label: t5("Eventos Activos", "Active Events", "Événements Actifs", "Aktive Events", "Eventi Attivi"), value: "18", change: "+4", trend: "up" },
        { label: t5("Próximos 7 Días", "Next 7 Days", "7 Prochains Jours", "Nächste 7 Tage", "Prossimi 7 Giorni"), value: "6", trend: "neutral" },
        { label: t5("Comensales Totales", "Total Guests", "Convives Totaux", "Gäste Gesamt", "Commensali Totali"), value: "2.340", change: "+320", trend: "up" },
        { label: t5("Ingreso Medio/Evento", "Avg Revenue/Event", "Revenu Moyen/Événement", "Durchschn. Umsatz/Event", "Ricavo Medio/Evento"), value: "€2.720", change: "+€180", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { Boda: "purple", Corporativo: "blue", Social: "green", Privado: "yellow" } },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "comensales", label: t5("Comensales", "Guests", "Convives", "Gäste", "Commensali"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Confirmado: "green", Pendiente: "yellow", "En Curso": "blue", Completado: "purple" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Boda García-López", tipo: "Boda", fecha: "2026-03-15", comensales: 180, estado: "Confirmado", acciones: "" },
          { nombre: "Gala Corporativa TechCo", tipo: "Corporativo", fecha: "2026-03-22", comensales: 250, estado: "Pendiente", acciones: "" },
          { nombre: "Fiesta de Graduación", tipo: "Social", fecha: "2026-03-20", comensales: 120, estado: "Confirmado", acciones: "" },
          { nombre: "Cena Aniversario Privada", tipo: "Privado", fecha: "2026-03-12", comensales: 30, estado: "Confirmado", acciones: "" },
          { nombre: "Congreso Médico", tipo: "Corporativo", fecha: "2026-03-25", comensales: 400, estado: "Pendiente", acciones: "" },
          { nombre: "Comunión Martínez", tipo: "Social", fecha: "2026-03-07", comensales: 85, estado: "En Curso", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar evento...", "Search event...", "Rechercher événement...", "Event suchen...", "Cerca evento..."),
      },
      modal: {
        title: t5("Nuevo Evento", "New Event", "Nouvel Événement", "Neues Event", "Nuovo Evento"),
        fields: [
          { name: "nombre", label: t5("Nombre del Evento", "Event Name", "Nom de l'Événement", "Eventname", "Nome dell'Evento"), type: "text", required: true, placeholder: t5("Ej: Boda García-López", "E.g.: García-López Wedding", "Ex : Mariage García-López", "Z.B.: Hochzeit García-López", "Es.: Matrimonio García-López") },
          { name: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "select", required: true, options: [
            { value: "boda", label: t5("Boda", "Wedding", "Mariage", "Hochzeit", "Matrimonio") },
            { value: "corporativo", label: t5("Corporativo", "Corporate", "Corporatif", "Firmenveranstaltung", "Aziendale") },
            { value: "social", label: t5("Social", "Social", "Social", "Sozial", "Sociale") },
            { value: "privado", label: t5("Privado", "Private", "Privé", "Privat", "Privato") },
          ]},
          { name: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora de Inicio", "Start Time", "Heure de Début", "Startzeit", "Ora di Inizio"), type: "time", required: true },
          { name: "comensales", label: t5("Número de Comensales", "Number of Guests", "Nombre de Convives", "Anzahl Gäste", "Numero di Commensali"), type: "number", required: true, placeholder: "0" },
          { name: "ubicacion", label: t5("Ubicación", "Location", "Lieu", "Veranstaltungsort", "Luogo"), type: "text", required: true, placeholder: t5("Dirección o salón", "Address or venue", "Adresse ou salle", "Adresse oder Saal", "Indirizzo o sala") },
          { name: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente", "Customer name", "Nom du client", "Name des Kunden", "Nome del cliente") },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Requisitos especiales...", "Special requirements...", "Exigences spéciales...", "Besondere Anforderungen...", "Requisiti speciali...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "all" },
        { id: "confirmados", label: t5("Confirmados", "Confirmed", "Confirmés", "Bestätigt", "Confermati"), filterField: "estado", filterValue: "Confirmado" },
        { id: "pendientes", label: t5("Pendientes", "Pending", "En Attente", "Ausstehend", "In Attesa"), filterField: "estado", filterValue: "Pendiente" },
        { id: "en_curso", label: t5("En Curso", "In Progress", "En Cours", "Laufend", "In Corso"), filterField: "estado", filterValue: "En Curso" },
        { id: "completados", label: t5("Completados", "Completed", "Terminés", "Abgeschlossen", "Completati"), filterField: "estado", filterValue: "Completado" },
      ],
    },
    {
      id: "menus",
      label: t5("Menús", "Menus", "Menus", "Menüs", "Menu"),
      icon: "book",
      kpis: [
        { label: t5("Menús Activos", "Active Menus", "Menus Actifs", "Aktive Menüs", "Menu Attivi"), value: "28", change: "+3", trend: "up" },
        { label: t5("Más Solicitado", "Most Requested", "Le Plus Demandé", "Am Meisten Nachgefragt", "Più Richiesto"), value: "Gourmet", trend: "neutral" },
        { label: t5("Precio Medio/Persona", "Avg Price/Person", "Prix Moyen/Personne", "Durchschn. Preis/Person", "Prezzo Medio/Persona"), value: "€45", change: "+€3", trend: "up" },
        { label: t5("Opciones Veganas", "Vegan Options", "Options Véganes", "Vegane Optionen", "Opzioni Vegane"), value: "8", change: "+2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Menú", "Menu", "Menu", "Menü", "Menu"), type: "text" },
          { key: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "text" },
          { key: "platos", label: t5("Platos", "Dishes", "Plats", "Gerichte", "Piatti"), type: "text" },
          { key: "precioPersona", label: t5("Precio/Persona", "Price/Person", "Prix/Personne", "Preis/Person", "Prezzo/Persona"), type: "currency" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Borrador: "yellow", Archivado: "gray" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Menú Gourmet Premium", categoria: "Premium", platos: 5, precioPersona: 75, estado: "Activo", acciones: "" },
          { nombre: "Menú Mediterráneo", categoria: "Clásico", platos: 4, precioPersona: 45, estado: "Activo", acciones: "" },
          { nombre: "Menú Vegano Deluxe", categoria: "Vegano", platos: 4, precioPersona: 50, estado: "Activo", acciones: "" },
          { nombre: "Menú Infantil", categoria: "Infantil", platos: 3, precioPersona: 20, estado: "Activo", acciones: "" },
          { nombre: "Menú Cocktail", categoria: "Cocktail", platos: 8, precioPersona: 35, estado: "Borrador", acciones: "" },
          { nombre: "Menú Navideño 2025", categoria: "Temporada", platos: 5, precioPersona: 65, estado: "Archivado", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar menú...", "Search menu...", "Rechercher menu...", "Menü suchen...", "Cerca menu..."),
      },
      modal: {
        title: t5("Crear Menú", "Create Menu", "Créer Menu", "Menü Erstellen", "Crea Menu"),
        fields: [
          { name: "nombre", label: t5("Nombre del Menú", "Menu Name", "Nom du Menu", "Menüname", "Nome del Menu"), type: "text", required: true, placeholder: t5("Ej: Menú Gourmet Premium", "E.g.: Premium Gourmet Menu", "Ex : Menu Gourmet Premium", "Z.B.: Premium Gourmet Menü", "Es.: Menu Gourmet Premium") },
          { name: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "select", required: true, options: [
            { value: "premium", label: "Premium" },
            { value: "clasico", label: t5("Clásico", "Classic", "Classique", "Klassisch", "Classico") },
            { value: "vegano", label: t5("Vegano", "Vegan", "Végane", "Vegan", "Vegano") },
            { value: "infantil", label: t5("Infantil", "Kids", "Enfant", "Kinder", "Bambini") },
            { value: "cocktail", label: "Cocktail" },
            { value: "temporada", label: t5("Temporada", "Seasonal", "Saison", "Saison", "Stagionale") },
          ]},
          { name: "precioPersona", label: t5("Precio por Persona (€)", "Price per Person (€)", "Prix par Personne (€)", "Preis pro Person (€)", "Prezzo per Persona (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "descripcion", label: t5("Descripción", "Description", "Description", "Beschreibung", "Descrizione"), type: "textarea", required: true, placeholder: t5("Entrantes, platos principales, postres...", "Starters, main courses, desserts...", "Entrées, plats principaux, desserts...", "Vorspeisen, Hauptgerichte, Desserts...", "Antipasti, piatti principali, dolci...") },
          { name: "alergenos", label: t5("Alérgenos", "Allergens", "Allergènes", "Allergene", "Allergeni"), type: "text", placeholder: t5("Gluten, lácteos, frutos secos...", "Gluten, dairy, nuts...", "Gluten, produits laitiers, fruits à coque...", "Gluten, Milchprodukte, Nüsse...", "Glutine, latticini, frutta secca...") },
        ],
      },
    },
    {
      id: "quotes",
      label: t5("Presupuestos", "Quotes", "Devis", "Angebote", "Preventivi"),
      icon: "file",
      kpis: [
        { label: t5("Presupuestos Abiertos", "Open Quotes", "Devis Ouverts", "Offene Angebote", "Preventivi Aperti"), value: "12", change: "+3", trend: "up" },
        { label: t5("Tasa de Conversión", "Conversion Rate", "Taux de Conversion", "Konversionsrate", "Tasso di Conversione"), value: "68%", change: "+5%", trend: "up" },
        { label: t5("Valor Medio", "Average Value", "Valeur Moyenne", "Durchschnittswert", "Valore Medio"), value: "€4.850", change: "+€420", trend: "up" },
        { label: t5("Respondidos < 24h", "Replied < 24h", "Répondus < 24h", "Beantwortet < 24h", "Risposti < 24h"), value: "92%", change: "+4%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "codigo", label: t5("Código", "Code", "Code", "Code", "Codice"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "importe", label: t5("Importe", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Enviado: "blue", Aceptado: "green", Rechazado: "red", Borrador: "yellow" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { codigo: "PRE-0421", cliente: "TechCo S.L.", evento: "Gala Corporativa", importe: 18750, estado: "Enviado", acciones: "" },
          { codigo: "PRE-0420", cliente: "Ana García", evento: "Boda García-López", importe: 13500, estado: "Aceptado", acciones: "" },
          { codigo: "PRE-0419", cliente: "Fundación Vida", evento: "Cena Benéfica", importe: 8200, estado: "Borrador", acciones: "" },
          { codigo: "PRE-0418", cliente: "MedCorp", evento: "Congreso Médico", importe: 22000, estado: "Enviado", acciones: "" },
          { codigo: "PRE-0417", cliente: "Familia Martínez", evento: "Comunión", importe: 3400, estado: "Aceptado", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar presupuesto...", "Search quote...", "Rechercher devis...", "Angebot suchen...", "Cerca preventivo..."),
      },
      modal: {
        title: t5("Nuevo Presupuesto", "New Quote", "Nouveau Devis", "Neues Angebot", "Nuovo Preventivo"),
        fields: [
          { name: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text", required: true, placeholder: t5("Nombre o empresa", "Name or company", "Nom ou entreprise", "Name oder Firma", "Nome o azienda") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("cliente@email.com", "customer@email.com", "client@email.com", "kunde@email.com", "cliente@email.com") },
          { name: "evento", label: t5("Tipo de Evento", "Event Type", "Type d'Événement", "Eventtyp", "Tipo di Evento"), type: "select", required: true, options: [
            { value: "boda", label: t5("Boda", "Wedding", "Mariage", "Hochzeit", "Matrimonio") },
            { value: "corporativo", label: t5("Corporativo", "Corporate", "Corporatif", "Firmenveranstaltung", "Aziendale") },
            { value: "social", label: t5("Social", "Social", "Social", "Sozial", "Sociale") },
            { value: "privado", label: t5("Privado", "Private", "Privé", "Privat", "Privato") },
          ]},
          { name: "comensales", label: t5("Comensales Estimados", "Estimated Guests", "Convives Estimés", "Geschätzte Gäste", "Commensali Stimati"), type: "number", required: true, placeholder: "0" },
          { name: "menu", label: t5("Menú Base", "Base Menu", "Menu de Base", "Basismenü", "Menu Base"), type: "select", options: [
            { value: "gourmet", label: t5("Gourmet Premium (€75/p)", "Gourmet Premium (€75/p)", "Gourmet Premium (€75/p)", "Gourmet Premium (€75/P)", "Gourmet Premium (€75/p)") },
            { value: "mediterraneo", label: t5("Mediterráneo (€45/p)", "Mediterranean (€45/p)", "Méditerranéen (€45/p)", "Mediterran (€45/P)", "Mediterraneo (€45/p)") },
            { value: "vegano", label: t5("Vegano Deluxe (€50/p)", "Vegan Deluxe (€50/p)", "Végane Deluxe (€50/p)", "Vegan Deluxe (€50/P)", "Vegano Deluxe (€50/p)") },
            { value: "cocktail", label: "Cocktail (€35/p)" },
          ]},
          { name: "fecha", label: t5("Fecha del Evento", "Event Date", "Date de l'Événement", "Eventdatum", "Data dell'Evento"), type: "date", required: true },
          { name: "notas", label: t5("Requisitos Adicionales", "Additional Requirements", "Exigences Supplémentaires", "Zusätzliche Anforderungen", "Requisiti Aggiuntivi"), type: "textarea", placeholder: t5("Decoración, música, necesidades especiales...", "Decoration, music, special needs...", "Décoration, musique, besoins spéciaux...", "Dekoration, Musik, besondere Bedürfnisse...", "Decorazione, musica, esigenze speciali...") },
        ],
      },
    },
    {
      id: "staff",
      label: t5("Personal", "Staff", "Personnel", "Personal", "Personale"),
      icon: "users",
      kpis: [
        { label: t5("Personal Total", "Total Staff", "Personnel Total", "Personal Gesamt", "Personale Totale"), value: "42", change: "+3", trend: "up" },
        { label: t5("Disponibles Hoy", "Available Today", "Disponibles Aujourd'hui", "Heute Verfügbar", "Disponibili Oggi"), value: "28", trend: "neutral" },
        { label: t5("Eventos Asignados", "Assigned Events", "Événements Assignés", "Zugewiesene Events", "Eventi Assegnati"), value: "18", change: "+4", trend: "up" },
        { label: t5("Horas Extra Mes", "Overtime Hours/Month", "Heures Sup. Mois", "Überstunden Monat", "Ore Extra Mese"), value: "124h", change: "+18h", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "text" },
          { key: "rol", label: t5("Rol", "Role", "Rôle", "Rolle", "Ruolo"), type: "badge", badgeColors: { Chef: "purple", Camarero: "blue", Auxiliar: "green", Coordinador: "orange" } },
          { key: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "text" },
          { key: "eventosAsignados", label: t5("Eventos", "Events", "Événements", "Events", "Eventi"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Disponible: "green", "En Evento": "blue", "Día Libre": "gray", Vacaciones: "yellow" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Chef Mario Rossi", rol: "Chef", telefono: "+34 611 234 567", eventosAsignados: 4, estado: "Disponible", acciones: "" },
          { nombre: "Laura Sánchez", rol: "Coordinador", telefono: "+34 622 345 678", eventosAsignados: 6, estado: "En Evento", acciones: "" },
          { nombre: "Pablo Moreno", rol: "Camarero", telefono: "+34 633 456 789", eventosAsignados: 3, estado: "Disponible", acciones: "" },
          { nombre: "Marta Vidal", rol: "Auxiliar", telefono: "+34 644 567 890", eventosAsignados: 2, estado: "Día Libre", acciones: "" },
          { nombre: "Diego Torres", rol: "Camarero", telefono: "+34 655 678 901", eventosAsignados: 5, estado: "En Evento", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar personal...", "Search staff...", "Rechercher personnel...", "Personal suchen...", "Cerca personale..."),
      },
      modal: {
        title: t5("Agregar Personal", "Add Staff", "Ajouter Personnel", "Personal Hinzufügen", "Aggiungi Personale"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "rol", label: t5("Rol", "Role", "Rôle", "Rolle", "Ruolo"), type: "select", required: true, options: [
            { value: "chef", label: "Chef" },
            { value: "camarero", label: t5("Camarero", "Waiter", "Serveur", "Kellner", "Cameriere") },
            { value: "auxiliar", label: t5("Auxiliar", "Assistant", "Auxiliaire", "Hilfskraft", "Ausiliario") },
            { value: "coordinador", label: t5("Coordinador", "Coordinator", "Coordinateur", "Koordinator", "Coordinatore") },
          ]},
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "experiencia", label: t5("Años de Experiencia", "Years of Experience", "Années d'Expérience", "Jahre Erfahrung", "Anni di Esperienza"), type: "number", placeholder: "0" },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Certificaciones, especialidades...", "Certifications, specialties...", "Certifications, spécialités...", "Zertifizierungen, Spezialgebiete...", "Certificazioni, specialità...") },
        ],
      },
    },
    {
      id: "invoicing",
      label: t5("Facturación", "Billing", "Facturation", "Rechnungsstellung", "Fatturazione"),
      icon: "dollar",
      kpis: [
        { label: t5("Facturado este Mes", "Billed This Month", "Facturé ce Mois", "Diesen Monat Abgerechnet", "Fatturato questo Mese"), value: "€92.400", change: "+18.5%", trend: "up" },
        { label: t5("Pendiente de Cobro", "Pending Collection", "En Attente de Paiement", "Ausstehende Zahlung", "In Attesa di Pagamento"), value: "€24.300", change: "-€3.200", trend: "down" },
        { label: t5("Facturas Emitidas", "Invoices Issued", "Factures Émises", "Ausgestellte Rechnungen", "Fatture Emesse"), value: "28", change: "+5", trend: "up" },
        { label: t5("Cobro Medio", "Average Collection", "Délai Moyen de Paiement", "Durchschn. Zahlungsfrist", "Incasso Medio"), value: t5("14 días", "14 days", "14 jours", "14 Tage", "14 giorni"), change: "-2 días", trend: "down" },
      ],
      table: {
        columns: [
          { key: "factura", label: t5("Factura", "Invoice", "Facture", "Rechnung", "Fattura"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "importe", label: t5("Importe", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Pagada: "green", Pendiente: "yellow", Vencida: "red", Parcial: "orange" } },
        ],
        rows: [
          { factura: "FAC-2041", cliente: "Roberto Díaz", evento: "Cumpleaños Privado", importe: 2800, fecha: "2026-03-06", estado: "Pagada" },
          { factura: "FAC-2040", cliente: "Ana García", evento: "Boda García-López (Anticipo)", importe: 6750, fecha: "2026-03-01", estado: "Pagada" },
          { factura: "FAC-2039", cliente: "Familia Martínez", evento: "Comunión", importe: 3400, fecha: "2026-02-28", estado: "Pendiente" },
          { factura: "FAC-2038", cliente: "Corp. Ibérica", evento: "Cena de Gala", importe: 12500, fecha: "2026-02-20", estado: "Parcial" },
          { factura: "FAC-2037", cliente: "Hotel Paraíso", evento: "Banquete Año Nuevo", importe: 18200, fecha: "2026-01-15", estado: "Vencida" },
        ],
        searchPlaceholder: t5("Buscar factura...", "Search invoice...", "Rechercher facture...", "Rechnung suchen...", "Cerca fattura..."),
      },
      modal: {
        title: t5("Nueva Factura", "New Invoice", "Nouvelle Facture", "Neue Rechnung", "Nuova Fattura"),
        fields: [
          { name: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text", required: true, placeholder: t5("Nombre o empresa", "Name or company", "Nom ou entreprise", "Name oder Firma", "Nome o azienda") },
          { name: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text", required: true, placeholder: t5("Nombre del evento", "Event name", "Nom de l'événement", "Eventname", "Nome dell'evento") },
          { name: "importe", label: t5("Importe (€)", "Amount (€)", "Montant (€)", "Betrag (€)", "Importo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "fecha", label: t5("Fecha de Emisión", "Issue Date", "Date d'Émission", "Ausstellungsdatum", "Data di Emissione"), type: "date", required: true },
          { name: "vencimiento", label: t5("Fecha de Vencimiento", "Due Date", "Date d'Échéance", "Fälligkeitsdatum", "Data di Scadenza"), type: "date", required: true },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Conceptos, condiciones de pago...", "Concepts, payment terms...", "Concepts, conditions de paiement...", "Positionen, Zahlungsbedingungen...", "Voci, condizioni di pagamento...") },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Tenants",
        icon: "building",
        kpis: [
          { label: t5("Empresas Catering", "Catering Companies", "Entreprises Traiteur", "Catering-Unternehmen", "Aziende Catering"), value: "15", change: "+2", trend: "up" },
          { label: t5("Eventos Totales/Mes", "Total Events/Month", "Événements Totaux/Mois", "Events Gesamt/Monat", "Eventi Totali/Mese"), value: "510", change: "+65", trend: "up" },
          { label: t5("Volumen Facturación", "Billing Volume", "Volume Facturation", "Rechnungsvolumen", "Volume Fatturazione"), value: "€1.38M", change: "+22%", trend: "up" },
          { label: t5("MRR Plataforma", "Platform MRR", "MRR Plateforme", "Plattform MRR", "MRR Piattaforma"), value: "€18.750", change: "+€2.500", trend: "up" },
        ],
        table: {
          columns: [
            { key: "empresa", label: t5("Empresa", "Company", "Entreprise", "Unternehmen", "Azienda"), type: "text" },
            { key: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text" },
            { key: "eventosmes", label: t5("Eventos/Mes", "Events/Month", "Événements/Mois", "Events/Monat", "Eventi/Mese"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Básico: "gray", Profesional: "blue", Enterprise: "purple" } },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Suspendido: "red", Trial: "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { empresa: "CaterLux", ciudad: "Madrid", eventosmes: 45, plan: "Enterprise", estado: "Activo", acciones: "" },
            { empresa: "Sabores del Sur", ciudad: "Sevilla", eventosmes: 28, plan: "Profesional", estado: "Activo", acciones: "" },
            { empresa: "Gourmet BCN", ciudad: "Barcelona", eventosmes: 52, plan: "Enterprise", estado: "Activo", acciones: "" },
            { empresa: "Delicias Express", ciudad: "Valencia", eventosmes: 15, plan: "Básico", estado: "Trial", acciones: "" },
            { empresa: "Banquetes Norte", ciudad: "Bilbao", eventosmes: 20, plan: "Profesional", estado: "Suspendido", acciones: "" },
          ],
          searchPlaceholder: t5("Buscar empresa...", "Search company...", "Rechercher entreprise...", "Unternehmen suchen...", "Cerca azienda..."),
        },
        modal: {
          title: t5("Agregar Tenant", "Add Tenant", "Ajouter Tenant", "Tenant Hinzufügen", "Aggiungi Tenant"),
          fields: [
            { name: "nombre", label: t5("Nombre de Empresa", "Company Name", "Nom de l'Entreprise", "Firmenname", "Nome dell'Azienda"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text", required: true, placeholder: t5("Ciudad principal", "Main city", "Ville principale", "Hauptstadt", "Città principale") },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico", "Basic", "Basique", "Basis", "Base") },
              { value: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Professionell", "Professionale") },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "contacto", label: t5("Email de Contacto", "Contact Email", "Email de Contact", "Kontakt-E-Mail", "Email di Contatto"), type: "email", required: true, placeholder: "admin@empresa.com" },
            { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          ],
        },
      },
    ],
  },
};
