import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const cleaningService: SystemConfig = {
  name: "CleanPro",
  subtitle: t5("Servicio de Limpieza", "Cleaning Service", "Service de Nettoyage", "Reinigungsservice", "Servizio di Pulizia"),
  brandColor: "#06b6d4",
  icon: "🧹",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Dashboard", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Reservas del Mes", "Monthly Bookings", "Réservations du Mois", "Buchungen des Monats", "Prenotazioni del Mese"), value: "284", change: "+32", trend: "up" },
        { label: t5("Ingresos del Mes", "Monthly Revenue", "Revenus du Mois", "Monatliche Einnahmen", "Entrate del Mese"), value: "€42,600", change: "+18%", trend: "up" },
        { label: t5("Clientes Activos", "Active Clients", "Clients Actifs", "Aktive Kunden", "Clienti Attivi"), value: "156", change: "+14", trend: "up" },
        { label: t5("Satisfacción", "Satisfaction", "Satisfaction", "Zufriedenheit", "Soddisfazione"), value: "4.8/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Client", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "servicio", label: t5("Servicio", "Service", "Service", "Dienstleistung", "Servizio"), type: "text" },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Completada": "green", "En Progreso": "blue", "Confirmada": "purple", "Nueva": "yellow" } },
        ],
        rows: [
          { actividad: "Limpieza completada", cliente: "Familia Rodríguez", servicio: "Residencial - Semanal", fecha: "2026-03-07", estado: "Completada" },
          { actividad: "Servicio en curso", cliente: "Oficinas TechHub", servicio: "Comercial - Diario", fecha: "2026-03-07", estado: "En Progreso" },
          { actividad: "Nueva reserva", cliente: "Ana María Costa", servicio: "Limpieza Profunda", fecha: "2026-03-07", estado: "Nueva" },
          { actividad: "Reserva confirmada", cliente: "Clínica Salud Plus", servicio: "Comercial - 3x/semana", fecha: "2026-03-06", estado: "Confirmada" },
          { actividad: "Limpieza de mudanza", cliente: "Carlos Herrero", servicio: "Mudanza - Entrada", fecha: "2026-03-06", estado: "Completada" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...", "Search recent activity...", "Rechercher activité récente...", "Letzte Aktivität suchen...", "Cerca attività recente..."),
      },
    },
    {
      id: "bookings",
      label: t5("Reservas", "Bookings", "Réservations", "Buchungen", "Prenotazioni"),
      icon: "calendar",
      kpis: [
        { label: t5("Reservas del Mes", "Monthly Bookings", "Réservations du Mois", "Buchungen des Monats", "Prenotazioni del Mese"), value: "284", change: "+32", trend: "up" },
        { label: t5("Hoy", "Today", "Aujourd'hui", "Heute", "Oggi"), value: "14", change: "+3", trend: "up" },
        { label: t5("Tasa Cancelación", "Cancellation Rate", "Taux d'Annulation", "Stornierungsrate", "Tasso di Cancellazione"), value: "4.2%", change: "-0.8%", trend: "up" },
        { label: t5("Valor Medio", "Average Value", "Valeur Moyenne", "Durchschnittswert", "Valore Medio"), value: "€150", change: "+€8", trend: "up" },
      ],
      table: {
        columns: [
          { key: "referencia", label: t5("Ref.", "Ref.", "Réf.", "Ref.", "Rif."), type: "text" },
          { key: "cliente", label: t5("Cliente", "Client", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "tipo_servicio", label: t5("Tipo Servicio", "Service Type", "Type de Service", "Dienstleistungsart", "Tipo di Servizio"), type: "badge", badgeColors: { "Residencial": "blue", "Comercial": "green", "Profunda": "purple", "Mudanza": "orange" } },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "text" },
          { key: "importe", label: t5("Importe", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Confirmada": "blue", "En Progreso": "yellow", "Completada": "green", "Cancelada": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { referencia: "RES-1042", cliente: "Familia Rodríguez", tipo_servicio: "Residencial", fecha: "2026-03-07", hora: "09:00", importe: 85, estado: "Completada" },
          { referencia: "RES-1043", cliente: "Oficinas TechHub", tipo_servicio: "Comercial", fecha: "2026-03-07", hora: "07:00", importe: 320, estado: "En Progreso" },
          { referencia: "RES-1044", cliente: "Ana María Costa", tipo_servicio: "Profunda", fecha: "2026-03-08", hora: "10:00", importe: 220, estado: "Confirmada" },
          { referencia: "RES-1045", cliente: "Clínica Salud Plus", tipo_servicio: "Comercial", fecha: "2026-03-08", hora: "20:00", importe: 280, estado: "Confirmada" },
          { referencia: "RES-1046", cliente: "Carlos Herrero", tipo_servicio: "Mudanza", fecha: "2026-03-09", hora: "08:00", importe: 350, estado: "Confirmada" },
          { referencia: "RES-1047", cliente: "Laura Prieto", tipo_servicio: "Residencial", fecha: "2026-03-07", hora: "14:00", importe: 95, estado: "Cancelada" },
        ],
        searchPlaceholder: t5("Buscar reservas...", "Search bookings...", "Rechercher des réservations...", "Buchungen suchen...", "Cerca prenotazioni..."),
      },
      modal: {
        title: t5("Nueva Reserva", "New Booking", "Nouvelle Réservation", "Neue Buchung", "Nuova Prenotazione"),
        fields: [
          { name: "cliente", label: t5("Cliente", "Client", "Client", "Kunde", "Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente", "Client name", "Nom du client", "Name des Kunden", "Nome del cliente") },
          { name: "tipo_servicio", label: t5("Tipo de Servicio", "Service Type", "Type de Service", "Dienstleistungsart", "Tipo di Servizio"), type: "select", required: true, options: [
            { value: "residencial", label: t5("Residencial", "Residential", "Résidentiel", "Privat", "Residenziale") },
            { value: "comercial", label: t5("Comercial", "Commercial", "Commercial", "Gewerblich", "Commerciale") },
            { value: "profunda", label: t5("Limpieza Profunda", "Deep Cleaning", "Nettoyage en Profondeur", "Grundreinigung", "Pulizia Profonda") },
            { value: "mudanza", label: t5("Mudanza", "Move-in/Move-out", "Déménagement", "Umzug", "Trasloco") },
          ]},
          { name: "direccion", label: t5("Dirección", "Address", "Adresse", "Adresse", "Indirizzo"), type: "text", required: true, placeholder: t5("Dirección del servicio", "Service address", "Adresse du service", "Adresse der Dienstleistung", "Indirizzo del servizio") },
          { name: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "time", required: true },
          { name: "duracion", label: t5("Duración Estimada (horas)", "Estimated Duration (hours)", "Durée Estimée (heures)", "Geschätzte Dauer (Stunden)", "Durata Stimata (ore)"), type: "number", required: true, placeholder: "3" },
          { name: "personal", label: t5("Personal Necesario", "Staff Required", "Personnel Nécessaire", "Benötigtes Personal", "Personale Necessario"), type: "number", required: true, placeholder: "2" },
          { name: "notas", label: t5("Notas Especiales", "Special Notes", "Notes Spéciales", "Besondere Hinweise", "Note Speciali"), type: "textarea", required: false, placeholder: t5("Instrucciones especiales, acceso, etc.", "Special instructions, access, etc.", "Instructions spéciales, accès, etc.", "Besondere Anweisungen, Zugang, usw.", "Istruzioni speciali, accesso, ecc.") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "" },
        { id: "confirmadas", label: t5("Confirmadas", "Confirmed", "Confirmées", "Bestätigt", "Confermate"), filterField: "estado", filterValue: "Confirmada" },
        { id: "en_progreso", label: t5("En Progreso", "In Progress", "En Cours", "In Bearbeitung", "In Corso"), filterField: "estado", filterValue: "En Progreso" },
        { id: "completadas", label: t5("Completadas", "Completed", "Terminées", "Abgeschlossen", "Completate"), filterField: "estado", filterValue: "Completada" },
        { id: "canceladas", label: t5("Canceladas", "Cancelled", "Annulées", "Storniert", "Cancellate"), filterField: "estado", filterValue: "Cancelada" },
      ],
    },
    {
      id: "staff",
      label: t5("Personal", "Staff", "Personnel", "Personal", "Personale"),
      icon: "users",
      kpis: [
        { label: t5("Total Personal", "Total Staff", "Total Personnel", "Personal Gesamt", "Personale Totale"), value: "42", change: "+4", trend: "up" },
        { label: t5("Disponibles Hoy", "Available Today", "Disponibles Aujourd'hui", "Heute Verfügbar", "Disponibili Oggi"), value: "34", change: "+2", trend: "up" },
        { label: t5("Horas Trabajadas/Mes", "Hours Worked/Month", "Heures Travaillées/Mois", "Arbeitsstunden/Monat", "Ore Lavorate/Mese"), value: "5,040", change: "+320", trend: "up" },
        { label: t5("Rendimiento Medio", "Average Performance", "Performance Moyenne", "Durchschnittliche Leistung", "Rendimento Medio"), value: "4.6/5", change: "+0.2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "avatar" },
          { key: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "text" },
          { key: "especialidad", label: t5("Especialidad", "Specialty", "Spécialité", "Fachgebiet", "Specialità"), type: "text" },
          { key: "zona", label: t5("Zona", "Zone", "Zone", "Zone", "Zona"), type: "text" },
          { key: "servicios_mes", label: t5("Servicios/Mes", "Services/Month", "Services/Mois", "Dienstleistungen/Monat", "Servizi/Mese"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Disponible": "green", "En Servicio": "blue", "Descanso": "yellow", "Baja": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Rosa Delgado", telefono: "+34 612 345 678", especialidad: "Residencial, Profunda", zona: "Madrid Centro", servicios_mes: 28, estado: "Disponible" },
          { nombre: "Patricia Molina", telefono: "+34 623 456 789", especialidad: "Comercial", zona: "Madrid Norte", servicios_mes: 22, estado: "En Servicio" },
          { nombre: "Luisa Fernández", telefono: "+34 634 567 890", especialidad: "Residencial, Mudanza", zona: "Madrid Sur", servicios_mes: 25, estado: "Disponible" },
          { nombre: "Beatriz Sanz", telefono: "+34 645 678 901", especialidad: "Comercial, Profunda", zona: "Madrid Este", servicios_mes: 20, estado: "Descanso" },
          { nombre: "Carmen Iglesias", telefono: "+34 656 789 012", especialidad: "Residencial", zona: "Madrid Centro", servicios_mes: 0, estado: "Baja" },
        ],
        searchPlaceholder: t5("Buscar personal...", "Search staff...", "Rechercher du personnel...", "Personal suchen...", "Cerca personale..."),
      },
      modal: {
        title: t5("Nuevo Empleado", "New Employee", "Nouvel Employé", "Neuer Mitarbeiter", "Nuovo Dipendente"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "empleado@cleanpro.com" },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "especialidad", label: t5("Especialidad", "Specialty", "Spécialité", "Fachgebiet", "Specialità"), type: "select", required: true, options: [
            { value: "residencial", label: t5("Residencial", "Residential", "Résidentiel", "Privat", "Residenziale") },
            { value: "comercial", label: t5("Comercial", "Commercial", "Commercial", "Gewerblich", "Commerciale") },
            { value: "profunda", label: t5("Limpieza Profunda", "Deep Cleaning", "Nettoyage en Profondeur", "Grundreinigung", "Pulizia Profonda") },
            { value: "mudanza", label: t5("Mudanza", "Move-in/Move-out", "Déménagement", "Umzug", "Trasloco") },
          ]},
          { name: "zona", label: t5("Zona Asignada", "Assigned Zone", "Zone Assignée", "Zugewiesene Zone", "Zona Assegnata"), type: "select", required: true, options: [
            { value: "centro", label: "Madrid Centro" },
            { value: "norte", label: "Madrid Norte" },
            { value: "sur", label: "Madrid Sur" },
            { value: "este", label: "Madrid Este" },
            { value: "oeste", label: "Madrid Oeste" },
          ]},
          { name: "fecha_incorporacion", label: t5("Fecha de Incorporación", "Start Date", "Date d'Embauche", "Eintrittsdatum", "Data di Assunzione"), type: "date", required: true },
        ],
      },
    },
    {
      id: "clients",
      label: t5("Clientes", "Clients", "Clients", "Kunden", "Clienti"),
      icon: "heart",
      kpis: [
        { label: t5("Total Clientes", "Total Clients", "Total Clients", "Kunden Gesamt", "Clienti Totali"), value: "156", change: "+14", trend: "up" },
        { label: t5("Recurrentes", "Recurring", "Récurrents", "Wiederkehrend", "Ricorrenti"), value: "98", change: "+8", trend: "up" },
        { label: t5("Nuevos Este Mes", "New This Month", "Nouveaux Ce Mois", "Neu Diesen Monat", "Nuovi Questo Mese"), value: "14", change: "+4", trend: "up" },
        { label: t5("Retención", "Retention", "Rétention", "Bindungsrate", "Fidelizzazione"), value: "89%", change: "+2%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "avatar" },
          { key: "email", label: "Email", type: "text" },
          { key: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { "Particular": "blue", "Empresa": "purple", "Comunidad": "green" } },
          { key: "servicios_total", label: t5("Servicios", "Services", "Services", "Dienstleistungen", "Servizi"), type: "text" },
          { key: "frecuencia", label: t5("Frecuencia", "Frequency", "Fréquence", "Häufigkeit", "Frequenza"), type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Familia Rodríguez", email: "rodriguez@email.com", telefono: "+34 611 222 333", tipo: "Particular", servicios_total: 48, frecuencia: "Semanal" },
          { nombre: "Oficinas TechHub", email: "admin@techhub.es", telefono: "+34 900 111 222", tipo: "Empresa", servicios_total: 120, frecuencia: "Diario" },
          { nombre: "Ana María Costa", email: "a.costa@email.com", telefono: "+34 622 333 444", tipo: "Particular", servicios_total: 6, frecuencia: "Mensual" },
          { nombre: "Clínica Salud Plus", email: "limpieza@saludplus.es", telefono: "+34 900 222 333", tipo: "Empresa", servicios_total: 72, frecuencia: "3x/semana" },
          { nombre: "Comunidad Edificio Sol", email: "admin@edificiosol.es", telefono: "+34 633 444 555", tipo: "Comunidad", servicios_total: 96, frecuencia: "2x/semana" },
          { nombre: "Carlos Herrero", email: "c.herrero@email.com", telefono: "+34 644 555 666", tipo: "Particular", servicios_total: 1, frecuencia: "Puntual" },
        ],
        searchPlaceholder: t5("Buscar clientes...", "Search clients...", "Rechercher des clients...", "Kunden suchen...", "Cerca clienti..."),
      },
      modal: {
        title: t5("Nuevo Cliente", "New Client", "Nouveau Client", "Neuer Kunde", "Nuovo Cliente"),
        fields: [
          { name: "nombre", label: t5("Nombre / Razón Social", "Name / Company", "Nom / Raison Sociale", "Name / Firma", "Nome / Ragione Sociale"), type: "text", required: true, placeholder: t5("Nombre del cliente o empresa", "Client or company name", "Nom du client ou de l'entreprise", "Kunden- oder Firmenname", "Nome del cliente o dell'azienda") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "cliente@email.com" },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "tipo", label: t5("Tipo de Cliente", "Client Type", "Type de Client", "Kundentyp", "Tipo di Cliente"), type: "select", required: true, options: [
            { value: "particular", label: t5("Particular", "Individual", "Particulier", "Privat", "Privato") },
            { value: "empresa", label: t5("Empresa", "Company", "Entreprise", "Unternehmen", "Azienda") },
            { value: "comunidad", label: t5("Comunidad de Vecinos", "Homeowners Association", "Copropriété", "Eigentümergemeinschaft", "Condominio") },
          ]},
          { name: "direccion", label: t5("Dirección", "Address", "Adresse", "Adresse", "Indirizzo"), type: "text", required: true, placeholder: t5("Dirección principal", "Main address", "Adresse principale", "Hauptadresse", "Indirizzo principale") },
          { name: "frecuencia", label: t5("Frecuencia Deseada", "Desired Frequency", "Fréquence Souhaitée", "Gewünschte Häufigkeit", "Frequenza Desiderata"), type: "select", required: false, options: [
            { value: "puntual", label: t5("Puntual", "One-time", "Ponctuel", "Einmalig", "Occasionale") },
            { value: "semanal", label: t5("Semanal", "Weekly", "Hebdomadaire", "Wöchentlich", "Settimanale") },
            { value: "quincenal", label: t5("Quincenal", "Biweekly", "Bimensuel", "Zweiwöchentlich", "Quindicinale") },
            { value: "mensual", label: t5("Mensual", "Monthly", "Mensuel", "Monatlich", "Mensile") },
            { value: "diario", label: t5("Diario", "Daily", "Quotidien", "Täglich", "Giornaliero") },
          ]},
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", required: false, placeholder: t5("Preferencias, acceso, alergias a productos...", "Preferences, access, product allergies...", "Préférences, accès, allergies aux produits...", "Vorlieben, Zugang, Produktallergien...", "Preferenze, accesso, allergie ai prodotti...") },
        ],
      },
    },
    {
      id: "scheduling",
      label: t5("Planificación", "Scheduling", "Planification", "Planung", "Pianificazione"),
      icon: "clock",
      kpis: [
        { label: t5("Servicios Programados/Semana", "Scheduled Services/Week", "Services Programmés/Semaine", "Geplante Dienste/Woche", "Servizi Programmati/Settimana"), value: "78", change: "+6", trend: "up" },
        { label: t5("Ocupación Personal", "Staff Occupancy", "Occupation du Personnel", "Personalauslastung", "Occupazione Personale"), value: "82%", change: "+4%", trend: "up" },
        { label: t5("Rutas Optimizadas", "Optimized Routes", "Itinéraires Optimisés", "Optimierte Routen", "Percorsi Ottimizzati"), value: "12", change: "+1", trend: "up" },
        { label: t5("Horas No Asignadas", "Unassigned Hours", "Heures Non Assignées", "Nicht Zugewiesene Stunden", "Ore Non Assegnate"), value: "48", change: "-12", trend: "up" },
      ],
      table: {
        columns: [
          { key: "empleado", label: t5("Empleado", "Employee", "Employé", "Mitarbeiter", "Dipendente"), type: "text" },
          { key: "dia", label: t5("Día", "Day", "Jour", "Tag", "Giorno"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Client", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "servicio", label: t5("Servicio", "Service", "Service", "Dienstleistung", "Servizio"), type: "text" },
          { key: "horario", label: t5("Horario", "Schedule", "Horaire", "Zeitplan", "Orario"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Asignado": "green", "Pendiente": "yellow", "Conflicto": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { empleado: "Rosa Delgado", dia: "Lunes", cliente: "Familia Rodríguez", servicio: "Residencial", horario: "09:00 - 12:00", estado: "Asignado" },
          { empleado: "Patricia Molina", dia: "Lunes", cliente: "Oficinas TechHub", servicio: "Comercial", horario: "07:00 - 10:00", estado: "Asignado" },
          { empleado: "Luisa Fernández", dia: "Martes", cliente: "Comunidad Edificio Sol", servicio: "Residencial", horario: "08:00 - 11:00", estado: "Asignado" },
          { empleado: "Beatriz Sanz", dia: "Martes", cliente: "Clínica Salud Plus", servicio: "Comercial", horario: "20:00 - 23:00", estado: "Pendiente" },
          { empleado: "Rosa Delgado", dia: "Miércoles", cliente: "Ana María Costa", servicio: "Profunda", horario: "10:00 - 15:00", estado: "Asignado" },
        ],
        searchPlaceholder: t5("Buscar planificación...", "Search schedule...", "Rechercher dans la planification...", "Planung suchen...", "Cerca pianificazione..."),
      },
      modal: {
        title: t5("Nueva Asignación", "New Assignment", "Nouvelle Affectation", "Neue Zuweisung", "Nuova Assegnazione"),
        fields: [
          { name: "empleado", label: t5("Empleado", "Employee", "Employé", "Mitarbeiter", "Dipendente"), type: "select", required: true, options: [
            { value: "rosa", label: "Rosa Delgado" },
            { value: "patricia", label: "Patricia Molina" },
            { value: "luisa", label: "Luisa Fernández" },
            { value: "beatriz", label: "Beatriz Sanz" },
          ]},
          { name: "cliente", label: t5("Cliente", "Client", "Client", "Kunde", "Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente", "Client name", "Nom du client", "Name des Kunden", "Nome del cliente") },
          { name: "servicio", label: t5("Tipo de Servicio", "Service Type", "Type de Service", "Dienstleistungsart", "Tipo di Servizio"), type: "select", required: true, options: [
            { value: "residencial", label: t5("Residencial", "Residential", "Résidentiel", "Privat", "Residenziale") },
            { value: "comercial", label: t5("Comercial", "Commercial", "Commercial", "Gewerblich", "Commerciale") },
            { value: "profunda", label: t5("Limpieza Profunda", "Deep Cleaning", "Nettoyage en Profondeur", "Grundreinigung", "Pulizia Profonda") },
            { value: "mudanza", label: t5("Mudanza", "Move-in/Move-out", "Déménagement", "Umzug", "Trasloco") },
          ]},
          { name: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "hora_inicio", label: t5("Hora Inicio", "Start Time", "Heure de Début", "Startzeit", "Ora di Inizio"), type: "time", required: true },
          { name: "hora_fin", label: t5("Hora Fin", "End Time", "Heure de Fin", "Endzeit", "Ora di Fine"), type: "time", required: true },
        ],
      },
    },
    {
      id: "invoicing",
      label: t5("Facturación", "Invoicing", "Facturation", "Rechnungsstellung", "Fatturazione"),
      icon: "dollar",
      kpis: [
        { label: t5("Facturado Este Mes", "Invoiced This Month", "Facturé Ce Mois", "Diesen Monat Abgerechnet", "Fatturato Questo Mese"), value: "€42,600", change: "+18%", trend: "up" },
        { label: t5("Pendiente de Cobro", "Pending Collection", "En Attente de Paiement", "Ausstehende Zahlungen", "In Attesa di Pagamento"), value: "€5,800", change: "-€1,200", trend: "up" },
        { label: t5("Facturas Emitidas", "Invoices Issued", "Factures Émises", "Ausgestellte Rechnungen", "Fatture Emesse"), value: "156", change: "+18", trend: "up" },
        { label: t5("Ticket Medio", "Average Ticket", "Ticket Moyen", "Durchschnittlicher Bon", "Scontrino Medio"), value: "€273", change: "+€15", trend: "up" },
      ],
      table: {
        columns: [
          { key: "numero", label: t5("Nº Factura", "Invoice No.", "Nº Facture", "Rechnungsnr.", "Nº Fattura"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Client", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "concepto", label: t5("Concepto", "Concept", "Objet", "Beschreibung", "Descrizione"), type: "text" },
          { key: "importe", label: t5("Importe", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Pagada": "green", "Pendiente": "yellow", "Vencida": "red", "Borrador": "gray" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { numero: "FAC-2026-0284", cliente: "Oficinas TechHub", concepto: "Limpieza Comercial - Marzo 2026", importe: 6400, fecha: "2026-03-01", estado: "Pagada" },
          { numero: "FAC-2026-0285", cliente: "Clínica Salud Plus", concepto: "Limpieza Comercial - Marzo 2026", importe: 3360, fecha: "2026-03-01", estado: "Pendiente" },
          { numero: "FAC-2026-0286", cliente: "Comunidad Edificio Sol", concepto: "Limpieza Comunitaria - Marzo 2026", importe: 1920, fecha: "2026-03-01", estado: "Pagada" },
          { numero: "FAC-2026-0287", cliente: "Familia Rodríguez", concepto: "Limpieza Semanal - Marzo 2026", importe: 340, fecha: "2026-03-01", estado: "Pagada" },
          { numero: "FAC-2026-0288", cliente: "Carlos Herrero", concepto: "Limpieza Mudanza - Entrada", importe: 350, fecha: "2026-03-06", estado: "Pendiente" },
          { numero: "FAC-2026-0289", cliente: "Ana María Costa", concepto: "Limpieza Profunda", importe: 220, fecha: "2026-03-08", estado: "Borrador" },
        ],
        searchPlaceholder: t5("Buscar facturas...", "Search invoices...", "Rechercher des factures...", "Rechnungen suchen...", "Cerca fatture..."),
      },
      modal: {
        title: t5("Nueva Factura", "New Invoice", "Nouvelle Facture", "Neue Rechnung", "Nuova Fattura"),
        fields: [
          { name: "cliente", label: t5("Cliente", "Client", "Client", "Kunde", "Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente", "Client name", "Nom du client", "Name des Kunden", "Nome del cliente") },
          { name: "concepto", label: t5("Concepto", "Concept", "Objet", "Beschreibung", "Descrizione"), type: "text", required: true, placeholder: t5("Descripción del servicio", "Service description", "Description du service", "Beschreibung der Dienstleistung", "Descrizione del servizio") },
          { name: "importe", label: t5("Importe (€)", "Amount (€)", "Montant (€)", "Betrag (€)", "Importo (€)"), type: "number", required: true, placeholder: "350" },
          { name: "fecha", label: t5("Fecha de Emisión", "Issue Date", "Date d'Émission", "Ausstellungsdatum", "Data di Emissione"), type: "date", required: true },
          { name: "vencimiento", label: t5("Fecha de Vencimiento", "Due Date", "Date d'Échéance", "Fälligkeitsdatum", "Data di Scadenza"), type: "date", required: true },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", required: false, placeholder: t5("Notas adicionales para la factura...", "Additional notes for the invoice...", "Notes supplémentaires pour la facture...", "Zusätzliche Anmerkungen zur Rechnung...", "Note aggiuntive per la fattura...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "" },
        { id: "pagadas", label: t5("Pagadas", "Paid", "Payées", "Bezahlt", "Pagate"), filterField: "estado", filterValue: "Pagada" },
        { id: "pendientes", label: t5("Pendientes", "Pending", "En Attente", "Ausstehend", "In Sospeso"), filterField: "estado", filterValue: "Pendiente" },
        { id: "vencidas", label: t5("Vencidas", "Overdue", "Échues", "Überfällig", "Scadute"), filterField: "estado", filterValue: "Vencida" },
        { id: "borradores", label: t5("Borradores", "Drafts", "Brouillons", "Entwürfe", "Bozze"), filterField: "estado", filterValue: "Borrador" },
      ],
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Empresas de Limpieza", "Cleaning Companies", "Entreprises de Nettoyage", "Reinigungsunternehmen", "Imprese di Pulizia"),
        icon: "building",
        kpis: [
          { label: t5("Total Empresas", "Total Companies", "Total Entreprises", "Unternehmen Gesamt", "Aziende Totali"), value: "36", change: "+5", trend: "up" },
          { label: t5("Activas", "Active", "Actives", "Aktiv", "Attive"), value: "32", change: "+4", trend: "up" },
          { label: t5("Personal Total", "Total Staff", "Personnel Total", "Personal Gesamt", "Personale Totale"), value: "1,512", change: "+168", trend: "up" },
          { label: "MRR", value: "€16,800", change: "+€2,100", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Empresa", "Company", "Entreprise", "Unternehmen", "Azienda"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { "Premium": "purple", "Profesional": "blue", "Básico": "gray" } },
            { key: "empleados", label: t5("Empleados", "Employees", "Employés", "Mitarbeiter", "Dipendenti"), type: "text" },
            { key: "clientes", label: t5("Clientes", "Clients", "Clients", "Kunden", "Clienti"), type: "text" },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activa": "green", "Suspendida": "red", "Trial": "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "LimpiaHogar España", plan: "Premium", empleados: 180, clientes: 850, estado: "Activa" },
            { nombre: "Brillante Servicios", plan: "Profesional", empleados: 65, clientes: 320, estado: "Activa" },
            { nombre: "CleanMax Pro", plan: "Premium", empleados: 240, clientes: 1100, estado: "Activa" },
            { nombre: "Limpieza Express", plan: "Básico", empleados: 12, clientes: 45, estado: "Trial" },
            { nombre: "EcoClean Solutions", plan: "Profesional", empleados: 42, clientes: 180, estado: "Activa" },
          ],
          searchPlaceholder: t5("Buscar empresas...", "Search companies...", "Rechercher des entreprises...", "Unternehmen suchen...", "Cerca aziende..."),
        },
        modal: {
          title: t5("Nueva Empresa", "New Company", "Nouvelle Entreprise", "Neues Unternehmen", "Nuova Azienda"),
          fields: [
            { name: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "text", required: true, placeholder: t5("Nombre de la empresa", "Company name", "Nom de l'entreprise", "Name des Unternehmens", "Nome dell'azienda") },
            { name: "email_admin", label: "Email Admin", type: "email", required: true, placeholder: "admin@empresa.com" },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico", "Basic", "Basique", "Basis", "Base") },
              { value: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Professionell", "Professionale") },
              { value: "premium", label: "Premium" },
            ]},
            { name: "max_empleados", label: t5("Máx. Empleados", "Max. Employees", "Max. Employés", "Max. Mitarbeiter", "Max. Dipendenti"), type: "number", required: true, placeholder: "50" },
          ],
        },
      },
    ],
  },
};
