import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const clinicOSConfig: SystemConfig = {
  name: t5("ClinicOS", "ClinicOS", "ClinicOS", "ClinicOS", "ClinicOS"),
  subtitle: t5("Suite de Gestión", "Management Suite", "Suite de Gestion", "Verwaltungssuite", "Suite di Gestione"),
  brandColor: "#10b981",
  icon: "💚",
  modules: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: "dashboard",
      kpis: [
        { label: t5("Total Pacientes", "Total Patients", "Total Patients", "Patienten Gesamt", "Pazienti Totali"), value: "2,847", change: "+12.5%", trend: "up" },
        { label: t5("Citas Hoy", "Appointments Today", "Rendez-vous Aujourd'hui", "Termine Heute", "Appuntamenti Oggi"), value: "38", change: "+8.3%", trend: "up" },
        { label: t5("Ingresos (Mes)", "Revenue (MTD)", "Revenus (Mois)", "Umsatz (Monat)", "Ricavi (Mese)"), value: "$48,290", change: "+23.1%", trend: "up" },
        { label: t5("Teleconsultas Activas", "Active Teleconsults", "Téléconsultations Actives", "Aktive Telekonsultationen", "Teleconsulti Attivi"), value: "5", trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "avatar" },
          { key: "time", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora") },
          { key: "type", label: t5("Tipo", "Type", "Type", "Typ", "Tipo") },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore") },
          { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Confirmada": "green", "Pendiente": "yellow", "En Curso": "blue", "Cancelada": "red" } },
        ],
        rows: [
          { patient: "Sarah Anderson", time: "10:30 AM", type: "General Checkup", doctor: "Dr. Martinez", status: "Confirmada" },
          { patient: "James Chen", time: "11:00 AM", type: "Cardiología", doctor: "Dr. Patel", status: "En Curso" },
          { patient: "Maria Lopez", time: "11:30 AM", type: "Dermatología", doctor: "Dr. Kim", status: "Pendiente" },
          { patient: "Robert Wilson", time: "12:00 PM", type: "Teleconsulta", doctor: "Dr. Martinez", status: "Confirmada" },
          { patient: "Ana García", time: "12:30 PM", type: "Pediatría", doctor: "Dr. Reyes", status: "Pendiente" },
        ],
        searchPlaceholder: t5("Buscar citas de hoy...", "Search today's appointments...", "Rechercher rendez-vous du jour...", "Heutige Termine suchen...", "Cerca appuntamenti di oggi..."),
      },
    },
    {
      id: "patients",
      label: t5("Pacientes", "Patients", "Patients", "Patienten", "Pazienti"),
      icon: "users",
      kpis: [
        { label: t5("Total Pacientes", "Total Patients", "Total Patients", "Patienten Gesamt", "Pazienti Totali"), value: "2,847", change: "+156", trend: "up" },
        { label: t5("Nuevos (Mes)", "New (Month)", "Nouveaux (Mois)", "Neu (Monat)", "Nuovi (Mese)"), value: "89", change: "+12%", trend: "up" },
        { label: t5("Activos", "Active", "Actifs", "Aktiv", "Attivi"), value: "2,341", trend: "neutral" },
        { label: t5("Inactivos", "Inactive", "Inactifs", "Inaktiv", "Inattivi"), value: "506", trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "name", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "avatar" },
          { key: "age", label: t5("Edad", "Age", "Âge", "Alter", "Età") },
          { key: "phone", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono") },
          { key: "doctor", label: t5("Doctor Asignado", "Assigned Doctor", "Médecin Assigné", "Zugewiesener Arzt", "Dottore Assegnato") },
          { key: "lastVisit", label: t5("Última Visita", "Last Visit", "Dernière Visite", "Letzter Besuch", "Ultima Visita"), type: "date" },
          { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activo": "green", "Inactivo": "gray", "Nuevo": "blue" } },
        ],
        rows: [
          { name: "Sarah Anderson", age: 34, phone: "+1 555-0123", doctor: "Dr. Martinez", lastVisit: "Mar 5, 2026", status: "Activo" },
          { name: "James Chen", age: 52, phone: "+1 555-0456", doctor: "Dr. Patel", lastVisit: "Mar 4, 2026", status: "Activo" },
          { name: "Maria Lopez", age: 28, phone: "+1 555-0789", doctor: "Dr. Kim", lastVisit: "Mar 3, 2026", status: "Nuevo" },
          { name: "Robert Wilson", age: 67, phone: "+1 555-0321", doctor: "Dr. Martinez", lastVisit: "Feb 28, 2026", status: "Activo" },
          { name: "Emma Davis", age: 41, phone: "+1 555-0654", doctor: "Dr. Reyes", lastVisit: "Feb 25, 2026", status: "Inactivo" },
          { name: "Carlos Mendoza", age: 45, phone: "+1 555-0987", doctor: "Dr. Patel", lastVisit: "Mar 6, 2026", status: "Activo" },
        ],
        searchPlaceholder: t5("Buscar pacientes...", "Search patients...", "Rechercher patients...", "Patienten suchen...", "Cerca pazienti..."),
      },
      modal: {
        title: t5("Nuevo Paciente", "New Patient", "Nouveau Patient", "Neuer Patient", "Nuovo Paziente"),
        fields: [
          { name: "name", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Ej: Juan Pérez", "E.g.: John Smith", "Ex : Jean Dupont", "Z.B.: Max Müller", "Es.: Mario Rossi") },
          { name: "age", label: t5("Edad", "Age", "Âge", "Alter", "Età"), type: "number", required: true },
          { name: "phone", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+1 555-0000" },
          { name: "email", label: "Email", type: "email", placeholder: t5("paciente@email.com", "patient@email.com", "patient@email.com", "patient@email.com", "paziente@email.com") },
          { name: "doctor", label: t5("Doctor Asignado", "Assigned Doctor", "Médecin Assigné", "Zugewiesener Arzt", "Dottore Assegnato"), type: "select", required: true, options: [
            { value: "Dr. Martinez", label: t5("Dr. Martinez - General", "Dr. Martinez - General", "Dr. Martinez - Général", "Dr. Martinez - Allgemein", "Dr. Martinez - Generale") },
            { value: "Dr. Patel", label: t5("Dr. Patel - Cardiología", "Dr. Patel - Cardiology", "Dr. Patel - Cardiologie", "Dr. Patel - Kardiologie", "Dr. Patel - Cardiologia") },
            { value: "Dr. Kim", label: t5("Dr. Kim - Dermatología", "Dr. Kim - Dermatology", "Dr. Kim - Dermatologie", "Dr. Kim - Dermatologie", "Dr. Kim - Dermatologia") },
            { value: "Dr. Reyes", label: t5("Dr. Reyes - Pediatría", "Dr. Reyes - Pediatrics", "Dr. Reyes - Pédiatrie", "Dr. Reyes - Pädiatrie", "Dr. Reyes - Pediatria") },
          ]},
          { name: "blood", label: t5("Tipo de Sangre", "Blood Type", "Groupe Sanguin", "Blutgruppe", "Gruppo Sanguigno"), type: "select", options: [
            { value: "A+", label: "A+" }, { value: "A-", label: "A-" },
            { value: "B+", label: "B+" }, { value: "B-", label: "B-" },
            { value: "O+", label: "O+" }, { value: "O-", label: "O-" },
            { value: "AB+", label: "AB+" }, { value: "AB-", label: "AB-" },
          ]},
          { name: "notes", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Alergias, condiciones previas...", "Allergies, pre-existing conditions...", "Allergies, conditions préexistantes...", "Allergien, Vorerkrankungen...", "Allergie, condizioni pregresse...") },
        ],
      },
    },
    {
      id: "appointments",
      label: t5("Citas", "Appointments", "Rendez-vous", "Termine", "Appuntamenti"),
      icon: "calendar",
      kpis: [
        { label: t5("Citas Hoy", "Appointments Today", "Rendez-vous Aujourd'hui", "Termine Heute", "Appuntamenti Oggi"), value: "38", change: "+5", trend: "up" },
        { label: t5("Esta Semana", "This Week", "Cette Semaine", "Diese Woche", "Questa Settimana"), value: "167", trend: "neutral" },
        { label: t5("Completadas", "Completed", "Terminées", "Abgeschlossen", "Completati"), value: "22", trend: "neutral" },
        { label: "No Shows", value: "3", trend: "down" },
      ],
      table: {
        columns: [
          { key: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "avatar" },
          { key: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "time", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora") },
          { key: "type", label: t5("Tipo", "Type", "Type", "Typ", "Tipo") },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore") },
          { key: "room", label: t5("Sala", "Room", "Salle", "Raum", "Sala") },
          { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Confirmada": "green", "Pendiente": "yellow", "En Curso": "blue", "Completada": "gray", "No Show": "red" } },
        ],
        rows: [
          { patient: "Sarah Anderson", date: "Mar 7, 2026", time: "10:30 AM", type: "Checkup General", doctor: "Dr. Martinez", room: "Sala 3", status: "Confirmada" },
          { patient: "James Chen", date: "Mar 7, 2026", time: "11:00 AM", type: "Cardiología", doctor: "Dr. Patel", room: "Sala 5", status: "En Curso" },
          { patient: "Maria Lopez", date: "Mar 7, 2026", time: "11:30 AM", type: "Dermatología", doctor: "Dr. Kim", room: "Sala 2", status: "Pendiente" },
          { patient: "Robert Wilson", date: "Mar 7, 2026", time: "12:00 PM", type: "Teleconsulta", doctor: "Dr. Martinez", room: "Virtual", status: "Confirmada" },
          { patient: "Ana García", date: "Mar 7, 2026", time: "12:30 PM", type: "Pediatría", doctor: "Dr. Reyes", room: "Sala 1", status: "Pendiente" },
          { patient: "Luis Torres", date: "Mar 7, 2026", time: "09:00 AM", type: "Laboratorio", doctor: "Dr. Patel", room: "Lab 1", status: "Completada" },
          { patient: "Carmen Ruiz", date: "Mar 7, 2026", time: "09:30 AM", type: "General", doctor: "Dr. Martinez", room: "Sala 3", status: "No Show" },
        ],
        searchPlaceholder: t5("Buscar citas...", "Search appointments...", "Rechercher rendez-vous...", "Termine suchen...", "Cerca appuntamenti..."),
      },
      tabs: [
        { id: "all", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "6", filterValue: "all" },
        { id: "confirmed", label: t5("Confirmadas", "Confirmed", "Confirmées", "Bestätigt", "Confermate"), filterField: "6", filterValue: "Confirmada" },
        { id: "pending", label: t5("Pendientes", "Pending", "En Attente", "Ausstehend", "In Attesa"), filterField: "6", filterValue: "Pendiente" },
        { id: "completed", label: t5("Completadas", "Completed", "Terminées", "Abgeschlossen", "Completate"), filterField: "6", filterValue: "Completada" },
      ],
      modal: {
        title: t5("Nueva Cita", "New Appointment", "Nouveau Rendez-vous", "Neuer Termin", "Nuovo Appuntamento"),
        fields: [
          { name: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true, placeholder: t5("Nombre del paciente", "Patient name", "Nom du patient", "Name des Patienten", "Nome del paziente") },
          { name: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "time", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "time", required: true },
          { name: "type", label: t5("Tipo de Consulta", "Consultation Type", "Type de Consultation", "Konsultationstyp", "Tipo di Consulto"), type: "select", required: true, options: [
            { value: "General", label: t5("Checkup General", "General Checkup", "Bilan Général", "Allgemeine Untersuchung", "Visita Generale") },
            { value: "Cardiología", label: t5("Cardiología", "Cardiology", "Cardiologie", "Kardiologie", "Cardiologia") },
            { value: "Dermatología", label: t5("Dermatología", "Dermatology", "Dermatologie", "Dermatologie", "Dermatologia") },
            { value: "Pediatría", label: t5("Pediatría", "Pediatrics", "Pédiatrie", "Pädiatrie", "Pediatria") },
            { value: "Teleconsulta", label: t5("Teleconsulta", "Teleconsult", "Téléconsultation", "Telekonsultation", "Teleconsulto") },
          ]},
          { name: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "select", required: true, options: [
            { value: "Dr. Martinez", label: "Dr. Martinez" },
            { value: "Dr. Patel", label: "Dr. Patel" },
            { value: "Dr. Kim", label: "Dr. Kim" },
            { value: "Dr. Reyes", label: "Dr. Reyes" },
          ]},
          { name: "room", label: t5("Sala", "Room", "Salle", "Raum", "Sala"), type: "select", options: [
            { value: "Sala 1", label: "Sala 1" }, { value: "Sala 2", label: "Sala 2" },
            { value: "Sala 3", label: "Sala 3" }, { value: "Sala 5", label: "Sala 5" },
            { value: "Virtual", label: t5("Virtual (Teleconsulta)", "Virtual (Teleconsult)", "Virtuel (Téléconsultation)", "Virtuell (Telekonsultation)", "Virtuale (Teleconsulto)") },
          ]},
          { name: "reminder", label: t5("Enviar recordatorio SMS", "Send SMS reminder", "Envoyer rappel SMS", "SMS-Erinnerung senden", "Invia promemoria SMS"), type: "checkbox" },
          { name: "notes", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Instrucciones especiales...", "Special instructions...", "Instructions spéciales...", "Besondere Anweisungen...", "Istruzioni speciali...") },
        ],
      },
    },
    {
      id: "medical_records",
      label: t5("Historiales", "Medical Records", "Dossiers Médicaux", "Krankenakten", "Cartelle Cliniche"),
      icon: "clipboard",
      kpis: [
        { label: t5("Total Registros", "Total Records", "Total Dossiers", "Akten Gesamt", "Registri Totali"), value: "12,543", trend: "neutral" },
        { label: t5("Este Mes", "This Month", "Ce Mois", "Diesen Monat", "Questo Mese"), value: "342", change: "+18%", trend: "up" },
        { label: t5("Lab Pendientes", "Pending Lab", "Labo en Attente", "Labor Ausstehend", "Lab in Attesa"), value: "15", trend: "neutral" },
        { label: t5("Seguimientos", "Follow-ups", "Suivis", "Nachkontrollen", "Controlli"), value: "28", trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "avatar" },
          { key: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "type", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { "Consulta": "blue", "Laboratorio": "purple", "Cirugía": "red", "Seguimiento": "green" } },
          { key: "diagnosis", label: t5("Diagnóstico", "Diagnosis", "Diagnostic", "Diagnose", "Diagnosi") },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore") },
        ],
        rows: [
          { patient: "Sarah Anderson", date: "Mar 5, 2026", type: "Consulta", diagnosis: "Hipertensión leve — control", doctor: "Dr. Martinez" },
          { patient: "James Chen", date: "Mar 4, 2026", type: "Laboratorio", diagnosis: "Perfil lipídico — colesterol elevado", doctor: "Dr. Patel" },
          { patient: "Maria Lopez", date: "Mar 3, 2026", type: "Seguimiento", diagnosis: "Dermatitis — mejora notable", doctor: "Dr. Kim" },
          { patient: "Robert Wilson", date: "Feb 28, 2026", type: "Cirugía", diagnosis: "Artroscopia rodilla derecha", doctor: "Dr. Reyes" },
          { patient: "Emma Davis", date: "Feb 25, 2026", type: "Consulta", diagnosis: "Revisión anual — sin novedades", doctor: "Dr. Martinez" },
        ],
        searchPlaceholder: t5("Buscar historiales...", "Search records...", "Rechercher dossiers...", "Akten suchen...", "Cerca cartelle..."),
      },
      modal: {
        title: t5("Nuevo Registro", "New Record", "Nouveau Dossier", "Neuer Eintrag", "Nuovo Registro"),
        fields: [
          { name: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true },
          { name: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "type", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "select", required: true, options: [
            { value: "Consulta", label: t5("Consulta", "Consultation", "Consultation", "Konsultation", "Consulto") }, { value: "Laboratorio", label: t5("Laboratorio", "Laboratory", "Laboratoire", "Labor", "Laboratorio") },
            { value: "Cirugía", label: t5("Cirugía", "Surgery", "Chirurgie", "Chirurgie", "Chirurgia") }, { value: "Seguimiento", label: t5("Seguimiento", "Follow-up", "Suivi", "Nachkontrolle", "Controllo") },
          ]},
          { name: "diagnosis", label: t5("Diagnóstico", "Diagnosis", "Diagnostic", "Diagnose", "Diagnosi"), type: "textarea", required: true, placeholder: t5("Descripción del diagnóstico...", "Diagnosis description...", "Description du diagnostic...", "Beschreibung der Diagnose...", "Descrizione della diagnosi...") },
          { name: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "select", required: true, options: [
            { value: "Dr. Martinez", label: "Dr. Martinez" }, { value: "Dr. Patel", label: "Dr. Patel" },
            { value: "Dr. Kim", label: "Dr. Kim" }, { value: "Dr. Reyes", label: "Dr. Reyes" },
          ]},
        ],
      },
    },
    {
      id: "prescriptions",
      label: t5("Recetas", "Prescriptions", "Ordonnances", "Rezepte", "Ricette"),
      icon: "pill",
      kpis: [
        { label: t5("Recetas Emitidas", "Prescriptions Issued", "Ordonnances Émises", "Ausgestellte Rezepte", "Ricette Emesse"), value: "8,924", trend: "neutral" },
        { label: t5("Este Mes", "This Month", "Ce Mois", "Diesen Monat", "Questo Mese"), value: "234", change: "+9%", trend: "up" },
        { label: t5("Refills Pendientes", "Pending Refills", "Renouvellements en Attente", "Ausstehende Nachfüllungen", "Ricariche in Attesa"), value: "42", trend: "neutral" },
        { label: t5("Por Expirar", "Expiring Soon", "Bientôt Expirées", "Bald Ablaufend", "In Scadenza"), value: "18", change: "-3", trend: "down" },
      ],
      table: {
        columns: [
          { key: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "avatar" },
          { key: "medication", label: t5("Medicamento", "Medication", "Médicament", "Medikament", "Farmaco") },
          { key: "dosage", label: t5("Dosis", "Dosage", "Dosage", "Dosierung", "Dosaggio") },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore") },
          { key: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activa": "green", "Completada": "gray", "Refill": "blue", "Expirada": "red" } },
        ],
        rows: [
          { patient: "Sarah Anderson", medication: "Lisinopril 10mg", dosage: "1x día", doctor: "Dr. Martinez", date: "Mar 5, 2026", status: "Activa" },
          { patient: "James Chen", medication: "Atorvastatina 20mg", dosage: "1x noche", doctor: "Dr. Patel", date: "Mar 4, 2026", status: "Activa" },
          { patient: "Robert Wilson", medication: "Ibuprofeno 400mg", dosage: "3x día", doctor: "Dr. Reyes", date: "Feb 28, 2026", status: "Completada" },
          { patient: "Emma Davis", medication: "Omeprazol 20mg", dosage: "1x mañana", doctor: "Dr. Martinez", date: "Feb 25, 2026", status: "Refill" },
          { patient: "Ana García", medication: "Amoxicilina 500mg", dosage: "3x día x 7 días", doctor: "Dr. Reyes", date: "Mar 6, 2026", status: "Activa" },
          { patient: "Luis Torres", medication: "Metformina 850mg", dosage: "2x día", doctor: "Dr. Patel", date: "Jan 15, 2026", status: "Expirada" },
        ],
        searchPlaceholder: t5("Buscar recetas...", "Search prescriptions...", "Rechercher ordonnances...", "Rezepte suchen...", "Cerca ricette..."),
      },
      modal: {
        title: t5("Nueva Receta", "New Prescription", "Nouvelle Ordonnance", "Neues Rezept", "Nuova Ricetta"),
        fields: [
          { name: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true },
          { name: "medication", label: t5("Medicamento", "Medication", "Médicament", "Medikament", "Farmaco"), type: "text", required: true, placeholder: t5("Ej: Amoxicilina 500mg", "E.g.: Amoxicillin 500mg", "Ex : Amoxicilline 500mg", "Z.B.: Amoxicillin 500mg", "Es.: Amoxicillina 500mg") },
          { name: "dosage", label: t5("Dosis", "Dosage", "Dosage", "Dosierung", "Dosaggio"), type: "text", required: true, placeholder: t5("Ej: 1 tableta cada 8 horas", "E.g.: 1 tablet every 8 hours", "Ex : 1 comprimé toutes les 8 heures", "Z.B.: 1 Tablette alle 8 Stunden", "Es.: 1 compressa ogni 8 ore") },
          { name: "duration", label: t5("Duración", "Duration", "Durée", "Dauer", "Durata"), type: "text", placeholder: t5("Ej: 7 días", "E.g.: 7 days", "Ex : 7 jours", "Z.B.: 7 Tage", "Es.: 7 giorni") },
          { name: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "select", required: true, options: [
            { value: "Dr. Martinez", label: "Dr. Martinez" }, { value: "Dr. Patel", label: "Dr. Patel" },
            { value: "Dr. Kim", label: "Dr. Kim" }, { value: "Dr. Reyes", label: "Dr. Reyes" },
          ]},
          { name: "notes", label: t5("Instrucciones especiales", "Special Instructions", "Instructions Spéciales", "Besondere Anweisungen", "Istruzioni Speciali"), type: "textarea", placeholder: t5("Tomar con alimentos, evitar alcohol...", "Take with food, avoid alcohol...", "Prendre avec de la nourriture, éviter l'alcool...", "Mit Essen einnehmen, Alkohol vermeiden...", "Assumere con cibo, evitare alcol...") },
        ],
      },
    },
    {
      id: "billing",
      label: t5("Facturación", "Billing", "Facturation", "Rechnungsstellung", "Fatturazione"),
      icon: "dollar",
      kpis: [
        { label: t5("Ingresos (Mes)", "Revenue (Month)", "Revenus (Mois)", "Umsatz (Monat)", "Ricavi (Mese)"), value: "$48,290", change: "+23.1%", trend: "up" },
        { label: t5("Pendiente", "Pending", "En Attente", "Ausstehend", "In Attesa"), value: "$12,450", trend: "neutral" },
        { label: t5("Cobros Seguros", "Insurance Claims", "Assurances", "Versicherungsansprüche", "Rimborsi Assicurativi"), value: "$31,200", trend: "neutral" },
        { label: t5("Vencido", "Overdue", "En Retard", "Überfällig", "Scaduto"), value: "$3,890", change: "+$890", trend: "down" },
      ],
      table: {
        columns: [
          { key: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "avatar" },
          { key: "invoice", label: t5("Factura", "Invoice", "Facture", "Rechnung", "Fattura") },
          { key: "service", label: t5("Servicio", "Service", "Service", "Leistung", "Servizio") },
          { key: "amount", label: t5("Monto", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Pagada": "green", "Pendiente": "yellow", "Vencida": "red", "Seguro": "blue" } },
        ],
        rows: [
          { patient: "Sarah Anderson", invoice: "INV-2847", service: "Consulta General", amount: "$150.00", date: "Mar 5, 2026", status: "Pagada" },
          { patient: "James Chen", invoice: "INV-2848", service: "Cardiología + Lab", amount: "$350.00", date: "Mar 4, 2026", status: "Seguro" },
          { patient: "Maria Lopez", invoice: "INV-2849", service: "Dermatología", amount: "$200.00", date: "Mar 3, 2026", status: "Pendiente" },
          { patient: "Robert Wilson", invoice: "INV-2843", service: "Artroscopia", amount: "$2,500.00", date: "Feb 28, 2026", status: "Seguro" },
          { patient: "Emma Davis", invoice: "INV-2830", service: "Revisión Anual", amount: "$180.00", date: "Feb 25, 2026", status: "Vencida" },
        ],
        searchPlaceholder: t5("Buscar facturas...", "Search invoices...", "Rechercher factures...", "Rechnungen suchen...", "Cerca fatture..."),
      },
      tabs: [
        { id: "all", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "5", filterValue: "all" },
        { id: "paid", label: t5("Pagadas", "Paid", "Payées", "Bezahlt", "Pagate"), filterField: "5", filterValue: "Pagada" },
        { id: "pending", label: t5("Pendientes", "Pending", "En Attente", "Ausstehend", "In Attesa"), filterField: "5", filterValue: "Pendiente" },
        { id: "overdue", label: t5("Vencidas", "Overdue", "En Retard", "Überfällig", "Scadute"), filterField: "5", filterValue: "Vencida" },
        { id: "insurance", label: t5("Seguros", "Insurance", "Assurances", "Versicherung", "Assicurazione"), filterField: "5", filterValue: "Seguro" },
      ],
      modal: {
        title: t5("Nueva Factura", "New Invoice", "Nouvelle Facture", "Neue Rechnung", "Nuova Fattura"),
        fields: [
          { name: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true },
          { name: "service", label: t5("Servicio", "Service", "Service", "Leistung", "Servizio"), type: "text", required: true, placeholder: t5("Ej: Consulta General", "E.g.: General Consultation", "Ex : Consultation Générale", "Z.B.: Allgemeine Konsultation", "Es.: Consulto Generale") },
          { name: "amount", label: t5("Monto ($)", "Amount ($)", "Montant ($)", "Betrag ($)", "Importo ($)"), type: "number", required: true, placeholder: "0.00" },
          { name: "insurance", label: t5("Seguro", "Insurance", "Assurance", "Versicherung", "Assicurazione"), type: "select", options: [
            { value: "none", label: t5("Sin seguro", "No insurance", "Sans assurance", "Ohne Versicherung", "Senza assicurazione") }, { value: "aetna", label: "Aetna" },
            { value: "cigna", label: "Cigna" }, { value: "united", label: "United Health" },
          ]},
          { name: "notes", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea" },
        ],
      },
    },
    {
      id: "telemedicine",
      label: t5("Telemedicina", "Telemedicine", "Télémédecine", "Telemedizin", "Telemedicina"),
      icon: "video",
      kpis: [
        { label: t5("Sesiones Activas", "Active Sessions", "Sessions Actives", "Aktive Sitzungen", "Sessioni Attive"), value: "5", trend: "neutral" },
        { label: t5("Programadas Hoy", "Scheduled Today", "Programmées Aujourd'hui", "Heute Geplant", "Programmate Oggi"), value: "12", trend: "neutral" },
        { label: t5("Completadas (Semana)", "Completed (Week)", "Terminées (Semaine)", "Abgeschlossen (Woche)", "Completate (Settimana)"), value: "67", change: "+15%", trend: "up" },
        { label: t5("Duración Promedio", "Average Duration", "Durée Moyenne", "Durchschnittliche Dauer", "Durata Media"), value: t5("18 min", "18 min", "18 min", "18 Min", "18 min"), trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "avatar" },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore") },
          { key: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "time", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora") },
          { key: "duration", label: t5("Duración", "Duration", "Durée", "Dauer", "Durata") },
          { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "En Vivo": "green", "Programada": "blue", "Completada": "gray", "Cancelada": "red" } },
        ],
        rows: [
          { patient: "Robert Wilson", doctor: "Dr. Martinez", date: "Mar 7, 2026", time: "12:00 PM", duration: "15 min", status: "En Vivo" },
          { patient: "Carmen Ruiz", doctor: "Dr. Patel", date: "Mar 7, 2026", time: "01:00 PM", duration: "—", status: "Programada" },
          { patient: "Luis Torres", doctor: "Dr. Kim", date: "Mar 7, 2026", time: "02:30 PM", duration: "—", status: "Programada" },
          { patient: "Sarah Anderson", doctor: "Dr. Martinez", date: "Mar 6, 2026", time: "10:00 AM", duration: "22 min", status: "Completada" },
          { patient: "James Chen", doctor: "Dr. Patel", date: "Mar 6, 2026", time: "11:30 AM", duration: "18 min", status: "Completada" },
        ],
        searchPlaceholder: t5("Buscar teleconsultas...", "Search teleconsults...", "Rechercher téléconsultations...", "Telekonsultationen suchen...", "Cerca teleconsulti..."),
      },
      modal: {
        title: t5("Nueva Teleconsulta", "New Teleconsult", "Nouvelle Téléconsultation", "Neue Telekonsultation", "Nuovo Teleconsulto"),
        fields: [
          { name: "patient", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true },
          { name: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "select", required: true, options: [
            { value: "Dr. Martinez", label: "Dr. Martinez" }, { value: "Dr. Patel", label: "Dr. Patel" },
            { value: "Dr. Kim", label: "Dr. Kim" }, { value: "Dr. Reyes", label: "Dr. Reyes" },
          ]},
          { name: "date", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "time", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "time", required: true },
          { name: "reason", label: t5("Motivo", "Reason", "Motif", "Grund", "Motivo"), type: "textarea", required: true, placeholder: t5("Razón de la consulta...", "Reason for consultation...", "Raison de la consultation...", "Grund der Konsultation...", "Motivo del consulto...") },
          { name: "sendLink", label: t5("Enviar link al paciente por SMS", "Send link to patient via SMS", "Envoyer le lien au patient par SMS", "Link per SMS an Patient senden", "Invia link al paziente via SMS"), type: "checkbox" },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Tenants",
        icon: "building",
        kpis: [
          { label: t5("Total Clínicas", "Total Clinics", "Total Cliniques", "Kliniken Gesamt", "Cliniche Totali"), value: "47", change: "+3", trend: "up" },
          { label: "MRR", value: "$14,100", change: "+8%", trend: "up" },
          { label: t5("Activas", "Active", "Actives", "Aktiv", "Attive"), value: "42", trend: "neutral" },
          { label: "Churn", value: "2.1%", change: "-0.3%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "clinic", label: t5("Clínica", "Clinic", "Clinique", "Klinik", "Clinica"), type: "avatar" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { "Pro": "purple", "Basic": "blue", "Enterprise": "green" } },
            { key: "patients", label: t5("Pacientes", "Patients", "Patients", "Patienten", "Pazienti") },
            { key: "mrr", label: "MRR", type: "currency" },
            { key: "since", label: t5("Desde", "Since", "Depuis", "Seit", "Dal"), type: "date" },
            { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activa": "green", "Trial": "yellow", "Suspendida": "red" } },
          ],
          rows: [
            { clinic: "Sunrise Medical", plan: "Pro", patients: "2,847", mrr: "$299/mo", since: "Jan 2024", status: "Activa" },
            { clinic: "Valley Health", plan: "Enterprise", patients: "5,120", mrr: "$599/mo", since: "Mar 2023", status: "Activa" },
            { clinic: "Central Clinic", plan: "Basic", patients: "890", mrr: "$99/mo", since: "Nov 2024", status: "Activa" },
            { clinic: "Westside Medical", plan: "Pro", patients: "1,456", mrr: "$299/mo", since: "Jun 2024", status: "Activa" },
            { clinic: "Pediatric Care", plan: "Pro", patients: "678", mrr: "$299/mo", since: "Sep 2025", status: "Trial" },
            { clinic: "Dental Plus", plan: "Basic", patients: "234", mrr: "$99/mo", since: "Feb 2026", status: "Trial" },
            { clinic: "OrthoClinic", plan: "Enterprise", patients: "3,200", mrr: "$599/mo", since: "Apr 2023", status: "Activa" },
          ],
          searchPlaceholder: t5("Buscar clínicas...", "Search clinics...", "Rechercher cliniques...", "Kliniken suchen...", "Cerca cliniche..."),
        },
        modal: {
          title: t5("Nueva Clínica", "New Clinic", "Nouvelle Clinique", "Neue Klinik", "Nuova Clinica"),
          fields: [
            { name: "clinic", label: t5("Nombre de la Clínica", "Clinic Name", "Nom de la Clinique", "Klinikname", "Nome della Clinica"), type: "text", required: true },
            { name: "email", label: t5("Email del Admin", "Admin Email", "Email de l'Admin", "Admin-E-Mail", "Email dell'Admin"), type: "email", required: true },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "Basic", label: "Basic — $99/mo" },
              { value: "Pro", label: "Pro — $299/mo" },
              { value: "Enterprise", label: "Enterprise — $599/mo" },
            ]},
            { name: "phone", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel" },
          ],
        },
      },
      {
        id: "platform",
        label: t5("Configuración", "Settings", "Configuration", "Einstellungen", "Configurazione"),
        icon: "settings",
        kpis: [
          { label: "Uptime", value: "99.9%", trend: "up" },
          { label: t5("API Calls (Hoy)", "API Calls (Today)", "Appels API (Aujourd'hui)", "API-Aufrufe (Heute)", "Chiamate API (Oggi)"), value: "24,567", trend: "neutral" },
          { label: t5("Storage Usado", "Storage Used", "Stockage Utilisé", "Genutzter Speicher", "Spazio Utilizzato"), value: "67 GB", trend: "neutral" },
          { label: t5("Usuarios Activos", "Active Users", "Utilisateurs Actifs", "Aktive Nutzer", "Utenti Attivi"), value: "1,234", change: "+12%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "setting", label: t5("Configuración", "Setting", "Configuration", "Einstellung", "Configurazione") },
            { key: "value", label: t5("Valor", "Value", "Valeur", "Wert", "Valore") },
            { key: "updated", label: t5("Última Actualización", "Last Updated", "Dernière Mise à Jour", "Letzte Aktualisierung", "Ultimo Aggiornamento"), type: "date" },
            { key: "status", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activo": "green", "Inactivo": "gray", "Beta": "yellow" } },
          ],
          rows: [
            { setting: "Stripe Payments", value: "Conectado (Live)", updated: "Mar 1, 2026", status: "Activo" },
            { setting: "Twilio SMS", value: "Conectado", updated: "Feb 15, 2026", status: "Activo" },
            { setting: "SendGrid Email", value: "Conectado", updated: "Feb 20, 2026", status: "Activo" },
            { setting: "HL7 FHIR", value: "No conectado", updated: "—", status: "Inactivo" },
            { setting: "2FA Obligatorio", value: "Habilitado", updated: "Mar 5, 2026", status: "Activo" },
            { setting: "Auto-backup", value: "Diario 3:00 AM", updated: "Mar 7, 2026", status: "Activo" },
          ],
          searchPlaceholder: t5("Buscar configuración...", "Search settings...", "Rechercher configuration...", "Einstellungen suchen...", "Cerca configurazione..."),
        },
      },
    ],
  },
};
