import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const dentalClinic: SystemConfig = {
  name: t5("DentalCare", "DentalCare", "DentalCare", "DentalCare", "DentalCare"),
  subtitle: t5("Clínica Dental", "Dental Clinic", "Clinique Dentaire", "Zahnarztpraxis", "Clinica Dentale"),
  brandColor: "#0284c7",
  icon: "🦷",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Übersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Citas Hoy", "Appointments Today", "Rendez-vous Aujourd'hui", "Termine Heute", "Appuntamenti Oggi"), value: "24", change: "+3", trend: "up" },
        { label: t5("Ingresos del Mes", "Monthly Revenue", "Revenus du Mois", "Monatsumsatz", "Ricavi del Mese"), value: "€67.200", change: "+14.2%", trend: "up" },
        { label: t5("Pacientes Activos", "Active Patients", "Patients Actifs", "Aktive Patienten", "Pazienti Attivi"), value: "2.180", change: "+85", trend: "up" },
        { label: t5("Tratamientos en Curso", "Treatments in Progress", "Traitements en Cours", "Laufende Behandlungen", "Trattamenti in Corso"), value: "142", change: "+12", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text" },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Cita completada": "green", "En consulta": "blue", "Nueva cita": "yellow", Cancelación: "red" } },
          { key: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "text" },
        ],
        rows: [
          { actividad: "Limpieza dental completada", paciente: "Carmen López", doctor: "Dr. Martínez", estado: "Cita completada", hora: "09:45" },
          { actividad: "Paciente en consulta", paciente: "Alberto Ruiz", doctor: "Dra. Sánchez", estado: "En consulta", hora: "10:00" },
          { actividad: "Cita programada", paciente: "Elena Torres", doctor: "Dr. García", estado: "Nueva cita", hora: "10:30" },
          { actividad: "Ortodoncia revisión", paciente: "Pablo Moreno", doctor: "Dra. Sánchez", estado: "Cita completada", hora: "09:00" },
          { actividad: "Cita cancelada", paciente: "Rosa Vidal", doctor: "Dr. Martínez", estado: "Cancelación", hora: "11:00" },
        ],
        searchPlaceholder: t5("Buscar actividad...", "Search activity...", "Rechercher activité...", "Aktivität suchen...", "Cerca attività..."),
      },
    },
    {
      id: "patients",
      label: t5("Pacientes", "Patients", "Patients", "Patienten", "Pazienti"),
      icon: "users",
      kpis: [
        { label: t5("Total Pacientes", "Total Patients", "Total Patients", "Patienten Gesamt", "Pazienti Totali"), value: "2.180", change: "+85", trend: "up" },
        { label: t5("Nuevos este Mes", "New This Month", "Nouveaux ce Mois", "Neu diesen Monat", "Nuovi questo Mese"), value: "38", change: "+6", trend: "up" },
        { label: t5("Con Tratamiento Activo", "With Active Treatment", "Avec Traitement Actif", "Mit aktiver Behandlung", "Con Trattamento Attivo"), value: "142", change: "+12", trend: "up" },
        { label: t5("Satisfacción", "Satisfaction", "Satisfaction", "Zufriedenheit", "Soddisfazione"), value: "4.8/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text" },
          { key: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "text" },
          { key: "ultimaVisita", label: t5("Última Visita", "Last Visit", "Dernière Visite", "Letzter Besuch", "Ultima Visita"), type: "date" },
          { key: "tratamiento", label: t5("Tratamiento", "Treatment", "Traitement", "Behandlung", "Trattamento"), type: "text" },
          { key: "proximaCita", label: t5("Próxima Cita", "Next Appointment", "Prochain RDV", "Nächster Termin", "Prossimo Appuntamento"), type: "date" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Carmen López", telefono: "+34 611 234 567", ultimaVisita: "2026-03-07", tratamiento: "Limpieza", proximaCita: "2026-09-07", acciones: "" },
          { nombre: "Alberto Ruiz", telefono: "+34 622 345 678", ultimaVisita: "2026-03-07", tratamiento: "Implante", proximaCita: "2026-03-21", acciones: "" },
          { nombre: "Elena Torres", telefono: "+34 633 456 789", ultimaVisita: "2026-02-15", tratamiento: "Ortodoncia", proximaCita: "2026-03-07", acciones: "" },
          { nombre: "Pablo Moreno", telefono: "+34 644 567 890", ultimaVisita: "2026-03-07", tratamiento: "Ortodoncia", proximaCita: "2026-04-07", acciones: "" },
          { nombre: "Rosa Vidal", telefono: "+34 655 678 901", ultimaVisita: "2026-01-20", tratamiento: "Endodoncia", proximaCita: "2026-03-10", acciones: "" },
          { nombre: "Javier Díaz", telefono: "+34 666 789 012", ultimaVisita: "2025-11-15", tratamiento: "-", proximaCita: "-", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar paciente...", "Search patient...", "Rechercher patient...", "Patient suchen...", "Cerca paziente..."),
      },
      modal: {
        title: t5("Nuevo Paciente", "New Patient", "Nouveau Patient", "Neuer Patient", "Nuovo Paziente"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "fechaNacimiento", label: t5("Fecha de Nacimiento", "Date of Birth", "Date de Naissance", "Geburtsdatum", "Data di Nascita"), type: "date", required: true },
          { name: "alergias", label: t5("Alergias", "Allergies", "Allergies", "Allergien", "Allergie"), type: "textarea", placeholder: t5("Medicamentos, látex, anestesia...", "Medications, latex, anesthesia...", "Médicaments, latex, anesthésie...", "Medikamente, Latex, Anästhesie...", "Farmaci, lattice, anestesia...") },
          { name: "antecedentes", label: t5("Antecedentes Médicos", "Medical History", "Antécédents Médicaux", "Krankengeschichte", "Anamnesi"), type: "textarea", placeholder: t5("Enfermedades, medicación actual...", "Diseases, current medication...", "Maladies, médication actuelle...", "Krankheiten, aktuelle Medikation...", "Malattie, farmaci attuali...") },
        ],
      },
    },
    {
      id: "treatments",
      label: t5("Tratamientos", "Treatments", "Traitements", "Behandlungen", "Trattamenti"),
      icon: "heart",
      kpis: [
        { label: t5("Tratamientos Activos", "Active Treatments", "Traitements Actifs", "Aktive Behandlungen", "Trattamenti Attivi"), value: "142", change: "+12", trend: "up" },
        { label: t5("Más Frecuente", "Most Frequent", "Le Plus Fréquent", "Am Häufigsten", "Più Frequente"), value: t5("Limpieza", "Cleaning", "Nettoyage", "Reinigung", "Pulizia"), trend: "neutral" },
        { label: t5("Valor Medio", "Average Value", "Valeur Moyenne", "Durchschnittswert", "Valore Medio"), value: "€480", change: "+€35", trend: "up" },
        { label: t5("Completados/Mes", "Completed/Month", "Terminés/Mois", "Abgeschlossen/Monat", "Completati/Mese"), value: "98", change: "+8", trend: "up" },
      ],
      table: {
        columns: [
          { key: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { Limpieza: "green", Ortodoncia: "blue", Endodoncia: "yellow", Implante: "purple", "Extracción": "red" } },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "text" },
          { key: "inicio", label: t5("Inicio", "Start", "Début", "Beginn", "Inizio"), type: "date" },
          { key: "progreso", label: t5("Progreso", "Progress", "Progrès", "Fortschritt", "Progresso"), type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { paciente: "Alberto Ruiz", tipo: "Implante", doctor: "Dr. Martínez", inicio: "2026-02-10", progreso: "60%", acciones: "" },
          { paciente: "Elena Torres", tipo: "Ortodoncia", doctor: "Dra. Sánchez", inicio: "2025-09-01", progreso: "45%", acciones: "" },
          { paciente: "Pablo Moreno", tipo: "Ortodoncia", doctor: "Dra. Sánchez", inicio: "2025-06-15", progreso: "70%", acciones: "" },
          { paciente: "Rosa Vidal", tipo: "Endodoncia", doctor: "Dr. García", inicio: "2026-02-20", progreso: "80%", acciones: "" },
          { paciente: "Carmen López", tipo: "Limpieza", doctor: "Dr. Martínez", inicio: "2026-03-07", progreso: "100%", acciones: "" },
          { paciente: "Sofía Navarro", tipo: "Extracción", doctor: "Dr. García", inicio: "2026-03-05", progreso: "100%", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar tratamiento...", "Search treatment...", "Rechercher traitement...", "Behandlung suchen...", "Cerca trattamento..."),
      },
      modal: {
        title: t5("Nuevo Tratamiento", "New Treatment", "Nouveau Traitement", "Neue Behandlung", "Nuovo Trattamento"),
        fields: [
          { name: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true, placeholder: t5("Nombre del paciente", "Patient name", "Nom du patient", "Name des Patienten", "Nome del paziente") },
          { name: "tipo", label: t5("Tipo de Tratamiento", "Treatment Type", "Type de Traitement", "Behandlungstyp", "Tipo di Trattamento"), type: "select", required: true, options: [
            { value: "limpieza", label: t5("Limpieza", "Cleaning", "Nettoyage", "Reinigung", "Pulizia") },
            { value: "ortodoncia", label: t5("Ortodoncia", "Orthodontics", "Orthodontie", "Kieferorthopädie", "Ortodonzia") },
            { value: "endodoncia", label: t5("Endodoncia", "Endodontics", "Endodontie", "Endodontie", "Endodonzia") },
            { value: "implante", label: t5("Implante", "Implant", "Implant", "Implantat", "Impianto") },
            { value: "extraccion", label: t5("Extracción", "Extraction", "Extraction", "Extraktion", "Estrazione") },
          ]},
          { name: "doctor", label: t5("Doctor Asignado", "Assigned Doctor", "Médecin Assigné", "Zugewiesener Arzt", "Dottore Assegnato"), type: "select", required: true, options: [
            { value: "martinez", label: "Dr. Martínez" },
            { value: "sanchez", label: "Dra. Sánchez" },
            { value: "garcia", label: "Dr. García" },
          ]},
          { name: "pieza", label: t5("Pieza Dental", "Tooth Number", "Dent", "Zahn", "Dente"), type: "text", placeholder: t5("Ej: 36, 14-15", "E.g.: 36, 14-15", "Ex : 36, 14-15", "Z.B.: 36, 14-15", "Es.: 36, 14-15") },
          { name: "presupuesto", label: t5("Presupuesto (€)", "Budget (€)", "Budget (€)", "Budget (€)", "Preventivo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "notas", label: t5("Plan de Tratamiento", "Treatment Plan", "Plan de Traitement", "Behandlungsplan", "Piano di Trattamento"), type: "textarea", required: true, placeholder: t5("Fases, sesiones previstas...", "Phases, planned sessions...", "Phases, séances prévues...", "Phasen, geplante Sitzungen...", "Fasi, sessioni previste...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "tipo", filterValue: "all" },
        { id: "limpieza", label: t5("Limpieza", "Cleaning", "Nettoyage", "Reinigung", "Pulizia"), filterField: "tipo", filterValue: "Limpieza" },
        { id: "ortodoncia", label: t5("Ortodoncia", "Orthodontics", "Orthodontie", "Kieferorthopädie", "Ortodonzia"), filterField: "tipo", filterValue: "Ortodoncia" },
        { id: "endodoncia", label: t5("Endodoncia", "Endodontics", "Endodontie", "Endodontie", "Endodonzia"), filterField: "tipo", filterValue: "Endodoncia" },
        { id: "implante", label: t5("Implante", "Implant", "Implant", "Implantat", "Impianto"), filterField: "tipo", filterValue: "Implante" },
        { id: "extraccion", label: t5("Extracción", "Extraction", "Extraction", "Extraktion", "Estrazione"), filterField: "tipo", filterValue: "Extracción" },
      ],
    },
    {
      id: "appointments",
      label: t5("Citas", "Appointments", "Rendez-vous", "Termine", "Appuntamenti"),
      icon: "calendar",
      kpis: [
        { label: t5("Citas Hoy", "Appointments Today", "Rendez-vous Aujourd'hui", "Termine Heute", "Appuntamenti Oggi"), value: "24", change: "+3", trend: "up" },
        { label: t5("Esta Semana", "This Week", "Cette Semaine", "Diese Woche", "Questa Settimana"), value: "112", change: "+14", trend: "up" },
        { label: t5("Cancelaciones", "Cancellations", "Annulations", "Stornierungen", "Cancellazioni"), value: "4.1%", change: "-0.9%", trend: "down" },
        { label: t5("Duración Media", "Average Duration", "Durée Moyenne", "Durchschnittliche Dauer", "Durata Media"), value: t5("35 min", "35 min", "35 min", "35 Min", "35 min"), trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "text" },
          { key: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text" },
          { key: "tratamiento", label: t5("Tratamiento", "Treatment", "Traitement", "Behandlung", "Trattamento"), type: "text" },
          { key: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "text" },
          { key: "duracion", label: t5("Duración", "Duration", "Durée", "Dauer", "Durata"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Programada: "blue", "En Consulta": "green", Completada: "purple", Cancelada: "red" } },
        ],
        rows: [
          { hora: "09:00", paciente: "Pablo Moreno", tratamiento: "Ortodoncia - Revisión", doctor: "Dra. Sánchez", duracion: "30 min", estado: "Completada" },
          { hora: "09:30", paciente: "Carmen López", tratamiento: "Limpieza Dental", doctor: "Dr. Martínez", duracion: "45 min", estado: "Completada" },
          { hora: "10:00", paciente: "Alberto Ruiz", tratamiento: "Implante - Fase 2", doctor: "Dr. García", duracion: "60 min", estado: "En Consulta" },
          { hora: "10:30", paciente: "Elena Torres", tratamiento: "Ortodoncia - Ajuste", doctor: "Dra. Sánchez", duracion: "30 min", estado: "Programada" },
          { hora: "11:00", paciente: "Rosa Vidal", tratamiento: "Endodoncia", doctor: "Dr. Martínez", duracion: "45 min", estado: "Cancelada" },
          { hora: "11:30", paciente: "Marta Gil", tratamiento: "Revisión General", doctor: "Dr. García", duracion: "20 min", estado: "Programada" },
        ],
        searchPlaceholder: t5("Buscar cita...", "Search appointment...", "Rechercher rendez-vous...", "Termin suchen...", "Cerca appuntamento..."),
      },
      modal: {
        title: t5("Nueva Cita", "New Appointment", "Nouveau Rendez-vous", "Neuer Termin", "Nuovo Appuntamento"),
        fields: [
          { name: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true, placeholder: t5("Nombre del paciente", "Patient name", "Nom du patient", "Name des Patienten", "Nome del paziente") },
          { name: "tratamiento", label: t5("Motivo", "Reason", "Motif", "Grund", "Motivo"), type: "select", required: true, options: [
            { value: "revision", label: t5("Revisión General", "General Check-up", "Révision Générale", "Allgemeine Untersuchung", "Revisione Generale") },
            { value: "limpieza", label: t5("Limpieza Dental", "Dental Cleaning", "Nettoyage Dentaire", "Zahnreinigung", "Pulizia Dentale") },
            { value: "ortodoncia", label: t5("Ortodoncia", "Orthodontics", "Orthodontie", "Kieferorthopädie", "Ortodonzia") },
            { value: "endodoncia", label: t5("Endodoncia", "Endodontics", "Endodontie", "Endodontie", "Endodonzia") },
            { value: "implante", label: t5("Implante", "Implant", "Implant", "Implantat", "Impianto") },
            { value: "extraccion", label: t5("Extracción", "Extraction", "Extraction", "Extraktion", "Estrazione") },
            { value: "urgencia", label: t5("Urgencia", "Emergency", "Urgence", "Notfall", "Urgenza") },
          ]},
          { name: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "select", required: true, options: [
            { value: "martinez", label: "Dr. Martínez" },
            { value: "sanchez", label: "Dra. Sánchez" },
            { value: "garcia", label: "Dr. García" },
          ]},
          { name: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "time", required: true },
          { name: "duracion", label: t5("Duración Estimada (min)", "Estimated Duration (min)", "Durée Estimée (min)", "Geschätzte Dauer (Min)", "Durata Stimata (min)"), type: "number", placeholder: "30" },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Observaciones previas...", "Prior observations...", "Observations préalables...", "Vorherige Beobachtungen...", "Osservazioni precedenti...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "all" },
        { id: "programadas", label: t5("Programadas", "Scheduled", "Programmées", "Geplant", "Programmate"), filterField: "estado", filterValue: "Programada" },
        { id: "en_consulta", label: t5("En Consulta", "In Consultation", "En Consultation", "In Behandlung", "In Visita"), filterField: "estado", filterValue: "En Consulta" },
        { id: "completadas", label: t5("Completadas", "Completed", "Terminées", "Abgeschlossen", "Completate"), filterField: "estado", filterValue: "Completada" },
        { id: "canceladas", label: t5("Canceladas", "Cancelled", "Annulées", "Storniert", "Cancellate"), filterField: "estado", filterValue: "Cancelada" },
      ],
    },
    {
      id: "billing",
      label: t5("Facturación", "Billing", "Facturation", "Rechnungsstellung", "Fatturazione"),
      icon: "dollar",
      kpis: [
        { label: t5("Facturado este Mes", "Billed This Month", "Facturé ce Mois", "Diesen Monat Abgerechnet", "Fatturato questo Mese"), value: "€67.200", change: "+14.2%", trend: "up" },
        { label: t5("Pendiente de Cobro", "Pending Collection", "En Attente de Paiement", "Ausstehende Zahlung", "In Attesa di Pagamento"), value: "€12.800", change: "-€2.400", trend: "down" },
        { label: t5("Ticket Medio", "Average Ticket", "Ticket Moyen", "Durchschnittlicher Bon", "Scontrino Medio"), value: "€185", change: "+€12", trend: "up" },
        { label: t5("Cobros del Día", "Collections Today", "Encaissements du Jour", "Tageseinnahmen", "Incassi del Giorno"), value: "€4.350", change: "+€820", trend: "up" },
      ],
      table: {
        columns: [
          { key: "factura", label: t5("Factura", "Invoice", "Facture", "Rechnung", "Fattura"), type: "text" },
          { key: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text" },
          { key: "concepto", label: t5("Concepto", "Concept", "Concept", "Beschreibung", "Descrizione"), type: "text" },
          { key: "importe", label: t5("Importe", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Pagada: "green", Pendiente: "yellow", Vencida: "red", "Pago Parcial": "orange" } },
        ],
        rows: [
          { factura: "FAC-5021", paciente: "Carmen López", concepto: "Limpieza Dental", importe: 80, fecha: "2026-03-07", estado: "Pagada" },
          { factura: "FAC-5020", paciente: "Alberto Ruiz", concepto: "Implante - Fase 2", importe: 1200, fecha: "2026-03-07", estado: "Pendiente" },
          { factura: "FAC-5019", paciente: "Pablo Moreno", concepto: "Ortodoncia - Mensualidad", importe: 150, fecha: "2026-03-07", estado: "Pagada" },
          { factura: "FAC-5018", paciente: "Rosa Vidal", concepto: "Endodoncia", importe: 350, fecha: "2026-02-20", estado: "Pago Parcial" },
          { factura: "FAC-5017", paciente: "Javier Díaz", concepto: "Extracción + Revisión", importe: 180, fecha: "2026-01-15", estado: "Vencida" },
        ],
        searchPlaceholder: t5("Buscar factura...", "Search invoice...", "Rechercher facture...", "Rechnung suchen...", "Cerca fattura..."),
      },
      modal: {
        title: t5("Nueva Factura", "New Invoice", "Nouvelle Facture", "Neue Rechnung", "Nuova Fattura"),
        fields: [
          { name: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true, placeholder: t5("Nombre del paciente", "Patient name", "Nom du patient", "Name des Patienten", "Nome del paziente") },
          { name: "concepto", label: t5("Concepto", "Concept", "Concept", "Beschreibung", "Descrizione"), type: "text", required: true, placeholder: t5("Descripción del tratamiento", "Treatment description", "Description du traitement", "Behandlungsbeschreibung", "Descrizione del trattamento") },
          { name: "importe", label: t5("Importe (€)", "Amount (€)", "Montant (€)", "Betrag (€)", "Importo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "metodo", label: t5("Método de Pago", "Payment Method", "Méthode de Paiement", "Zahlungsmethode", "Metodo di Pagamento"), type: "select", options: [
            { value: "tarjeta", label: t5("Tarjeta de Crédito", "Credit Card", "Carte de Crédit", "Kreditkarte", "Carta di Credito") },
            { value: "efectivo", label: t5("Efectivo", "Cash", "Espèces", "Bargeld", "Contanti") },
            { value: "transferencia", label: t5("Transferencia", "Bank Transfer", "Virement", "Überweisung", "Bonifico") },
            { value: "seguro", label: t5("Seguro Dental", "Dental Insurance", "Assurance Dentaire", "Zahnversicherung", "Assicurazione Dentale") },
          ]},
          { name: "seguro", label: t5("Compañía de Seguro", "Insurance Company", "Compagnie d'Assurance", "Versicherungsgesellschaft", "Compagnia Assicurativa"), type: "text", placeholder: t5("Si aplica...", "If applicable...", "Si applicable...", "Falls zutreffend...", "Se applicabile...") },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Observaciones...", "Observations...", "Observations...", "Bemerkungen...", "Osservazioni...") },
        ],
      },
    },
    {
      id: "records",
      label: t5("Historial Clínico", "Clinical Records", "Dossier Clinique", "Klinische Akte", "Cartella Clinica"),
      icon: "file",
      kpis: [
        { label: t5("Historiales Activos", "Active Records", "Dossiers Actifs", "Aktive Akten", "Cartelle Attive"), value: "2.180", change: "+85", trend: "up" },
        { label: t5("Radiografías Digitales", "Digital X-Rays", "Radiographies Numériques", "Digitale Röntgenbilder", "Radiografie Digitali"), value: "4.560", change: "+120", trend: "up" },
        { label: t5("Actualizados Hoy", "Updated Today", "Mis à Jour Aujourd'hui", "Heute Aktualisiert", "Aggiornati Oggi"), value: "18", trend: "neutral" },
        { label: t5("Consentimientos Firmados", "Signed Consents", "Consentements Signés", "Unterzeichnete Einwilligungen", "Consensi Firmati"), value: "98%", change: "+1%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text" },
          { key: "ultimaActualizacion", label: t5("Última Actualización", "Last Updated", "Dernière Mise à Jour", "Letzte Aktualisierung", "Ultimo Aggiornamento"), type: "date" },
          { key: "radiografias", label: t5("Radiografías", "X-Rays", "Radiographies", "Röntgenbilder", "Radiografie"), type: "text" },
          { key: "tratamientos", label: t5("Tratamientos", "Treatments", "Traitements", "Behandlungen", "Trattamenti"), type: "text" },
          { key: "alergias", label: t5("Alergias", "Allergies", "Allergies", "Allergien", "Allergie"), type: "badge", badgeColors: { Sí: "red", No: "green" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { paciente: "Carmen López", ultimaActualizacion: "2026-03-07", radiografias: 3, tratamientos: 8, alergias: "No", acciones: "" },
          { paciente: "Alberto Ruiz", ultimaActualizacion: "2026-03-07", radiografias: 5, tratamientos: 4, alergias: "Sí", acciones: "" },
          { paciente: "Elena Torres", ultimaActualizacion: "2026-02-15", radiografias: 4, tratamientos: 2, alergias: "No", acciones: "" },
          { paciente: "Pablo Moreno", ultimaActualizacion: "2026-03-07", radiografias: 6, tratamientos: 3, alergias: "No", acciones: "" },
          { paciente: "Rosa Vidal", ultimaActualizacion: "2026-02-20", radiografias: 2, tratamientos: 5, alergias: "Sí", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar historial...", "Search record...", "Rechercher dossier...", "Akte suchen...", "Cerca cartella..."),
      },
      modal: {
        title: t5("Nueva Entrada Clínica", "New Clinical Entry", "Nouvelle Entrée Clinique", "Neuer Klinischer Eintrag", "Nuova Voce Clinica"),
        fields: [
          { name: "paciente", label: t5("Paciente", "Patient", "Patient", "Patient", "Paziente"), type: "text", required: true, placeholder: t5("Nombre del paciente", "Patient name", "Nom du patient", "Name des Patienten", "Nome del paziente") },
          { name: "tipo", label: t5("Tipo de Registro", "Record Type", "Type de Registre", "Eintragstyp", "Tipo di Registro"), type: "select", required: true, options: [
            { value: "consulta", label: t5("Nota de Consulta", "Consultation Note", "Note de Consultation", "Konsultationsnotiz", "Nota di Consulto") },
            { value: "radiografia", label: t5("Radiografía", "X-Ray", "Radiographie", "Röntgenbild", "Radiografia") },
            { value: "tratamiento", label: t5("Registro de Tratamiento", "Treatment Record", "Registre de Traitement", "Behandlungseintrag", "Registro di Trattamento") },
            { value: "consentimiento", label: t5("Consentimiento Informado", "Informed Consent", "Consentement Éclairé", "Einwilligungserklärung", "Consenso Informato") },
          ]},
          { name: "doctor", label: t5("Doctor", "Doctor", "Médecin", "Arzt", "Dottore"), type: "select", required: true, options: [
            { value: "martinez", label: "Dr. Martínez" },
            { value: "sanchez", label: "Dra. Sánchez" },
            { value: "garcia", label: "Dr. García" },
          ]},
          { name: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "notas", label: t5("Descripción Clínica", "Clinical Description", "Description Clinique", "Klinische Beschreibung", "Descrizione Clinica"), type: "textarea", required: true, placeholder: t5("Hallazgos, diagnóstico, procedimiento realizado...", "Findings, diagnosis, procedure performed...", "Résultats, diagnostic, procédure effectuée...", "Befunde, Diagnose, durchgeführter Eingriff...", "Risultati, diagnosi, procedura eseguita...") },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Tenants",
        icon: "building",
        kpis: [
          { label: t5("Clínicas Activas", "Active Clinics", "Cliniques Actives", "Aktive Kliniken", "Cliniche Attive"), value: "22", change: "+3", trend: "up" },
          { label: t5("Pacientes Totales", "Total Patients", "Patients Totaux", "Patienten Gesamt", "Pazienti Totali"), value: "47.960", change: "+1.870", trend: "up" },
          { label: t5("Citas/Día Global", "Global Appts/Day", "RDV/Jour Global", "Globale Termine/Tag", "App/Giorno Globale"), value: "528", change: "+10%", trend: "up" },
          { label: t5("MRR Plataforma", "Platform MRR", "MRR Plateforme", "Plattform MRR", "MRR Piattaforma"), value: "€28.600", change: "+16%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "clinica", label: t5("Clínica", "Clinic", "Clinique", "Klinik", "Clinica"), type: "text" },
            { key: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text" },
            { key: "doctores", label: t5("Doctores", "Doctors", "Médecins", "Ärzte", "Dottori"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Básico: "gray", Profesional: "blue", Enterprise: "purple" } },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Suspendido: "red", Trial: "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { clinica: "DentalCare Madrid Centro", ciudad: "Madrid", doctores: 8, plan: "Enterprise", estado: "Activo", acciones: "" },
            { clinica: "Clínica Dental Sonrisa", ciudad: "Barcelona", doctores: 6, plan: "Enterprise", estado: "Activo", acciones: "" },
            { clinica: "Odontología Avanzada", ciudad: "Valencia", doctores: 4, plan: "Profesional", estado: "Activo", acciones: "" },
            { clinica: "Dental Express", ciudad: "Sevilla", doctores: 2, plan: "Básico", estado: "Trial", acciones: "" },
            { clinica: "Clínica Dr. Navarro", ciudad: "Málaga", doctores: 3, plan: "Profesional", estado: "Suspendido", acciones: "" },
          ],
          searchPlaceholder: t5("Buscar clínica...", "Search clinic...", "Rechercher clinique...", "Klinik suchen...", "Cerca clinica..."),
        },
        modal: {
          title: t5("Agregar Tenant", "Add Tenant", "Ajouter Tenant", "Tenant Hinzufügen", "Aggiungi Tenant"),
          fields: [
            { name: "nombre", label: t5("Nombre de la Clínica", "Clinic Name", "Nom de la Clinique", "Klinikname", "Nome della Clinica"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text", required: true, placeholder: t5("Ciudad", "City", "Ville", "Stadt", "Città") },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico", "Basic", "Basique", "Basis", "Base") },
              { value: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Professionell", "Professionale") },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "contacto", label: t5("Email de Contacto", "Contact Email", "Email de Contact", "Kontakt-E-Mail", "Email di Contatto"), type: "email", required: true, placeholder: "admin@clinica.com" },
            { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          ],
        },
      },
    ],
  },
};
