import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const eventManagement: SystemConfig = {
  name: "EventPro",
  subtitle: t5("Gestión de Eventos", "Event Management", "Gestion d'Événements", "Eventmanagement", "Gestione Eventi"),
  brandColor: "#c2410c",
  icon: "🎫",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Dashboard", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Eventos Activos", "Active Events", "Événements Actifs", "Aktive Events", "Eventi Attivi"), value: "12", change: "+3", trend: "up" },
        { label: t5("Entradas Vendidas", "Tickets Sold", "Billets Vendus", "Verkaufte Tickets", "Biglietti Venduti"), value: "2.340", change: "+42%", trend: "up" },
        { label: t5("Ingresos del Mes", "Monthly Revenue", "Revenus du Mois", "Monatsumsatz", "Ricavi del Mese"), value: "€67.800", change: "+28%", trend: "up" },
        { label: t5("Asistencia Media", "Average Attendance", "Taux de Présence Moyen", "Durchschnittliche Teilnahme", "Partecipazione Media"), value: "87%", change: "+5%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { Conferencia: "blue", Workshop: "green", Webinar: "purple", Networking: "orange", Gala: "indigo" } },
          { key: "entradas", label: t5("Entradas", "Tickets", "Billets", "Tickets", "Biglietti"), type: "text" },
        ],
        rows: [
          { fecha: "2026-03-07", actividad: "15 nuevas inscripciones", evento: "Tech Summit 2026", tipo: "Conferencia", entradas: "342/500" },
          { fecha: "2026-03-07", actividad: "Ponente confirmado", evento: "Workshop UX Avanzado", tipo: "Workshop", entradas: "28/40" },
          { fecha: "2026-03-06", actividad: "Evento finalizado", evento: "Webinar: IA para PYMES", tipo: "Webinar", entradas: "189/200" },
          { fecha: "2026-03-06", actividad: "Patrocinador Gold añadido", evento: "Gala Premios Innovación", tipo: "Gala", entradas: "156/300" },
          { fecha: "2026-03-05", actividad: "Early Bird agotado", evento: "Networking Startups Mar", tipo: "Networking", entradas: "78/100" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...", "Search recent activity...", "Rechercher activité récente...", "Letzte Aktivität suchen...", "Cerca attività recente..."),
      },
    },
    {
      id: "events",
      label: t5("Eventos", "Events", "Événements", "Events", "Eventi"),
      icon: "calendar",
      kpis: [
        { label: t5("Total Eventos", "Total Events", "Total Événements", "Events Gesamt", "Eventi Totali"), value: "34", change: "+8", trend: "up" },
        { label: t5("Próximos", "Upcoming", "À Venir", "Bevorstehend", "Prossimi"), value: "12", change: "+3", trend: "up" },
        { label: t5("Completados", "Completed", "Terminés", "Abgeschlossen", "Completati"), value: "19", change: "+4", trend: "up" },
        { label: t5("Satisfacción Media", "Average Satisfaction", "Satisfaction Moyenne", "Durchschnittliche Zufriedenheit", "Soddisfazione Media"), value: "4.6/5", change: "+0.2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { Conferencia: "blue", Workshop: "green", Webinar: "purple", Networking: "orange", Gala: "indigo" } },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "ubicacion", label: t5("Ubicación", "Location", "Lieu", "Ort", "Luogo"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Próximo": "blue", "En Vivo": "green", Completado: "gray", Cancelado: "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Tech Summit 2026", tipo: "Conferencia", fecha: "2026-04-15", ubicacion: "Madrid - IFEMA", estado: "Próximo" },
          { nombre: "Workshop UX Avanzado", tipo: "Workshop", fecha: "2026-03-22", ubicacion: "Barcelona - Hub Creativo", estado: "Próximo" },
          { nombre: "Webinar: IA para PYMES", tipo: "Webinar", fecha: "2026-03-06", ubicacion: "Online - Zoom", estado: "Completado" },
          { nombre: "Gala Premios Innovación", tipo: "Gala", fecha: "2026-05-10", ubicacion: "Valencia - Palau de les Arts", estado: "Próximo" },
          { nombre: "Networking Startups Marzo", tipo: "Networking", fecha: "2026-03-20", ubicacion: "Madrid - WeWork Castellana", estado: "Próximo" },
          { nombre: "Conferencia Fintech 2026", tipo: "Conferencia", fecha: "2026-02-18", ubicacion: "Madrid - Hotel Marriott", estado: "Completado" },
        ],
        searchPlaceholder: t5("Buscar eventos...", "Search events...", "Rechercher événements...", "Events suchen...", "Cerca eventi..."),
      },
      modal: {
        title: t5("Nuevo Evento", "New Event", "Nouvel Événement", "Neues Event", "Nuovo Evento"),
        fields: [
          { name: "nombre", label: t5("Nombre del Evento", "Event Name", "Nom de l'Événement", "Name des Events", "Nome dell'Evento"), type: "text", required: true, placeholder: t5("Nombre del evento", "Event name", "Nom de l'événement", "Name des Events", "Nome dell'evento") },
          { name: "tipo", label: t5("Tipo de Evento", "Event Type", "Type d'Événement", "Eventtyp", "Tipo di Evento"), type: "select", required: true, options: [{ value: "conferencia", label: t5("Conferencia", "Conference", "Conférence", "Konferenz", "Conferenza") }, { value: "workshop", label: "Workshop" }, { value: "webinar", label: "Webinar" }, { value: "networking", label: "Networking" }, { value: "gala", label: "Gala" }] },
          { name: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora de Inicio", "Start Time", "Heure de Début", "Startzeit", "Ora di Inizio"), type: "time", required: true },
          { name: "ubicacion", label: t5("Ubicación", "Location", "Lieu", "Ort", "Luogo"), type: "text", required: true, placeholder: t5("Dirección o enlace online", "Address or online link", "Adresse ou lien en ligne", "Adresse oder Online-Link", "Indirizzo o link online") },
          { name: "capacidad", label: t5("Capacidad Máxima", "Maximum Capacity", "Capacité Maximale", "Maximale Kapazität", "Capacità Massima"), type: "number", required: true, placeholder: "100" },
          { name: "descripcion", label: t5("Descripción", "Description", "Description", "Beschreibung", "Descrizione"), type: "textarea", placeholder: t5("Descripción del evento...", "Event description...", "Description de l'événement...", "Beschreibung des Events...", "Descrizione dell'evento...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "" },
        { id: "proximos", label: t5("Próximos", "Upcoming", "À Venir", "Bevorstehend", "Prossimi"), filterField: "estado", filterValue: "Próximo" },
        { id: "envivo", label: t5("En Vivo", "Live", "En Direct", "Live", "In Diretta"), filterField: "estado", filterValue: "En Vivo" },
        { id: "completados", label: t5("Completados", "Completed", "Terminés", "Abgeschlossen", "Completati"), filterField: "estado", filterValue: "Completado" },
        { id: "cancelados", label: t5("Cancelados", "Cancelled", "Annulés", "Storniert", "Cancellati"), filterField: "estado", filterValue: "Cancelado" },
      ],
    },
    {
      id: "tickets",
      label: t5("Entradas", "Tickets", "Billets", "Tickets", "Biglietti"),
      icon: "tag",
      kpis: [
        { label: t5("Entradas Vendidas", "Tickets Sold", "Billets Vendus", "Verkaufte Tickets", "Biglietti Venduti"), value: "2.340", change: "+420", trend: "up" },
        { label: t5("Ingresos Entradas", "Ticket Revenue", "Revenus Billets", "Ticket-Einnahmen", "Ricavi Biglietti"), value: "€67.800", change: "+28%", trend: "up" },
        { label: t5("Precio Medio", "Average Price", "Prix Moyen", "Durchschnittspreis", "Prezzo Medio"), value: "€29", change: "+€3", trend: "up" },
        { label: t5("Tasa de Conversión", "Conversion Rate", "Taux de Conversion", "Konversionsrate", "Tasso di Conversione"), value: "12.4%", change: "+1.8%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "tipo", label: t5("Tipo Entrada", "Ticket Type", "Type de Billet", "Tickettyp", "Tipo Biglietto"), type: "badge", badgeColors: { General: "blue", VIP: "purple", "Early Bird": "green", Estudiante: "yellow" } },
          { key: "precio", label: t5("Precio", "Price", "Prix", "Preis", "Prezzo"), type: "currency" },
          { key: "vendidas", label: t5("Vendidas", "Sold", "Vendus", "Verkauft", "Venduti"), type: "text" },
          { key: "disponibles", label: t5("Disponibles", "Available", "Disponibles", "Verfügbar", "Disponibili"), type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { evento: "Tech Summit 2026", tipo: "General", precio: "€49", vendidas: "210", disponibles: "140" },
          { evento: "Tech Summit 2026", tipo: "VIP", precio: "€149", vendidas: "42", disponibles: "8" },
          { evento: "Tech Summit 2026", tipo: "Early Bird", precio: "€29", vendidas: "50", disponibles: "0" },
          { evento: "Workshop UX Avanzado", tipo: "General", precio: "€35", vendidas: "28", disponibles: "12" },
          { evento: "Gala Premios Innovación", tipo: "VIP", precio: "€120", vendidas: "78", disponibles: "72" },
          { evento: "Networking Startups Mar", tipo: "Estudiante", precio: "€10", vendidas: "23", disponibles: "27" },
        ],
        searchPlaceholder: t5("Buscar entradas...", "Search tickets...", "Rechercher billets...", "Tickets suchen...", "Cerca biglietti..."),
      },
      modal: {
        title: t5("Nuevo Tipo de Entrada", "New Ticket Type", "Nouveau Type de Billet", "Neuer Tickettyp", "Nuovo Tipo di Biglietto"),
        fields: [
          { name: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "select", required: true, options: [{ value: "tech_summit", label: "Tech Summit 2026" }, { value: "workshop_ux", label: "Workshop UX Avanzado" }, { value: "gala_premios", label: "Gala Premios Innovación" }, { value: "networking_startups", label: "Networking Startups" }] },
          { name: "tipo", label: t5("Tipo de Entrada", "Ticket Type", "Type de Billet", "Tickettyp", "Tipo di Biglietto"), type: "select", required: true, options: [{ value: "general", label: "General" }, { value: "vip", label: "VIP" }, { value: "early_bird", label: "Early Bird" }, { value: "estudiante", label: t5("Estudiante", "Student", "Étudiant", "Student", "Studente") }] },
          { name: "precio", label: t5("Precio (€)", "Price (€)", "Prix (€)", "Preis (€)", "Prezzo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "cantidad", label: t5("Cantidad Disponible", "Available Quantity", "Quantité Disponible", "Verfügbare Menge", "Quantità Disponibile"), type: "number", required: true, placeholder: "100" },
          { name: "fechaLimite", label: t5("Fecha Límite de Venta", "Sales Deadline", "Date Limite de Vente", "Verkaufsschluss", "Data Limite di Vendita"), type: "date" },
          { name: "descripcion", label: t5("Qué Incluye", "What's Included", "Ce Qui Est Inclus", "Was Enthalten Ist", "Cosa Include"), type: "textarea", placeholder: t5("Acceso general, coffee break, material...", "General access, coffee break, materials...", "Accès général, pause café, matériel...", "Allgemeiner Zugang, Kaffeepause, Material...", "Accesso generale, coffee break, materiale...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "tipo", filterValue: "" },
        { id: "general", label: "General", filterField: "tipo", filterValue: "General" },
        { id: "vip", label: "VIP", filterField: "tipo", filterValue: "VIP" },
        { id: "earlybird", label: "Early Bird", filterField: "tipo", filterValue: "Early Bird" },
        { id: "estudiante", label: t5("Estudiante", "Student", "Étudiant", "Student", "Studente"), filterField: "tipo", filterValue: "Estudiante" },
      ],
    },
    {
      id: "registrations",
      label: t5("Inscripciones", "Registrations", "Inscriptions", "Anmeldungen", "Iscrizioni"),
      icon: "clipboard",
      kpis: [
        { label: t5("Total Inscritos", "Total Registered", "Total Inscrits", "Anmeldungen Gesamt", "Totale Iscritti"), value: "2.340", change: "+420", trend: "up" },
        { label: t5("Check-ins Hoy", "Check-ins Today", "Check-ins Aujourd'hui", "Check-ins Heute", "Check-in Oggi"), value: "189", trend: "neutral" },
        { label: t5("Tasa de Asistencia", "Attendance Rate", "Taux de Présence", "Anwesenheitsquote", "Tasso di Partecipazione"), value: "87%", change: "+5%", trend: "up" },
        { label: "No-Shows", value: "13%", change: "-5%", trend: "down" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Asistente", "Attendee", "Participant", "Teilnehmer", "Partecipante"), type: "text" },
          { key: "email", label: "Email", type: "text" },
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "entrada", label: t5("Entrada", "Ticket", "Billet", "Ticket", "Biglietto"), type: "badge", badgeColors: { General: "blue", VIP: "purple", "Early Bird": "green", Estudiante: "yellow" } },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Confirmado: "green", Pendiente: "yellow", Cancelado: "red", "Check-in": "blue" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "María García López", email: "maria@email.com", evento: "Tech Summit 2026", entrada: "VIP", estado: "Confirmado" },
          { nombre: "Carlos Rodríguez", email: "carlos@empresa.com", evento: "Tech Summit 2026", entrada: "General", estado: "Confirmado" },
          { nombre: "Ana Fernández", email: "ana.f@startup.io", evento: "Workshop UX Avanzado", entrada: "General", estado: "Pendiente" },
          { nombre: "Pedro Martínez", email: "pedro@universidad.es", evento: "Networking Startups", entrada: "Estudiante", estado: "Confirmado" },
          { nombre: "Laura Sánchez", email: "laura@tech.com", evento: "Webinar: IA para PYMES", entrada: "General", estado: "Check-in" },
          { nombre: "Miguel Torres", email: "miguel@corp.es", evento: "Gala Premios Innovación", entrada: "VIP", estado: "Cancelado" },
        ],
        searchPlaceholder: t5("Buscar asistentes...", "Search attendees...", "Rechercher participants...", "Teilnehmer suchen...", "Cerca partecipanti..."),
      },
      modal: {
        title: t5("Nueva Inscripción", "New Registration", "Nouvelle Inscription", "Neue Anmeldung", "Nuova Iscrizione"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "email@ejemplo.com" },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          { name: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "select", required: true, options: [{ value: "tech_summit", label: "Tech Summit 2026" }, { value: "workshop_ux", label: "Workshop UX Avanzado" }, { value: "gala_premios", label: "Gala Premios Innovación" }, { value: "networking_startups", label: "Networking Startups" }] },
          { name: "tipoEntrada", label: t5("Tipo de Entrada", "Ticket Type", "Type de Billet", "Tickettyp", "Tipo di Biglietto"), type: "select", required: true, options: [{ value: "general", label: "General" }, { value: "vip", label: "VIP" }, { value: "early_bird", label: "Early Bird" }, { value: "estudiante", label: t5("Estudiante", "Student", "Étudiant", "Student", "Studente") }] },
          { name: "dietaEspecial", label: t5("Dieta Especial", "Special Diet", "Régime Spécial", "Besondere Ernährung", "Dieta Speciale"), type: "text", placeholder: t5("Alergias o preferencias alimentarias", "Allergies or food preferences", "Allergies ou préférences alimentaires", "Allergien oder Ernährungspräferenzen", "Allergie o preferenze alimentari") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "" },
        { id: "confirmados", label: t5("Confirmados", "Confirmed", "Confirmés", "Bestätigt", "Confermati"), filterField: "estado", filterValue: "Confirmado" },
        { id: "pendientes", label: t5("Pendientes", "Pending", "En Attente", "Ausstehend", "In Attesa"), filterField: "estado", filterValue: "Pendiente" },
        { id: "checkin", label: "Check-in", filterField: "estado", filterValue: "Check-in" },
        { id: "cancelados", label: t5("Cancelados", "Cancelled", "Annulés", "Storniert", "Cancellati"), filterField: "estado", filterValue: "Cancelado" },
      ],
    },
    {
      id: "speakers",
      label: t5("Ponentes", "Speakers", "Conférenciers", "Referenten", "Relatori"),
      icon: "users",
      kpis: [
        { label: t5("Total Ponentes", "Total Speakers", "Total Conférenciers", "Referenten Gesamt", "Relatori Totali"), value: "28", change: "+6", trend: "up" },
        { label: t5("Confirmados", "Confirmed", "Confirmés", "Bestätigt", "Confermati"), value: "24", change: "+4", trend: "up" },
        { label: t5("Charlas Programadas", "Scheduled Talks", "Présentations Programmées", "Geplante Vorträge", "Presentazioni Programmate"), value: "32", change: "+8", trend: "up" },
        { label: t5("Valoración Media", "Average Rating", "Note Moyenne", "Durchschnittsbewertung", "Valutazione Media"), value: "4.8/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Ponente", "Speaker", "Conférencier", "Referent", "Relatore"), type: "text" },
          { key: "empresa", label: t5("Empresa / Cargo", "Company / Role", "Entreprise / Poste", "Unternehmen / Position", "Azienda / Ruolo"), type: "text" },
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "tema", label: t5("Tema", "Topic", "Sujet", "Thema", "Argomento"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Confirmado: "green", Invitado: "yellow", Rechazado: "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Dra. Elena Vázquez", empresa: "Google - VP Engineering", evento: "Tech Summit 2026", tema: "IA Generativa en Producción", estado: "Confirmado" },
          { nombre: "Carlos Blanco", empresa: "Fundador Nuclio", evento: "Tech Summit 2026", tema: "Ecosistema Startup España", estado: "Confirmado" },
          { nombre: "María Rodríguez", empresa: "Figma - Lead Designer", evento: "Workshop UX Avanzado", tema: "Design Systems Escalables", estado: "Confirmado" },
          { nombre: "Javier Megías", empresa: "Startupxplore CEO", evento: "Networking Startups", tema: "Cómo Levantar tu Primera Ronda", estado: "Invitado" },
          { nombre: "Ana Botella", empresa: "Microsoft - Country Manager", evento: "Gala Premios Innovación", tema: "Presentación premios", estado: "Confirmado" },
        ],
        searchPlaceholder: t5("Buscar ponentes...", "Search speakers...", "Rechercher conférenciers...", "Referenten suchen...", "Cerca relatori..."),
      },
      modal: {
        title: t5("Nuevo Ponente", "New Speaker", "Nouveau Conférencier", "Neuer Referent", "Nuovo Relatore"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "ponente@email.com" },
          { name: "empresa", label: t5("Empresa / Cargo", "Company / Role", "Entreprise / Poste", "Unternehmen / Position", "Azienda / Ruolo"), type: "text", required: true, placeholder: t5("Empresa - Cargo", "Company - Role", "Entreprise - Poste", "Unternehmen - Position", "Azienda - Ruolo") },
          { name: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "select", required: true, options: [{ value: "tech_summit", label: "Tech Summit 2026" }, { value: "workshop_ux", label: "Workshop UX Avanzado" }, { value: "gala_premios", label: "Gala Premios Innovación" }, { value: "networking_startups", label: "Networking Startups" }] },
          { name: "tema", label: t5("Tema de la Charla", "Talk Topic", "Sujet de la Présentation", "Vortragsthema", "Argomento della Presentazione"), type: "text", required: true, placeholder: t5("Título de la presentación", "Presentation title", "Titre de la présentation", "Titel der Präsentation", "Titolo della presentazione") },
          { name: "bio", label: t5("Biografía", "Biography", "Biographie", "Biographie", "Biografia"), type: "textarea", placeholder: t5("Biografía breve del ponente...", "Brief speaker biography...", "Biographie brève du conférencier...", "Kurzbiographie des Referenten...", "Breve biografia del relatore...") },
        ],
      },
    },
    {
      id: "sponsors",
      label: t5("Patrocinadores", "Sponsors", "Sponsors", "Sponsoren", "Sponsor"),
      icon: "star",
      kpis: [
        { label: t5("Total Patrocinadores", "Total Sponsors", "Total Sponsors", "Sponsoren Gesamt", "Sponsor Totali"), value: "18", change: "+4", trend: "up" },
        { label: t5("Ingresos Patrocinio", "Sponsorship Revenue", "Revenus Parrainage", "Sponsoring-Einnahmen", "Ricavi Sponsorizzazione"), value: "€42.000", change: "+35%", trend: "up" },
        { label: "Sponsors Gold", value: "4", change: "+1", trend: "up" },
        { label: t5("Leads Generados", "Leads Generated", "Leads Générés", "Generierte Leads", "Lead Generati"), value: "340", change: "+28%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "empresa", label: t5("Empresa", "Company", "Entreprise", "Unternehmen", "Azienda"), type: "text" },
          { key: "nivel", label: t5("Nivel", "Level", "Niveau", "Level", "Livello"), type: "badge", badgeColors: { Platinum: "purple", Gold: "yellow", Silver: "gray", Bronze: "orange" } },
          { key: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "text" },
          { key: "aportacion", label: t5("Aportación", "Contribution", "Contribution", "Beitrag", "Contributo"), type: "currency" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Negociando: "yellow", Pendiente: "blue" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { empresa: "Google España", nivel: "Platinum", evento: "Tech Summit 2026", aportacion: "€15.000", estado: "Activo" },
          { empresa: "AWS", nivel: "Gold", evento: "Tech Summit 2026", aportacion: "€8.000", estado: "Activo" },
          { empresa: "Telefónica", nivel: "Gold", evento: "Gala Premios Innovación", aportacion: "€7.500", estado: "Activo" },
          { empresa: "Stripe", nivel: "Silver", evento: "Tech Summit 2026", aportacion: "€3.500", estado: "Negociando" },
          { empresa: "Notion", nivel: "Silver", evento: "Workshop UX Avanzado", aportacion: "€2.500", estado: "Activo" },
          { empresa: "Startup Valencia", nivel: "Bronze", evento: "Networking Startups", aportacion: "€1.000", estado: "Pendiente" },
        ],
        searchPlaceholder: t5("Buscar patrocinadores...", "Search sponsors...", "Rechercher sponsors...", "Sponsoren suchen...", "Cerca sponsor..."),
      },
      modal: {
        title: t5("Nuevo Patrocinador", "New Sponsor", "Nouveau Sponsor", "Neuer Sponsor", "Nuovo Sponsor"),
        fields: [
          { name: "empresa", label: t5("Nombre de Empresa", "Company Name", "Nom de l'Entreprise", "Firmenname", "Nome dell'Azienda"), type: "text", required: true, placeholder: t5("Empresa patrocinadora", "Sponsoring company", "Entreprise sponsor", "Sponsorunternehmen", "Azienda sponsor") },
          { name: "contacto", label: t5("Persona de Contacto", "Contact Person", "Personne de Contact", "Ansprechpartner", "Persona di Contatto"), type: "text", required: true, placeholder: t5("Nombre del contacto", "Contact name", "Nom du contact", "Name des Ansprechpartners", "Nome del contatto") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "contacto@empresa.com" },
          { name: "nivel", label: t5("Nivel de Patrocinio", "Sponsorship Level", "Niveau de Parrainage", "Sponsoring-Level", "Livello di Sponsorizzazione"), type: "select", required: true, options: [{ value: "platinum", label: "Platinum" }, { value: "gold", label: "Gold" }, { value: "silver", label: "Silver" }, { value: "bronze", label: "Bronze" }] },
          { name: "aportacion", label: t5("Aportación (€)", "Contribution (€)", "Contribution (€)", "Beitrag (€)", "Contributo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "evento", label: t5("Evento", "Event", "Événement", "Event", "Evento"), type: "select", required: true, options: [{ value: "tech_summit", label: "Tech Summit 2026" }, { value: "workshop_ux", label: "Workshop UX Avanzado" }, { value: "gala_premios", label: "Gala Premios Innovación" }, { value: "networking_startups", label: "Networking Startups" }] },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Gestión de Tenants", "Tenant Management", "Gestion des Tenants", "Tenant-Verwaltung", "Gestione Tenant"),
        icon: "building",
        kpis: [
          { label: "Total Tenants", value: "52", change: "+7", trend: "up" },
          { label: t5("Tenants Activos", "Active Tenants", "Tenants Actifs", "Aktive Tenants", "Tenant Attivi"), value: "46", change: "+5", trend: "up" },
          { label: t5("Ingresos MRR", "MRR Revenue", "Revenus MRR", "MRR-Einnahmen", "Ricavi MRR"), value: "€14.300", change: "+21%", trend: "up" },
          { label: "Churn Rate", value: "1.9%", change: "-0.6%", trend: "down" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Organizador / Empresa", "Organizer / Company", "Organisateur / Entreprise", "Veranstalter / Unternehmen", "Organizzatore / Azienda"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Starter: "gray", Professional: "blue", Enterprise: "purple" } },
            { key: "eventos", label: t5("Eventos", "Events", "Événements", "Events", "Eventi"), type: "text" },
            { key: "asistentes", label: t5("Asistentes", "Attendees", "Participants", "Teilnehmer", "Partecipanti"), type: "text" },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Suspendido: "red", Trial: "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "Eventbrite España", plan: "Enterprise", eventos: "124", asistentes: "45K", estado: "Activo" },
            { nombre: "IFEMA Madrid", plan: "Enterprise", eventos: "56", asistentes: "120K", estado: "Activo" },
            { nombre: "Startup Grind BCN", plan: "Professional", eventos: "18", asistentes: "3.2K", estado: "Activo" },
            { nombre: "Colegio de Ingenieros", plan: "Professional", eventos: "8", asistentes: "1.1K", estado: "Trial" },
            { nombre: "Bar Club Nocturno XL", plan: "Starter", eventos: "34", asistentes: "8.4K", estado: "Suspendido" },
          ],
          searchPlaceholder: t5("Buscar tenants...", "Search tenants...", "Rechercher tenants...", "Tenants suchen...", "Cerca tenant..."),
        },
        modal: {
          title: t5("Nuevo Tenant", "New Tenant", "Nouveau Tenant", "Neuer Tenant", "Nuovo Tenant"),
          fields: [
            { name: "nombre", label: t5("Nombre de Organizador", "Organizer Name", "Nom de l'Organisateur", "Name des Veranstalters", "Nome dell'Organizzatore"), type: "text", required: true, placeholder: t5("Empresa u organización", "Company or organization", "Entreprise ou organisation", "Unternehmen oder Organisation", "Azienda o organizzazione") },
            { name: "email", label: t5("Email Administrador", "Admin Email", "Email Administrateur", "Admin-E-Mail", "Email Amministratore"), type: "email", required: true, placeholder: "admin@organizador.com" },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [{ value: "starter", label: "Starter" }, { value: "professional", label: "Professional" }, { value: "enterprise", label: "Enterprise" }] },
            { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          ],
        },
      },
    ],
  },
};
