import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const foodDelivery: SystemConfig = {
  name: t5("DeliveryPro", "DeliveryPro", "DeliveryPro", "DeliveryPro", "DeliveryPro"),
  subtitle: t5("Delivery de Comida", "Food Delivery", "Livraison de Repas", "Essenslieferung", "Consegna Cibo"),
  brandColor: "#ea580c",
  icon: "🛵",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Übersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Pedidos Hoy", "Orders Today", "Commandes Aujourd'hui", "Bestellungen Heute", "Ordini Oggi"), value: "347", change: "+12.3%", trend: "up" },
        { label: t5("Ingresos del Día", "Daily Revenue", "Revenus du Jour", "Tagesumsatz", "Ricavi del Giorno"), value: "€8.920", change: "+9.7%", trend: "up" },
        { label: t5("Tiempo Medio Entrega", "Avg Delivery Time", "Temps Moyen Livraison", "Durchschn. Lieferzeit", "Tempo Medio Consegna"), value: t5("28 min", "28 min", "28 min", "28 Min", "28 min"), change: "-3 min", trend: "down" },
        { label: t5("Satisfacción", "Satisfaction", "Satisfaction", "Zufriedenheit", "Soddisfazione"), value: "4.6/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "restaurante", label: t5("Restaurante", "Restaurant", "Restaurant", "Restaurant", "Ristorante"), type: "text" },
          { key: "repartidor", label: t5("Repartidor", "Driver", "Livreur", "Fahrer", "Corriere"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Nuevo pedido": "blue", Entregado: "green", "En camino": "yellow", Cancelado: "red" } },
          { key: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "text" },
        ],
        rows: [
          { actividad: "Pedido #4521 recibido", restaurante: "Pizzería Roma", repartidor: "Daniel Ortiz", estado: "Nuevo pedido", hora: "14:32" },
          { actividad: "Entrega completada #4518", restaurante: "Sushi Zen", repartidor: "Laura Pérez", estado: "Entregado", hora: "14:28" },
          { actividad: "Pedido #4520 en camino", restaurante: "Burger House", repartidor: "Miguel Ángel", estado: "En camino", hora: "14:25" },
          { actividad: "Pedido #4517 cancelado", restaurante: "Taco Loco", repartidor: "-", estado: "Cancelado", hora: "14:20" },
          { actividad: "Entrega completada #4516", restaurante: "Wok Express", repartidor: "Carlos Ruiz", estado: "Entregado", hora: "14:15" },
        ],
        searchPlaceholder: t5("Buscar actividad...", "Search activity...", "Rechercher activité...", "Aktivität suchen...", "Cerca attività..."),
      },
    },
    {
      id: "restaurants",
      label: t5("Restaurantes", "Restaurants", "Restaurants", "Restaurants", "Ristoranti"),
      icon: "building",
      kpis: [
        { label: t5("Restaurantes Activos", "Active Restaurants", "Restaurants Actifs", "Aktive Restaurants", "Ristoranti Attivi"), value: "86", change: "+4", trend: "up" },
        { label: t5("Nuevos este Mes", "New This Month", "Nouveaux ce Mois", "Neu diesen Monat", "Nuovi questo Mese"), value: "7", change: "+2", trend: "up" },
        { label: t5("Rating Promedio", "Average Rating", "Note Moyenne", "Durchschnittsbewertung", "Valutazione Media"), value: "4.3/5", trend: "neutral" },
        { label: t5("Pedidos/Restaurante", "Orders/Restaurant", "Commandes/Restaurant", "Bestellungen/Restaurant", "Ordini/Ristorante"), value: "4.0", change: "+0.5", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Restaurante", "Restaurant", "Restaurant", "Restaurant", "Ristorante"), type: "text" },
          { key: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "text" },
          { key: "rating", label: "Rating", type: "text" },
          { key: "pedidosHoy", label: t5("Pedidos Hoy", "Orders Today", "Commandes Aujourd'hui", "Bestellungen Heute", "Ordini Oggi"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Abierto: "green", Cerrado: "red", Pausado: "yellow" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Pizzería Roma", categoria: "Italiana", rating: "4.7", pedidosHoy: 23, estado: "Abierto", acciones: "" },
          { nombre: "Sushi Zen", categoria: "Japonesa", rating: "4.5", pedidosHoy: 18, estado: "Abierto", acciones: "" },
          { nombre: "Burger House", categoria: "Americana", rating: "4.2", pedidosHoy: 31, estado: "Abierto", acciones: "" },
          { nombre: "Taco Loco", categoria: "Mexicana", rating: "4.4", pedidosHoy: 15, estado: "Pausado", acciones: "" },
          { nombre: "Wok Express", categoria: "China", rating: "4.1", pedidosHoy: 0, estado: "Cerrado", acciones: "" },
          { nombre: "El Asador", categoria: "Parrilla", rating: "4.6", pedidosHoy: 12, estado: "Abierto", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar restaurante...", "Search restaurant...", "Rechercher restaurant...", "Restaurant suchen...", "Cerca ristorante..."),
      },
      modal: {
        title: t5("Agregar Restaurante", "Add Restaurant", "Ajouter Restaurant", "Restaurant Hinzufügen", "Aggiungi Ristorante"),
        fields: [
          { name: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "text", required: true, placeholder: t5("Nombre del restaurante", "Restaurant name", "Nom du restaurant", "Name des Restaurants", "Nome del ristorante") },
          { name: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "select", required: true, options: [
            { value: "italiana", label: t5("Italiana", "Italian", "Italienne", "Italienisch", "Italiana") },
            { value: "japonesa", label: t5("Japonesa", "Japanese", "Japonaise", "Japanisch", "Giapponese") },
            { value: "americana", label: t5("Americana", "American", "Américaine", "Amerikanisch", "Americana") },
            { value: "mexicana", label: t5("Mexicana", "Mexican", "Mexicaine", "Mexikanisch", "Messicana") },
            { value: "china", label: t5("China", "Chinese", "Chinoise", "Chinesisch", "Cinese") },
            { value: "parrilla", label: t5("Parrilla", "Grill", "Grillade", "Grill", "Griglia") },
            { value: "otra", label: t5("Otra", "Other", "Autre", "Andere", "Altra") },
          ]},
          { name: "direccion", label: t5("Dirección", "Address", "Adresse", "Adresse", "Indirizzo"), type: "text", required: true, placeholder: t5("Calle y número", "Street and number", "Rue et numéro", "Straße und Nummer", "Via e numero") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("restaurante@email.com", "restaurant@email.com", "restaurant@email.com", "restaurant@email.com", "ristorante@email.com") },
          { name: "comision", label: t5("Comisión (%)", "Commission (%)", "Commission (%)", "Provision (%)", "Commissione (%)"), type: "number", required: true, placeholder: "15" },
        ],
      },
    },
    {
      id: "orders",
      label: t5("Pedidos", "Orders", "Commandes", "Bestellungen", "Ordini"),
      icon: "clipboard",
      kpis: [
        { label: t5("Pedidos Activos", "Active Orders", "Commandes Actives", "Aktive Bestellungen", "Ordini Attivi"), value: "42", change: "+8", trend: "up" },
        { label: t5("Completados Hoy", "Completed Today", "Complétées Aujourd'hui", "Heute Abgeschlossen", "Completati Oggi"), value: "305", change: "+15%", trend: "up" },
        { label: t5("Ticket Medio", "Average Ticket", "Ticket Moyen", "Durchschnittlicher Bon", "Scontrino Medio"), value: "€25.70", change: "+€2.30", trend: "up" },
        { label: t5("Cancelaciones", "Cancellations", "Annulations", "Stornierungen", "Cancellazioni"), value: "3.2%", change: "-0.8%", trend: "down" },
      ],
      table: {
        columns: [
          { key: "pedido", label: t5("Pedido", "Order", "Commande", "Bestellung", "Ordine"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text" },
          { key: "restaurante", label: t5("Restaurante", "Restaurant", "Restaurant", "Restaurant", "Ristorante"), type: "text" },
          { key: "total", label: "Total", type: "currency" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Nuevo: "blue", Preparando: "yellow", "En Camino": "orange", Entregado: "green", Cancelado: "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { pedido: "#4521", cliente: "Sofía Martín", restaurante: "Pizzería Roma", total: 32.50, estado: "Nuevo", acciones: "" },
          { pedido: "#4520", cliente: "Roberto Díaz", restaurante: "Burger House", total: 18.90, estado: "En Camino", acciones: "" },
          { pedido: "#4519", cliente: "Isabel Navarro", restaurante: "Sushi Zen", total: 45.00, estado: "Preparando", acciones: "" },
          { pedido: "#4518", cliente: "Fernando Gil", restaurante: "Sushi Zen", total: 28.30, estado: "Entregado", acciones: "" },
          { pedido: "#4517", cliente: "Patricia Ruiz", restaurante: "Taco Loco", total: 15.40, estado: "Cancelado", acciones: "" },
          { pedido: "#4516", cliente: "Andrés Moreno", restaurante: "Wok Express", total: 22.10, estado: "Entregado", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar pedido o cliente...", "Search order or customer...", "Rechercher commande ou client...", "Bestellung oder Kunde suchen...", "Cerca ordine o cliente..."),
      },
      modal: {
        title: t5("Nuevo Pedido", "New Order", "Nouvelle Commande", "Neue Bestellung", "Nuovo Ordine"),
        fields: [
          { name: "cliente", label: t5("Cliente", "Customer", "Client", "Kunde", "Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente", "Customer name", "Nom du client", "Name des Kunden", "Nome del cliente") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "direccion", label: t5("Dirección de Entrega", "Delivery Address", "Adresse de Livraison", "Lieferadresse", "Indirizzo di Consegna"), type: "text", required: true, placeholder: t5("Dirección completa", "Full address", "Adresse complète", "Vollständige Adresse", "Indirizzo completo") },
          { name: "restaurante", label: t5("Restaurante", "Restaurant", "Restaurant", "Restaurant", "Ristorante"), type: "select", required: true, options: [
            { value: "pizzeria_roma", label: "Pizzería Roma" },
            { value: "sushi_zen", label: "Sushi Zen" },
            { value: "burger_house", label: "Burger House" },
            { value: "taco_loco", label: "Taco Loco" },
            { value: "wok_express", label: "Wok Express" },
          ]},
          { name: "notas", label: t5("Notas del Pedido", "Order Notes", "Notes de Commande", "Bestellnotizen", "Note dell'Ordine"), type: "textarea", placeholder: t5("Instrucciones especiales...", "Special instructions...", "Instructions spéciales...", "Besondere Anweisungen...", "Istruzioni speciali...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "all" },
        { id: "nuevos", label: t5("Nuevos", "New", "Nouveaux", "Neu", "Nuovi"), filterField: "estado", filterValue: "Nuevo" },
        { id: "preparando", label: t5("Preparando", "Preparing", "En Préparation", "In Zubereitung", "In Preparazione"), filterField: "estado", filterValue: "Preparando" },
        { id: "en_camino", label: t5("En Camino", "On the Way", "En Route", "Unterwegs", "In Consegna"), filterField: "estado", filterValue: "En Camino" },
        { id: "entregados", label: t5("Entregados", "Delivered", "Livrés", "Geliefert", "Consegnati"), filterField: "estado", filterValue: "Entregado" },
        { id: "cancelados", label: t5("Cancelados", "Cancelled", "Annulés", "Storniert", "Cancellati"), filterField: "estado", filterValue: "Cancelado" },
      ],
    },
    {
      id: "drivers",
      label: t5("Repartidores", "Drivers", "Livreurs", "Fahrer", "Corrieri"),
      icon: "truck",
      kpis: [
        { label: t5("Repartidores Activos", "Active Drivers", "Livreurs Actifs", "Aktive Fahrer", "Corrieri Attivi"), value: "28", change: "+3", trend: "up" },
        { label: t5("En Entrega", "On Delivery", "En Livraison", "Auf Lieferung", "In Consegna"), value: "14", trend: "neutral" },
        { label: t5("Entregas/Repartidor", "Deliveries/Driver", "Livraisons/Livreur", "Lieferungen/Fahrer", "Consegne/Corriere"), value: "10.9", change: "+1.2", trend: "up" },
        { label: t5("Rating Promedio", "Average Rating", "Note Moyenne", "Durchschnittsbewertung", "Valutazione Media"), value: "4.5/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Repartidor", "Driver", "Livreur", "Fahrer", "Corriere"), type: "text" },
          { key: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "text" },
          { key: "vehiculo", label: t5("Vehículo", "Vehicle", "Véhicule", "Fahrzeug", "Veicolo"), type: "text" },
          { key: "entregasHoy", label: t5("Entregas Hoy", "Deliveries Today", "Livraisons Aujourd'hui", "Lieferungen Heute", "Consegne Oggi"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Disponible: "green", "En Entrega": "blue", Desconectado: "gray" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Daniel Ortiz", telefono: "+34 611 222 333", vehiculo: "Moto", entregasHoy: 12, estado: "En Entrega", acciones: "" },
          { nombre: "Laura Pérez", telefono: "+34 622 333 444", vehiculo: "Bicicleta", entregasHoy: 8, estado: "Disponible", acciones: "" },
          { nombre: "Miguel Ángel", telefono: "+34 633 444 555", vehiculo: "Moto", entregasHoy: 15, estado: "En Entrega", acciones: "" },
          { nombre: "Carlos Ruiz", telefono: "+34 644 555 666", vehiculo: "Coche", entregasHoy: 11, estado: "Disponible", acciones: "" },
          { nombre: "Ana Belén", telefono: "+34 655 666 777", vehiculo: "Bicicleta", entregasHoy: 0, estado: "Desconectado", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar repartidor...", "Search driver...", "Rechercher livreur...", "Fahrer suchen...", "Cerca corriere..."),
      },
      modal: {
        title: t5("Agregar Repartidor", "Add Driver", "Ajouter Livreur", "Fahrer Hinzufügen", "Aggiungi Corriere"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "vehiculo", label: t5("Vehículo", "Vehicle", "Véhicule", "Fahrzeug", "Veicolo"), type: "select", required: true, options: [
            { value: "moto", label: t5("Moto", "Motorcycle", "Moto", "Motorrad", "Moto") },
            { value: "bicicleta", label: t5("Bicicleta", "Bicycle", "Vélo", "Fahrrad", "Bicicletta") },
            { value: "coche", label: t5("Coche", "Car", "Voiture", "Auto", "Auto") },
            { value: "patinete", label: t5("Patinete Eléctrico", "Electric Scooter", "Trottinette Électrique", "E-Roller", "Monopattino Elettrico") },
          ]},
          { name: "zona", label: t5("Zona de Cobertura", "Coverage Area", "Zone de Couverture", "Versorgungsgebiet", "Zona di Copertura"), type: "text", placeholder: t5("Barrio o zona", "Neighborhood or area", "Quartier ou zone", "Viertel oder Gebiet", "Quartiere o zona") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "all" },
        { id: "disponibles", label: t5("Disponibles", "Available", "Disponibles", "Verfügbar", "Disponibili"), filterField: "estado", filterValue: "Disponible" },
        { id: "en_entrega", label: t5("En Entrega", "On Delivery", "En Livraison", "Auf Lieferung", "In Consegna"), filterField: "estado", filterValue: "En Entrega" },
        { id: "desconectados", label: t5("Desconectados", "Disconnected", "Déconnectés", "Offline", "Disconnessi"), filterField: "estado", filterValue: "Desconectado" },
      ],
    },
    {
      id: "tracking",
      label: t5("Seguimiento", "Tracking", "Suivi", "Verfolgung", "Tracciamento"),
      icon: "map",
      kpis: [
        { label: t5("Entregas en Curso", "Deliveries in Progress", "Livraisons en Cours", "Laufende Lieferungen", "Consegne in Corso"), value: "14", trend: "neutral" },
        { label: t5("Tiempo Medio", "Average Time", "Temps Moyen", "Durchschnittliche Zeit", "Tempo Medio"), value: t5("28 min", "28 min", "28 min", "28 Min", "28 min"), change: "-3 min", trend: "down" },
        { label: t5("A Tiempo", "On Time", "À l'Heure", "Pünktlich", "In Orario"), value: "91%", change: "+2%", trend: "up" },
        { label: t5("Retrasados", "Delayed", "En Retard", "Verspätet", "In Ritardo"), value: "3", change: "-1", trend: "down" },
      ],
      table: {
        columns: [
          { key: "pedido", label: t5("Pedido", "Order", "Commande", "Bestellung", "Ordine"), type: "text" },
          { key: "repartidor", label: t5("Repartidor", "Driver", "Livreur", "Fahrer", "Corriere"), type: "text" },
          { key: "origen", label: t5("Origen", "Origin", "Origine", "Herkunft", "Origine"), type: "text" },
          { key: "destino", label: t5("Destino", "Destination", "Destination", "Ziel", "Destinazione"), type: "text" },
          { key: "tiempoEstimado", label: "ETA", type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "En Recogida": "yellow", "En Ruta": "blue", "Llegando": "green", Retrasado: "red" } },
        ],
        rows: [
          { pedido: "#4521", repartidor: "Daniel Ortiz", origen: "Pizzería Roma", destino: "C/ Mayor 15", tiempoEstimado: "12 min", estado: "En Recogida" },
          { pedido: "#4520", repartidor: "Miguel Ángel", origen: "Burger House", destino: "Av. Libertad 42", tiempoEstimado: "8 min", estado: "En Ruta" },
          { pedido: "#4519", repartidor: "Carlos Ruiz", origen: "Sushi Zen", destino: "Plaza Central 3", tiempoEstimado: "3 min", estado: "Llegando" },
          { pedido: "#4515", repartidor: "Laura Pérez", origen: "El Asador", destino: "C/ Sol 28", tiempoEstimado: "22 min", estado: "Retrasado" },
          { pedido: "#4514", repartidor: "Ana Belén", origen: "Wok Express", destino: "C/ Luna 7", tiempoEstimado: "15 min", estado: "En Ruta" },
        ],
        searchPlaceholder: t5("Buscar pedido en ruta...", "Search order in transit...", "Rechercher commande en route...", "Bestellung unterwegs suchen...", "Cerca ordine in transito..."),
      },
    },
    {
      id: "payments",
      label: t5("Pagos", "Payments", "Paiements", "Zahlungen", "Pagamenti"),
      icon: "dollar",
      kpis: [
        { label: t5("Cobrado Hoy", "Collected Today", "Encaissé Aujourd'hui", "Heute Eingezogen", "Incassato Oggi"), value: "€8.920", change: "+9.7%", trend: "up" },
        { label: t5("Comisiones", "Commissions", "Commissions", "Provisionen", "Commissioni"), value: "€1.338", change: "+11%", trend: "up" },
        { label: t5("Pendiente Pago Rest.", "Pending Restaurant Pay", "Paiement Rest. en Attente", "Ausstehende Rest.-Zahlung", "Pagamento Rist. in Attesa"), value: "€6.420", trend: "neutral" },
        { label: t5("Reembolsos", "Refunds", "Remboursements", "Erstattungen", "Rimborsi"), value: "€142", change: "-€58", trend: "down" },
      ],
      table: {
        columns: [
          { key: "referencia", label: t5("Referencia", "Reference", "Référence", "Referenz", "Riferimento"), type: "text" },
          { key: "restaurante", label: t5("Restaurante", "Restaurant", "Restaurant", "Restaurant", "Ristorante"), type: "text" },
          { key: "periodo", label: t5("Periodo", "Period", "Période", "Zeitraum", "Periodo"), type: "text" },
          { key: "importe", label: t5("Importe", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "comision", label: t5("Comisión", "Commission", "Commission", "Provision", "Commissione"), type: "currency" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Pagado: "green", Pendiente: "yellow", Procesando: "blue" } },
        ],
        rows: [
          { referencia: "PAY-1201", restaurante: "Pizzería Roma", periodo: "01-07 Mar", importe: 2450, comision: 367.50, estado: "Pendiente" },
          { referencia: "PAY-1200", restaurante: "Sushi Zen", periodo: "01-07 Mar", importe: 1890, comision: 283.50, estado: "Procesando" },
          { referencia: "PAY-1199", restaurante: "Burger House", periodo: "22-28 Feb", importe: 3200, comision: 480, estado: "Pagado" },
          { referencia: "PAY-1198", restaurante: "Taco Loco", periodo: "22-28 Feb", importe: 980, comision: 147, estado: "Pagado" },
          { referencia: "PAY-1197", restaurante: "El Asador", periodo: "22-28 Feb", importe: 1560, comision: 234, estado: "Pagado" },
        ],
        searchPlaceholder: t5("Buscar pago...", "Search payment...", "Rechercher paiement...", "Zahlung suchen...", "Cerca pagamento..."),
      },
      modal: {
        title: t5("Registrar Pago", "Register Payment", "Enregistrer Paiement", "Zahlung Erfassen", "Registra Pagamento"),
        fields: [
          { name: "restaurante", label: t5("Restaurante", "Restaurant", "Restaurant", "Restaurant", "Ristorante"), type: "select", required: true, options: [
            { value: "pizzeria_roma", label: "Pizzería Roma" },
            { value: "sushi_zen", label: "Sushi Zen" },
            { value: "burger_house", label: "Burger House" },
            { value: "taco_loco", label: "Taco Loco" },
            { value: "wok_express", label: "Wok Express" },
          ]},
          { name: "importe", label: t5("Importe (€)", "Amount (€)", "Montant (€)", "Betrag (€)", "Importo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "metodo", label: t5("Método", "Method", "Méthode", "Methode", "Metodo"), type: "select", required: true, options: [
            { value: "transferencia", label: t5("Transferencia Bancaria", "Bank Transfer", "Virement Bancaire", "Banküberweisung", "Bonifico Bancario") },
            { value: "paypal", label: "PayPal" },
            { value: "stripe", label: "Stripe" },
          ]},
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Referencia bancaria...", "Bank reference...", "Référence bancaire...", "Bankreferenz...", "Riferimento bancario...") },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Tenants",
        icon: "building",
        kpis: [
          { label: t5("Plataformas Activas", "Active Platforms", "Plateformes Actives", "Aktive Plattformen", "Piattaforme Attive"), value: "18", change: "+2", trend: "up" },
          { label: t5("Restaurantes Totales", "Total Restaurants", "Restaurants Totaux", "Restaurants Gesamt", "Ristoranti Totali"), value: "1.548", change: "+72", trend: "up" },
          { label: t5("Pedidos/Día Global", "Global Orders/Day", "Commandes/Jour Global", "Globale Bestellungen/Tag", "Ordini/Giorno Globale"), value: "6.240", change: "+15%", trend: "up" },
          { label: t5("MRR Plataforma", "Platform MRR", "MRR Plateforme", "Plattform MRR", "MRR Piattaforma"), value: "€32.400", change: "+22%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "plataforma", label: t5("Plataforma", "Platform", "Plateforme", "Plattform", "Piattaforma"), type: "text" },
            { key: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text" },
            { key: "restaurantes", label: t5("Restaurantes", "Restaurants", "Restaurants", "Restaurants", "Ristoranti"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Starter: "gray", Growth: "blue", Enterprise: "purple" } },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Suspendido: "red", Trial: "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { plataforma: "DeliveryBCN", ciudad: "Barcelona", restaurantes: 245, plan: "Enterprise", estado: "Activo", acciones: "" },
            { plataforma: "ComidaYA Madrid", ciudad: "Madrid", restaurantes: 380, plan: "Enterprise", estado: "Activo", acciones: "" },
            { plataforma: "RapidFood", ciudad: "Valencia", restaurantes: 120, plan: "Growth", estado: "Activo", acciones: "" },
            { plataforma: "PideLo", ciudad: "Sevilla", restaurantes: 65, plan: "Starter", estado: "Trial", acciones: "" },
            { plataforma: "EntregaFácil", ciudad: "Bilbao", restaurantes: 88, plan: "Growth", estado: "Suspendido", acciones: "" },
          ],
          searchPlaceholder: t5("Buscar plataforma...", "Search platform...", "Rechercher plateforme...", "Plattform suchen...", "Cerca piattaforma..."),
        },
        modal: {
          title: t5("Agregar Tenant", "Add Tenant", "Ajouter Tenant", "Tenant Hinzufügen", "Aggiungi Tenant"),
          fields: [
            { name: "nombre", label: t5("Nombre de Plataforma", "Platform Name", "Nom de la Plateforme", "Plattformname", "Nome della Piattaforma"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text", required: true, placeholder: t5("Ciudad principal", "Main city", "Ville principale", "Hauptstadt", "Città principale") },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "starter", label: "Starter" },
              { value: "growth", label: "Growth" },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "contacto", label: t5("Email de Contacto", "Contact Email", "Email de Contact", "Kontakt-E-Mail", "Email di Contatto"), type: "email", required: true, placeholder: "admin@plataforma.com" },
            { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          ],
        },
      },
    ],
  },
};
