import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const gymFitness: SystemConfig = {
  name: t5("FitCenter", "FitCenter", "FitCenter", "FitCenter", "FitCenter"),
  subtitle: t5("Gimnasio y Fitness", "Gym & Fitness", "Salle de Sport & Fitness", "Fitnessstudio", "Palestra e Fitness"),
  brandColor: "#16a34a",
  icon: "💪",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Übersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Miembros Activos", "Active Members", "Membres Actifs", "Aktive Mitglieder", "Membri Attivi"), value: "1.245", change: "+42", trend: "up" },
        { label: t5("Ingresos Mensuales", "Monthly Revenue", "Revenus Mensuels", "Monatsumsatz", "Ricavi Mensili"), value: "€48.600", change: "+8.3%", trend: "up" },
        { label: t5("Asistencia Hoy", "Attendance Today", "Fréquentation Aujourd'hui", "Anwesenheit Heute", "Presenze Oggi"), value: "187", change: "+15", trend: "up" },
        { label: t5("Clases Hoy", "Classes Today", "Cours Aujourd'hui", "Kurse Heute", "Lezioni Oggi"), value: "12", trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "miembro", label: t5("Miembro", "Member", "Membre", "Mitglied", "Membro"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { "Alta": "green", "Clase": "blue", "Renovación": "purple", "Baja": "red" } },
          { key: "detalle", label: t5("Detalle", "Detail", "Détail", "Detail", "Dettaglio"), type: "text" },
          { key: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "text" },
        ],
        rows: [
          { actividad: "Nuevo miembro registrado", miembro: "Sofía Navarro", tipo: "Alta", detalle: "Plan Mensual", hora: "09:15" },
          { actividad: "Clase reservada", miembro: "Carlos Vega", tipo: "Clase", detalle: "CrossFit 10:00", hora: "09:02" },
          { actividad: "Suscripción renovada", miembro: "Laura Jiménez", tipo: "Renovación", detalle: "Plan Anual", hora: "08:45" },
          { actividad: "Clase reservada", miembro: "Pedro Alonso", tipo: "Clase", detalle: "Yoga 11:00", hora: "08:30" },
          { actividad: "Baja procesada", miembro: "Marcos Gil", tipo: "Baja", detalle: "Motivo: mudanza", hora: "08:10" },
        ],
        searchPlaceholder: t5("Buscar actividad...", "Search activity...", "Rechercher activité...", "Aktivität suchen...", "Cerca attività..."),
      },
    },
    {
      id: "members",
      label: t5("Miembros", "Members", "Membres", "Mitglieder", "Membri"),
      icon: "users",
      kpis: [
        { label: t5("Total Miembros", "Total Members", "Total Membres", "Mitglieder Gesamt", "Membri Totali"), value: "1.245", change: "+42", trend: "up" },
        { label: t5("Activos", "Active", "Actifs", "Aktiv", "Attivi"), value: "1.082", change: "+28", trend: "up" },
        { label: t5("Retención Mensual", "Monthly Retention", "Rétention Mensuelle", "Monatliche Bindung", "Fidelizzazione Mensile"), value: "91%", change: "+1.5%", trend: "up" },
        { label: t5("Nuevos este Mes", "New This Month", "Nouveaux ce Mois", "Neu diesen Monat", "Nuovi questo Mese"), value: "67", change: "+12", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "text" },
          { key: "email", label: "Email", type: "text" },
          { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "text" },
          { key: "fechaAlta", label: t5("Fecha Alta", "Sign-up Date", "Date d'Inscription", "Anmeldedatum", "Data Iscrizione"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Vencido: "red", Congelado: "blue", Trial: "yellow" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Sofía Navarro", email: "sofia@email.com", plan: "Mensual", fechaAlta: "2026-03-07", estado: "Activo", acciones: "" },
          { nombre: "Carlos Vega", email: "carlos.v@email.com", plan: "Anual", fechaAlta: "2025-06-15", estado: "Activo", acciones: "" },
          { nombre: "Laura Jiménez", email: "laura.j@email.com", plan: "Anual", fechaAlta: "2025-03-20", estado: "Activo", acciones: "" },
          { nombre: "Pedro Alonso", email: "pedro.a@email.com", plan: "Trimestral", fechaAlta: "2025-12-01", estado: "Vencido", acciones: "" },
          { nombre: "Ana Beltrán", email: "ana.b@email.com", plan: "Mensual", fechaAlta: "2026-01-10", estado: "Congelado", acciones: "" },
          { nombre: "Marcos Gil", email: "marcos.g@email.com", plan: "VIP", fechaAlta: "2026-03-01", estado: "Trial", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar miembro...", "Search member...", "Rechercher membre...", "Mitglied suchen...", "Cerca membro..."),
      },
      modal: {
        title: t5("Nuevo Miembro", "New Member", "Nouveau Membre", "Neues Mitglied", "Nuovo Membro"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
            { value: "mensual", label: t5("Mensual", "Monthly", "Mensuel", "Monatlich", "Mensile") },
            { value: "trimestral", label: t5("Trimestral", "Quarterly", "Trimestriel", "Vierteljährlich", "Trimestrale") },
            { value: "anual", label: t5("Anual", "Annual", "Annuel", "Jährlich", "Annuale") },
            { value: "vip", label: "VIP" },
          ]},
          { name: "fechaNacimiento", label: t5("Fecha de Nacimiento", "Date of Birth", "Date de Naissance", "Geburtsdatum", "Data di Nascita"), type: "date" },
          { name: "objetivos", label: t5("Objetivos", "Goals", "Objectifs", "Ziele", "Obiettivi"), type: "textarea", placeholder: t5("Pérdida de peso, ganar músculo...", "Weight loss, muscle gain...", "Perte de poids, prise de muscle...", "Gewichtsverlust, Muskelaufbau...", "Perdita di peso, aumento massa muscolare...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "all" },
        { id: "activos", label: t5("Activos", "Active", "Actifs", "Aktiv", "Attivi"), filterField: "estado", filterValue: "Activo" },
        { id: "vencidos", label: t5("Vencidos", "Expired", "Expirés", "Abgelaufen", "Scaduti"), filterField: "estado", filterValue: "Vencido" },
        { id: "congelados", label: t5("Congelados", "Frozen", "Gelés", "Eingefroren", "Congelati"), filterField: "estado", filterValue: "Congelado" },
        { id: "trial", label: "Trial", filterField: "estado", filterValue: "Trial" },
      ],
    },
    {
      id: "classes",
      label: t5("Clases", "Classes", "Cours", "Kurse", "Lezioni"),
      icon: "calendar",
      kpis: [
        { label: t5("Clases Semanales", "Weekly Classes", "Cours Hebdomadaires", "Wöchentliche Kurse", "Lezioni Settimanali"), value: "56", change: "+4", trend: "up" },
        { label: t5("Ocupación Media", "Average Occupancy", "Occupation Moyenne", "Durchschnittliche Auslastung", "Occupazione Media"), value: "78%", change: "+5%", trend: "up" },
        { label: t5("Más Popular", "Most Popular", "Le Plus Populaire", "Am Beliebtesten", "Più Popolare"), value: "CrossFit", trend: "neutral" },
        { label: t5("Instructores Activos", "Active Instructors", "Instructeurs Actifs", "Aktive Trainer", "Istruttori Attivi"), value: "14", change: "+1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "clase", label: t5("Clase", "Class", "Cours", "Kurs", "Lezione"), type: "text" },
          { key: "instructor", label: t5("Instructor", "Instructor", "Instructeur", "Trainer", "Istruttore"), type: "text" },
          { key: "horario", label: t5("Horario", "Schedule", "Horaire", "Zeitplan", "Orario"), type: "text" },
          { key: "capacidad", label: t5("Capacidad", "Capacity", "Capacité", "Kapazität", "Capacità"), type: "text" },
          { key: "inscritos", label: t5("Inscritos", "Enrolled", "Inscrits", "Eingeschrieben", "Iscritti"), type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { clase: "CrossFit", instructor: "David Martín", horario: "Lun-Mié-Vie 07:00", capacidad: 20, inscritos: 18, acciones: "" },
          { clase: "Yoga Flow", instructor: "Marta López", horario: "Mar-Jue 09:00", capacidad: 15, inscritos: 14, acciones: "" },
          { clase: "Spinning", instructor: "Raúl Gómez", horario: "Lun-Mié-Vie 18:00", capacidad: 25, inscritos: 25, acciones: "" },
          { clase: "Pilates", instructor: "Elena Ruiz", horario: "Mar-Jue 10:30", capacidad: 12, inscritos: 8, acciones: "" },
          { clase: "Boxing Fitness", instructor: "Alejandro Torres", horario: "Lun-Mié 19:30", capacidad: 18, inscritos: 16, acciones: "" },
          { clase: "Zumba", instructor: "Carolina Díaz", horario: "Mar-Jue-Sáb 11:00", capacidad: 30, inscritos: 22, acciones: "" },
        ],
        searchPlaceholder: t5("Buscar clase...", "Search class...", "Rechercher cours...", "Kurs suchen...", "Cerca lezione..."),
      },
      modal: {
        title: t5("Nueva Clase", "New Class", "Nouveau Cours", "Neuer Kurs", "Nuova Lezione"),
        fields: [
          { name: "nombre", label: t5("Nombre de la Clase", "Class Name", "Nom du Cours", "Kursname", "Nome della Lezione"), type: "text", required: true, placeholder: t5("Ej: CrossFit Avanzado", "E.g.: Advanced CrossFit", "Ex : CrossFit Avancé", "Z.B.: CrossFit Fortgeschritten", "Es.: CrossFit Avanzato") },
          { name: "instructor", label: t5("Instructor", "Instructor", "Instructeur", "Trainer", "Istruttore"), type: "select", required: true, options: [
            { value: "david", label: "David Martín" },
            { value: "marta", label: "Marta López" },
            { value: "raul", label: "Raúl Gómez" },
            { value: "elena", label: "Elena Ruiz" },
            { value: "alejandro", label: "Alejandro Torres" },
            { value: "carolina", label: "Carolina Díaz" },
          ]},
          { name: "horario", label: t5("Horario", "Schedule", "Horaire", "Zeitplan", "Orario"), type: "text", required: true, placeholder: t5("Ej: Lun-Mié-Vie 07:00", "E.g.: Mon-Wed-Fri 07:00", "Ex : Lun-Mer-Ven 07:00", "Z.B.: Mo-Mi-Fr 07:00", "Es.: Lun-Mer-Ven 07:00") },
          { name: "capacidad", label: t5("Capacidad Máxima", "Max Capacity", "Capacité Maximale", "Maximale Kapazität", "Capacità Massima"), type: "number", required: true, placeholder: "20" },
          { name: "sala", label: t5("Sala", "Room", "Salle", "Raum", "Sala"), type: "select", required: true, options: [
            { value: "sala_a", label: t5("Sala A - Principal", "Room A - Main", "Salle A - Principale", "Raum A - Haupt", "Sala A - Principale") },
            { value: "sala_b", label: t5("Sala B - Spinning", "Room B - Spinning", "Salle B - Spinning", "Raum B - Spinning", "Sala B - Spinning") },
            { value: "sala_c", label: t5("Sala C - Yoga", "Room C - Yoga", "Salle C - Yoga", "Raum C - Yoga", "Sala C - Yoga") },
            { value: "exterior", label: t5("Zona Exterior", "Outdoor Area", "Zone Extérieure", "Außenbereich", "Area Esterna") },
          ]},
          { name: "descripcion", label: t5("Descripción", "Description", "Description", "Beschreibung", "Descrizione"), type: "textarea", placeholder: t5("Nivel, requisitos, material...", "Level, requirements, equipment...", "Niveau, prérequis, matériel...", "Level, Anforderungen, Material...", "Livello, requisiti, materiale...") },
        ],
      },
    },
    {
      id: "trainers",
      label: t5("Entrenadores", "Trainers", "Entraîneurs", "Trainer", "Allenatori"),
      icon: "star",
      kpis: [
        { label: t5("Entrenadores", "Trainers", "Entraîneurs", "Trainer", "Allenatori"), value: "14", change: "+1", trend: "up" },
        { label: t5("Sesiones Personales/Sem", "Personal Sessions/Week", "Séances Perso/Sem", "Personal-Training/Woche", "Sessioni Personali/Sett"), value: "86", change: "+12", trend: "up" },
        { label: t5("Rating Medio", "Average Rating", "Note Moyenne", "Durchschnittsbewertung", "Valutazione Media"), value: "4.7/5", change: "+0.1", trend: "up" },
        { label: t5("Ingresos PT/Mes", "PT Revenue/Month", "Revenus PT/Mois", "PT-Umsatz/Monat", "Ricavi PT/Mese"), value: "€12.400", change: "+15%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Entrenador", "Trainer", "Entraîneur", "Trainer", "Allenatore"), type: "text" },
          { key: "especialidad", label: t5("Especialidad", "Specialty", "Spécialité", "Spezialität", "Specialità"), type: "text" },
          { key: "clientes", label: t5("Clientes PT", "PT Clients", "Clients PT", "PT-Kunden", "Clienti PT"), type: "text" },
          { key: "rating", label: "Rating", type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Vacaciones: "yellow", Baja: "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "David Martín", especialidad: "CrossFit / Funcional", clientes: 12, rating: "4.9", estado: "Activo", acciones: "" },
          { nombre: "Marta López", especialidad: "Yoga / Pilates", clientes: 8, rating: "4.8", estado: "Activo", acciones: "" },
          { nombre: "Raúl Gómez", especialidad: "Spinning / Cardio", clientes: 10, rating: "4.6", estado: "Activo", acciones: "" },
          { nombre: "Elena Ruiz", especialidad: "Pilates / Rehabilitación", clientes: 6, rating: "4.7", estado: "Vacaciones", acciones: "" },
          { nombre: "Alejandro Torres", especialidad: "Boxing / MMA", clientes: 14, rating: "4.8", estado: "Activo", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar entrenador...", "Search trainer...", "Rechercher entraîneur...", "Trainer suchen...", "Cerca allenatore..."),
      },
      modal: {
        title: t5("Agregar Entrenador", "Add Trainer", "Ajouter Entraîneur", "Trainer Hinzufügen", "Aggiungi Allenatore"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "especialidad", label: t5("Especialidad", "Specialty", "Spécialité", "Spezialität", "Specialità"), type: "text", required: true, placeholder: t5("CrossFit, Yoga, etc.", "CrossFit, Yoga, etc.", "CrossFit, Yoga, etc.", "CrossFit, Yoga, etc.", "CrossFit, Yoga, ecc.") },
          { name: "certificaciones", label: t5("Certificaciones", "Certifications", "Certifications", "Zertifizierungen", "Certificazioni"), type: "textarea", placeholder: t5("Títulos y certificaciones...", "Degrees and certifications...", "Diplômes et certifications...", "Abschlüsse und Zertifizierungen...", "Titoli e certificazioni...") },
          { name: "tarifa", label: t5("Tarifa/Sesión (€)", "Rate/Session (€)", "Tarif/Séance (€)", "Tarif/Sitzung (€)", "Tariffa/Sessione (€)"), type: "number", required: true, placeholder: "0.00" },
        ],
      },
    },
    {
      id: "subscriptions",
      label: t5("Suscripciones", "Subscriptions", "Abonnements", "Abonnements", "Abbonamenti"),
      icon: "tag",
      kpis: [
        { label: t5("Suscripciones Activas", "Active Subscriptions", "Abonnements Actifs", "Aktive Abonnements", "Abbonamenti Attivi"), value: "1.082", change: "+28", trend: "up" },
        { label: "MRR", value: "€48.600", change: "+8.3%", trend: "up" },
        { label: t5("Plan Más Popular", "Most Popular Plan", "Plan le Plus Populaire", "Beliebtester Plan", "Piano Più Popolare"), value: t5("Mensual (52%)", "Monthly (52%)", "Mensuel (52%)", "Monatlich (52%)", "Mensile (52%)"), trend: "neutral" },
        { label: t5("Tasa de Churn", "Churn Rate", "Taux de Désabonnement", "Abwanderungsrate", "Tasso di Abbandono"), value: "4.2%", change: "-0.8%", trend: "down" },
      ],
      table: {
        columns: [
          { key: "miembro", label: t5("Miembro", "Member", "Membre", "Mitglied", "Membro"), type: "text" },
          { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Mensual: "blue", Trimestral: "green", Anual: "purple", VIP: "orange" } },
          { key: "precio", label: t5("Precio", "Price", "Prix", "Preis", "Prezzo"), type: "currency" },
          { key: "inicio", label: t5("Inicio", "Start", "Début", "Beginn", "Inizio"), type: "date" },
          { key: "vencimiento", label: t5("Vencimiento", "Expiry", "Échéance", "Ablauf", "Scadenza"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activa: "green", "Por Vencer": "yellow", Vencida: "red", Cancelada: "gray" } },
        ],
        rows: [
          { miembro: "Sofía Navarro", plan: "Mensual", precio: 39.90, inicio: "2026-03-07", vencimiento: "2026-04-07", estado: "Activa" },
          { miembro: "Carlos Vega", plan: "Anual", precio: 359, inicio: "2025-06-15", vencimiento: "2026-06-15", estado: "Activa" },
          { miembro: "Laura Jiménez", plan: "Anual", precio: 359, inicio: "2025-03-20", vencimiento: "2026-03-20", estado: "Por Vencer" },
          { miembro: "Pedro Alonso", plan: "Trimestral", precio: 99, inicio: "2025-12-01", vencimiento: "2026-03-01", estado: "Vencida" },
          { miembro: "Ana Beltrán", plan: "Mensual", precio: 39.90, inicio: "2026-01-10", vencimiento: "2026-02-10", estado: "Cancelada" },
          { miembro: "Marcos Gil", plan: "VIP", precio: 89.90, inicio: "2026-03-01", vencimiento: "2026-04-01", estado: "Activa" },
        ],
        searchPlaceholder: t5("Buscar suscripción...", "Search subscription...", "Rechercher abonnement...", "Abonnement suchen...", "Cerca abbonamento..."),
      },
      modal: {
        title: t5("Nueva Suscripción", "New Subscription", "Nouvel Abonnement", "Neues Abonnement", "Nuovo Abbonamento"),
        fields: [
          { name: "miembro", label: t5("Miembro", "Member", "Membre", "Mitglied", "Membro"), type: "text", required: true, placeholder: t5("Nombre del miembro", "Member name", "Nom du membre", "Name des Mitglieds", "Nome del membro") },
          { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
            { value: "mensual", label: t5("Mensual - €39.90/mes", "Monthly - €39.90/mo", "Mensuel - €39.90/mois", "Monatlich - €39.90/Monat", "Mensile - €39.90/mese") },
            { value: "trimestral", label: t5("Trimestral - €99/trim", "Quarterly - €99/qtr", "Trimestriel - €99/trim", "Vierteljährlich - €99/Quartal", "Trimestrale - €99/trim") },
            { value: "anual", label: t5("Anual - €359/año", "Annual - €359/year", "Annuel - €359/an", "Jährlich - €359/Jahr", "Annuale - €359/anno") },
            { value: "vip", label: t5("VIP - €89.90/mes", "VIP - €89.90/mo", "VIP - €89.90/mois", "VIP - €89.90/Monat", "VIP - €89.90/mese") },
          ]},
          { name: "inicio", label: t5("Fecha de Inicio", "Start Date", "Date de Début", "Startdatum", "Data di Inizio"), type: "date", required: true },
          { name: "metodo", label: t5("Método de Pago", "Payment Method", "Méthode de Paiement", "Zahlungsmethode", "Metodo di Pagamento"), type: "select", required: true, options: [
            { value: "tarjeta", label: t5("Tarjeta de Crédito", "Credit Card", "Carte de Crédit", "Kreditkarte", "Carta di Credito") },
            { value: "domiciliacion", label: t5("Domiciliación Bancaria", "Direct Debit", "Prélèvement Bancaire", "Lastschrift", "Addebito Diretto") },
            { value: "efectivo", label: t5("Efectivo", "Cash", "Espèces", "Bargeld", "Contanti") },
          ]},
          { name: "renovacion", label: t5("Renovación Automática", "Auto-Renewal", "Renouvellement Automatique", "Automatische Verlängerung", "Rinnovo Automatico"), type: "checkbox" },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "all" },
        { id: "activas", label: t5("Activas", "Active", "Actifs", "Aktiv", "Attive"), filterField: "estado", filterValue: "Activa" },
        { id: "por_vencer", label: t5("Por Vencer", "Expiring Soon", "Bientôt Échues", "Bald Ablaufend", "In Scadenza"), filterField: "estado", filterValue: "Por Vencer" },
        { id: "vencidas", label: t5("Vencidas", "Expired", "Échues", "Abgelaufen", "Scadute"), filterField: "estado", filterValue: "Vencida" },
        { id: "canceladas", label: t5("Canceladas", "Cancelled", "Annulées", "Storniert", "Cancellate"), filterField: "estado", filterValue: "Cancelada" },
      ],
    },
    {
      id: "workouts",
      label: t5("Rutinas", "Workouts", "Routines", "Trainingspläne", "Schede"),
      icon: "clipboard",
      kpis: [
        { label: t5("Rutinas Creadas", "Workouts Created", "Routines Créées", "Trainingspläne Erstellt", "Schede Create"), value: "124", change: "+18", trend: "up" },
        { label: t5("Rutinas Activas", "Active Workouts", "Routines Actives", "Aktive Trainingspläne", "Schede Attive"), value: "86", trend: "neutral" },
        { label: t5("Ejercicios en Base", "Exercises in Database", "Exercices en Base", "Übungen in Datenbank", "Esercizi in Database"), value: "340", change: "+12", trend: "up" },
        { label: t5("Uso Semanal", "Weekly Usage", "Utilisation Hebdomadaire", "Wöchentliche Nutzung", "Utilizzo Settimanale"), value: "68%", change: "+4%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Rutina", "Workout", "Routine", "Trainingsplan", "Scheda"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "badge", badgeColors: { Fuerza: "red", Cardio: "blue", Flexibilidad: "green", Mixta: "purple" } },
          { key: "nivel", label: t5("Nivel", "Level", "Niveau", "Level", "Livello"), type: "text" },
          { key: "duracion", label: t5("Duración", "Duration", "Durée", "Dauer", "Durata"), type: "text" },
          { key: "asignada", label: t5("Asignada a", "Assigned to", "Assignée à", "Zugewiesen an", "Assegnata a"), type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Full Body Principiante", tipo: "Mixta", nivel: "Principiante", duracion: "45 min", asignada: "12 miembros", acciones: "" },
          { nombre: "Hipertrofia Avanzada", tipo: "Fuerza", nivel: "Avanzado", duracion: "60 min", asignada: "8 miembros", acciones: "" },
          { nombre: "HIIT Quema Grasa", tipo: "Cardio", nivel: "Intermedio", duracion: "30 min", asignada: "15 miembros", acciones: "" },
          { nombre: "Yoga Restaurativo", tipo: "Flexibilidad", nivel: "Todos", duracion: "50 min", asignada: "6 miembros", acciones: "" },
          { nombre: "Fuerza Funcional", tipo: "Fuerza", nivel: "Intermedio", duracion: "55 min", asignada: "10 miembros", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar rutina...", "Search workout...", "Rechercher routine...", "Trainingsplan suchen...", "Cerca scheda..."),
      },
      modal: {
        title: t5("Crear Rutina", "Create Workout", "Créer Routine", "Trainingsplan Erstellen", "Crea Scheda"),
        fields: [
          { name: "nombre", label: t5("Nombre de la Rutina", "Workout Name", "Nom de la Routine", "Name des Trainingsplans", "Nome della Scheda"), type: "text", required: true, placeholder: t5("Ej: Full Body Principiante", "E.g.: Full Body Beginner", "Ex : Full Body Débutant", "Z.B.: Ganzkörper Anfänger", "Es.: Full Body Principiante") },
          { name: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "select", required: true, options: [
            { value: "fuerza", label: t5("Fuerza", "Strength", "Force", "Kraft", "Forza") },
            { value: "cardio", label: "Cardio" },
            { value: "flexibilidad", label: t5("Flexibilidad", "Flexibility", "Flexibilité", "Flexibilität", "Flessibilità") },
            { value: "mixta", label: t5("Mixta", "Mixed", "Mixte", "Gemischt", "Mista") },
          ]},
          { name: "nivel", label: t5("Nivel", "Level", "Niveau", "Level", "Livello"), type: "select", required: true, options: [
            { value: "principiante", label: t5("Principiante", "Beginner", "Débutant", "Anfänger", "Principiante") },
            { value: "intermedio", label: t5("Intermedio", "Intermediate", "Intermédiaire", "Fortgeschritten", "Intermedio") },
            { value: "avanzado", label: t5("Avanzado", "Advanced", "Avancé", "Experte", "Avanzato") },
            { value: "todos", label: t5("Todos los Niveles", "All Levels", "Tous les Niveaux", "Alle Levels", "Tutti i Livelli") },
          ]},
          { name: "duracion", label: t5("Duración (min)", "Duration (min)", "Durée (min)", "Dauer (Min)", "Durata (min)"), type: "number", required: true, placeholder: "45" },
          { name: "descripcion", label: t5("Ejercicios y Series", "Exercises and Sets", "Exercices et Séries", "Übungen und Sätze", "Esercizi e Serie"), type: "textarea", required: true, placeholder: t5("Detalle de ejercicios, series y repeticiones...", "Detail of exercises, sets and reps...", "Détail des exercices, séries et répétitions...", "Details zu Übungen, Sätzen und Wiederholungen...", "Dettaglio esercizi, serie e ripetizioni...") },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Tenants",
        icon: "building",
        kpis: [
          { label: t5("Gimnasios Activos", "Active Gyms", "Salles de Sport Actives", "Aktive Fitnessstudios", "Palestre Attive"), value: "32", change: "+4", trend: "up" },
          { label: t5("Miembros Totales", "Total Members", "Membres Totaux", "Mitglieder Gesamt", "Membri Totali"), value: "39.840", change: "+1.340", trend: "up" },
          { label: t5("MRR Global", "Global MRR", "MRR Global", "Globaler MRR", "MRR Globale"), value: "€128.500", change: "+14%", trend: "up" },
          { label: t5("Retención Plataforma", "Platform Retention", "Rétention Plateforme", "Plattform-Bindung", "Fidelizzazione Piattaforma"), value: "96%", change: "+1%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "gimnasio", label: t5("Gimnasio", "Gym", "Salle de Sport", "Fitnessstudio", "Palestra"), type: "text" },
            { key: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text" },
            { key: "miembros", label: t5("Miembros", "Members", "Membres", "Mitglieder", "Membri"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Básico: "gray", Profesional: "blue", Enterprise: "purple" } },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Suspendido: "red", Trial: "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { gimnasio: "FitZone Madrid", ciudad: "Madrid", miembros: 3200, plan: "Enterprise", estado: "Activo", acciones: "" },
            { gimnasio: "PowerGym BCN", ciudad: "Barcelona", miembros: 2800, plan: "Enterprise", estado: "Activo", acciones: "" },
            { gimnasio: "CrossFit Valencia", ciudad: "Valencia", miembros: 450, plan: "Profesional", estado: "Activo", acciones: "" },
            { gimnasio: "Gym Express", ciudad: "Málaga", miembros: 180, plan: "Básico", estado: "Trial", acciones: "" },
            { gimnasio: "Iron Paradise", ciudad: "Zaragoza", miembros: 620, plan: "Profesional", estado: "Suspendido", acciones: "" },
          ],
          searchPlaceholder: t5("Buscar gimnasio...", "Search gym...", "Rechercher salle de sport...", "Fitnessstudio suchen...", "Cerca palestra..."),
        },
        modal: {
          title: t5("Agregar Tenant", "Add Tenant", "Ajouter Tenant", "Tenant Hinzufügen", "Aggiungi Tenant"),
          fields: [
            { name: "nombre", label: t5("Nombre del Gimnasio", "Gym Name", "Nom de la Salle", "Name des Fitnessstudios", "Nome della Palestra"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text", required: true, placeholder: t5("Ciudad", "City", "Ville", "Stadt", "Città") },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico", "Basic", "Basique", "Basis", "Base") },
              { value: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Professionell", "Professionale") },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "contacto", label: t5("Email de Contacto", "Contact Email", "Email de Contact", "Kontakt-E-Mail", "Email di Contatto"), type: "email", required: true, placeholder: "admin@gimnasio.com" },
            { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          ],
        },
      },
    ],
  },
};
