import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const hotelBooking: SystemConfig = {
  name: t5("HotelManager", "HotelManager", "HotelManager", "HotelManager", "HotelManager"),
  subtitle: t5("Gestión Hotelera", "Hotel Management", "Gestion Hôtelière", "Hotelverwaltung", "Gestione Alberghiera"),
  brandColor: "#b45309",
  icon: "🏨",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Übersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Ocupación Actual", "Current Occupancy", "Occupation Actuelle", "Aktuelle Auslastung", "Occupazione Attuale"), value: "78%", change: "+5.2%", trend: "up" },
        { label: t5("Ingresos del Mes", "Monthly Revenue", "Revenus du Mois", "Monatsumsatz", "Ricavi del Mese"), value: "€184.500", change: "+12.1%", trend: "up" },
        { label: t5("Reservas Activas", "Active Bookings", "Réservations Actives", "Aktive Buchungen", "Prenotazioni Attive"), value: "142", change: "+8", trend: "up" },
        { label: t5("Check-outs Hoy", "Check-outs Today", "Check-outs Aujourd'hui", "Check-outs Heute", "Check-out Oggi"), value: "23", change: "-3", trend: "down" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "habitacion", label: t5("Habitación", "Room", "Chambre", "Zimmer", "Camera"), type: "text" },
          { key: "huesped", label: t5("Huésped", "Guest", "Client", "Gast", "Ospite"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Check-in": "green", "Check-out": "blue", Reserva: "yellow", Cancelación: "red" } },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
        ],
        rows: [
          { actividad: "Check-in realizado", habitacion: "Suite 401", huesped: "Carlos Mendoza", estado: "Check-in", fecha: "2026-03-07" },
          { actividad: "Reserva confirmada", habitacion: "Doble 215", huesped: "Ana García", estado: "Reserva", fecha: "2026-03-07" },
          { actividad: "Check-out procesado", habitacion: "Individual 108", huesped: "Pedro Ruiz", estado: "Check-out", fecha: "2026-03-07" },
          { actividad: "Cancelación recibida", habitacion: "Suite 502", huesped: "María López", estado: "Cancelación", fecha: "2026-03-07" },
          { actividad: "Check-in realizado", habitacion: "Doble 310", huesped: "Jorge Fernández", estado: "Check-in", fecha: "2026-03-07" },
        ],
        searchPlaceholder: t5("Buscar actividad...", "Search activity...", "Rechercher activité...", "Aktivität suchen...", "Cerca attività..."),
      },
    },
    {
      id: "rooms",
      label: t5("Habitaciones", "Rooms", "Chambres", "Zimmer", "Camere"),
      icon: "home",
      kpis: [
        { label: t5("Total Habitaciones", "Total Rooms", "Total Chambres", "Zimmer Gesamt", "Camere Totali"), value: "120", trend: "neutral" },
        { label: t5("Disponibles", "Available", "Disponibles", "Verfügbar", "Disponibili"), value: "26", change: "-4", trend: "down" },
        { label: t5("Ocupadas", "Occupied", "Occupées", "Belegt", "Occupate"), value: "88", change: "+6", trend: "up" },
        { label: t5("En Limpieza", "Being Cleaned", "En Nettoyage", "In Reinigung", "In Pulizia"), value: "6", change: "-2", trend: "down" },
      ],
      table: {
        columns: [
          { key: "numero", label: t5("Número", "Number", "Numéro", "Nummer", "Numero"), type: "text" },
          { key: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "text" },
          { key: "piso", label: t5("Piso", "Floor", "Étage", "Stockwerk", "Piano"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Disponible: "green", Ocupada: "blue", Limpieza: "yellow", Mantenimiento: "red" } },
          { key: "precio", label: t5("Precio/Noche", "Price/Night", "Prix/Nuit", "Preis/Nacht", "Prezzo/Notte"), type: "currency" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { numero: "101", tipo: "Individual", piso: "1", estado: "Disponible", precio: 85, acciones: "" },
          { numero: "215", tipo: "Doble", piso: "2", estado: "Ocupada", precio: 140, acciones: "" },
          { numero: "310", tipo: "Doble Superior", piso: "3", estado: "Ocupada", precio: 175, acciones: "" },
          { numero: "401", tipo: "Suite Junior", piso: "4", estado: "Ocupada", precio: 250, acciones: "" },
          { numero: "502", tipo: "Suite Premium", piso: "5", estado: "Limpieza", precio: 380, acciones: "" },
          { numero: "108", tipo: "Individual", piso: "1", estado: "Mantenimiento", precio: 85, acciones: "" },
        ],
        searchPlaceholder: t5("Buscar habitación...", "Search room...", "Rechercher chambre...", "Zimmer suchen...", "Cerca camera..."),
      },
      modal: {
        title: t5("Agregar Habitación", "Add Room", "Ajouter Chambre", "Zimmer Hinzufügen", "Aggiungi Camera"),
        fields: [
          { name: "numero", label: t5("Número", "Number", "Numéro", "Nummer", "Numero"), type: "text", required: true, placeholder: t5("Ej: 301", "E.g.: 301", "Ex : 301", "Z.B.: 301", "Es.: 301") },
          { name: "tipo", label: t5("Tipo", "Type", "Type", "Typ", "Tipo"), type: "select", required: true, options: [
            { value: "individual", label: t5("Individual", "Single", "Individuelle", "Einzelzimmer", "Singola") },
            { value: "doble", label: t5("Doble", "Double", "Double", "Doppelzimmer", "Doppia") },
            { value: "doble_superior", label: t5("Doble Superior", "Superior Double", "Double Supérieure", "Superior Doppelzimmer", "Doppia Superior") },
            { value: "suite_junior", label: t5("Suite Junior", "Junior Suite", "Suite Junior", "Junior Suite", "Suite Junior") },
            { value: "suite_premium", label: t5("Suite Premium", "Premium Suite", "Suite Premium", "Premium Suite", "Suite Premium") },
          ]},
          { name: "piso", label: t5("Piso", "Floor", "Étage", "Stockwerk", "Piano"), type: "number", required: true, placeholder: "1-5" },
          { name: "precio", label: t5("Precio por Noche (€)", "Price per Night (€)", "Prix par Nuit (€)", "Preis pro Nacht (€)", "Prezzo per Notte (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Características especiales...", "Special features...", "Caractéristiques spéciales...", "Besondere Merkmale...", "Caratteristiche speciali...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "all" },
        { id: "disponibles", label: t5("Disponibles", "Available", "Disponibles", "Verfügbar", "Disponibili"), filterField: "estado", filterValue: "Disponible" },
        { id: "ocupadas", label: t5("Ocupadas", "Occupied", "Occupées", "Belegt", "Occupate"), filterField: "estado", filterValue: "Ocupada" },
        { id: "limpieza", label: t5("Limpieza", "Cleaning", "Nettoyage", "Reinigung", "Pulizia"), filterField: "estado", filterValue: "Limpieza" },
        { id: "mantenimiento", label: t5("Mantenimiento", "Maintenance", "Maintenance", "Wartung", "Manutenzione"), filterField: "estado", filterValue: "Mantenimiento" },
      ],
    },
    {
      id: "reservations",
      label: t5("Reservas", "Reservations", "Réservations", "Reservierungen", "Prenotazioni"),
      icon: "calendar",
      kpis: [
        { label: t5("Reservas Hoy", "Reservations Today", "Réservations Aujourd'hui", "Reservierungen Heute", "Prenotazioni Oggi"), value: "18", change: "+3", trend: "up" },
        { label: t5("Pendientes Check-in", "Pending Check-in", "Check-in en Attente", "Ausstehende Check-ins", "Check-in in Attesa"), value: "7", trend: "neutral" },
        { label: t5("Estancia Media", "Average Stay", "Séjour Moyen", "Durchschnittliche Aufenthaltsdauer", "Soggiorno Medio"), value: t5("3.2 noches", "3.2 nights", "3.2 nuits", "3.2 Nächte", "3.2 notti"), change: "+0.4", trend: "up" },
        { label: t5("Tasa Cancelación", "Cancellation Rate", "Taux d'Annulation", "Stornierungsrate", "Tasso Cancellazione"), value: "4.8%", change: "-1.2%", trend: "down" },
      ],
      table: {
        columns: [
          { key: "codigo", label: t5("Código", "Code", "Code", "Code", "Codice"), type: "text" },
          { key: "huesped", label: t5("Huésped", "Guest", "Client", "Gast", "Ospite"), type: "text" },
          { key: "habitacion", label: t5("Habitación", "Room", "Chambre", "Zimmer", "Camera"), type: "text" },
          { key: "entrada", label: t5("Entrada", "Check-in", "Arrivée", "Anreise", "Arrivo"), type: "date" },
          { key: "salida", label: t5("Salida", "Check-out", "Départ", "Abreise", "Partenza"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Confirmada: "green", "Check-in": "blue", "Check-out": "purple", Cancelada: "red" } },
        ],
        rows: [
          { codigo: "RES-2041", huesped: "Carlos Mendoza", habitacion: "Suite 401", entrada: "2026-03-07", salida: "2026-03-10", estado: "Check-in" },
          { codigo: "RES-2042", huesped: "Ana García", habitacion: "Doble 215", entrada: "2026-03-08", salida: "2026-03-12", estado: "Confirmada" },
          { codigo: "RES-2043", huesped: "Luis Torres", habitacion: "Individual 103", entrada: "2026-03-06", salida: "2026-03-07", estado: "Check-out" },
          { codigo: "RES-2044", huesped: "María López", habitacion: "Suite 502", entrada: "2026-03-09", salida: "2026-03-14", estado: "Cancelada" },
          { codigo: "RES-2045", huesped: "Jorge Fernández", habitacion: "Doble 310", entrada: "2026-03-07", salida: "2026-03-09", estado: "Check-in" },
          { codigo: "RES-2046", huesped: "Elena Vargas", habitacion: "Suite Junior 403", entrada: "2026-03-10", salida: "2026-03-15", estado: "Confirmada" },
        ],
        searchPlaceholder: t5("Buscar reserva o huésped...", "Search reservation or guest...", "Rechercher réservation ou client...", "Reservierung oder Gast suchen...", "Cerca prenotazione o ospite..."),
      },
      modal: {
        title: t5("Nueva Reserva", "New Reservation", "Nouvelle Réservation", "Neue Reservierung", "Nuova Prenotazione"),
        fields: [
          { name: "huesped", label: t5("Nombre del Huésped", "Guest Name", "Nom du Client", "Name des Gastes", "Nome dell'Ospite"), type: "text", required: true, placeholder: t5("Nombre completo", "Full name", "Nom complet", "Vollständiger Name", "Nome completo") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@ejemplo.com", "email@example.com", "email@exemple.com", "email@beispiel.com", "email@esempio.com") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          { name: "habitacion", label: t5("Tipo de Habitación", "Room Type", "Type de Chambre", "Zimmertyp", "Tipo di Camera"), type: "select", required: true, options: [
            { value: "individual", label: t5("Individual", "Single", "Individuelle", "Einzelzimmer", "Singola") },
            { value: "doble", label: t5("Doble", "Double", "Double", "Doppelzimmer", "Doppia") },
            { value: "doble_superior", label: t5("Doble Superior", "Superior Double", "Double Supérieure", "Superior Doppelzimmer", "Doppia Superior") },
            { value: "suite_junior", label: t5("Suite Junior", "Junior Suite", "Suite Junior", "Junior Suite", "Suite Junior") },
            { value: "suite_premium", label: t5("Suite Premium", "Premium Suite", "Suite Premium", "Premium Suite", "Suite Premium") },
          ]},
          { name: "entrada", label: t5("Fecha de Entrada", "Check-in Date", "Date d'Arrivée", "Anreisedatum", "Data di Arrivo"), type: "date", required: true },
          { name: "salida", label: t5("Fecha de Salida", "Check-out Date", "Date de Départ", "Abreisedatum", "Data di Partenza"), type: "date", required: true },
          { name: "notas", label: t5("Notas Especiales", "Special Notes", "Notes Spéciales", "Besondere Hinweise", "Note Speciali"), type: "textarea", placeholder: t5("Peticiones del huésped...", "Guest requests...", "Demandes du client...", "Gästewünsche...", "Richieste dell'ospite...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "all" },
        { id: "confirmadas", label: t5("Confirmadas", "Confirmed", "Confirmées", "Bestätigt", "Confermate"), filterField: "estado", filterValue: "Confirmada" },
        { id: "checkin", label: "Check-in", filterField: "estado", filterValue: "Check-in" },
        { id: "checkout", label: "Check-out", filterField: "estado", filterValue: "Check-out" },
        { id: "canceladas", label: t5("Canceladas", "Cancelled", "Annulées", "Storniert", "Cancellate"), filterField: "estado", filterValue: "Cancelada" },
      ],
    },
    {
      id: "guests",
      label: t5("Huéspedes", "Guests", "Clients", "Gäste", "Ospiti"),
      icon: "users",
      kpis: [
        { label: t5("Huéspedes Actuales", "Current Guests", "Clients Actuels", "Aktuelle Gäste", "Ospiti Attuali"), value: "156", change: "+12", trend: "up" },
        { label: t5("Nuevos este Mes", "New This Month", "Nouveaux ce Mois", "Neu diesen Monat", "Nuovi questo Mese"), value: "43", change: "+8", trend: "up" },
        { label: t5("Repetidores", "Returning", "Fidèles", "Stammgäste", "Abituali"), value: "34%", change: "+2.5%", trend: "up" },
        { label: t5("Satisfacción", "Satisfaction", "Satisfaction", "Zufriedenheit", "Soddisfazione"), value: "4.7/5", change: "+0.2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre", "Name", "Nom", "Name", "Nome"), type: "text" },
          { key: "email", label: "Email", type: "text" },
          { key: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "text" },
          { key: "visitas", label: t5("Visitas", "Visits", "Visites", "Besuche", "Visite"), type: "text" },
          { key: "ultimaVisita", label: t5("Última Visita", "Last Visit", "Dernière Visite", "Letzter Besuch", "Ultima Visita"), type: "date" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Carlos Mendoza", email: "carlos@email.com", telefono: "+34 612 345 678", visitas: 5, ultimaVisita: "2026-03-07" },
          { nombre: "Ana García", email: "ana.garcia@email.com", telefono: "+34 623 456 789", visitas: 2, ultimaVisita: "2026-02-15" },
          { nombre: "Pedro Ruiz", email: "pedro.ruiz@email.com", telefono: "+34 634 567 890", visitas: 8, ultimaVisita: "2026-03-07" },
          { nombre: "María López", email: "maria.lopez@email.com", telefono: "+34 645 678 901", visitas: 1, ultimaVisita: "2026-01-20" },
          { nombre: "Jorge Fernández", email: "jorge.f@email.com", telefono: "+34 656 789 012", visitas: 3, ultimaVisita: "2026-03-07" },
        ],
        searchPlaceholder: t5("Buscar huésped...", "Search guest...", "Rechercher client...", "Gast suchen...", "Cerca ospite..."),
      },
      modal: {
        title: t5("Registrar Huésped", "Register Guest", "Enregistrer Client", "Gast Registrieren", "Registra Ospite"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@ejemplo.com", "email@example.com", "email@exemple.com", "email@beispiel.com", "email@esempio.com") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "documento", label: t5("Documento de Identidad", "ID Document", "Pièce d'Identité", "Ausweisdokument", "Documento d'Identità"), type: "text", required: true, placeholder: t5("DNI/Pasaporte", "ID/Passport", "CNI/Passeport", "Ausweis/Reisepass", "CI/Passaporto") },
          { name: "nacionalidad", label: t5("Nacionalidad", "Nationality", "Nationalité", "Nationalität", "Nazionalità"), type: "text", placeholder: t5("País de origen", "Country of origin", "Pays d'origine", "Herkunftsland", "Paese di origine") },
          { name: "notas", label: t5("Preferencias", "Preferences", "Préférences", "Präferenzen", "Preferenze"), type: "textarea", placeholder: t5("Alergias, preferencias...", "Allergies, preferences...", "Allergies, préférences...", "Allergien, Präferenzen...", "Allergie, preferenze...") },
        ],
      },
    },
    {
      id: "housekeeping",
      label: t5("Limpieza", "Housekeeping", "Ménage", "Reinigung", "Pulizia"),
      icon: "tool",
      kpis: [
        { label: t5("Pendientes Hoy", "Pending Today", "En Attente Aujourd'hui", "Ausstehend Heute", "In Attesa Oggi"), value: "14", change: "-3", trend: "down" },
        { label: t5("Completadas", "Completed", "Terminées", "Abgeschlossen", "Completate"), value: "28", change: "+5", trend: "up" },
        { label: t5("Personal Activo", "Active Staff", "Personnel Actif", "Aktives Personal", "Personale Attivo"), value: "8", trend: "neutral" },
        { label: t5("Tiempo Promedio", "Average Time", "Temps Moyen", "Durchschnittliche Zeit", "Tempo Medio"), value: t5("32 min", "32 min", "32 min", "32 Min", "32 min"), change: "-4 min", trend: "down" },
      ],
      table: {
        columns: [
          { key: "habitacion", label: t5("Habitación", "Room", "Chambre", "Zimmer", "Camera"), type: "text" },
          { key: "tipo", label: t5("Tipo Limpieza", "Cleaning Type", "Type de Nettoyage", "Reinigungsart", "Tipo Pulizia"), type: "text" },
          { key: "asignado", label: t5("Asignado a", "Assigned to", "Assigné à", "Zugewiesen an", "Assegnato a"), type: "text" },
          { key: "prioridad", label: t5("Prioridad", "Priority", "Priorité", "Priorität", "Priorità"), type: "badge", badgeColors: { Alta: "red", Media: "yellow", Baja: "green" } },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Pendiente: "yellow", "En Proceso": "blue", Completada: "green" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { habitacion: "Suite 502", tipo: "Profunda", asignado: "Lucía Ramos", prioridad: "Alta", estado: "En Proceso", acciones: "" },
          { habitacion: "Doble 215", tipo: "Salida", asignado: "Carmen Díaz", prioridad: "Alta", estado: "Pendiente", acciones: "" },
          { habitacion: "Individual 108", tipo: "Mantenimiento", asignado: "Roberto Vega", prioridad: "Media", estado: "Pendiente", acciones: "" },
          { habitacion: "Doble 312", tipo: "Diaria", asignado: "Lucía Ramos", prioridad: "Baja", estado: "Completada", acciones: "" },
          { habitacion: "Suite 401", tipo: "Diaria", asignado: "Carmen Díaz", prioridad: "Baja", estado: "Completada", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar tarea de limpieza...", "Search cleaning task...", "Rechercher tâche de ménage...", "Reinigungsaufgabe suchen...", "Cerca attività di pulizia..."),
      },
      modal: {
        title: t5("Asignar Limpieza", "Assign Cleaning", "Assigner Nettoyage", "Reinigung Zuweisen", "Assegna Pulizia"),
        fields: [
          { name: "habitacion", label: t5("Habitación", "Room", "Chambre", "Zimmer", "Camera"), type: "text", required: true, placeholder: t5("Número de habitación", "Room number", "Numéro de chambre", "Zimmernummer", "Numero camera") },
          { name: "tipo", label: t5("Tipo de Limpieza", "Cleaning Type", "Type de Nettoyage", "Reinigungsart", "Tipo di Pulizia"), type: "select", required: true, options: [
            { value: "diaria", label: t5("Diaria", "Daily", "Quotidien", "Täglich", "Giornaliera") },
            { value: "salida", label: t5("Salida", "Checkout", "Départ", "Abreise", "Partenza") },
            { value: "profunda", label: t5("Profunda", "Deep", "Approfondi", "Gründlich", "Profonda") },
            { value: "mantenimiento", label: t5("Mantenimiento", "Maintenance", "Maintenance", "Wartung", "Manutenzione") },
          ]},
          { name: "asignado", label: t5("Asignar a", "Assign to", "Assigner à", "Zuweisen an", "Assegnare a"), type: "select", required: true, options: [
            { value: "lucia", label: "Lucía Ramos" },
            { value: "carmen", label: "Carmen Díaz" },
            { value: "roberto", label: "Roberto Vega" },
          ]},
          { name: "prioridad", label: t5("Prioridad", "Priority", "Priorité", "Priorität", "Priorità"), type: "select", required: true, options: [
            { value: "alta", label: t5("Alta", "High", "Haute", "Hoch", "Alta") },
            { value: "media", label: t5("Media", "Medium", "Moyenne", "Mittel", "Media") },
            { value: "baja", label: t5("Baja", "Low", "Basse", "Niedrig", "Bassa") },
          ]},
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Instrucciones especiales...", "Special instructions...", "Instructions spéciales...", "Besondere Anweisungen...", "Istruzioni speciali...") },
        ],
      },
    },
    {
      id: "billing",
      label: t5("Facturación", "Billing", "Facturation", "Rechnungsstellung", "Fatturazione"),
      icon: "dollar",
      kpis: [
        { label: t5("Facturado Hoy", "Billed Today", "Facturé Aujourd'hui", "Heute Abgerechnet", "Fatturato Oggi"), value: "€12.450", change: "+18%", trend: "up" },
        { label: t5("Pendiente de Cobro", "Pending Collection", "En Attente de Paiement", "Ausstehende Zahlung", "In Attesa di Pagamento"), value: "€8.320", change: "-5%", trend: "down" },
        { label: t5("Ingreso Mensual", "Monthly Revenue", "Revenu Mensuel", "Monatsumsatz", "Ricavo Mensile"), value: "€184.500", change: "+12.1%", trend: "up" },
        { label: t5("Ticket Medio", "Average Ticket", "Ticket Moyen", "Durchschnittlicher Bon", "Scontrino Medio"), value: "€425", change: "+€32", trend: "up" },
      ],
      table: {
        columns: [
          { key: "factura", label: t5("Factura", "Invoice", "Facture", "Rechnung", "Fattura"), type: "text" },
          { key: "huesped", label: t5("Huésped", "Guest", "Client", "Gast", "Ospite"), type: "text" },
          { key: "concepto", label: t5("Concepto", "Concept", "Concept", "Beschreibung", "Descrizione"), type: "text" },
          { key: "importe", label: t5("Importe", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Pagada: "green", Pendiente: "yellow", Vencida: "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { factura: "FAC-3021", huesped: "Carlos Mendoza", concepto: "Suite 401 - 3 noches", importe: 750, estado: "Pendiente", acciones: "" },
          { factura: "FAC-3020", huesped: "Pedro Ruiz", concepto: "Individual 108 - 2 noches", importe: 170, estado: "Pagada", acciones: "" },
          { factura: "FAC-3019", huesped: "Elena Vargas", concepto: "Suite Premium - 5 noches", importe: 1900, estado: "Pendiente", acciones: "" },
          { factura: "FAC-3018", huesped: "Luis Torres", concepto: "Doble 215 - 4 noches + Spa", importe: 680, estado: "Pagada", acciones: "" },
          { factura: "FAC-3017", huesped: "Rosa Martín", concepto: "Individual 105 - 1 noche", importe: 85, estado: "Vencida", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar factura...", "Search invoice...", "Rechercher facture...", "Rechnung suchen...", "Cerca fattura..."),
      },
      modal: {
        title: t5("Nueva Factura", "New Invoice", "Nouvelle Facture", "Neue Rechnung", "Nuova Fattura"),
        fields: [
          { name: "huesped", label: t5("Huésped", "Guest", "Client", "Gast", "Ospite"), type: "text", required: true, placeholder: t5("Nombre del huésped", "Guest name", "Nom du client", "Name des Gastes", "Nome dell'ospite") },
          { name: "concepto", label: t5("Concepto", "Concept", "Concept", "Beschreibung", "Descrizione"), type: "text", required: true, placeholder: t5("Descripción del cargo", "Charge description", "Description du frais", "Gebührenbeschreibung", "Descrizione dell'addebito") },
          { name: "importe", label: t5("Importe (€)", "Amount (€)", "Montant (€)", "Betrag (€)", "Importo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "metodo", label: t5("Método de Pago", "Payment Method", "Méthode de Paiement", "Zahlungsmethode", "Metodo di Pagamento"), type: "select", options: [
            { value: "tarjeta", label: t5("Tarjeta de Crédito", "Credit Card", "Carte de Crédit", "Kreditkarte", "Carta di Credito") },
            { value: "efectivo", label: t5("Efectivo", "Cash", "Espèces", "Bargeld", "Contanti") },
            { value: "transferencia", label: t5("Transferencia", "Bank Transfer", "Virement", "Überweisung", "Bonifico") },
          ]},
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Observaciones...", "Observations...", "Observations...", "Bemerkungen...", "Osservazioni...") },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Tenants",
        icon: "building",
        kpis: [
          { label: t5("Hoteles Activos", "Active Hotels", "Hôtels Actifs", "Aktive Hotels", "Hotel Attivi"), value: "24", change: "+3", trend: "up" },
          { label: t5("Habitaciones Totales", "Total Rooms", "Chambres Totales", "Zimmer Gesamt", "Camere Totali"), value: "2.880", change: "+360", trend: "up" },
          { label: t5("Ocupación Global", "Global Occupancy", "Occupation Globale", "Globale Auslastung", "Occupazione Globale"), value: "73%", change: "+4.1%", trend: "up" },
          { label: t5("Ingresos Plataforma", "Platform Revenue", "Revenus Plateforme", "Plattformumsatz", "Ricavi Piattaforma"), value: "€45.200/mes", change: "+18%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "hotel", label: "Hotel", type: "text" },
            { key: "ubicacion", label: t5("Ubicación", "Location", "Emplacement", "Standort", "Posizione"), type: "text" },
            { key: "habitaciones", label: t5("Habitaciones", "Rooms", "Chambres", "Zimmer", "Camere"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Básico: "gray", Profesional: "blue", Enterprise: "purple" } },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Suspendido: "red", Trial: "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { hotel: "Hotel Playa Sol", ubicacion: "Málaga", habitaciones: 120, plan: "Enterprise", estado: "Activo", acciones: "" },
            { hotel: "Hostal Luna", ubicacion: "Barcelona", habitaciones: 45, plan: "Profesional", estado: "Activo", acciones: "" },
            { hotel: "Resort Montaña", ubicacion: "Granada", habitaciones: 200, plan: "Enterprise", estado: "Activo", acciones: "" },
            { hotel: "Pensión Central", ubicacion: "Madrid", habitaciones: 20, plan: "Básico", estado: "Trial", acciones: "" },
            { hotel: "Hotel Rías Baixas", ubicacion: "Pontevedra", habitaciones: 80, plan: "Profesional", estado: "Suspendido", acciones: "" },
          ],
          searchPlaceholder: t5("Buscar hotel...", "Search hotel...", "Rechercher hôtel...", "Hotel suchen...", "Cerca hotel..."),
        },
        modal: {
          title: t5("Agregar Tenant", "Add Tenant", "Ajouter Tenant", "Tenant Hinzufügen", "Aggiungi Tenant"),
          fields: [
            { name: "nombre", label: t5("Nombre del Hotel", "Hotel Name", "Nom de l'Hôtel", "Hotelname", "Nome dell'Hotel"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "ubicacion", label: t5("Ubicación", "Location", "Emplacement", "Standort", "Posizione"), type: "text", required: true, placeholder: t5("Ciudad", "City", "Ville", "Stadt", "Città") },
            { name: "habitaciones", label: t5("Nº Habitaciones", "No. of Rooms", "Nbre de Chambres", "Anzahl Zimmer", "N. Camere"), type: "number", required: true, placeholder: "0" },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico", "Basic", "Basique", "Basis", "Base") },
              { value: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Professionell", "Professionale") },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "contacto", label: t5("Email de Contacto", "Contact Email", "Email de Contact", "Kontakt-E-Mail", "Email di Contatto"), type: "email", required: true, placeholder: "admin@hotel.com" },
          ],
        },
      },
    ],
  },
};
