import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const lms: SystemConfig = {
  name: "LearnHub",
  subtitle: t5("Plataforma de Aprendizaje","Learning Platform","Plateforme d'Apprentissage","Lernplattform","Piattaforma di Apprendimento"),
  brandColor: "#7c3aed",
  icon: "🎓",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal","Dashboard","Tableau de Bord","Dashboard","Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Cursos Activos","Active Courses","Cours Actifs","Aktive Kurse","Corsi Attivi"), value: "48", change: "+5", trend: "up" },
        { label: t5("Estudiantes Inscritos","Enrolled Students","Étudiants Inscrits","Eingeschriebene Studenten","Studenti Iscritti"), value: "1,240", change: "+87", trend: "up" },
        { label: t5("Tasa de Completado","Completion Rate","Taux de Complétion","Abschlussrate","Tasso di Completamento"), value: "72%", change: "+3%", trend: "up" },
        { label: t5("Ingresos del Mes","Monthly Revenue","Revenus du Mois","Monatsumsatz","Entrate del Mese"), value: "€18,450", change: "+12%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad","Activity","Activité","Aktivität","Attività"), type: "text" },
          { key: "usuario", label: t5("Usuario","User","Utilisateur","Benutzer","Utente"), type: "text" },
          { key: "curso", label: t5("Curso","Course","Cours","Kurs","Corso"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Completado": "green", "En Progreso": "blue", "Nuevo": "purple" } },
        ],
        rows: [
          { actividad: "Lección completada", usuario: "María López", curso: "Python Avanzado", fecha: "2026-03-07", estado: "Completado" },
          { actividad: "Inscripción nueva", usuario: "Carlos Ruiz", curso: "Diseño UX/UI", fecha: "2026-03-07", estado: "Nuevo" },
          { actividad: "Quiz aprobado", usuario: "Ana Torres", curso: "Marketing Digital", fecha: "2026-03-06", estado: "Completado" },
          { actividad: "Curso iniciado", usuario: "Pedro García", curso: "React Profesional", fecha: "2026-03-06", estado: "En Progreso" },
          { actividad: "Certificado emitido", usuario: "Laura Sánchez", curso: "Data Science", fecha: "2026-03-05", estado: "Completado" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...","Search recent activity...","Rechercher activité récente...","Letzte Aktivität suchen...","Cerca attività recente..."),
      },
    },
    {
      id: "courses",
      label: t5("Cursos","Courses","Cours","Kurse","Corsi"),
      icon: "book",
      kpis: [
        { label: t5("Total Cursos","Total Courses","Total Cours","Kurse Gesamt","Corsi Totali"), value: "48", change: "+5", trend: "up" },
        { label: t5("Publicados","Published","Publiés","Veröffentlicht","Pubblicati"), value: "35", change: "+3", trend: "up" },
        { label: t5("Borradores","Drafts","Brouillons","Entwürfe","Bozze"), value: "10", change: "-1", trend: "down" },
        { label: t5("Valoración Media","Average Rating","Note Moyenne","Durchschnittsbewertung","Valutazione Media"), value: "4.6/5", change: "+0.2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre del Curso","Course Name","Nom du Cours","Kursname","Nome del Corso"), type: "text" },
          { key: "instructor", label: t5("Instructor","Instructor","Instructeur","Dozent","Istruttore"), type: "text" },
          { key: "estudiantes", label: t5("Estudiantes","Students","Étudiants","Studenten","Studenti"), type: "text" },
          { key: "duracion", label: t5("Duración","Duration","Durée","Dauer","Durata"), type: "text" },
          { key: "precio", label: t5("Precio","Price","Prix","Preis","Prezzo"), type: "currency" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Publicado": "green", "Borrador": "yellow", "Archivado": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Python Avanzado", instructor: "Dr. Miguel Fernández", estudiantes: 245, duracion: "40h", precio: 89, estado: "Publicado" },
          { nombre: "Diseño UX/UI", instructor: "Sofía Martín", estudiantes: 189, duracion: "32h", precio: 79, estado: "Publicado" },
          { nombre: "Marketing Digital", instructor: "Javier Díaz", estudiantes: 312, duracion: "28h", precio: 69, estado: "Publicado" },
          { nombre: "React Profesional", instructor: "Elena Romero", estudiantes: 156, duracion: "36h", precio: 99, estado: "Borrador" },
          { nombre: "Data Science", instructor: "Dr. Luis Herrera", estudiantes: 203, duracion: "48h", precio: 119, estado: "Publicado" },
          { nombre: "Fotografía Digital", instructor: "Carmen Vega", estudiantes: 0, duracion: "20h", precio: 49, estado: "Archivado" },
        ],
        searchPlaceholder: t5("Buscar cursos...","Search courses...","Rechercher des cours...","Kurse suchen...","Cerca corsi..."),
      },
      modal: {
        title: t5("Nuevo Curso","New Course","Nouveau Cours","Neuer Kurs","Nuovo Corso"),
        fields: [
          { name: "nombre", label: t5("Nombre del Curso","Course Name","Nom du Cours","Kursname","Nome del Corso"), type: "text", required: true, placeholder: t5("Ej: Introducción a JavaScript","E.g.: Introduction to JavaScript","Ex : Introduction à JavaScript","Z.B.: Einführung in JavaScript","Es.: Introduzione a JavaScript") },
          { name: "instructor", label: t5("Instructor","Instructor","Instructeur","Dozent","Istruttore"), type: "text", required: true, placeholder: t5("Nombre del instructor","Instructor name","Nom de l'instructeur","Name des Dozenten","Nome dell'istruttore") },
          { name: "descripcion", label: t5("Descripción","Description","Description","Beschreibung","Descrizione"), type: "textarea", required: true, placeholder: t5("Descripción del curso...","Course description...","Description du cours...","Kursbeschreibung...","Descrizione del corso...") },
          { name: "duracion", label: t5("Duración (horas)","Duration (hours)","Durée (heures)","Dauer (Stunden)","Durata (ore)"), type: "number", required: true, placeholder: "40" },
          { name: "precio", label: t5("Precio (€)","Price (€)","Prix (€)","Preis (€)","Prezzo (€)"), type: "number", required: true, placeholder: "89" },
          { name: "categoria", label: t5("Categoría","Category","Catégorie","Kategorie","Categoria"), type: "select", required: true, options: [
            { value: "programacion", label: t5("Programación","Programming","Programmation","Programmierung","Programmazione") },
            { value: "diseno", label: t5("Diseño","Design","Design","Design","Design") },
            { value: "marketing", label: "Marketing" },
            { value: "datos", label: t5("Ciencia de Datos","Data Science","Science des Données","Datenwissenschaft","Scienza dei Dati") },
            { value: "negocios", label: t5("Negocios","Business","Affaires","Business","Business") },
          ]},
          { name: "fecha_inicio", label: t5("Fecha de Inicio","Start Date","Date de Début","Startdatum","Data di Inizio"), type: "date", required: false },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "estado", filterValue: "" },
        { id: "publicados", label: t5("Publicados","Published","Publiés","Veröffentlicht","Pubblicati"), filterField: "estado", filterValue: "Publicado" },
        { id: "borradores", label: t5("Borradores","Drafts","Brouillons","Entwürfe","Bozze"), filterField: "estado", filterValue: "Borrador" },
        { id: "archivados", label: t5("Archivados","Archived","Archivés","Archiviert","Archiviati"), filterField: "estado", filterValue: "Archivado" },
      ],
    },
    {
      id: "students",
      label: t5("Estudiantes","Students","Étudiants","Studenten","Studenti"),
      icon: "users",
      kpis: [
        { label: t5("Total Estudiantes","Total Students","Total Étudiants","Studenten Gesamt","Studenti Totali"), value: "1,240", change: "+87", trend: "up" },
        { label: t5("Activos Este Mes","Active This Month","Actifs Ce Mois","Aktiv Diesen Monat","Attivi Questo Mese"), value: "834", change: "+45", trend: "up" },
        { label: t5("Tasa de Retención","Retention Rate","Taux de Rétention","Bindungsrate","Tasso di Ritenzione"), value: "88%", change: "+2%", trend: "up" },
        { label: t5("Satisfacción","Satisfaction","Satisfaction","Zufriedenheit","Soddisfazione"), value: "4.5/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "avatar" },
          { key: "email", label: "Email", type: "text" },
          { key: "cursos", label: t5("Cursos Inscritos","Enrolled Courses","Cours Inscrits","Eingeschriebene Kurse","Corsi Iscritti"), type: "text" },
          { key: "progreso", label: t5("Progreso","Progress","Progrès","Fortschritt","Progresso"), type: "badge", badgeColors: { "Completado": "green", "En Progreso": "blue", "No Iniciado": "gray" } },
          { key: "fecha_registro", label: t5("Registro","Registration","Inscription","Registrierung","Registrazione"), type: "date" },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "María López", email: "maria.lopez@email.com", cursos: 4, progreso: "En Progreso", fecha_registro: "2025-09-15" },
          { nombre: "Carlos Ruiz", email: "carlos.ruiz@email.com", cursos: 2, progreso: "No Iniciado", fecha_registro: "2026-03-07" },
          { nombre: "Ana Torres", email: "ana.torres@email.com", cursos: 6, progreso: "Completado", fecha_registro: "2025-06-20" },
          { nombre: "Pedro García", email: "pedro.garcia@email.com", cursos: 3, progreso: "En Progreso", fecha_registro: "2025-11-03" },
          { nombre: "Laura Sánchez", email: "laura.sanchez@email.com", cursos: 5, progreso: "Completado", fecha_registro: "2025-04-12" },
        ],
        searchPlaceholder: t5("Buscar estudiantes...","Search students...","Rechercher des étudiants...","Studenten suchen...","Cerca studenti..."),
      },
      modal: {
        title: t5("Nuevo Estudiante","New Student","Nouvel Étudiant","Neuer Student","Nuovo Studente"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo","Full Name","Nom Complet","Vollständiger Name","Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos","First and last name","Prénom et nom","Vor- und Nachname","Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("email@ejemplo.com","email@example.com","email@exemple.com","email@beispiel.com","email@esempio.com") },
          { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: false, placeholder: "+34 600 000 000" },
          { name: "curso", label: t5("Curso a Inscribir","Course to Enroll","Cours à Inscrire","Kurs zur Einschreibung","Corso da Iscrivere"), type: "select", required: true, options: [
            { value: "python", label: "Python Avanzado" },
            { value: "ux", label: "Diseño UX/UI" },
            { value: "marketing", label: "Marketing Digital" },
            { value: "react", label: "React Profesional" },
            { value: "data", label: "Data Science" },
          ]},
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "progreso", filterValue: "" },
        { id: "completado", label: t5("Completado","Completed","Terminé","Abgeschlossen","Completato"), filterField: "progreso", filterValue: "Completado" },
        { id: "en_progreso", label: t5("En Progreso","In Progress","En Cours","In Bearbeitung","In Corso"), filterField: "progreso", filterValue: "En Progreso" },
        { id: "no_iniciado", label: t5("No Iniciado","Not Started","Non Commencé","Nicht Gestartet","Non Iniziato"), filterField: "progreso", filterValue: "No Iniciado" },
      ],
    },
    {
      id: "lessons",
      label: t5("Lecciones","Lessons","Leçons","Lektionen","Lezioni"),
      icon: "play",
      kpis: [
        { label: t5("Total Lecciones","Total Lessons","Total Leçons","Lektionen Gesamt","Lezioni Totali"), value: "384", change: "+22", trend: "up" },
        { label: t5("Videos Subidos","Uploaded Videos","Vidéos Téléchargées","Hochgeladene Videos","Video Caricati"), value: "310", change: "+15", trend: "up" },
        { label: t5("Duración Total","Total Duration","Durée Totale","Gesamtdauer","Durata Totale"), value: "620h", change: "+18h", trend: "up" },
        { label: t5("Visualizaciones","Views","Vues","Aufrufe","Visualizzazioni"), value: "45,320", change: "+2,100", trend: "up" },
      ],
      table: {
        columns: [
          { key: "titulo", label: t5("Título","Title","Titre","Titel","Titolo"), type: "text" },
          { key: "curso", label: t5("Curso","Course","Cours","Kurs","Corso"), type: "text" },
          { key: "duracion", label: t5("Duración","Duration","Durée","Dauer","Durata"), type: "text" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Video": "blue", "Texto": "gray", "Interactivo": "purple" } },
          { key: "vistas", label: t5("Vistas","Views","Vues","Aufrufe","Visualizzazioni"), type: "text" },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { titulo: "Variables y Tipos de Datos", curso: "Python Avanzado", duracion: "45 min", tipo: "Video", vistas: 1230 },
          { titulo: "Principios de Diseño", curso: "Diseño UX/UI", duracion: "30 min", tipo: "Video", vistas: 980 },
          { titulo: "SEO Básico", curso: "Marketing Digital", duracion: "25 min", tipo: "Texto", vistas: 1540 },
          { titulo: "Hooks en React", curso: "React Profesional", duracion: "50 min", tipo: "Video", vistas: 870 },
          { titulo: "Regresión Lineal", curso: "Data Science", duracion: "60 min", tipo: "Interactivo", vistas: 1100 },
          { titulo: "Composición Fotográfica", curso: "Fotografía Digital", duracion: "35 min", tipo: "Video", vistas: 650 },
        ],
        searchPlaceholder: t5("Buscar lecciones...","Search lessons...","Rechercher des leçons...","Lektionen suchen...","Cerca lezioni..."),
      },
      modal: {
        title: t5("Nueva Lección","New Lesson","Nouvelle Leçon","Neue Lektion","Nuova Lezione"),
        fields: [
          { name: "titulo", label: t5("Título","Title","Titre","Titel","Titolo"), type: "text", required: true, placeholder: t5("Título de la lección","Lesson title","Titre de la leçon","Titel der Lektion","Titolo della lezione") },
          { name: "curso", label: t5("Curso","Course","Cours","Kurs","Corso"), type: "select", required: true, options: [
            { value: "python", label: "Python Avanzado" },
            { value: "ux", label: "Diseño UX/UI" },
            { value: "marketing", label: "Marketing Digital" },
            { value: "react", label: "React Profesional" },
            { value: "data", label: "Data Science" },
          ]},
          { name: "tipo", label: t5("Tipo de Contenido","Content Type","Type de Contenu","Inhaltstyp","Tipo di Contenuto"), type: "select", required: true, options: [
            { value: "video", label: "Video" },
            { value: "texto", label: t5("Texto","Text","Texte","Text","Testo") },
            { value: "interactivo", label: t5("Interactivo","Interactive","Interactif","Interaktiv","Interattivo") },
          ]},
          { name: "duracion", label: t5("Duración (minutos)","Duration (minutes)","Durée (minutes)","Dauer (Minuten)","Durata (minuti)"), type: "number", required: true, placeholder: "45" },
          { name: "descripcion", label: t5("Descripción","Description","Description","Beschreibung","Descrizione"), type: "textarea", required: false, placeholder: t5("Descripción de la lección...","Lesson description...","Description de la leçon...","Beschreibung der Lektion...","Descrizione della lezione...") },
        ],
      },
    },
    {
      id: "quizzes",
      label: t5("Evaluaciones","Assessments","Évaluations","Prüfungen","Valutazioni"),
      icon: "clipboard",
      kpis: [
        { label: t5("Total Evaluaciones","Total Assessments","Total Évaluations","Prüfungen Gesamt","Valutazioni Totali"), value: "96", change: "+8", trend: "up" },
        { label: t5("Completadas Hoy","Completed Today","Terminées Aujourd'hui","Heute Abgeschlossen","Completate Oggi"), value: "34", change: "+12", trend: "up" },
        { label: t5("Nota Media","Average Grade","Note Moyenne","Durchschnittsnote","Voto Medio"), value: "7.8/10", change: "+0.3", trend: "up" },
        { label: t5("Tasa de Aprobación","Pass Rate","Taux de Réussite","Bestehensquote","Tasso di Superamento"), value: "85%", change: "+2%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "titulo", label: t5("Evaluación","Assessment","Évaluation","Prüfung","Valutazione"), type: "text" },
          { key: "curso", label: t5("Curso","Course","Cours","Kurs","Corso"), type: "text" },
          { key: "preguntas", label: t5("Preguntas","Questions","Questions","Fragen","Domande"), type: "text" },
          { key: "intentos", label: t5("Intentos","Attempts","Tentatives","Versuche","Tentativi"), type: "text" },
          { key: "nota_media", label: t5("Nota Media","Average Grade","Note Moyenne","Durchschnittsnote","Voto Medio"), type: "text" },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { titulo: "Examen Final Python", curso: "Python Avanzado", preguntas: 30, intentos: 198, nota_media: "8.2/10" },
          { titulo: "Quiz Diseño UI", curso: "Diseño UX/UI", preguntas: 20, intentos: 145, nota_media: "7.5/10" },
          { titulo: "Test SEO y SEM", curso: "Marketing Digital", preguntas: 25, intentos: 267, nota_media: "7.9/10" },
          { titulo: "Quiz React Hooks", curso: "React Profesional", preguntas: 15, intentos: 112, nota_media: "8.0/10" },
          { titulo: "Evaluación Estadística", curso: "Data Science", preguntas: 35, intentos: 176, nota_media: "7.4/10" },
        ],
        searchPlaceholder: t5("Buscar evaluaciones...","Search assessments...","Rechercher des évaluations...","Prüfungen suchen...","Cerca valutazioni..."),
      },
      modal: {
        title: t5("Nueva Evaluación","New Assessment","Nouvelle Évaluation","Neue Prüfung","Nuova Valutazione"),
        fields: [
          { name: "titulo", label: t5("Título","Title","Titre","Titel","Titolo"), type: "text", required: true, placeholder: t5("Nombre de la evaluación","Assessment name","Nom de l'évaluation","Name der Prüfung","Nome della valutazione") },
          { name: "curso", label: t5("Curso","Course","Cours","Kurs","Corso"), type: "select", required: true, options: [
            { value: "python", label: "Python Avanzado" },
            { value: "ux", label: "Diseño UX/UI" },
            { value: "marketing", label: "Marketing Digital" },
            { value: "react", label: "React Profesional" },
            { value: "data", label: "Data Science" },
          ]},
          { name: "preguntas", label: t5("Número de Preguntas","Number of Questions","Nombre de Questions","Anzahl der Fragen","Numero di Domande"), type: "number", required: true, placeholder: "20" },
          { name: "duracion", label: t5("Tiempo Límite (minutos)","Time Limit (minutes)","Temps Limite (minutes)","Zeitlimit (Minuten)","Tempo Limite (minuti)"), type: "number", required: true, placeholder: "60" },
          { name: "nota_minima", label: t5("Nota Mínima Aprobación","Minimum Passing Grade","Note Minimale de Réussite","Mindestbestehungsnote","Voto Minimo di Superamento"), type: "number", required: true, placeholder: "5" },
        ],
      },
    },
    {
      id: "certificates",
      label: t5("Certificados","Certificates","Certificats","Zertifikate","Certificati"),
      icon: "star",
      kpis: [
        { label: t5("Certificados Emitidos","Certificates Issued","Certificats Émis","Ausgestellte Zertifikate","Certificati Emessi"), value: "2,340", change: "+156", trend: "up" },
        { label: t5("Este Mes","This Month","Ce Mois","Diesen Monat","Questo Mese"), value: "89", change: "+23", trend: "up" },
        { label: t5("Tasa de Certificación","Certification Rate","Taux de Certification","Zertifizierungsrate","Tasso di Certificazione"), value: "68%", change: "+4%", trend: "up" },
        { label: t5("Verificaciones","Verifications","Vérifications","Überprüfungen","Verifiche"), value: "1,230", change: "+78", trend: "up" },
      ],
      table: {
        columns: [
          { key: "estudiante", label: t5("Estudiante","Student","Étudiant","Student","Studente"), type: "text" },
          { key: "curso", label: t5("Curso","Course","Cours","Kurs","Corso"), type: "text" },
          { key: "fecha_emision", label: t5("Fecha Emisión","Issue Date","Date d'Émission","Ausstellungsdatum","Data di Emissione"), type: "date" },
          { key: "codigo", label: t5("Código","Code","Code","Code","Codice"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Válido": "green", "Expirado": "red", "Revocado": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { estudiante: "Ana Torres", curso: "Marketing Digital", fecha_emision: "2026-03-05", codigo: "CERT-MKT-2340", estado: "Válido" },
          { estudiante: "Laura Sánchez", curso: "Data Science", fecha_emision: "2026-03-01", codigo: "CERT-DS-2339", estado: "Válido" },
          { estudiante: "Roberto Méndez", curso: "Python Avanzado", fecha_emision: "2026-02-20", codigo: "CERT-PY-2338", estado: "Válido" },
          { estudiante: "Isabel Flores", curso: "Diseño UX/UI", fecha_emision: "2025-12-15", codigo: "CERT-UX-2200", estado: "Válido" },
          { estudiante: "Diego Moreno", curso: "React Profesional", fecha_emision: "2025-03-10", codigo: "CERT-RC-1800", estado: "Expirado" },
        ],
        searchPlaceholder: t5("Buscar certificados...","Search certificates...","Rechercher des certificats...","Zertifikate suchen...","Cerca certificati..."),
      },
      modal: {
        title: t5("Emitir Certificado","Issue Certificate","Émettre un Certificat","Zertifikat Ausstellen","Emetti Certificato"),
        fields: [
          { name: "estudiante", label: t5("Estudiante","Student","Étudiant","Student","Studente"), type: "text", required: true, placeholder: t5("Nombre del estudiante","Student name","Nom de l'étudiant","Name des Studenten","Nome dello studente") },
          { name: "curso", label: t5("Curso","Course","Cours","Kurs","Corso"), type: "select", required: true, options: [
            { value: "python", label: "Python Avanzado" },
            { value: "ux", label: "Diseño UX/UI" },
            { value: "marketing", label: "Marketing Digital" },
            { value: "react", label: "React Profesional" },
            { value: "data", label: "Data Science" },
          ]},
          { name: "fecha_emision", label: t5("Fecha de Emisión","Issue Date","Date d'Émission","Ausstellungsdatum","Data di Emissione"), type: "date", required: true },
          { name: "valido_hasta", label: t5("Válido Hasta","Valid Until","Valide Jusqu'au","Gültig Bis","Valido Fino Al"), type: "date", required: false },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Organizaciones","Organizations","Organisations","Organisationen","Organizzazioni"),
        icon: "building",
        kpis: [
          { label: t5("Total Organizaciones","Total Organizations","Total Organisations","Organisationen Gesamt","Organizzazioni Totali"), value: "24", change: "+3", trend: "up" },
          { label: t5("Activas","Active","Actives","Aktiv","Attive"), value: "21", change: "+2", trend: "up" },
          { label: t5("Usuarios Totales","Total Users","Utilisateurs Totaux","Benutzer Gesamt","Utenti Totali"), value: "3,680", change: "+340", trend: "up" },
          { label: "MRR", value: "€12,400", change: "+€1,200", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Organización","Organization","Organisation","Organisation","Organizzazione"), type: "text" },
            { key: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "badge", badgeColors: { "Enterprise": "purple", "Pro": "blue", "Básico": "gray" } },
            { key: "usuarios", label: t5("Usuarios","Users","Utilisateurs","Benutzer","Utenti"), type: "text" },
            { key: "cursos", label: t5("Cursos","Courses","Cours","Kurse","Corsi"), type: "text" },
            { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activa": "green", "Suspendida": "red", "Trial": "yellow" } },
            { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "Universidad TechHub", plan: "Enterprise", usuarios: 850, cursos: 120, estado: "Activa" },
            { nombre: "Academia Digital Pro", plan: "Pro", usuarios: 340, cursos: 45, estado: "Activa" },
            { nombre: "FormaTech Solutions", plan: "Pro", usuarios: 210, cursos: 32, estado: "Activa" },
            { nombre: "EduStartup", plan: "Básico", usuarios: 45, cursos: 8, estado: "Trial" },
            { nombre: "Global Learning Co.", plan: "Enterprise", usuarios: 1200, cursos: 200, estado: "Activa" },
          ],
          searchPlaceholder: t5("Buscar organizaciones...","Search organizations...","Rechercher des organisations...","Organisationen suchen...","Cerca organizzazioni..."),
        },
        modal: {
          title: t5("Nueva Organización","New Organization","Nouvelle Organisation","Neue Organisation","Nuova Organizzazione"),
          fields: [
            { name: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "text", required: true, placeholder: t5("Nombre de la organización","Organization name","Nom de l'organisation","Name der Organisation","Nome dell'organizzazione") },
            { name: "email_admin", label: "Email Admin", type: "email", required: true, placeholder: t5("admin@organizacion.com","admin@organization.com","admin@organisation.com","admin@organisation.com","admin@organizzazione.com") },
            { name: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico","Basic","Basique","Basis","Base") },
              { value: "pro", label: "Pro" },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "max_usuarios", label: t5("Máx. Usuarios","Max. Users","Max. Utilisateurs","Max. Benutzer","Max. Utenti"), type: "number", required: true, placeholder: "100" },
          ],
        },
      },
    ],
  },
};
