import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const marketplace: SystemConfig = {
  name: "MarketPro",
  subtitle: t5("Marketplace Multi-Vendedor", "Multi-Vendor Marketplace", "Marketplace Multi-Vendeurs", "Multi-Anbieter-Marktplatz", "Marketplace Multi-Venditore"),
  brandColor: "#7c3aed",
  icon: "🏬",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Übersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Ventas del Mes", "Monthly Sales", "Ventes du Mois", "Monatsumsatz", "Vendite del Mese"), value: "€128.340", change: "+22%", trend: "up" },
        { label: t5("Pedidos Activos", "Active Orders", "Commandes Actives", "Aktive Bestellungen", "Ordini Attivi"), value: "234", change: "+45", trend: "up" },
        { label: t5("Vendedores Activos", "Active Sellers", "Vendeurs Actifs", "Aktive Verkäufer", "Venditori Attivi"), value: "89", change: "+7", trend: "up" },
        { label: t5("Comisiones Generadas", "Generated Commissions", "Commissions Générées", "Generierte Provisionen", "Commissioni Generate"), value: "€15.400", change: "+18%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "vendedor", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "text" },
          { key: "monto", label: t5("Monto", "Amount", "Montant", "Betrag", "Importo"), type: "currency" },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Completado": "green", "Procesando": "blue", "Nuevo": "purple" } },
        ],
        rows: [
          { actividad: "Pedido #4521 - Electrónica", vendedor: "TechStore Madrid", monto: "€345.00", fecha: "2026-03-07", estado: "Nuevo" },
          { actividad: "Pedido #4520 - Moda", vendedor: "ModaUrban BCN", monto: "€89.90", fecha: "2026-03-07", estado: "Procesando" },
          { actividad: "Devolución #4498 procesada", vendedor: "HomeDecor Plus", monto: "€45.00", fecha: "2026-03-06", estado: "Completado" },
          { actividad: "Pedido #4519 - Deportes", vendedor: "SportLife Pro", monto: "€234.50", fecha: "2026-03-06", estado: "Completado" },
          { actividad: "Nuevo vendedor registrado", vendedor: "ArtesaniaLocal", monto: "€0", fecha: "2026-03-06", estado: "Nuevo" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...", "Search recent activity...", "Rechercher une activité récente...", "Letzte Aktivität suchen...", "Cerca attività recente..."),
      },
    },
    {
      id: "vendors",
      label: t5("Vendedores", "Sellers", "Vendeurs", "Verkäufer", "Venditori"),
      icon: "users",
      kpis: [
        { label: t5("Total Vendedores", "Total Sellers", "Total Vendeurs", "Verkäufer Gesamt", "Totale Venditori"), value: "124", change: "+7", trend: "up" },
        { label: t5("Verificados", "Verified", "Vérifiés", "Verifiziert", "Verificati"), value: "89", change: "+5", trend: "up" },
        { label: t5("Pendientes Revisión", "Pending Review", "En Attente de Révision", "Überprüfung Ausstehend", "In Attesa di Revisione"), value: "12", change: "+3", trend: "up" },
        { label: t5("Ventas Promedio", "Average Sales", "Ventes Moyennes", "Durchschnittliche Verkäufe", "Vendite Medie"), value: t5("€2.340/mes", "€2,340/mo", "€2 340/mois", "€2.340/Mon.", "€2.340/mese"), change: "+12%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "avatar" },
          { key: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "text" },
          { key: "productos", label: t5("Productos", "Products", "Produits", "Produkte", "Prodotti"), type: "text" },
          { key: "ventas_mes", label: t5("Ventas/Mes", "Sales/Month", "Ventes/Mois", "Verkäufe/Monat", "Vendite/Mese"), type: "currency" },
          { key: "valoracion", label: t5("Valoración", "Rating", "Évaluation", "Bewertung", "Valutazione"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Verificado": "green", "Pendiente": "yellow", "Suspendido": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "TechStore Madrid", categoria: "Electrónica", productos: 234, ventas_mes: "€12.450", valoracion: "4.8/5", estado: "Verificado" },
          { nombre: "ModaUrban BCN", categoria: "Moda y Ropa", productos: 567, ventas_mes: "€8.900", valoracion: "4.6/5", estado: "Verificado" },
          { nombre: "HomeDecor Plus", categoria: "Hogar y Decoración", productos: 189, ventas_mes: "€5.670", valoracion: "4.4/5", estado: "Verificado" },
          { nombre: "SportLife Pro", categoria: "Deportes", productos: 312, ventas_mes: "€7.230", valoracion: "4.7/5", estado: "Verificado" },
          { nombre: "ArtesaniaLocal", categoria: "Artesanía", productos: 45, ventas_mes: "€890", valoracion: "4.9/5", estado: "Pendiente" },
          { nombre: "GadgetWorld", categoria: "Electrónica", productos: 78, ventas_mes: "€0", valoracion: "3.2/5", estado: "Suspendido" },
        ],
        searchPlaceholder: t5("Buscar vendedor...", "Search seller...", "Rechercher un vendeur...", "Verkäufer suchen...", "Cerca venditore..."),
      },
      modal: {
        title: t5("Nuevo Vendedor", "New Seller", "Nouveau Vendeur", "Neuer Verkäufer", "Nuovo Venditore"),
        fields: [
          { name: "nombre", label: t5("Nombre de la Tienda", "Store Name", "Nom de la Boutique", "Shopname", "Nome del Negozio"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "contacto@tienda.com" },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          { name: "categoria", label: t5("Categoría Principal", "Main Category", "Catégorie Principale", "Hauptkategorie", "Categoria Principale"), type: "select", required: true, options: [
            { value: "electronica", label: t5("Electrónica", "Electronics", "Électronique", "Elektronik", "Elettronica") },
            { value: "moda", label: t5("Moda y Ropa", "Fashion & Clothing", "Mode et Vêtements", "Mode & Kleidung", "Moda e Abbigliamento") },
            { value: "hogar", label: t5("Hogar y Decoración", "Home & Décor", "Maison et Décoration", "Haus & Dekoration", "Casa e Arredamento") },
            { value: "deportes", label: t5("Deportes", "Sports", "Sports", "Sport", "Sport") },
            { value: "artesania", label: t5("Artesanía", "Crafts", "Artisanat", "Kunsthandwerk", "Artigianato") },
            { value: "alimentacion", label: t5("Alimentación", "Food", "Alimentation", "Lebensmittel", "Alimentari") },
          ]},
          { name: "descripcion", label: t5("Descripción de la Tienda", "Store Description", "Description de la Boutique", "Shopbeschreibung", "Descrizione del Negozio"), type: "textarea", placeholder: t5("Describe tu negocio...", "Describe your business...", "Décrivez votre activité...", "Beschreiben Sie Ihr Geschäft...", "Descrivi la tua attività...") },
          { name: "comision", label: t5("Comisión (%)", "Commission (%)", "Commission (%)", "Provision (%)", "Commissione (%)"), type: "number", placeholder: "12" },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "" },
        { id: "verificados", label: t5("Verificados", "Verified", "Vérifiés", "Verifiziert", "Verificati"), filterField: "estado", filterValue: "Verificado" },
        { id: "pendientes", label: t5("Pendientes", "Pending", "En Attente", "Ausstehend", "In Sospeso"), filterField: "estado", filterValue: "Pendiente" },
        { id: "suspendidos", label: t5("Suspendidos", "Suspended", "Suspendus", "Gesperrt", "Sospesi"), filterField: "estado", filterValue: "Suspendido" },
      ],
    },
    {
      id: "products",
      label: t5("Productos", "Products", "Produits", "Produkte", "Prodotti"),
      icon: "shopping",
      kpis: [
        { label: t5("Total Productos", "Total Products", "Total Produits", "Produkte Gesamt", "Totale Prodotti"), value: "4.567", change: "+123", trend: "up" },
        { label: t5("Productos Activos", "Active Products", "Produits Actifs", "Aktive Produkte", "Prodotti Attivi"), value: "3.892", change: "+87", trend: "up" },
        { label: t5("Sin Stock", "Out of Stock", "Rupture de Stock", "Nicht auf Lager", "Esaurito"), value: "45", change: "+8", trend: "up" },
        { label: t5("Precio Medio", "Average Price", "Prix Moyen", "Durchschnittspreis", "Prezzo Medio"), value: "€67.40", change: "+€2.10", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Producto", "Product", "Produit", "Produkt", "Prodotto"), type: "text" },
          { key: "vendedor", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "text" },
          { key: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "badge", badgeColors: { "Electrónica": "blue", "Moda": "purple", "Hogar": "green", "Deportes": "orange", "Artesanía": "yellow" } },
          { key: "precio", label: t5("Precio", "Price", "Prix", "Preis", "Prezzo"), type: "currency" },
          { key: "stock", label: "Stock", type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Auriculares Bluetooth Pro X3", vendedor: "TechStore Madrid", categoria: "Electrónica", precio: "€79.99", stock: 145 },
          { nombre: "Chaqueta Urban Fit Invierno", vendedor: "ModaUrban BCN", categoria: "Moda", precio: "€129.90", stock: 67 },
          { nombre: "Lámpara LED Diseño Nórdico", vendedor: "HomeDecor Plus", categoria: "Hogar", precio: "€45.00", stock: 32 },
          { nombre: "Zapatillas Running Carbon X", vendedor: "SportLife Pro", categoria: "Deportes", precio: "€189.00", stock: 28 },
          { nombre: "Bolso Artesanal Cuero Natural", vendedor: "ArtesaniaLocal", categoria: "Artesanía", precio: "€95.00", stock: 12 },
        ],
        searchPlaceholder: t5("Buscar producto...", "Search product...", "Rechercher un produit...", "Produkt suchen...", "Cerca prodotto..."),
      },
      modal: {
        title: t5("Nuevo Producto", "New Product", "Nouveau Produit", "Neues Produkt", "Nuovo Prodotto"),
        fields: [
          { name: "nombre", label: t5("Nombre del Producto", "Product Name", "Nom du Produit", "Produktname", "Nome del Prodotto"), type: "text", required: true, placeholder: t5("Nombre del producto", "Product name", "Nom du produit", "Produktname", "Nome del prodotto") },
          { name: "vendedor", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "text", required: true, placeholder: t5("Tienda propietaria", "Owner store", "Boutique propriétaire", "Besitzer-Shop", "Negozio proprietario") },
          { name: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "select", required: true, options: [
            { value: "electronica", label: t5("Electrónica", "Electronics", "Électronique", "Elektronik", "Elettronica") },
            { value: "moda", label: t5("Moda", "Fashion", "Mode", "Mode", "Moda") },
            { value: "hogar", label: t5("Hogar", "Home", "Maison", "Haushalt", "Casa") },
            { value: "deportes", label: t5("Deportes", "Sports", "Sports", "Sport", "Sport") },
            { value: "artesania", label: t5("Artesanía", "Crafts", "Artisanat", "Kunsthandwerk", "Artigianato") },
          ]},
          { name: "precio", label: t5("Precio (€)", "Price (€)", "Prix (€)", "Preis (€)", "Prezzo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "stock", label: t5("Stock Inicial", "Initial Stock", "Stock Initial", "Anfangsbestand", "Stock Iniziale"), type: "number", required: true, placeholder: "0" },
          { name: "descripcion", label: t5("Descripción", "Description", "Description", "Beschreibung", "Descrizione"), type: "textarea", placeholder: t5("Descripción del producto...", "Product description...", "Description du produit...", "Produktbeschreibung...", "Descrizione del prodotto...") },
        ],
      },
    },
    {
      id: "orders",
      label: t5("Pedidos", "Orders", "Commandes", "Bestellungen", "Ordini"),
      icon: "clipboard",
      kpis: [
        { label: t5("Pedidos del Mes", "Monthly Orders", "Commandes du Mois", "Monatsbestellungen", "Ordini del Mese"), value: "1.234", change: "+189", trend: "up" },
        { label: t5("En Proceso", "In Progress", "En Cours", "In Bearbeitung", "In Corso"), value: "234", change: "+12", trend: "up" },
        { label: t5("Tasa Devolución", "Return Rate", "Taux de Retour", "Retourenquote", "Tasso di Reso"), value: "3.2%", change: "-0.5%", trend: "down" },
        { label: t5("Valor Medio Pedido", "Average Order Value", "Valeur Moyenne Commande", "Durchschnittlicher Bestellwert", "Valore Medio Ordine"), value: "€104", change: "+€8", trend: "up" },
      ],
      table: {
        columns: [
          { key: "pedido", label: t5("Nº Pedido", "Order #", "Nº Commande", "Bestell-Nr.", "N° Ordine"), type: "text" },
          { key: "comprador", label: t5("Comprador", "Buyer", "Acheteur", "Käufer", "Acquirente"), type: "text" },
          { key: "vendedor", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "text" },
          { key: "total", label: "Total", type: "currency" },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Nuevo": "purple", "Procesando": "blue", "Enviado": "indigo", "Entregado": "green", "Devuelto": "red" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { pedido: "PED-4521", comprador: "Laura Méndez", vendedor: "TechStore Madrid", total: "€345.00", fecha: "2026-03-07", estado: "Nuevo" },
          { pedido: "PED-4520", comprador: "Diego Soto", vendedor: "ModaUrban BCN", total: "€89.90", fecha: "2026-03-07", estado: "Procesando" },
          { pedido: "PED-4519", comprador: "Sofía Reyes", vendedor: "SportLife Pro", total: "€234.50", fecha: "2026-03-06", estado: "Enviado" },
          { pedido: "PED-4518", comprador: "Andrés Gil", vendedor: "HomeDecor Plus", total: "€156.00", fecha: "2026-03-06", estado: "Entregado" },
          { pedido: "PED-4498", comprador: "Patricia Luna", vendedor: "HomeDecor Plus", total: "€45.00", fecha: "2026-03-03", estado: "Devuelto" },
          { pedido: "PED-4497", comprador: "Marcos Peña", vendedor: "TechStore Madrid", total: "€412.80", fecha: "2026-03-02", estado: "Entregado" },
        ],
        searchPlaceholder: t5("Buscar pedido...", "Search order...", "Rechercher une commande...", "Bestellung suchen...", "Cerca ordine..."),
      },
      modal: {
        title: t5("Nuevo Pedido", "New Order", "Nouvelle Commande", "Neue Bestellung", "Nuovo Ordine"),
        fields: [
          { name: "comprador", label: t5("Comprador", "Buyer", "Acheteur", "Käufer", "Acquirente"), type: "text", required: true, placeholder: t5("Nombre del comprador", "Buyer name", "Nom de l'acheteur", "Name des Käufers", "Nome dell'acquirente") },
          { name: "email", label: t5("Email Comprador", "Buyer Email", "Email Acheteur", "Käufer-E-Mail", "Email Acquirente"), type: "email", required: true, placeholder: "correo@ejemplo.com" },
          { name: "vendedor", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "text", required: true, placeholder: t5("Tienda del vendedor", "Seller store", "Boutique du vendeur", "Shop des Verkäufers", "Negozio del venditore") },
          { name: "producto", label: t5("Producto", "Product", "Produit", "Produkt", "Prodotto"), type: "text", required: true, placeholder: t5("Nombre del producto", "Product name", "Nom du produit", "Produktname", "Nome del prodotto") },
          { name: "cantidad", label: t5("Cantidad", "Quantity", "Quantité", "Menge", "Quantità"), type: "number", required: true, placeholder: "1" },
          { name: "notas", label: t5("Notas del Pedido", "Order Notes", "Notes de Commande", "Bestellnotizen", "Note dell'Ordine"), type: "textarea", placeholder: t5("Instrucciones especiales...", "Special instructions...", "Instructions spéciales...", "Besondere Anweisungen...", "Istruzioni speciali...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos", "All", "Tous", "Alle", "Tutti"), filterField: "estado", filterValue: "" },
        { id: "nuevos", label: t5("Nuevos", "New", "Nouveaux", "Neu", "Nuovi"), filterField: "estado", filterValue: "Nuevo" },
        { id: "procesando", label: t5("Procesando", "Processing", "En Cours", "In Bearbeitung", "In Elaborazione"), filterField: "estado", filterValue: "Procesando" },
        { id: "enviados", label: t5("Enviados", "Shipped", "Expédiés", "Versendet", "Spediti"), filterField: "estado", filterValue: "Enviado" },
        { id: "entregados", label: t5("Entregados", "Delivered", "Livrés", "Zugestellt", "Consegnati"), filterField: "estado", filterValue: "Entregado" },
        { id: "devueltos", label: t5("Devueltos", "Returned", "Retournés", "Zurückgesandt", "Restituiti"), filterField: "estado", filterValue: "Devuelto" },
      ],
    },
    {
      id: "commissions",
      label: t5("Comisiones", "Commissions", "Commissions", "Provisionen", "Commissioni"),
      icon: "percent",
      kpis: [
        { label: t5("Comisiones (Mes)", "Commissions (Month)", "Commissions (Mois)", "Provisionen (Monat)", "Commissioni (Mese)"), value: "€15.400", change: "+18%", trend: "up" },
        { label: t5("Pendientes de Pago", "Pending Payment", "En Attente de Paiement", "Ausstehende Zahlung", "In Attesa di Pagamento"), value: "€4.230", change: "-€800", trend: "down" },
        { label: t5("Comisión Media", "Average Commission", "Commission Moyenne", "Durchschnittliche Provision", "Commissione Media"), value: "12%", change: "0%", trend: "neutral" },
        { label: t5("Pagos Realizados", "Payments Made", "Paiements Effectués", "Durchgeführte Zahlungen", "Pagamenti Effettuati"), value: "87", change: "+12", trend: "up" },
      ],
      table: {
        columns: [
          { key: "vendedor", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "text" },
          { key: "ventas", label: t5("Ventas Totales", "Total Sales", "Ventes Totales", "Gesamtverkäufe", "Vendite Totali"), type: "currency" },
          { key: "tasa", label: t5("Tasa Comisión", "Commission Rate", "Taux de Commission", "Provisionssatz", "Tasso di Commissione"), type: "text" },
          { key: "comision", label: t5("Comisión", "Commission", "Commission", "Provision", "Commissione"), type: "currency" },
          { key: "periodo", label: t5("Período", "Period", "Période", "Zeitraum", "Periodo"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Pagado": "green", "Pendiente": "yellow", "En Proceso": "blue" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { vendedor: "TechStore Madrid", ventas: "€12.450", tasa: "10%", comision: "€1.245", periodo: "Marzo 2026", estado: "Pendiente" },
          { vendedor: "ModaUrban BCN", ventas: "€8.900", tasa: "12%", comision: "€1.068", periodo: "Marzo 2026", estado: "Pendiente" },
          { vendedor: "SportLife Pro", ventas: "€7.230", tasa: "12%", comision: "€867.60", periodo: "Marzo 2026", estado: "En Proceso" },
          { vendedor: "HomeDecor Plus", ventas: "€5.670", tasa: "15%", comision: "€850.50", periodo: "Febrero 2026", estado: "Pagado" },
          { vendedor: "ArtesaniaLocal", ventas: "€890", tasa: "8%", comision: "€71.20", periodo: "Febrero 2026", estado: "Pagado" },
        ],
        searchPlaceholder: t5("Buscar comisión por vendedor...", "Search commission by seller...", "Rechercher une commission par vendeur...", "Provision nach Verkäufer suchen...", "Cerca commissione per venditore..."),
      },
    },
    {
      id: "reviews",
      label: t5("Reseñas", "Reviews", "Avis", "Bewertungen", "Recensioni"),
      icon: "star",
      kpis: [
        { label: t5("Total Reseñas", "Total Reviews", "Total Avis", "Bewertungen Gesamt", "Totale Recensioni"), value: "8.432", change: "+234", trend: "up" },
        { label: t5("Valoración Media", "Average Rating", "Évaluation Moyenne", "Durchschnittsbewertung", "Valutazione Media"), value: "4.5/5", change: "+0.1", trend: "up" },
        { label: t5("Pendientes Moderación", "Pending Moderation", "En Attente de Modération", "Moderation Ausstehend", "In Attesa di Moderazione"), value: "18", change: "+5", trend: "up" },
        { label: t5("Reportadas", "Reported", "Signalés", "Gemeldet", "Segnalate"), value: "3", change: "-1", trend: "down" },
      ],
      table: {
        columns: [
          { key: "comprador", label: t5("Comprador", "Buyer", "Acheteur", "Käufer", "Acquirente"), type: "text" },
          { key: "producto", label: t5("Producto", "Product", "Produit", "Produkt", "Prodotto"), type: "text" },
          { key: "vendedor", label: t5("Vendedor", "Seller", "Vendeur", "Verkäufer", "Venditore"), type: "text" },
          { key: "valoracion", label: t5("Valoración", "Rating", "Évaluation", "Bewertung", "Valutazione"), type: "text" },
          { key: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Publicada": "green", "Pendiente": "yellow", "Reportada": "red", "Rechazada": "gray" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { comprador: "Laura Méndez", producto: "Auriculares Bluetooth Pro X3", vendedor: "TechStore Madrid", valoracion: "5/5", fecha: "2026-03-07", estado: "Publicada" },
          { comprador: "Diego Soto", producto: "Chaqueta Urban Fit", vendedor: "ModaUrban BCN", valoracion: "4/5", fecha: "2026-03-06", estado: "Publicada" },
          { comprador: "Sofía Reyes", producto: "Zapatillas Running Carbon X", vendedor: "SportLife Pro", valoracion: "5/5", fecha: "2026-03-06", estado: "Pendiente" },
          { comprador: "Andrés Gil", producto: "Lámpara LED Nórdico", vendedor: "HomeDecor Plus", valoracion: "3/5", fecha: "2026-03-05", estado: "Publicada" },
          { comprador: "Patricia Luna", producto: "Cojín Decorativo", vendedor: "HomeDecor Plus", valoracion: "1/5", fecha: "2026-03-03", estado: "Reportada" },
        ],
        searchPlaceholder: t5("Buscar reseña...", "Search review...", "Rechercher un avis...", "Bewertung suchen...", "Cerca recensione..."),
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Marketplaces",
        icon: "building",
        kpis: [
          { label: "Total Marketplaces", value: "15", change: "+2", trend: "up" },
          { label: t5("Activos", "Active", "Actifs", "Aktiv", "Attivi"), value: "13", change: "+1", trend: "up" },
          { label: t5("Vendedores Totales", "Total Sellers", "Total Vendeurs", "Verkäufer Gesamt", "Totale Venditori"), value: "1.567", change: "+89", trend: "up" },
          { label: "MRR", value: "€18.900", change: "+22%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: "Marketplace", type: "text" },
            { key: "plan", label: "Plan", type: "badge", badgeColors: { "Starter": "gray", "Growth": "blue", "Enterprise": "purple" } },
            { key: "vendedores", label: t5("Vendedores", "Sellers", "Vendeurs", "Verkäufer", "Venditori"), type: "text" },
            { key: "gmv", label: t5("GMV/Mes", "GMV/Month", "GMV/Mois", "GMV/Monat", "GMV/Mese"), type: "currency" },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { "Activo": "green", "Trial": "yellow", "Suspendido": "red" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "MercadoTech España", plan: "Enterprise", vendedores: 234, gmv: "€456.000", estado: "Activo" },
            { nombre: "ModaOnline Hub", plan: "Growth", vendedores: 89, gmv: "€128.000", estado: "Activo" },
            { nombre: "FoodMarket Local", plan: "Growth", vendedores: 56, gmv: "€67.000", estado: "Activo" },
            { nombre: "ArteDeco Market", plan: "Starter", vendedores: 23, gmv: "€18.000", estado: "Trial" },
            { nombre: "SportZone Pro", plan: "Enterprise", vendedores: 145, gmv: "€312.000", estado: "Activo" },
          ],
          searchPlaceholder: t5("Buscar marketplace...", "Search marketplace...", "Rechercher un marketplace...", "Marktplatz suchen...", "Cerca marketplace..."),
        },
        modal: {
          title: t5("Nuevo Marketplace", "New Marketplace", "Nouveau Marketplace", "Neuer Marktplatz", "Nuovo Marketplace"),
          fields: [
            { name: "nombre", label: t5("Nombre del Marketplace", "Marketplace Name", "Nom du Marketplace", "Name des Marktplatzes", "Nome del Marketplace"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "plan", label: "Plan", type: "select", required: true, options: [
              { value: "starter", label: "Starter" },
              { value: "growth", label: "Growth" },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "email_admin", label: t5("Email Administrador", "Admin Email", "Email Administrateur", "Admin-E-Mail", "Email Amministratore"), type: "email", required: true, placeholder: "admin@marketplace.com" },
            { name: "comision_base", label: t5("Comisión Base (%)", "Base Commission (%)", "Commission de Base (%)", "Basisprovision (%)", "Commissione Base (%)"), type: "number", placeholder: "12" },
          ],
        },
      },
    ],
  },
};
