import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const propertyManagement: SystemConfig = {
  name: "RentFlow",
  subtitle: t5("Gestión de Propiedades", "Property Management", "Gestion Immobilière", "Immobilienverwaltung", "Gestione Immobili"),
  brandColor: "#4f46e5",
  icon: "🏘️",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal","Dashboard","Tableau de Bord","Dashboard","Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Propiedades Gestionadas","Managed Properties","Propriétés Gérées","Verwaltete Immobilien","Proprietà Gestite"), value: "312", change: "+18", trend: "up" },
        { label: t5("Tasa de Ocupación","Occupancy Rate","Taux d'Occupation","Auslastungsrate","Tasso di Occupazione"), value: "94%", change: "+2%", trend: "up" },
        { label: t5("Ingresos del Mes","Monthly Revenue","Revenus du Mois","Monatsumsatz","Entrate del Mese"), value: "€186,400", change: "+8%", trend: "up" },
        { label: t5("Incidencias Abiertas","Open Issues","Incidents Ouverts","Offene Vorfälle","Incidenze Aperte"), value: "23", change: "-5", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad","Activity","Activité","Aktivität","Attività"), type: "text" },
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "inquilino", label: t5("Inquilino","Tenant","Locataire","Mieter","Inquilino"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Pago": "green", "Contrato": "blue", "Mantenimiento": "yellow", "Incidencia": "red" } },
        ],
        rows: [
          { actividad: "Renta cobrada", propiedad: "Apt. 4B - Edificio Sol", inquilino: "Carmen Vidal", fecha: "2026-03-07", tipo: "Pago" },
          { actividad: "Contrato renovado", propiedad: "Local 2 - Plaza Mayor", inquilino: "Café Europa SL", fecha: "2026-03-07", tipo: "Contrato" },
          { actividad: "Reparación fontanería", propiedad: "Piso 3A - C/ Luna 8", inquilino: "Jorge Ruiz", fecha: "2026-03-06", tipo: "Mantenimiento" },
          { actividad: "Queja de ruido", propiedad: "Apt. 2C - Edificio Sol", inquilino: "María Ortega", fecha: "2026-03-06", tipo: "Incidencia" },
          { actividad: "Nuevo contrato firmado", propiedad: "Oficina 5 - Torre Norte", inquilino: "TechStart SL", fecha: "2026-03-05", tipo: "Contrato" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...","Search recent activity...","Rechercher activité récente...","Letzte Aktivität suchen...","Cerca attività recente..."),
      },
    },
    {
      id: "properties",
      label: t5("Propiedades","Properties","Propriétés","Immobilien","Proprietà"),
      icon: "home",
      kpis: [
        { label: t5("Total Propiedades","Total Properties","Total Propriétés","Immobilien Gesamt","Proprietà Totali"), value: "312", change: "+18", trend: "up" },
        { label: t5("Ocupadas","Occupied","Occupées","Belegt","Occupate"), value: "293", change: "+12", trend: "up" },
        { label: t5("Vacantes","Vacant","Vacantes","Leer","Vacanti"), value: "19", change: "-6", trend: "up" },
        { label: t5("Valor Medio Renta","Average Rent","Loyer Moyen","Durchschnittsmiete","Affitto Medio"), value: t5("€598/mes","€598/mo","€598/mois","€598/Mon","€598/mese"), change: "+€22", trend: "up" },
      ],
      table: {
        columns: [
          { key: "referencia", label: t5("Ref.","Ref.","Réf.","Ref.","Rif."), type: "text" },
          { key: "direccion", label: t5("Dirección","Address","Adresse","Adresse","Indirizzo"), type: "text" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Residencial": "blue", "Comercial": "orange", "Oficina": "purple", "Garaje": "gray" } },
          { key: "superficie", label: t5("Superficie","Area","Surface","Fläche","Superficie"), type: "text" },
          { key: "renta", label: t5("Renta/Mes","Rent/Month","Loyer/Mois","Miete/Monat","Affitto/Mese"), type: "currency" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Ocupada": "green", "Vacante": "yellow", "En Reforma": "orange", "No Disponible": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { referencia: "RF-001", direccion: "Apt. 4B, Edificio Sol, C/ Mayor 12", tipo: "Residencial", superficie: "85 m²", renta: 750, estado: "Ocupada" },
          { referencia: "RF-002", direccion: "Local 2, Plaza Mayor 5", tipo: "Comercial", superficie: "120 m²", renta: 1800, estado: "Ocupada" },
          { referencia: "RF-003", direccion: "Piso 3A, C/ Luna 8", tipo: "Residencial", superficie: "65 m²", renta: 580, estado: "Ocupada" },
          { referencia: "RF-004", direccion: "Oficina 5, Torre Norte, Piso 8", tipo: "Oficina", superficie: "200 m²", renta: 2400, estado: "Ocupada" },
          { referencia: "RF-005", direccion: "Apt. 1A, Edificio Mar, Av. Costa 3", tipo: "Residencial", superficie: "70 m²", renta: 620, estado: "Vacante" },
          { referencia: "RF-006", direccion: "Plaza Garaje 24, Edificio Sol", tipo: "Garaje", superficie: "15 m²", renta: 80, estado: "En Reforma" },
        ],
        searchPlaceholder: t5("Buscar propiedades...","Search properties...","Rechercher des propriétés...","Immobilien suchen...","Cerca proprietà..."),
      },
      modal: {
        title: t5("Nueva Propiedad","New Property","Nouvelle Propriété","Neue Immobilie","Nuova Proprietà"),
        fields: [
          { name: "direccion", label: t5("Dirección","Address","Adresse","Adresse","Indirizzo"), type: "text", required: true, placeholder: t5("Dirección completa","Full address","Adresse complète","Vollständige Adresse","Indirizzo completo") },
          { name: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "select", required: true, options: [
            { value: "residencial", label: t5("Residencial","Residential","Résidentiel","Wohn","Residenziale") },
            { value: "comercial", label: t5("Comercial","Commercial","Commercial","Gewerbe","Commerciale") },
            { value: "oficina", label: t5("Oficina","Office","Bureau","Büro","Ufficio") },
            { value: "garaje", label: t5("Garaje","Garage","Garage","Garage","Garage") },
          ]},
          { name: "superficie", label: t5("Superficie (m²)","Area (m²)","Surface (m²)","Fläche (m²)","Superficie (m²)"), type: "number", required: true, placeholder: "85" },
          { name: "habitaciones", label: t5("Habitaciones","Bedrooms","Chambres","Schlafzimmer","Camere"), type: "number", required: false, placeholder: "2" },
          { name: "renta", label: t5("Renta Mensual (€)","Monthly Rent (€)","Loyer Mensuel (€)","Monatsmiete (€)","Affitto Mensile (€)"), type: "number", required: true, placeholder: "750" },
          { name: "deposito", label: t5("Depósito (€)","Deposit (€)","Dépôt (€)","Kaution (€)","Deposito (€)"), type: "number", required: true, placeholder: "1500" },
          { name: "descripcion", label: t5("Descripción","Description","Description","Beschreibung","Descrizione"), type: "textarea", required: false, placeholder: t5("Descripción de la propiedad...","Property description...","Description de la propriété...","Beschreibung der Immobilie...","Descrizione della proprietà...") },
        ],
      },
    },
    {
      id: "tenants_module",
      label: t5("Inquilinos","Tenants","Locataires","Mieter","Inquilini"),
      icon: "users",
      kpis: [
        { label: t5("Total Inquilinos","Total Tenants","Total Locataires","Mieter Gesamt","Inquilini Totali"), value: "287", change: "+14", trend: "up" },
        { label: t5("Al Corriente de Pago","Up to Date","À Jour de Paiement","Zahlungen Aktuell","In Regola coi Pagamenti"), value: "268", change: "+8", trend: "up" },
        { label: t5("Con Retraso","Late","En Retard","Verspätet","In Ritardo"), value: "19", change: "-3", trend: "up" },
        { label: t5("Antigüedad Media","Average Tenure","Ancienneté Moyenne","Durchschnittliche Mietdauer","Anzianità Media"), value: t5("2.4 años","2.4 years","2,4 ans","2,4 Jahre","2,4 anni"), change: "+0.2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "avatar" },
          { key: "email", label: "Email", type: "text" },
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "renta", label: t5("Renta","Rent","Loyer","Miete","Affitto"), type: "currency" },
          { key: "contrato_fin", label: t5("Fin Contrato","Lease End","Fin du Bail","Vertragsende","Fine Contratto"), type: "date" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Al Corriente": "green", "Retraso": "red", "Nuevo": "blue" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Carmen Vidal", email: "c.vidal@email.com", propiedad: "Apt. 4B - Edificio Sol", renta: 750, contrato_fin: "2027-06-30", estado: "Al Corriente" },
          { nombre: "Café Europa SL", email: "admin@cafeeuropa.es", propiedad: "Local 2 - Plaza Mayor", renta: 1800, contrato_fin: "2028-12-31", estado: "Al Corriente" },
          { nombre: "Jorge Ruiz", email: "j.ruiz@email.com", propiedad: "Piso 3A - C/ Luna 8", renta: 580, contrato_fin: "2026-09-15", estado: "Retraso" },
          { nombre: "TechStart SL", email: "info@techstart.es", propiedad: "Oficina 5 - Torre Norte", renta: 2400, contrato_fin: "2029-03-01", estado: "Nuevo" },
          { nombre: "María Ortega", email: "m.ortega@email.com", propiedad: "Apt. 2C - Edificio Sol", renta: 720, contrato_fin: "2026-12-31", estado: "Al Corriente" },
        ],
        searchPlaceholder: t5("Buscar inquilinos...","Search tenants...","Rechercher des locataires...","Mieter suchen...","Cerca inquilini..."),
      },
      modal: {
        title: t5("Nuevo Inquilino","New Tenant","Nouveau Locataire","Neuer Mieter","Nuovo Inquilino"),
        fields: [
          { name: "nombre", label: t5("Nombre / Razón Social","Name / Company","Nom / Raison Sociale","Name / Firma","Nome / Ragione Sociale"), type: "text", required: true, placeholder: t5("Nombre o empresa","Name or company","Nom ou entreprise","Name oder Firma","Nome o azienda") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("inquilino@email.com","tenant@email.com","locataire@email.com","mieter@email.com","inquilino@email.com") },
          { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "dni_cif", label: t5("DNI / CIF","ID / Tax Number","DNI / SIRET","Ausweis / Steuernummer","CF / P.IVA"), type: "text", required: true, placeholder: "12345678A" },
          { name: "propiedad", label: t5("Propiedad Asignada","Assigned Property","Propriété Assignée","Zugewiesene Immobilie","Proprietà Assegnata"), type: "text", required: true, placeholder: t5("Referencia de la propiedad","Property reference","Référence de la propriété","Immobilienreferenz","Riferimento della proprietà") },
          { name: "fecha_entrada", label: t5("Fecha de Entrada","Move-in Date","Date d'Entrée","Einzugsdatum","Data di Ingresso"), type: "date", required: true },
        ],
      },
    },
    {
      id: "leases",
      label: t5("Contratos","Leases","Baux","Mietverträge","Contratti"),
      icon: "file",
      kpis: [
        { label: t5("Contratos Activos","Active Leases","Baux Actifs","Aktive Mietverträge","Contratti Attivi"), value: "287", change: "+14", trend: "up" },
        { label: t5("Renovaciones Pendientes","Pending Renewals","Renouvellements en Attente","Ausstehende Verlängerungen","Rinnovi in Sospeso"), value: "18", change: "+5", trend: "down" },
        { label: t5("Vencen Este Mes","Expiring This Month","Expirent Ce Mois","Laufen Diesen Monat Aus","Scadono Questo Mese"), value: "8", change: "+2", trend: "down" },
        { label: t5("Duración Media","Average Duration","Durée Moyenne","Durchschnittliche Dauer","Durata Media"), value: t5("3.2 años","3.2 years","3,2 ans","3,2 Jahre","3,2 anni"), change: "+0.3", trend: "up" },
      ],
      table: {
        columns: [
          { key: "inquilino", label: t5("Inquilino","Tenant","Locataire","Mieter","Inquilino"), type: "text" },
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "inicio", label: t5("Inicio","Start","Début","Beginn","Inizio"), type: "date" },
          { key: "fin", label: t5("Fin","End","Fin","Ende","Fine"), type: "date" },
          { key: "renta", label: t5("Renta","Rent","Loyer","Miete","Affitto"), type: "currency" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activo": "green", "Vencido": "red", "Renovación": "yellow", "Terminado": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { inquilino: "Carmen Vidal", propiedad: "Apt. 4B - Edificio Sol", inicio: "2024-07-01", fin: "2027-06-30", renta: 750, estado: "Activo" },
          { inquilino: "Café Europa SL", propiedad: "Local 2 - Plaza Mayor", inicio: "2024-01-01", fin: "2028-12-31", renta: 1800, estado: "Activo" },
          { inquilino: "Jorge Ruiz", propiedad: "Piso 3A - C/ Luna 8", inicio: "2023-09-15", fin: "2026-09-15", renta: 580, estado: "Renovación" },
          { inquilino: "TechStart SL", propiedad: "Oficina 5 - Torre Norte", inicio: "2026-03-01", fin: "2029-03-01", renta: 2400, estado: "Activo" },
          { inquilino: "Antiguo Inquilino SL", propiedad: "Local 3 - C/ Estrella 7", inicio: "2022-01-01", fin: "2025-12-31", renta: 1200, estado: "Vencido" },
          { inquilino: "Familia Rodríguez", propiedad: "Piso 1B - C/ Luna 8", inicio: "2021-06-01", fin: "2026-01-31", renta: 550, estado: "Terminado" },
        ],
        searchPlaceholder: t5("Buscar contratos...","Search leases...","Rechercher des baux...","Mietverträge suchen...","Cerca contratti..."),
      },
      modal: {
        title: t5("Nuevo Contrato","New Lease","Nouveau Bail","Neuer Mietvertrag","Nuovo Contratto"),
        fields: [
          { name: "inquilino", label: t5("Inquilino","Tenant","Locataire","Mieter","Inquilino"), type: "text", required: true, placeholder: t5("Nombre del inquilino","Tenant name","Nom du locataire","Name des Mieters","Nome dell'inquilino") },
          { name: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text", required: true, placeholder: t5("Referencia de la propiedad","Property reference","Référence de la propriété","Immobilienreferenz","Riferimento della proprietà") },
          { name: "fecha_inicio", label: t5("Fecha de Inicio","Start Date","Date de Début","Startdatum","Data di Inizio"), type: "date", required: true },
          { name: "fecha_fin", label: t5("Fecha de Fin","End Date","Date de Fin","Enddatum","Data di Fine"), type: "date", required: true },
          { name: "renta", label: t5("Renta Mensual (€)","Monthly Rent (€)","Loyer Mensuel (€)","Monatsmiete (€)","Affitto Mensile (€)"), type: "number", required: true, placeholder: "750" },
          { name: "deposito", label: t5("Depósito (€)","Deposit (€)","Dépôt (€)","Kaution (€)","Deposito (€)"), type: "number", required: true, placeholder: "1500" },
          { name: "clausulas", label: t5("Cláusulas Especiales","Special Clauses","Clauses Spéciales","Sonderklauseln","Clausole Speciali"), type: "textarea", required: false, placeholder: t5("Cláusulas adicionales del contrato...","Additional contract clauses...","Clauses supplémentaires du contrat...","Zusätzliche Vertragsklauseln...","Clausole aggiuntive del contratto...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "estado", filterValue: "" },
        { id: "activos", label: t5("Activos","Active","Actifs","Aktiv","Attivi"), filterField: "estado", filterValue: "Activo" },
        { id: "vencidos", label: t5("Vencidos","Expired","Échus","Abgelaufen","Scaduti"), filterField: "estado", filterValue: "Vencido" },
        { id: "renovacion", label: t5("Renovación","Renewal","Renouvellement","Verlängerung","Rinnovo"), filterField: "estado", filterValue: "Renovación" },
        { id: "terminados", label: t5("Terminados","Terminated","Terminés","Beendet","Terminati"), filterField: "estado", filterValue: "Terminado" },
      ],
    },
    {
      id: "maintenance",
      label: t5("Mantenimiento","Maintenance","Maintenance","Wartung","Manutenzione"),
      icon: "tool",
      kpis: [
        { label: t5("Solicitudes Abiertas","Open Requests","Demandes Ouvertes","Offene Anfragen","Richieste Aperte"), value: "23", change: "-5", trend: "up" },
        { label: t5("Resueltas Este Mes","Resolved This Month","Résolues Ce Mois","Diesen Monat Gelöst","Risolte Questo Mese"), value: "45", change: "+12", trend: "up" },
        { label: t5("Tiempo Medio Resolución","Avg. Resolution Time","Temps Moyen de Résolution","Durchschnittliche Lösungszeit","Tempo Medio Risoluzione"), value: t5("3.2 días","3.2 days","3,2 jours","3,2 Tage","3,2 giorni"), change: "-0.5", trend: "up" },
        { label: t5("Coste Mensual","Monthly Cost","Coût Mensuel","Monatliche Kosten","Costo Mensile"), value: "€8,400", change: "-€600", trend: "up" },
      ],
      table: {
        columns: [
          { key: "ticket", label: "Ticket", type: "text" },
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "descripcion", label: t5("Descripción","Description","Description","Beschreibung","Descrizione"), type: "text" },
          { key: "prioridad", label: t5("Prioridad","Priority","Priorité","Priorität","Priorità"), type: "badge", badgeColors: { "Urgente": "red", "Alta": "orange", "Normal": "blue", "Baja": "gray" } },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Pendiente": "yellow", "En Proceso": "blue", "Resuelto": "green", "Cerrado": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { ticket: "MNT-089", propiedad: "Piso 3A - C/ Luna 8", descripcion: "Fuga en tubería del baño", prioridad: "Urgente", fecha: "2026-03-06", estado: "En Proceso" },
          { ticket: "MNT-088", propiedad: "Apt. 2C - Edificio Sol", descripcion: "Caldera no enciende", prioridad: "Alta", fecha: "2026-03-05", estado: "Pendiente" },
          { ticket: "MNT-087", propiedad: "Local 2 - Plaza Mayor", descripcion: "Pintura fachada deteriorada", prioridad: "Normal", fecha: "2026-03-04", estado: "En Proceso" },
          { ticket: "MNT-086", propiedad: "Apt. 4B - Edificio Sol", descripcion: "Cambio de cerradura", prioridad: "Baja", fecha: "2026-03-03", estado: "Resuelto" },
          { ticket: "MNT-085", propiedad: "Oficina 5 - Torre Norte", descripcion: "Aire acondicionado averiado", prioridad: "Alta", fecha: "2026-03-02", estado: "Resuelto" },
          { ticket: "MNT-084", propiedad: "Garaje 24 - Edificio Sol", descripcion: "Puerta automática no funciona", prioridad: "Normal", fecha: "2026-03-01", estado: "Cerrado" },
        ],
        searchPlaceholder: t5("Buscar solicitudes...","Search requests...","Rechercher des demandes...","Anfragen suchen...","Cerca richieste..."),
      },
      modal: {
        title: t5("Nueva Solicitud","New Request","Nouvelle Demande","Neue Anfrage","Nuova Richiesta"),
        fields: [
          { name: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text", required: true, placeholder: t5("Referencia de la propiedad","Property reference","Référence de la propriété","Immobilienreferenz","Riferimento della proprietà") },
          { name: "descripcion", label: t5("Descripción del Problema","Problem Description","Description du Problème","Problembeschreibung","Descrizione del Problema"), type: "textarea", required: true, placeholder: t5("Describa el problema en detalle...","Describe the problem in detail...","Décrivez le problème en détail...","Beschreiben Sie das Problem im Detail...","Descriva il problema in dettaglio...") },
          { name: "prioridad", label: t5("Prioridad","Priority","Priorité","Priorität","Priorità"), type: "select", required: true, options: [
            { value: "urgente", label: t5("Urgente","Urgent","Urgent","Dringend","Urgente") },
            { value: "alta", label: t5("Alta","High","Haute","Hoch","Alta") },
            { value: "normal", label: "Normal" },
            { value: "baja", label: t5("Baja","Low","Basse","Niedrig","Bassa") },
          ]},
          { name: "categoria", label: t5("Categoría","Category","Catégorie","Kategorie","Categoria"), type: "select", required: true, options: [
            { value: "fontaneria", label: t5("Fontanería","Plumbing","Plomberie","Sanitär","Idraulica") },
            { value: "electricidad", label: t5("Electricidad","Electrical","Électricité","Elektrik","Elettricità") },
            { value: "climatizacion", label: t5("Climatización","HVAC","Climatisation","Klimatisierung","Climatizzazione") },
            { value: "cerrajeria", label: t5("Cerrajería","Locksmith","Serrurerie","Schlüsseldienst","Fabbro") },
            { value: "pintura", label: t5("Pintura","Painting","Peinture","Malerei","Pittura") },
            { value: "otro", label: t5("Otro","Other","Autre","Andere","Altro") },
          ]},
          { name: "contacto", label: t5("Contacto del Inquilino","Tenant Contact","Contact du Locataire","Kontakt des Mieters","Contatto dell'Inquilino"), type: "tel", required: true, placeholder: "+34 600 000 000" },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas","All","Toutes","Alle","Tutte"), filterField: "estado", filterValue: "" },
        { id: "pendientes", label: t5("Pendientes","Pending","En Attente","Ausstehend","In Sospeso"), filterField: "estado", filterValue: "Pendiente" },
        { id: "en_proceso", label: t5("En Proceso","In Progress","En Cours","In Bearbeitung","In Corso"), filterField: "estado", filterValue: "En Proceso" },
        { id: "resueltas", label: t5("Resueltas","Resolved","Résolues","Gelöst","Risolte"), filterField: "estado", filterValue: "Resuelto" },
      ],
    },
    {
      id: "payments",
      label: t5("Pagos","Payments","Paiements","Zahlungen","Pagamenti"),
      icon: "dollar",
      kpis: [
        { label: t5("Cobrado Este Mes","Collected This Month","Encaissé Ce Mois","Diesen Monat Eingezogen","Incassato Questo Mese"), value: "€186,400", change: "+8%", trend: "up" },
        { label: t5("Pendiente de Cobro","Pending Collection","En Attente d'Encaissement","Ausstehende Einzüge","In Attesa di Incasso"), value: "€12,300", change: "-€2,100", trend: "up" },
        { label: t5("Morosidad","Delinquency","Impayés","Zahlungsverzug","Morosità"), value: "6.6%", change: "-1%", trend: "up" },
        { label: t5("Gastos del Mes","Monthly Expenses","Dépenses du Mois","Monatliche Ausgaben","Spese del Mese"), value: "€34,200", change: "-€1,800", trend: "up" },
      ],
      table: {
        columns: [
          { key: "inquilino", label: t5("Inquilino","Tenant","Locataire","Mieter","Inquilino"), type: "text" },
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "concepto", label: t5("Concepto","Concept","Concept","Konzept","Concetto"), type: "text" },
          { key: "monto", label: t5("Monto","Amount","Montant","Betrag","Importo"), type: "currency" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Cobrado": "green", "Pendiente": "yellow", "Vencido": "red", "Parcial": "orange" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { inquilino: "Carmen Vidal", propiedad: "Apt. 4B - Edificio Sol", concepto: "Renta Marzo 2026", monto: 750, fecha: "2026-03-01", estado: "Cobrado" },
          { inquilino: "Café Europa SL", propiedad: "Local 2 - Plaza Mayor", concepto: "Renta Marzo 2026", monto: 1800, fecha: "2026-03-01", estado: "Cobrado" },
          { inquilino: "Jorge Ruiz", propiedad: "Piso 3A - C/ Luna 8", concepto: "Renta Marzo 2026", monto: 580, fecha: "2026-03-01", estado: "Vencido" },
          { inquilino: "TechStart SL", propiedad: "Oficina 5 - Torre Norte", concepto: "Renta Marzo 2026", monto: 2400, fecha: "2026-03-01", estado: "Cobrado" },
          { inquilino: "María Ortega", propiedad: "Apt. 2C - Edificio Sol", concepto: "Renta Marzo 2026", monto: 720, fecha: "2026-03-01", estado: "Pendiente" },
        ],
        searchPlaceholder: t5("Buscar pagos...","Search payments...","Rechercher des paiements...","Zahlungen suchen...","Cerca pagamenti..."),
      },
      modal: {
        title: t5("Registrar Pago","Record Payment","Enregistrer un Paiement","Zahlung Erfassen","Registra Pagamento"),
        fields: [
          { name: "inquilino", label: t5("Inquilino","Tenant","Locataire","Mieter","Inquilino"), type: "text", required: true, placeholder: t5("Nombre del inquilino","Tenant name","Nom du locataire","Name des Mieters","Nome dell'inquilino") },
          { name: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text", required: true, placeholder: t5("Referencia de la propiedad","Property reference","Référence de la propriété","Immobilienreferenz","Riferimento della proprietà") },
          { name: "concepto", label: t5("Concepto","Concept","Concept","Konzept","Concetto"), type: "text", required: true, placeholder: t5("Renta Mes Año","Rent Month Year","Loyer Mois Année","Miete Monat Jahr","Affitto Mese Anno") },
          { name: "monto", label: t5("Monto (€)","Amount (€)","Montant (€)","Betrag (€)","Importo (€)"), type: "number", required: true, placeholder: "750" },
          { name: "fecha", label: t5("Fecha de Pago","Payment Date","Date de Paiement","Zahlungsdatum","Data di Pagamento"), type: "date", required: true },
          { name: "metodo", label: t5("Método de Pago","Payment Method","Méthode de Paiement","Zahlungsmethode","Metodo di Pagamento"), type: "select", required: true, options: [
            { value: "transferencia", label: t5("Transferencia","Transfer","Virement","Überweisung","Bonifico") },
            { value: "domiciliacion", label: t5("Domiciliación","Direct Debit","Prélèvement","Lastschrift","Addebito Diretto") },
            { value: "efectivo", label: t5("Efectivo","Cash","Espèces","Bargeld","Contanti") },
            { value: "tarjeta", label: t5("Tarjeta","Card","Carte","Karte","Carta") },
          ]},
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "estado", filterValue: "" },
        { id: "cobrados", label: t5("Cobrados","Collected","Encaissés","Eingezogen","Incassati"), filterField: "estado", filterValue: "Cobrado" },
        { id: "pendientes", label: t5("Pendientes","Pending","En Attente","Ausstehend","In Sospeso"), filterField: "estado", filterValue: "Pendiente" },
        { id: "vencidos", label: t5("Vencidos","Overdue","Échus","Überfällig","Scaduti"), filterField: "estado", filterValue: "Vencido" },
      ],
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Gestoras","Management Companies","Sociétés de Gestion","Verwaltungsgesellschaften","Società di Gestione"),
        icon: "building",
        kpis: [
          { label: t5("Total Gestoras","Total Companies","Total Sociétés","Gesellschaften Gesamt","Società Totali"), value: "28", change: "+4", trend: "up" },
          { label: t5("Activas","Active","Actives","Aktiv","Attive"), value: "25", change: "+3", trend: "up" },
          { label: t5("Propiedades Totales","Total Properties","Total Propriétés","Immobilien Gesamt","Proprietà Totali"), value: "8,736", change: "+504", trend: "up" },
          { label: "MRR", value: "€22,600", change: "+€2,800", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Gestora","Company","Société","Gesellschaft","Società"), type: "text" },
            { key: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "badge", badgeColors: { "Enterprise": "purple", "Profesional": "blue", "Básico": "gray" } },
            { key: "propiedades", label: t5("Propiedades","Properties","Propriétés","Immobilien","Proprietà"), type: "text" },
            { key: "inquilinos", label: t5("Inquilinos","Tenants","Locataires","Mieter","Inquilini"), type: "text" },
            { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activa": "green", "Suspendida": "red", "Trial": "yellow" } },
            { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "Gestión Inmobiliaria Mediterránea", plan: "Enterprise", propiedades: 1200, inquilinos: 1100, estado: "Activa" },
            { nombre: "AdminFincas Pro", plan: "Profesional", propiedades: 450, inquilinos: 420, estado: "Activa" },
            { nombre: "PropTech Gestión", plan: "Enterprise", propiedades: 890, inquilinos: 830, estado: "Activa" },
            { nombre: "MiCasa Admin", plan: "Básico", propiedades: 65, inquilinos: 58, estado: "Trial" },
            { nombre: "Urban Property Group", plan: "Profesional", propiedades: 320, inquilinos: 295, estado: "Activa" },
          ],
          searchPlaceholder: t5("Buscar gestoras...","Search companies...","Rechercher des sociétés...","Gesellschaften suchen...","Cerca società..."),
        },
        modal: {
          title: t5("Nueva Gestora","New Company","Nouvelle Société","Neue Gesellschaft","Nuova Società"),
          fields: [
            { name: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "text", required: true, placeholder: t5("Nombre de la gestora","Company name","Nom de la société","Name der Gesellschaft","Nome della società") },
            { name: "email_admin", label: "Email Admin", type: "email", required: true, placeholder: t5("admin@gestora.com","admin@company.com","admin@societe.com","admin@gesellschaft.com","admin@societa.com") },
            { name: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico","Basic","Basique","Basis","Base") },
              { value: "profesional", label: t5("Profesional","Professional","Professionnel","Professionell","Professionale") },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "max_propiedades", label: t5("Máx. Propiedades","Max. Properties","Max. Propriétés","Max. Immobilien","Max. Proprietà"), type: "number", required: true, placeholder: "500" },
          ],
        },
      },
    ],
  },
};
