import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const realEstate: SystemConfig = {
  name: "PropManager",
  subtitle: t5("Bienes Raices","Real Estate","Immobilier","Immobilien","Immobiliare"),
  brandColor: "#059669",
  icon: "🏠",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal","Dashboard","Tableau de Bord","Dashboard","Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Propiedades Activas","Active Properties","Propriétés Actives","Aktive Immobilien","Proprietà Attive"), value: "186", change: "+12", trend: "up" },
        { label: t5("Ventas del Mes","Monthly Sales","Ventes du Mois","Monatliche Verkäufe","Vendite del Mese"), value: "€2.4M", change: "+18%", trend: "up" },
        { label: t5("Leads Nuevos","New Leads","Nouveaux Leads","Neue Leads","Nuovi Lead"), value: "94", change: "+23", trend: "up" },
        { label: t5("Visitas Programadas","Scheduled Viewings","Visites Programmées","Geplante Besichtigungen","Visite Programmate"), value: "47", change: "+8", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad","Activity","Activité","Aktivität","Attività"), type: "text" },
          { key: "agente", label: t5("Agente","Agent","Agent","Makler","Agente"), type: "text" },
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Venta": "green", "Visita": "blue", "Lead": "purple", "Oferta": "yellow" } },
        ],
        rows: [
          { actividad: "Propiedad vendida", agente: "Roberto Navarro", propiedad: "Ático C/ Gran Vía 45", fecha: "2026-03-07", tipo: "Venta" },
          { actividad: "Nueva visita agendada", agente: "Clara Jiménez", propiedad: "Piso C/ Serrano 12", fecha: "2026-03-07", tipo: "Visita" },
          { actividad: "Lead cualificado", agente: "Miguel Herrera", propiedad: "Local Av. Diagonal 89", fecha: "2026-03-06", tipo: "Lead" },
          { actividad: "Oferta recibida", agente: "Elena Ruiz", propiedad: "Casa Urb. Los Robles", fecha: "2026-03-06", tipo: "Oferta" },
          { actividad: "Visita completada", agente: "Roberto Navarro", propiedad: "Oficina Pº Castellana 22", fecha: "2026-03-05", tipo: "Visita" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...","Search recent activity...","Rechercher activité récente...","Letzte Aktivität suchen...","Cerca attività recente..."),
      },
    },
    {
      id: "properties",
      label: t5("Propiedades","Properties","Propriétés","Immobilien","Proprietà"),
      icon: "home",
      kpis: [
        { label: t5("Total Propiedades","Total Properties","Total Propriétés","Immobilien Gesamt","Proprietà Totali"), value: "186", change: "+12", trend: "up" },
        { label: t5("En Venta","For Sale","En Vente","Zum Verkauf","In Vendita"), value: "98", change: "+5", trend: "up" },
        { label: t5("En Alquiler","For Rent","En Location","Zur Miete","In Affitto"), value: "64", change: "+3", trend: "up" },
        { label: t5("Valor Total Cartera","Total Portfolio Value","Valeur Totale du Portefeuille","Gesamtwert des Portfolios","Valore Totale Portafoglio"), value: "€48.5M", change: "+€3.2M", trend: "up" },
      ],
      table: {
        columns: [
          { key: "referencia", label: t5("Ref.","Ref.","Réf.","Ref.","Rif."), type: "text" },
          { key: "direccion", label: t5("Dirección","Address","Adresse","Adresse","Indirizzo"), type: "text" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Apartamento": "blue", "Casa": "green", "Local": "orange", "Oficina": "purple", "Terreno": "gray" } },
          { key: "superficie", label: t5("Superficie","Area","Surface","Fläche","Superficie"), type: "text" },
          { key: "precio", label: t5("Precio","Price","Prix","Preis","Prezzo"), type: "currency" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "En Venta": "blue", "Vendida": "green", "Alquilada": "purple", "Reservada": "yellow" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { referencia: "PROP-001", direccion: "C/ Gran Vía 45, 8ºA, Madrid", tipo: "Apartamento", superficie: "120 m²", precio: 385000, estado: "En Venta" },
          { referencia: "PROP-002", direccion: "Urb. Los Robles 12, Pozuelo", tipo: "Casa", superficie: "280 m²", precio: 650000, estado: "Reservada" },
          { referencia: "PROP-003", direccion: "Av. Diagonal 89, Barcelona", tipo: "Local", superficie: "95 m²", precio: 220000, estado: "En Venta" },
          { referencia: "PROP-004", direccion: "Pº Castellana 22, 4ª planta", tipo: "Oficina", superficie: "200 m²", precio: 4500, estado: "Alquilada" },
          { referencia: "PROP-005", direccion: "Parcela 8, Polígono Norte", tipo: "Terreno", superficie: "1,500 m²", precio: 180000, estado: "En Venta" },
          { referencia: "PROP-006", direccion: "C/ Serrano 12, 3ºB, Madrid", tipo: "Apartamento", superficie: "85 m²", precio: 295000, estado: "Vendida" },
        ],
        searchPlaceholder: t5("Buscar propiedades...","Search properties...","Rechercher des propriétés...","Immobilien suchen...","Cerca proprietà..."),
      },
      modal: {
        title: t5("Nueva Propiedad","New Property","Nouvelle Propriété","Neue Immobilie","Nuova Proprietà"),
        fields: [
          { name: "direccion", label: t5("Dirección","Address","Adresse","Adresse","Indirizzo"), type: "text", required: true, placeholder: t5("Dirección completa","Full address","Adresse complète","Vollständige Adresse","Indirizzo completo") },
          { name: "tipo", label: t5("Tipo de Propiedad","Property Type","Type de Propriété","Immobilientyp","Tipo di Proprietà"), type: "select", required: true, options: [
            { value: "apartamento", label: t5("Apartamento","Apartment","Appartement","Wohnung","Appartamento") },
            { value: "casa", label: t5("Casa","House","Maison","Haus","Casa") },
            { value: "local", label: t5("Local","Commercial","Local","Gewerbe","Locale") },
            { value: "oficina", label: t5("Oficina","Office","Bureau","Büro","Ufficio") },
            { value: "terreno", label: t5("Terreno","Land","Terrain","Grundstück","Terreno") },
          ]},
          { name: "superficie", label: t5("Superficie (m²)","Area (m²)","Surface (m²)","Fläche (m²)","Superficie (m²)"), type: "number", required: true, placeholder: "120" },
          { name: "habitaciones", label: t5("Habitaciones","Bedrooms","Chambres","Schlafzimmer","Camere"), type: "number", required: false, placeholder: "3" },
          { name: "banos", label: t5("Baños","Bathrooms","Salles de Bain","Badezimmer","Bagni"), type: "number", required: false, placeholder: "2" },
          { name: "precio", label: t5("Precio (€)","Price (€)","Prix (€)","Preis (€)","Prezzo (€)"), type: "number", required: true, placeholder: "350000" },
          { name: "operacion", label: t5("Operación","Operation","Opération","Vorgang","Operazione"), type: "select", required: true, options: [
            { value: "venta", label: t5("Venta","Sale","Vente","Verkauf","Vendita") },
            { value: "alquiler", label: t5("Alquiler","Rental","Location","Vermietung","Affitto") },
          ]},
          { name: "descripcion", label: t5("Descripción","Description","Description","Beschreibung","Descrizione"), type: "textarea", required: false, placeholder: t5("Descripción de la propiedad...","Property description...","Description de la propriété...","Beschreibung der Immobilie...","Descrizione della proprietà...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas","All","Toutes","Alle","Tutte"), filterField: "estado", filterValue: "" },
        { id: "en_venta", label: t5("En Venta","For Sale","En Vente","Zum Verkauf","In Vendita"), filterField: "estado", filterValue: "En Venta" },
        { id: "vendidas", label: t5("Vendidas","Sold","Vendues","Verkauft","Vendute"), filterField: "estado", filterValue: "Vendida" },
        { id: "alquiladas", label: t5("Alquiladas","Rented","Louées","Vermietet","Affittate"), filterField: "estado", filterValue: "Alquilada" },
        { id: "reservadas", label: t5("Reservadas","Reserved","Réservées","Reserviert","Riservate"), filterField: "estado", filterValue: "Reservada" },
      ],
    },
    {
      id: "listings",
      label: t5("Anuncios","Listings","Annonces","Anzeigen","Annunci"),
      icon: "globe",
      kpis: [
        { label: t5("Anuncios Activos","Active Listings","Annonces Actives","Aktive Anzeigen","Annunci Attivi"), value: "124", change: "+8", trend: "up" },
        { label: t5("Vistas Totales","Total Views","Vues Totales","Gesamtaufrufe","Visualizzazioni Totali"), value: "34,500", change: "+4,200", trend: "up" },
        { label: t5("Contactos Generados","Contacts Generated","Contacts Générés","Generierte Kontakte","Contatti Generati"), value: "186", change: "+32", trend: "up" },
        { label: t5("Tasa de Conversión","Conversion Rate","Taux de Conversion","Konversionsrate","Tasso di Conversione"), value: "5.4%", change: "+0.8%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "portal", label: "Portal", type: "text" },
          { key: "vistas", label: t5("Vistas","Views","Vues","Aufrufe","Visualizzazioni"), type: "text" },
          { key: "contactos", label: t5("Contactos","Contacts","Contacts","Kontakte","Contatti"), type: "text" },
          { key: "fecha_publicacion", label: t5("Publicado","Published","Publié","Veröffentlicht","Pubblicato"), type: "date" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activo": "green", "Pausado": "yellow", "Expirado": "red" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { propiedad: "Ático C/ Gran Vía 45", portal: "Idealista", vistas: 2340, contactos: 18, fecha_publicacion: "2026-02-15", estado: "Activo" },
          { propiedad: "Casa Urb. Los Robles", portal: "Fotocasa", vistas: 1890, contactos: 24, fecha_publicacion: "2026-02-20", estado: "Activo" },
          { propiedad: "Local Av. Diagonal 89", portal: "Idealista", vistas: 980, contactos: 8, fecha_publicacion: "2026-03-01", estado: "Activo" },
          { propiedad: "Piso C/ Serrano 12", portal: "Fotocasa", vistas: 3200, contactos: 32, fecha_publicacion: "2026-01-10", estado: "Pausado" },
          { propiedad: "Terreno Polígono Norte", portal: "Milanuncios", vistas: 450, contactos: 5, fecha_publicacion: "2026-02-28", estado: "Activo" },
        ],
        searchPlaceholder: t5("Buscar anuncios...","Search listings...","Rechercher des annonces...","Anzeigen suchen...","Cerca annunci..."),
      },
      modal: {
        title: t5("Nuevo Anuncio","New Listing","Nouvelle Annonce","Neue Anzeige","Nuovo Annuncio"),
        fields: [
          { name: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text", required: true, placeholder: t5("Seleccionar propiedad","Select property","Sélectionner la propriété","Immobilie auswählen","Seleziona proprietà") },
          { name: "portal", label: "Portal", type: "select", required: true, options: [
            { value: "idealista", label: "Idealista" },
            { value: "fotocasa", label: "Fotocasa" },
            { value: "milanuncios", label: "Milanuncios" },
            { value: "pisos", label: "Pisos.com" },
            { value: "web", label: t5("Web Propia","Own Website","Site Web","Eigene Website","Sito Web") },
          ]},
          { name: "titulo", label: t5("Título del Anuncio","Listing Title","Titre de l'Annonce","Anzeigentitel","Titolo dell'Annuncio"), type: "text", required: true, placeholder: t5("Título atractivo para el anuncio","Attractive listing title","Titre attractif pour l'annonce","Attraktiver Anzeigentitel","Titolo attraente per l'annuncio") },
          { name: "descripcion", label: t5("Descripción","Description","Description","Beschreibung","Descrizione"), type: "textarea", required: true, placeholder: t5("Descripción detallada...","Detailed description...","Description détaillée...","Detaillierte Beschreibung...","Descrizione dettagliata...") },
          { name: "destacado", label: t5("Anuncio Destacado","Featured Listing","Annonce en Vedette","Hervorgehobene Anzeige","Annuncio in Evidenza"), type: "checkbox", required: false },
        ],
      },
    },
    {
      id: "agents",
      label: t5("Agentes","Agents","Agents","Makler","Agenti"),
      icon: "briefcase",
      kpis: [
        { label: t5("Total Agentes","Total Agents","Total Agents","Makler Gesamt","Agenti Totali"), value: "24", change: "+2", trend: "up" },
        { label: t5("Ventas Este Mes","Sales This Month","Ventes Ce Mois","Verkäufe Diesen Monat","Vendite Questo Mese"), value: "18", change: "+5", trend: "up" },
        { label: t5("Comisiones del Mes","Monthly Commissions","Commissions du Mois","Monatliche Provisionen","Commissioni del Mese"), value: "€72,000", change: "+22%", trend: "up" },
        { label: t5("Media Ventas/Agente","Avg. Sales/Agent","Moy. Ventes/Agent","Durchschn. Verkäufe/Makler","Media Vendite/Agente"), value: "0.75", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "avatar" },
          { key: "email", label: "Email", type: "text" },
          { key: "zona", label: t5("Zona","Zone","Zone","Zone","Zona"), type: "text" },
          { key: "propiedades", label: t5("Propiedades","Properties","Propriétés","Immobilien","Proprietà"), type: "text" },
          { key: "ventas_mes", label: t5("Ventas/Mes","Sales/Month","Ventes/Mois","Verkäufe/Monat","Vendite/Mese"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activo": "green", "Vacaciones": "yellow", "Inactivo": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Roberto Navarro", email: "r.navarro@propmgr.com", zona: "Madrid Centro", propiedades: 32, ventas_mes: 3, estado: "Activo" },
          { nombre: "Clara Jiménez", email: "c.jimenez@propmgr.com", zona: "Madrid Norte", propiedades: 28, ventas_mes: 2, estado: "Activo" },
          { nombre: "Miguel Herrera", email: "m.herrera@propmgr.com", zona: "Barcelona", propiedades: 24, ventas_mes: 4, estado: "Activo" },
          { nombre: "Elena Ruiz", email: "e.ruiz@propmgr.com", zona: "Valencia", propiedades: 18, ventas_mes: 1, estado: "Activo" },
          { nombre: "Fernando López", email: "f.lopez@propmgr.com", zona: "Sevilla", propiedades: 15, ventas_mes: 0, estado: "Vacaciones" },
        ],
        searchPlaceholder: t5("Buscar agentes...","Search agents...","Rechercher des agents...","Makler suchen...","Cerca agenti..."),
      },
      modal: {
        title: t5("Nuevo Agente","New Agent","Nouvel Agent","Neuer Makler","Nuovo Agente"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo","Full Name","Nom Complet","Vollständiger Name","Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos","First and last name","Prénom et nom","Vor- und Nachname","Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("agente@inmobiliaria.com","agent@realestate.com","agent@immobilier.com","makler@immobilien.com","agente@immobiliare.com") },
          { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "zona", label: t5("Zona Asignada","Assigned Zone","Zone Assignée","Zugewiesene Zone","Zona Assegnata"), type: "select", required: true, options: [
            { value: "madrid_centro", label: "Madrid Centro" },
            { value: "madrid_norte", label: "Madrid Norte" },
            { value: "barcelona", label: "Barcelona" },
            { value: "valencia", label: "Valencia" },
            { value: "sevilla", label: "Sevilla" },
          ]},
          { name: "comision", label: t5("Comisión (%)","Commission (%)","Commission (%)","Provision (%)","Commissione (%)"), type: "number", required: true, placeholder: "3" },
        ],
      },
    },
    {
      id: "leads",
      label: "Leads",
      icon: "target",
      kpis: [
        { label: t5("Leads Totales","Total Leads","Total Leads","Leads Gesamt","Lead Totali"), value: "342", change: "+48", trend: "up" },
        { label: t5("Cualificados","Qualified","Qualifiés","Qualifiziert","Qualificati"), value: "128", change: "+18", trend: "up" },
        { label: t5("Tasa Conversión","Conversion Rate","Taux de Conversion","Konversionsrate","Tasso di Conversione"), value: "14%", change: "+2%", trend: "up" },
        { label: t5("Tiempo Respuesta","Response Time","Temps de Réponse","Antwortzeit","Tempo di Risposta"), value: "2.3h", change: "-0.5h", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "text" },
          { key: "email", label: "Email", type: "text" },
          { key: "interes", label: t5("Interés","Interest","Intérêt","Interesse","Interesse"), type: "text" },
          { key: "presupuesto", label: t5("Presupuesto","Budget","Budget","Budget","Budget"), type: "currency" },
          { key: "origen", label: t5("Origen","Source","Origine","Herkunft","Origine"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Nuevo": "blue", "Contactado": "yellow", "Cualificado": "green", "Descartado": "gray", "Convertido": "purple" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Andrés Molina", email: "a.molina@email.com", interes: "Apartamento 3 hab. Madrid", presupuesto: 400000, origen: "Idealista", estado: "Cualificado" },
          { nombre: "Patricia Sanz", email: "p.sanz@email.com", interes: "Casa con jardín", presupuesto: 550000, origen: "Fotocasa", estado: "Contactado" },
          { nombre: "David Ramos", email: "d.ramos@email.com", interes: "Local comercial centro", presupuesto: 200000, origen: "Web", estado: "Nuevo" },
          { nombre: "Silvia Moreno", email: "s.moreno@email.com", interes: "Oficina 150m²", presupuesto: 3000, origen: "Referido", estado: "Cualificado" },
          { nombre: "Javier Blanco", email: "j.blanco@email.com", interes: "Terreno urbanizable", presupuesto: 150000, origen: "Milanuncios", estado: "Descartado" },
        ],
        searchPlaceholder: t5("Buscar leads...","Search leads...","Rechercher des leads...","Leads suchen...","Cerca lead..."),
      },
      modal: {
        title: t5("Nuevo Lead","New Lead","Nouveau Lead","Neuer Lead","Nuovo Lead"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo","Full Name","Nom Complet","Vollständiger Name","Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos","First and last name","Prénom et nom","Vor- und Nachname","Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "lead@email.com" },
          { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "interes", label: t5("Interés","Interest","Intérêt","Interesse","Interesse"), type: "text", required: true, placeholder: t5("Qué tipo de propiedad busca","What type of property they're looking for","Quel type de propriété recherche-t-il","Welche Art von Immobilie wird gesucht","Che tipo di proprietà cerca") },
          { name: "presupuesto", label: t5("Presupuesto (€)","Budget (€)","Budget (€)","Budget (€)","Budget (€)"), type: "number", required: true, placeholder: "350000" },
          { name: "origen", label: t5("Origen","Source","Origine","Herkunft","Origine"), type: "select", required: true, options: [
            { value: "idealista", label: "Idealista" },
            { value: "fotocasa", label: "Fotocasa" },
            { value: "web", label: t5("Web Propia","Own Website","Site Web","Eigene Website","Sito Web") },
            { value: "referido", label: t5("Referido","Referral","Référence","Empfehlung","Referenza") },
            { value: "otro", label: t5("Otro","Other","Autre","Andere","Altro") },
          ]},
          { name: "notas", label: t5("Notas","Notes","Notes","Notizen","Note"), type: "textarea", required: false, placeholder: t5("Notas adicionales sobre el lead...","Additional notes about the lead...","Notes supplémentaires sur le lead...","Zusätzliche Anmerkungen zum Lead...","Note aggiuntive sul lead...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "estado", filterValue: "" },
        { id: "nuevos", label: t5("Nuevos","New","Nouveaux","Neu","Nuovi"), filterField: "estado", filterValue: "Nuevo" },
        { id: "contactados", label: t5("Contactados","Contacted","Contactés","Kontaktiert","Contattati"), filterField: "estado", filterValue: "Contactado" },
        { id: "cualificados", label: t5("Cualificados","Qualified","Qualifiés","Qualifiziert","Qualificati"), filterField: "estado", filterValue: "Cualificado" },
        { id: "convertidos", label: t5("Convertidos","Converted","Convertis","Konvertiert","Convertiti"), filterField: "estado", filterValue: "Convertido" },
      ],
    },
    {
      id: "viewings",
      label: t5("Visitas","Viewings","Visites","Besichtigungen","Visite"),
      icon: "calendar",
      kpis: [
        { label: t5("Visitas Programadas","Scheduled Viewings","Visites Programmées","Geplante Besichtigungen","Visite Programmate"), value: "47", change: "+8", trend: "up" },
        { label: t5("Realizadas Este Mes","Completed This Month","Réalisées Ce Mois","Diesen Monat Durchgeführt","Realizzate Questo Mese"), value: "124", change: "+15", trend: "up" },
        { label: t5("Tasa Conversión","Conversion Rate","Taux de Conversion","Konversionsrate","Tasso di Conversione"), value: "18%", change: "+3%", trend: "up" },
        { label: t5("Cancelaciones","Cancellations","Annulations","Stornierungen","Cancellazioni"), value: "5%", change: "-1%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text" },
          { key: "cliente", label: t5("Cliente","Client","Client","Kunde","Cliente"), type: "text" },
          { key: "agente", label: t5("Agente","Agent","Agent","Makler","Agente"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "hora", label: t5("Hora","Time","Heure","Uhrzeit","Ora"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Programada": "blue", "Realizada": "green", "Cancelada": "red", "No Asistió": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { propiedad: "Ático C/ Gran Vía 45", cliente: "Andrés Molina", agente: "Roberto Navarro", fecha: "2026-03-08", hora: "10:00", estado: "Programada" },
          { propiedad: "Casa Urb. Los Robles", cliente: "Patricia Sanz", agente: "Clara Jiménez", fecha: "2026-03-08", hora: "12:00", estado: "Programada" },
          { propiedad: "Piso C/ Serrano 12", cliente: "David Ramos", agente: "Miguel Herrera", fecha: "2026-03-07", hora: "16:00", estado: "Realizada" },
          { propiedad: "Oficina Pº Castellana", cliente: "Silvia Moreno", agente: "Elena Ruiz", fecha: "2026-03-07", hora: "11:00", estado: "Realizada" },
          { propiedad: "Local Av. Diagonal 89", cliente: "Javier Blanco", agente: "Roberto Navarro", fecha: "2026-03-06", hora: "15:00", estado: "Cancelada" },
        ],
        searchPlaceholder: t5("Buscar visitas...","Search viewings...","Rechercher des visites...","Besichtigungen suchen...","Cerca visite..."),
      },
      modal: {
        title: t5("Nueva Visita","New Viewing","Nouvelle Visite","Neue Besichtigung","Nuova Visita"),
        fields: [
          { name: "propiedad", label: t5("Propiedad","Property","Propriété","Immobilie","Proprietà"), type: "text", required: true, placeholder: t5("Referencia o dirección","Reference or address","Référence ou adresse","Referenz oder Adresse","Riferimento o indirizzo") },
          { name: "cliente", label: t5("Cliente","Client","Client","Kunde","Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente","Client name","Nom du client","Name des Kunden","Nome del cliente") },
          { name: "agente", label: t5("Agente","Agent","Agent","Makler","Agente"), type: "select", required: true, options: [
            { value: "navarro", label: "Roberto Navarro" },
            { value: "jimenez", label: "Clara Jiménez" },
            { value: "herrera", label: "Miguel Herrera" },
            { value: "ruiz", label: "Elena Ruiz" },
            { value: "lopez", label: "Fernando López" },
          ]},
          { name: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora","Time","Heure","Uhrzeit","Ora"), type: "time", required: true },
          { name: "notas", label: t5("Notas","Notes","Notes","Notizen","Note"), type: "textarea", required: false, placeholder: t5("Notas para la visita...","Notes for the viewing...","Notes pour la visite...","Anmerkungen zur Besichtigung...","Note per la visita...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas","All","Toutes","Alle","Tutte"), filterField: "estado", filterValue: "" },
        { id: "programadas", label: t5("Programadas","Scheduled","Programmées","Geplant","Programmate"), filterField: "estado", filterValue: "Programada" },
        { id: "realizadas", label: t5("Realizadas","Completed","Réalisées","Durchgeführt","Realizzate"), filterField: "estado", filterValue: "Realizada" },
        { id: "canceladas", label: t5("Canceladas","Cancelled","Annulées","Storniert","Cancellate"), filterField: "estado", filterValue: "Cancelada" },
      ],
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Inmobiliarias","Real Estate Agencies","Agences Immobilières","Immobilienagenturen","Agenzie Immobiliari"),
        icon: "building",
        kpis: [
          { label: t5("Total Inmobiliarias","Total Agencies","Total Agences","Agenturen Gesamt","Agenzie Totali"), value: "42", change: "+6", trend: "up" },
          { label: t5("Activas","Active","Actives","Aktiv","Attive"), value: "38", change: "+5", trend: "up" },
          { label: t5("Agentes Totales","Total Agents","Total Agents","Makler Gesamt","Agenti Totali"), value: "1,008", change: "+120", trend: "up" },
          { label: "MRR", value: "€28,400", change: "+€3,600", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Inmobiliaria","Agency","Agence","Agentur","Agenzia"), type: "text" },
            { key: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "badge", badgeColors: { "Enterprise": "purple", "Profesional": "blue", "Básico": "gray" } },
            { key: "agentes", label: t5("Agentes","Agents","Agents","Makler","Agenti"), type: "text" },
            { key: "propiedades", label: t5("Propiedades","Properties","Propriétés","Immobilien","Proprietà"), type: "text" },
            { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activa": "green", "Suspendida": "red", "Trial": "yellow" } },
            { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "Inmobiliaria Castilla", plan: "Enterprise", agentes: 85, propiedades: 620, estado: "Activa" },
            { nombre: "Fincas del Sol", plan: "Profesional", agentes: 32, propiedades: 240, estado: "Activa" },
            { nombre: "HomeFinder España", plan: "Enterprise", agentes: 120, propiedades: 890, estado: "Activa" },
            { nombre: "Pisos Rápido", plan: "Básico", agentes: 8, propiedades: 45, estado: "Trial" },
            { nombre: "Mediterranean Homes", plan: "Profesional", agentes: 45, propiedades: 310, estado: "Activa" },
          ],
          searchPlaceholder: t5("Buscar inmobiliarias...","Search agencies...","Rechercher des agences...","Agenturen suchen...","Cerca agenzie..."),
        },
        modal: {
          title: t5("Nueva Inmobiliaria","New Agency","Nouvelle Agence","Neue Agentur","Nuova Agenzia"),
          fields: [
            { name: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "text", required: true, placeholder: t5("Nombre de la inmobiliaria","Agency name","Nom de l'agence","Name der Agentur","Nome dell'agenzia") },
            { name: "email_admin", label: "Email Admin", type: "email", required: true, placeholder: t5("admin@inmobiliaria.com","admin@agency.com","admin@agence.com","admin@agentur.com","admin@agenzia.com") },
            { name: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico","Basic","Basique","Basis","Base") },
              { value: "profesional", label: t5("Profesional","Professional","Professionnel","Professionell","Professionale") },
              { value: "enterprise", label: "Enterprise" },
            ]},
            { name: "max_agentes", label: t5("Máx. Agentes","Max. Agents","Max. Agents","Max. Makler","Max. Agenti"), type: "number", required: true, placeholder: "50" },
          ],
        },
      },
    ],
  },
};
