import { t5 } from "../types";
import type { SystemConfig } from "../types";

export const salonSpa: SystemConfig = {
  name: t5("GlamourPro", "GlamourPro", "GlamourPro", "GlamourPro", "GlamourPro"),
  subtitle: t5("Salón y Spa", "Salon & Spa", "Salon & Spa", "Salon & Spa", "Salone & Spa"),
  brandColor: "#db2777",
  icon: "💅",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal", "Dashboard", "Tableau de Bord", "Übersicht", "Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Citas Hoy", "Appointments Today", "Rendez-vous Aujourd'hui", "Termine Heute", "Appuntamenti Oggi"), value: "28", change: "+5", trend: "up" },
        { label: t5("Ingresos del Día", "Daily Revenue", "Revenus du Jour", "Tagesumsatz", "Ricavi del Giorno"), value: "€2.840", change: "+12%", trend: "up" },
        { label: t5("Clientes Nuevos/Mes", "New Clients/Month", "Nouveaux Clients/Mois", "Neue Kunden/Monat", "Nuovi Clienti/Mese"), value: "34", change: "+8", trend: "up" },
        { label: t5("Ocupación", "Occupancy", "Occupation", "Auslastung", "Occupazione"), value: "85%", change: "+3%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad", "Activity", "Activité", "Aktivität", "Attività"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Client", "Client", "Kundin", "Cliente"), type: "text" },
          { key: "servicio", label: t5("Servicio", "Service", "Service", "Leistung", "Servizio"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Confirmada: "green", Completada: "blue", "No Show": "red", "Nueva cita": "yellow" } },
          { key: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "text" },
        ],
        rows: [
          { actividad: "Cita confirmada", cliente: "Lucía Fernández", servicio: "Corte + Color", estado: "Confirmada", hora: "10:00" },
          { actividad: "Servicio completado", cliente: "María Ruiz", servicio: "Manicura Gel", estado: "Completada", hora: "09:30" },
          { actividad: "No Show registrado", cliente: "Carmen Díaz", servicio: "Facial Hidratante", estado: "No Show", hora: "09:00" },
          { actividad: "Nueva cita reservada", cliente: "Isabel Moreno", servicio: "Masaje Relajante", estado: "Nueva cita", hora: "11:00" },
          { actividad: "Servicio completado", cliente: "Rosa Navarro", servicio: "Pedicura Spa", estado: "Completada", hora: "08:30" },
        ],
        searchPlaceholder: t5("Buscar actividad...", "Search activity...", "Rechercher activité...", "Aktivität suchen...", "Cerca attività..."),
      },
    },
    {
      id: "appointments",
      label: t5("Citas", "Appointments", "Rendez-vous", "Termine", "Appuntamenti"),
      icon: "calendar",
      kpis: [
        { label: t5("Citas Hoy", "Appointments Today", "Rendez-vous Aujourd'hui", "Termine Heute", "Appuntamenti Oggi"), value: "28", change: "+5", trend: "up" },
        { label: t5("Esta Semana", "This Week", "Cette Semaine", "Diese Woche", "Questa Settimana"), value: "142", change: "+18", trend: "up" },
        { label: t5("Tasa No Show", "No Show Rate", "Taux No Show", "No-Show-Rate", "Tasso No Show"), value: "5.2%", change: "-1.1%", trend: "down" },
        { label: t5("Duración Media", "Average Duration", "Durée Moyenne", "Durchschnittliche Dauer", "Durata Media"), value: t5("52 min", "52 min", "52 min", "52 Min", "52 min"), trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "text" },
          { key: "cliente", label: t5("Cliente", "Client", "Client", "Kundin", "Cliente"), type: "text" },
          { key: "servicio", label: t5("Servicio", "Service", "Service", "Leistung", "Servizio"), type: "text" },
          { key: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Fachkraft", "Professionista"), type: "text" },
          { key: "duracion", label: t5("Duración", "Duration", "Durée", "Dauer", "Durata"), type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Confirmada: "green", "En Progreso": "blue", Completada: "purple", "No Show": "red" } },
        ],
        rows: [
          { hora: "10:00", cliente: "Lucía Fernández", servicio: "Corte + Color", profesional: "Andrea Solis", duracion: "90 min", estado: "Confirmada" },
          { hora: "10:30", cliente: "Patricia Vega", servicio: "Manicura + Pedicura", profesional: "Yolanda Martín", duracion: "75 min", estado: "En Progreso" },
          { hora: "11:00", cliente: "Isabel Moreno", servicio: "Masaje Relajante", profesional: "Beatriz Lozano", duracion: "60 min", estado: "Confirmada" },
          { hora: "11:30", cliente: "Silvia Ramos", servicio: "Facial Anti-edad", profesional: "Clara Herrera", duracion: "45 min", estado: "Confirmada" },
          { hora: "09:30", cliente: "María Ruiz", servicio: "Manicura Gel", profesional: "Yolanda Martín", duracion: "40 min", estado: "Completada" },
          { hora: "09:00", cliente: "Carmen Díaz", servicio: "Facial Hidratante", profesional: "Clara Herrera", duracion: "50 min", estado: "No Show" },
        ],
        searchPlaceholder: t5("Buscar cita o cliente...", "Search appointment or client...", "Rechercher rendez-vous ou client...", "Termin oder Kundin suchen...", "Cerca appuntamento o cliente..."),
      },
      modal: {
        title: t5("Nueva Cita", "New Appointment", "Nouveau Rendez-vous", "Neuer Termin", "Nuovo Appuntamento"),
        fields: [
          { name: "cliente", label: t5("Cliente", "Client", "Client", "Kundin", "Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente", "Client name", "Nom du client", "Name der Kundin", "Nome del cliente") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "servicio", label: t5("Servicio", "Service", "Service", "Leistung", "Servizio"), type: "select", required: true, options: [
            { value: "corte", label: t5("Corte de Cabello", "Haircut", "Coupe de Cheveux", "Haarschnitt", "Taglio di Capelli") },
            { value: "color", label: t5("Coloración", "Coloring", "Coloration", "Färbung", "Colorazione") },
            { value: "corte_color", label: t5("Corte + Color", "Cut + Color", "Coupe + Couleur", "Schnitt + Farbe", "Taglio + Colore") },
            { value: "manicura", label: t5("Manicura", "Manicure", "Manucure", "Maniküre", "Manicure") },
            { value: "pedicura", label: t5("Pedicura", "Pedicure", "Pédicure", "Pediküre", "Pedicure") },
            { value: "facial", label: t5("Tratamiento Facial", "Facial Treatment", "Soin du Visage", "Gesichtsbehandlung", "Trattamento Viso") },
            { value: "masaje", label: t5("Masaje", "Massage", "Massage", "Massage", "Massaggio") },
            { value: "depilacion", label: t5("Depilación", "Waxing", "Épilation", "Enthaarung", "Depilazione") },
          ]},
          { name: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Fachkraft", "Professionista"), type: "select", required: true, options: [
            { value: "andrea", label: "Andrea Solis" },
            { value: "yolanda", label: "Yolanda Martín" },
            { value: "beatriz", label: "Beatriz Lozano" },
            { value: "clara", label: "Clara Herrera" },
          ]},
          { name: "fecha", label: t5("Fecha", "Date", "Date", "Datum", "Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora", "Time", "Heure", "Uhrzeit", "Ora"), type: "time", required: true },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Preferencias del cliente...", "Client preferences...", "Préférences du client...", "Kundenpräferenzen...", "Preferenze del cliente...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas", "All", "Toutes", "Alle", "Tutte"), filterField: "estado", filterValue: "all" },
        { id: "confirmadas", label: t5("Confirmadas", "Confirmed", "Confirmées", "Bestätigt", "Confermate"), filterField: "estado", filterValue: "Confirmada" },
        { id: "en_progreso", label: t5("En Progreso", "In Progress", "En Cours", "Laufend", "In Corso"), filterField: "estado", filterValue: "En Progreso" },
        { id: "completadas", label: t5("Completadas", "Completed", "Terminées", "Abgeschlossen", "Completate"), filterField: "estado", filterValue: "Completada" },
        { id: "no_show", label: "No Show", filterField: "estado", filterValue: "No Show" },
      ],
    },
    {
      id: "services",
      label: t5("Servicios", "Services", "Services", "Leistungen", "Servizi"),
      icon: "star",
      kpis: [
        { label: t5("Servicios Activos", "Active Services", "Services Actifs", "Aktive Leistungen", "Servizi Attivi"), value: "42", change: "+3", trend: "up" },
        { label: t5("Más Solicitado", "Most Requested", "Le Plus Demandé", "Am Meisten Nachgefragt", "Più Richiesto"), value: t5("Corte + Color", "Cut + Color", "Coupe + Couleur", "Schnitt + Farbe", "Taglio + Colore"), trend: "neutral" },
        { label: t5("Ticket Medio", "Average Ticket", "Ticket Moyen", "Durchschnittlicher Bon", "Scontrino Medio"), value: "€68", change: "+€5", trend: "up" },
        { label: t5("Categorías", "Categories", "Catégories", "Kategorien", "Categorie"), value: "5", trend: "neutral" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Servicio", "Service", "Service", "Leistung", "Servizio"), type: "text" },
          { key: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "badge", badgeColors: { Cabello: "purple", "Uñas": "orange", Facial: "blue", Corporal: "green", Masaje: "indigo" } },
          { key: "duracion", label: t5("Duración", "Duration", "Durée", "Dauer", "Durata"), type: "text" },
          { key: "precio", label: t5("Precio", "Price", "Prix", "Preis", "Prezzo"), type: "currency" },
          { key: "demanda", label: t5("Demanda", "Demand", "Demande", "Nachfrage", "Domanda"), type: "badge", badgeColors: { Alta: "green", Media: "yellow", Baja: "gray" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Corte + Color", categoria: "Cabello", duracion: "90 min", precio: 85, demanda: "Alta", acciones: "" },
          { nombre: "Manicura Gel", categoria: "Uñas", duracion: "40 min", precio: 35, demanda: "Alta", acciones: "" },
          { nombre: "Facial Anti-edad", categoria: "Facial", duracion: "45 min", precio: 65, demanda: "Media", acciones: "" },
          { nombre: "Masaje Relajante", categoria: "Masaje", duracion: "60 min", precio: 55, demanda: "Alta", acciones: "" },
          { nombre: "Tratamiento Corporal Reafirmante", categoria: "Corporal", duracion: "75 min", precio: 95, demanda: "Media", acciones: "" },
          { nombre: "Pedicura Spa", categoria: "Uñas", duracion: "50 min", precio: 42, demanda: "Baja", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar servicio...", "Search service...", "Rechercher service...", "Leistung suchen...", "Cerca servizio..."),
      },
      modal: {
        title: t5("Nuevo Servicio", "New Service", "Nouveau Service", "Neue Leistung", "Nuovo Servizio"),
        fields: [
          { name: "nombre", label: t5("Nombre del Servicio", "Service Name", "Nom du Service", "Name der Leistung", "Nome del Servizio"), type: "text", required: true, placeholder: t5("Ej: Corte + Color", "E.g.: Cut + Color", "Ex : Coupe + Couleur", "Z.B.: Schnitt + Farbe", "Es.: Taglio + Colore") },
          { name: "categoria", label: t5("Categoría", "Category", "Catégorie", "Kategorie", "Categoria"), type: "select", required: true, options: [
            { value: "cabello", label: t5("Cabello", "Hair", "Cheveux", "Haare", "Capelli") },
            { value: "unas", label: t5("Uñas", "Nails", "Ongles", "Nägel", "Unghie") },
            { value: "facial", label: t5("Facial", "Facial", "Visage", "Gesicht", "Viso") },
            { value: "corporal", label: t5("Corporal", "Body", "Corps", "Körper", "Corpo") },
            { value: "masaje", label: t5("Masaje", "Massage", "Massage", "Massage", "Massaggio") },
          ]},
          { name: "duracion", label: t5("Duración (min)", "Duration (min)", "Durée (min)", "Dauer (Min)", "Durata (min)"), type: "number", required: true, placeholder: "60" },
          { name: "precio", label: t5("Precio (€)", "Price (€)", "Prix (€)", "Preis (€)", "Prezzo (€)"), type: "number", required: true, placeholder: "0.00" },
          { name: "descripcion", label: t5("Descripción", "Description", "Description", "Beschreibung", "Descrizione"), type: "textarea", placeholder: t5("Detalles del servicio...", "Service details...", "Détails du service...", "Details der Leistung...", "Dettagli del servizio...") },
        ],
      },
    },
    {
      id: "staff",
      label: t5("Personal", "Staff", "Personnel", "Personal", "Personale"),
      icon: "users",
      kpis: [
        { label: t5("Total Personal", "Total Staff", "Personnel Total", "Personal Gesamt", "Personale Totale"), value: "12", trend: "neutral" },
        { label: t5("Disponibles Hoy", "Available Today", "Disponibles Aujourd'hui", "Heute Verfügbar", "Disponibili Oggi"), value: "9", trend: "neutral" },
        { label: t5("Citas/Profesional Hoy", "Appts/Professional Today", "RDV/Professionnel Aujourd'hui", "Termine/Fachkraft Heute", "App/Professionista Oggi"), value: "3.1", change: "+0.4", trend: "up" },
        { label: t5("Rating Medio", "Average Rating", "Note Moyenne", "Durchschnittsbewertung", "Valutazione Media"), value: "4.6/5", change: "+0.2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Profesional", "Professional", "Professionnel", "Fachkraft", "Professionista"), type: "text" },
          { key: "especialidad", label: t5("Especialidad", "Specialty", "Spécialité", "Spezialität", "Specialità"), type: "text" },
          { key: "citasHoy", label: t5("Citas Hoy", "Appts Today", "RDV Aujourd'hui", "Termine Heute", "App Oggi"), type: "text" },
          { key: "rating", label: "Rating", type: "text" },
          { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Disponible: "green", Ocupado: "blue", "Día Libre": "gray", Vacaciones: "yellow" } },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Andrea Solis", especialidad: "Cabello / Color", citasHoy: 5, rating: "4.8", estado: "Ocupado", acciones: "" },
          { nombre: "Yolanda Martín", especialidad: "Uñas", citasHoy: 6, rating: "4.7", estado: "Ocupado", acciones: "" },
          { nombre: "Beatriz Lozano", especialidad: "Masajes / Corporal", citasHoy: 4, rating: "4.9", estado: "Disponible", acciones: "" },
          { nombre: "Clara Herrera", especialidad: "Facial / Estética", citasHoy: 3, rating: "4.5", estado: "Disponible", acciones: "" },
          { nombre: "Paula Rivas", especialidad: "Cabello", citasHoy: 0, rating: "4.4", estado: "Día Libre", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar profesional...", "Search professional...", "Rechercher professionnel...", "Fachkraft suchen...", "Cerca professionista..."),
      },
      modal: {
        title: t5("Agregar Profesional", "Add Professional", "Ajouter Professionnel", "Fachkraft Hinzufügen", "Aggiungi Professionista"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "especialidad", label: t5("Especialidad", "Specialty", "Spécialité", "Spezialität", "Specialità"), type: "select", required: true, options: [
            { value: "cabello", label: t5("Cabello / Color", "Hair / Color", "Cheveux / Couleur", "Haare / Farbe", "Capelli / Colore") },
            { value: "unas", label: t5("Uñas", "Nails", "Ongles", "Nägel", "Unghie") },
            { value: "facial", label: t5("Facial / Estética", "Facial / Aesthetics", "Visage / Esthétique", "Gesicht / Ästhetik", "Viso / Estetica") },
            { value: "masaje", label: t5("Masajes / Corporal", "Massage / Body", "Massages / Corps", "Massage / Körper", "Massaggi / Corpo") },
            { value: "multidisciplinar", label: t5("Multidisciplinar", "Multidisciplinary", "Pluridisciplinaire", "Multidisziplinär", "Multidisciplinare") },
          ]},
          { name: "horario", label: t5("Horario", "Schedule", "Horaire", "Arbeitszeit", "Orario"), type: "text", placeholder: t5("Ej: Lun-Vie 09:00-18:00", "E.g.: Mon-Fri 09:00-18:00", "Ex : Lun-Ven 09:00-18:00", "Z.B.: Mo-Fr 09:00-18:00", "Es.: Lun-Ven 09:00-18:00") },
          { name: "notas", label: t5("Notas", "Notes", "Notes", "Notizen", "Note"), type: "textarea", placeholder: t5("Certificaciones, experiencia...", "Certifications, experience...", "Certifications, expérience...", "Zertifizierungen, Erfahrung...", "Certificazioni, esperienza...") },
        ],
      },
    },
    {
      id: "clients",
      label: t5("Clientes", "Clients", "Clients", "Kunden", "Clienti"),
      icon: "heart",
      kpis: [
        { label: t5("Total Clientes", "Total Clients", "Total Clients", "Kunden Gesamt", "Clienti Totali"), value: "1.842", change: "+34", trend: "up" },
        { label: t5("Frecuencia Media", "Average Frequency", "Fréquence Moyenne", "Durchschn. Häufigkeit", "Frequenza Media"), value: t5("1.8 visitas/mes", "1.8 visits/mo", "1.8 visites/mois", "1.8 Besuche/Monat", "1.8 visite/mese"), change: "+0.2", trend: "up" },
        { label: t5("Gasto Medio", "Average Spend", "Dépense Moyenne", "Durchschn. Ausgabe", "Spesa Media"), value: "€124/mes", change: "+€8", trend: "up" },
        { label: t5("Retención", "Retention", "Rétention", "Bindung", "Fidelizzazione"), value: "87%", change: "+2%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Cliente", "Client", "Client", "Kundin", "Cliente"), type: "text" },
          { key: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "text" },
          { key: "visitas", label: t5("Visitas", "Visits", "Visites", "Besuche", "Visite"), type: "text" },
          { key: "ultimaVisita", label: t5("Última Visita", "Last Visit", "Dernière Visite", "Letzter Besuch", "Ultima Visita"), type: "date" },
          { key: "gastoTotal", label: t5("Gasto Total", "Total Spend", "Dépense Totale", "Gesamtausgabe", "Spesa Totale"), type: "currency" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Lucía Fernández", telefono: "+34 611 111 111", visitas: 24, ultimaVisita: "2026-03-07", gastoTotal: 2160, acciones: "" },
          { nombre: "Patricia Vega", telefono: "+34 622 222 222", visitas: 18, ultimaVisita: "2026-03-07", gastoTotal: 1620, acciones: "" },
          { nombre: "Isabel Moreno", telefono: "+34 633 333 333", visitas: 12, ultimaVisita: "2026-02-28", gastoTotal: 980, acciones: "" },
          { nombre: "Silvia Ramos", telefono: "+34 644 444 444", visitas: 36, ultimaVisita: "2026-03-05", gastoTotal: 4320, acciones: "" },
          { nombre: "María Ruiz", telefono: "+34 655 555 555", visitas: 8, ultimaVisita: "2026-03-07", gastoTotal: 520, acciones: "" },
        ],
        searchPlaceholder: t5("Buscar cliente...", "Search client...", "Rechercher client...", "Kundin suchen...", "Cerca cliente..."),
      },
      modal: {
        title: t5("Nuevo Cliente", "New Client", "Nouveau Client", "Neue Kundin", "Nuovo Cliente"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo", "Full Name", "Nom Complet", "Vollständiger Name", "Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos", "First and last name", "Prénom et nom", "Vor- und Nachname", "Nome e cognome") },
          { name: "email", label: "Email", type: "email", placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "fechaNacimiento", label: t5("Fecha de Nacimiento", "Date of Birth", "Date de Naissance", "Geburtsdatum", "Data di Nascita"), type: "date" },
          { name: "alergias", label: t5("Alergias o Sensibilidades", "Allergies or Sensitivities", "Allergies ou Sensibilités", "Allergien oder Empfindlichkeiten", "Allergie o Sensibilità"), type: "textarea", placeholder: t5("Alérgenos, productos a evitar...", "Allergens, products to avoid...", "Allergènes, produits à éviter...", "Allergene, zu vermeidende Produkte...", "Allergeni, prodotti da evitare...") },
          { name: "notas", label: t5("Preferencias", "Preferences", "Préférences", "Präferenzen", "Preferenze"), type: "textarea", placeholder: t5("Preferencias de servicio...", "Service preferences...", "Préférences de service...", "Leistungspräferenzen...", "Preferenze di servizio...") },
        ],
      },
    },
    {
      id: "loyalty",
      label: t5("Fidelización", "Loyalty", "Fidélité", "Treue", "Fedeltà"),
      icon: "gift",
      kpis: [
        { label: t5("Miembros Programa", "Program Members", "Membres Programme", "Programm-Mitglieder", "Membri Programma"), value: "682", change: "+28", trend: "up" },
        { label: t5("Puntos Canjeados/Mes", "Points Redeemed/Month", "Points Échangés/Mois", "Eingelöste Punkte/Monat", "Punti Riscattati/Mese"), value: "12.400", change: "+15%", trend: "up" },
        { label: t5("Tasa de Uso", "Usage Rate", "Taux d'Utilisation", "Nutzungsrate", "Tasso di Utilizzo"), value: "74%", change: "+5%", trend: "up" },
        { label: t5("Descuentos Emitidos", "Discounts Issued", "Remises Émises", "Ausgegebene Rabatte", "Sconti Emessi"), value: "€4.200", change: "+€680", trend: "up" },
      ],
      table: {
        columns: [
          { key: "cliente", label: t5("Cliente", "Client", "Client", "Kundin", "Cliente"), type: "text" },
          { key: "nivel", label: t5("Nivel", "Level", "Niveau", "Level", "Livello"), type: "badge", badgeColors: { Bronce: "orange", Plata: "gray", Oro: "yellow", Platino: "purple" } },
          { key: "puntos", label: t5("Puntos", "Points", "Points", "Punkte", "Punti"), type: "text" },
          { key: "visitas", label: t5("Visitas", "Visits", "Visites", "Besuche", "Visite"), type: "text" },
          { key: "proximoNivel", label: t5("Próximo Nivel", "Next Level", "Prochain Niveau", "Nächstes Level", "Prossimo Livello"), type: "text" },
          { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
        ],
        rows: [
          { cliente: "Silvia Ramos", nivel: "Platino", puntos: 4320, visitas: 36, proximoNivel: "-", acciones: "" },
          { cliente: "Lucía Fernández", nivel: "Oro", puntos: 2160, visitas: 24, proximoNivel: "840 pts", acciones: "" },
          { cliente: "Patricia Vega", nivel: "Oro", puntos: 1620, visitas: 18, proximoNivel: "1380 pts", acciones: "" },
          { cliente: "Isabel Moreno", nivel: "Plata", puntos: 980, visitas: 12, proximoNivel: "520 pts", acciones: "" },
          { cliente: "María Ruiz", nivel: "Bronce", puntos: 520, visitas: 8, proximoNivel: "480 pts", acciones: "" },
        ],
        searchPlaceholder: t5("Buscar miembro...", "Search member...", "Rechercher membre...", "Mitglied suchen...", "Cerca membro..."),
      },
      modal: {
        title: t5("Inscribir en Programa", "Enroll in Program", "Inscrire au Programme", "In Programm Einschreiben", "Iscrivi al Programma"),
        fields: [
          { name: "cliente", label: t5("Cliente", "Client", "Client", "Kundin", "Cliente"), type: "text", required: true, placeholder: t5("Nombre del cliente", "Client name", "Nom du client", "Name der Kundin", "Nome del cliente") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("correo@email.com", "email@email.com", "email@email.com", "email@email.com", "email@email.com") },
          { name: "puntosIniciales", label: t5("Puntos Iniciales", "Initial Points", "Points Initiaux", "Anfangspunkte", "Punti Iniziali"), type: "number", placeholder: "0" },
          { name: "consentimiento", label: t5("Acepta comunicaciones comerciales", "Accepts marketing communications", "Accepte les communications commerciales", "Akzeptiert Werbemitteilungen", "Accetta comunicazioni commerciali"), type: "checkbox" },
        ],
      },
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: "Tenants",
        icon: "building",
        kpis: [
          { label: t5("Salones Activos", "Active Salons", "Salons Actifs", "Aktive Salons", "Saloni Attivi"), value: "28", change: "+3", trend: "up" },
          { label: t5("Clientes Totales", "Total Clients", "Clients Totaux", "Kunden Gesamt", "Clienti Totali"), value: "51.576", change: "+952", trend: "up" },
          { label: t5("Citas/Día Global", "Global Appts/Day", "RDV/Jour Global", "Globale Termine/Tag", "App/Giorno Globale"), value: "784", change: "+12%", trend: "up" },
          { label: t5("MRR Plataforma", "Platform MRR", "MRR Plateforme", "Plattform MRR", "MRR Piattaforma"), value: "€22.400", change: "+18%", trend: "up" },
        ],
        table: {
          columns: [
            { key: "salon", label: t5("Salón", "Salon", "Salon", "Salon", "Salone"), type: "text" },
            { key: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text" },
            { key: "profesionales", label: t5("Profesionales", "Professionals", "Professionnels", "Fachkräfte", "Professionisti"), type: "text" },
            { key: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "badge", badgeColors: { Básico: "gray", Profesional: "blue", Premium: "purple" } },
            { key: "estado", label: t5("Estado", "Status", "Statut", "Status", "Stato"), type: "badge", badgeColors: { Activo: "green", Suspendido: "red", Trial: "yellow" } },
            { key: "acciones", label: t5("Acciones", "Actions", "Actions", "Aktionen", "Azioni"), type: "actions" },
          ],
          rows: [
            { salon: "Glamour Studio Madrid", ciudad: "Madrid", profesionales: 18, plan: "Premium", estado: "Activo", acciones: "" },
            { salon: "Beauty Corner BCN", ciudad: "Barcelona", profesionales: 12, plan: "Premium", estado: "Activo", acciones: "" },
            { salon: "Salón Elegance", ciudad: "Valencia", profesionales: 8, plan: "Profesional", estado: "Activo", acciones: "" },
            { salon: "Estética Natural", ciudad: "Sevilla", profesionales: 4, plan: "Básico", estado: "Trial", acciones: "" },
            { salon: "Spa Zen Center", ciudad: "Bilbao", profesionales: 10, plan: "Profesional", estado: "Suspendido", acciones: "" },
          ],
          searchPlaceholder: t5("Buscar salón...", "Search salon...", "Rechercher salon...", "Salon suchen...", "Cerca salone..."),
        },
        modal: {
          title: t5("Agregar Tenant", "Add Tenant", "Ajouter Tenant", "Tenant Hinzufügen", "Aggiungi Tenant"),
          fields: [
            { name: "nombre", label: t5("Nombre del Salón", "Salon Name", "Nom du Salon", "Salonname", "Nome del Salone"), type: "text", required: true, placeholder: t5("Nombre comercial", "Business name", "Nom commercial", "Handelsname", "Nome commerciale") },
            { name: "ciudad", label: t5("Ciudad", "City", "Ville", "Stadt", "Città"), type: "text", required: true, placeholder: t5("Ciudad", "City", "Ville", "Stadt", "Città") },
            { name: "plan", label: t5("Plan", "Plan", "Plan", "Plan", "Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico", "Basic", "Basique", "Basis", "Base") },
              { value: "profesional", label: t5("Profesional", "Professional", "Professionnel", "Professionell", "Professionale") },
              { value: "premium", label: "Premium" },
            ]},
            { name: "contacto", label: t5("Email de Contacto", "Contact Email", "Email de Contact", "Kontakt-E-Mail", "Email di Contatto"), type: "email", required: true, placeholder: "admin@salon.com" },
            { name: "telefono", label: t5("Teléfono", "Phone", "Téléphone", "Telefon", "Telefono"), type: "tel", placeholder: "+34 600 000 000" },
          ],
        },
      },
    ],
  },
};
