import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const schoolManagement: SystemConfig = {
  name: "EduControl",
  subtitle: t5("Gestion Escolar","School Management","Gestion Scolaire","Schulverwaltung","Gestione Scolastica"),
  brandColor: "#2563eb",
  icon: "🏫",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal","Dashboard","Tableau de Bord","Dashboard","Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Total Alumnos","Total Students","Total Élèves","Schüler Gesamt","Alunni Totali"), value: "1,850", change: "+120", trend: "up" },
        { label: t5("Profesores","Teachers","Professeurs","Lehrer","Professori"), value: "94", change: "+6", trend: "up" },
        { label: t5("Asistencia Hoy","Attendance Today","Présence Aujourd'hui","Anwesenheit Heute","Presenze Oggi"), value: "92%", change: "+1%", trend: "up" },
        { label: t5("Promedio General","Overall Average","Moyenne Générale","Gesamtdurchschnitt","Media Generale"), value: "7.6/10", change: "+0.2", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad","Activity","Activité","Aktivität","Attività"), type: "text" },
          { key: "persona", label: t5("Persona","Person","Personne","Person","Persona"), type: "text" },
          { key: "detalle", label: t5("Detalle","Detail","Détail","Detail","Dettaglio"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Inscripción": "blue", "Calificación": "green", "Asistencia": "yellow", "Incidencia": "red" } },
        ],
        rows: [
          { actividad: "Nueva inscripción", persona: "Sofía Ramírez", detalle: "3° ESO - Grupo B", fecha: "2026-03-07", tipo: "Inscripción" },
          { actividad: "Calificaciones publicadas", persona: "Prof. García", detalle: "Matemáticas 4° ESO", fecha: "2026-03-07", tipo: "Calificación" },
          { actividad: "Falta justificada", persona: "Diego Martín", detalle: "Certificado médico", fecha: "2026-03-06", tipo: "Asistencia" },
          { actividad: "Reunión padres", persona: "Familia López", detalle: "Tutoría 2° ESO", fecha: "2026-03-06", tipo: "Incidencia" },
          { actividad: "Examen programado", persona: "Prof. Hernández", detalle: "Física 1° Bachillerato", fecha: "2026-03-05", tipo: "Calificación" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...","Search recent activity...","Rechercher activité récente...","Letzte Aktivität suchen...","Cerca attività recente..."),
      },
    },
    {
      id: "students",
      label: t5("Alumnos","Students","Élèves","Schüler","Alunni"),
      icon: "users",
      kpis: [
        { label: t5("Total Alumnos","Total Students","Total Élèves","Schüler Gesamt","Alunni Totali"), value: "1,850", change: "+120", trend: "up" },
        { label: t5("Activos","Active","Actifs","Aktiv","Attivi"), value: "1,720", change: "+95", trend: "up" },
        { label: t5("Nuevas Inscripciones","New Enrollments","Nouvelles Inscriptions","Neuanmeldungen","Nuove Iscrizioni"), value: "45", change: "+12", trend: "up" },
        { label: t5("Becados","Scholarship Students","Boursiers","Stipendiaten","Borsisti"), value: "230", change: "+15", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "avatar" },
          { key: "curso", label: t5("Curso","Grade","Classe","Klasse","Classe"), type: "text" },
          { key: "grupo", label: t5("Grupo","Group","Groupe","Gruppe","Gruppo"), type: "text" },
          { key: "tutor", label: t5("Tutor Legal","Legal Guardian","Tuteur Légal","Erziehungsberechtigter","Tutore Legale"), type: "text" },
          { key: "promedio", label: t5("Promedio","Average","Moyenne","Durchschnitt","Media"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activo": "green", "Graduado": "blue", "Baja": "red", "Suspendido": "yellow" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Sofía Ramírez", curso: "3° ESO", grupo: "B", tutor: "Carmen Ramírez", promedio: "8.4", estado: "Activo" },
          { nombre: "Diego Martín", curso: "4° ESO", grupo: "A", tutor: "José Martín", promedio: "7.2", estado: "Activo" },
          { nombre: "Lucía Fernández", curso: "1° Bachillerato", grupo: "C", tutor: "María Fernández", promedio: "9.1", estado: "Activo" },
          { nombre: "Alejandro Ruiz", curso: "2° ESO", grupo: "A", tutor: "Ana Ruiz", promedio: "6.5", estado: "Suspendido" },
          { nombre: "Valentina Gómez", curso: "2° Bachillerato", grupo: "B", tutor: "Pedro Gómez", promedio: "8.8", estado: "Activo" },
          { nombre: "Marco Jiménez", curso: "4° ESO", grupo: "A", tutor: "Laura Jiménez", promedio: "7.9", estado: "Graduado" },
        ],
        searchPlaceholder: t5("Buscar alumnos...","Search students...","Rechercher des élèves...","Schüler suchen...","Cerca alunni..."),
      },
      modal: {
        title: t5("Nuevo Alumno","New Student","Nouvel Élève","Neuer Schüler","Nuovo Alunno"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo","Full Name","Nom Complet","Vollständiger Name","Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos","First and last name","Prénom et nom","Vor- und Nachname","Nome e cognome") },
          { name: "fecha_nacimiento", label: t5("Fecha de Nacimiento","Date of Birth","Date de Naissance","Geburtsdatum","Data di Nascita"), type: "date", required: true },
          { name: "curso", label: t5("Curso","Grade","Classe","Klasse","Classe"), type: "select", required: true, options: [
            { value: "1eso", label: "1° ESO" },
            { value: "2eso", label: "2° ESO" },
            { value: "3eso", label: "3° ESO" },
            { value: "4eso", label: "4° ESO" },
            { value: "1bach", label: t5("1° Bachillerato","1st Bachillerato","1ère Bachillerato","1. Bachillerato","1° Bachillerato") },
            { value: "2bach", label: t5("2° Bachillerato","2nd Bachillerato","2ème Bachillerato","2. Bachillerato","2° Bachillerato") },
          ]},
          { name: "grupo", label: t5("Grupo","Group","Groupe","Gruppe","Gruppo"), type: "select", required: true, options: [
            { value: "A", label: t5("Grupo A","Group A","Groupe A","Gruppe A","Gruppo A") },
            { value: "B", label: t5("Grupo B","Group B","Groupe B","Gruppe B","Gruppo B") },
            { value: "C", label: t5("Grupo C","Group C","Groupe C","Gruppe C","Gruppo C") },
          ]},
          { name: "tutor_nombre", label: t5("Nombre del Tutor Legal","Legal Guardian Name","Nom du Tuteur Légal","Name des Erziehungsberechtigten","Nome del Tutore Legale"), type: "text", required: true, placeholder: t5("Nombre del padre/madre/tutor","Parent/guardian name","Nom du parent/tuteur","Name des Elternteils/Erziehungsberechtigten","Nome del genitore/tutore") },
          { name: "tutor_telefono", label: t5("Teléfono del Tutor","Guardian Phone","Téléphone du Tuteur","Telefon des Erziehungsberechtigten","Telefono del Tutore"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "tutor_email", label: t5("Email del Tutor","Guardian Email","Email du Tuteur","E-Mail des Erziehungsberechtigten","Email del Tutore"), type: "email", required: true, placeholder: "tutor@email.com" },
          { name: "becado", label: t5("Alumno Becado","Scholarship Student","Élève Boursier","Stipendiat","Alunno Borsista"), type: "checkbox", required: false },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "estado", filterValue: "" },
        { id: "activos", label: t5("Activos","Active","Actifs","Aktiv","Attivi"), filterField: "estado", filterValue: "Activo" },
        { id: "graduados", label: t5("Graduados","Graduated","Diplômés","Absolventen","Diplomati"), filterField: "estado", filterValue: "Graduado" },
        { id: "baja", label: t5("Baja","Withdrawn","Retirés","Abgemeldet","Ritirati"), filterField: "estado", filterValue: "Baja" },
        { id: "suspendidos", label: t5("Suspendidos","Suspended","Suspendus","Suspendiert","Sospesi"), filterField: "estado", filterValue: "Suspendido" },
      ],
    },
    {
      id: "teachers",
      label: t5("Profesores","Teachers","Professeurs","Lehrer","Professori"),
      icon: "briefcase",
      kpis: [
        { label: t5("Total Profesores","Total Teachers","Total Professeurs","Lehrer Gesamt","Professori Totali"), value: "94", change: "+6", trend: "up" },
        { label: t5("Tiempo Completo","Full Time","Temps Plein","Vollzeit","Tempo Pieno"), value: "72", change: "+4", trend: "up" },
        { label: t5("Media Experiencia","Average Experience","Expérience Moyenne","Durchschnittliche Erfahrung","Esperienza Media"), value: t5("12 años","12 years","12 ans","12 Jahre","12 anni"), change: "+0.5", trend: "up" },
        { label: t5("Satisfacción","Satisfaction","Satisfaction","Zufriedenheit","Soddisfazione"), value: "4.3/5", change: "+0.1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "avatar" },
          { key: "departamento", label: t5("Departamento","Department","Département","Abteilung","Dipartimento"), type: "text" },
          { key: "asignaturas", label: t5("Asignaturas","Subjects","Matières","Fächer","Materie"), type: "text" },
          { key: "horas_semana", label: t5("Horas/Semana","Hours/Week","Heures/Semaine","Stunden/Woche","Ore/Settimana"), type: "text" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Tiempo Completo": "green", "Medio Tiempo": "blue", "Sustituto": "yellow" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Prof. García Moreno", departamento: "Matemáticas", asignaturas: "Matemáticas, Estadística", horas_semana: 25, tipo: "Tiempo Completo" },
          { nombre: "Prof. Hernández Ruiz", departamento: "Ciencias", asignaturas: "Física, Química", horas_semana: 25, tipo: "Tiempo Completo" },
          { nombre: "Prof. López Vega", departamento: "Lenguas", asignaturas: "Inglés, Francés", horas_semana: 20, tipo: "Tiempo Completo" },
          { nombre: "Prof. Díaz Torres", departamento: "Historia", asignaturas: "Historia, Geografía", horas_semana: 15, tipo: "Medio Tiempo" },
          { nombre: "Prof. Martín Soto", departamento: "Educación Física", asignaturas: "Ed. Física", horas_semana: 12, tipo: "Sustituto" },
        ],
        searchPlaceholder: t5("Buscar profesores...","Search teachers...","Rechercher des professeurs...","Lehrer suchen...","Cerca professori..."),
      },
      modal: {
        title: t5("Nuevo Profesor","New Teacher","Nouveau Professeur","Neuer Lehrer","Nuovo Professore"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo","Full Name","Nom Complet","Vollständiger Name","Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos","First and last name","Prénom et nom","Vor- und Nachname","Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("profesor@colegio.edu","teacher@school.edu","professeur@ecole.edu","lehrer@schule.edu","professore@scuola.edu") },
          { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "departamento", label: t5("Departamento","Department","Département","Abteilung","Dipartimento"), type: "select", required: true, options: [
            { value: "matematicas", label: t5("Matemáticas","Mathematics","Mathématiques","Mathematik","Matematica") },
            { value: "ciencias", label: t5("Ciencias","Sciences","Sciences","Naturwissenschaften","Scienze") },
            { value: "lenguas", label: t5("Lenguas","Languages","Langues","Sprachen","Lingue") },
            { value: "historia", label: t5("Historia","History","Histoire","Geschichte","Storia") },
            { value: "educacion_fisica", label: t5("Educación Física","Physical Education","Éducation Physique","Sportunterricht","Educazione Fisica") },
            { value: "artes", label: t5("Artes","Arts","Arts","Kunst","Arti") },
          ]},
          { name: "tipo", label: t5("Tipo de Contrato","Contract Type","Type de Contrat","Vertragsart","Tipo di Contratto"), type: "select", required: true, options: [
            { value: "completo", label: t5("Tiempo Completo","Full Time","Temps Plein","Vollzeit","Tempo Pieno") },
            { value: "medio", label: t5("Medio Tiempo","Part Time","Mi-Temps","Teilzeit","Mezza Giornata") },
            { value: "sustituto", label: t5("Sustituto","Substitute","Suppléant","Vertretung","Supplente") },
          ]},
          { name: "fecha_incorporacion", label: t5("Fecha de Incorporación","Start Date","Date d'Intégration","Eintrittsdatum","Data di Assunzione"), type: "date", required: true },
        ],
      },
    },
    {
      id: "classes",
      label: t5("Clases","Classes","Classes","Klassen","Classi"),
      icon: "grid",
      kpis: [
        { label: t5("Total Clases","Total Classes","Total Classes","Klassen Gesamt","Classi Totali"), value: "62", change: "+4", trend: "up" },
        { label: t5("Aulas Ocupadas","Occupied Classrooms","Salles Occupées","Belegte Räume","Aule Occupate"), value: "58", change: "+2", trend: "up" },
        { label: t5("Alumnos/Clase","Students/Class","Élèves/Classe","Schüler/Klasse","Alunni/Classe"), value: "29.8", change: "-0.5", trend: "up" },
        { label: t5("Horas Semanales","Weekly Hours","Heures Hebdomadaires","Wochenstunden","Ore Settimanali"), value: "186", change: "+8", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Clase","Class","Classe","Klasse","Classe"), type: "text" },
          { key: "profesor", label: t5("Profesor","Teacher","Professeur","Lehrer","Professore"), type: "text" },
          { key: "aula", label: t5("Aula","Classroom","Salle","Raum","Aula"), type: "text" },
          { key: "alumnos", label: t5("Alumnos","Students","Élèves","Schüler","Alunni"), type: "text" },
          { key: "horario", label: t5("Horario","Schedule","Horaire","Stundenplan","Orario"), type: "text" },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Matemáticas 4° ESO-A", profesor: "Prof. García Moreno", aula: "Aula 201", alumnos: 28, horario: "Lun-Mié-Vie 9:00" },
          { nombre: "Física 1° Bach-C", profesor: "Prof. Hernández Ruiz", aula: "Lab. Ciencias", alumnos: 25, horario: "Mar-Jue 10:30" },
          { nombre: "Inglés 3° ESO-B", profesor: "Prof. López Vega", aula: "Aula 105", alumnos: 30, horario: "Lun-Mié-Vie 11:00" },
          { nombre: "Historia 2° ESO-A", profesor: "Prof. Díaz Torres", aula: "Aula 302", alumnos: 32, horario: "Mar-Jue 9:00" },
          { nombre: "Ed. Física 4° ESO-A", profesor: "Prof. Martín Soto", aula: "Gimnasio", alumnos: 28, horario: "Vie 12:00" },
        ],
        searchPlaceholder: t5("Buscar clases...","Search classes...","Rechercher des classes...","Klassen suchen...","Cerca classi..."),
      },
      modal: {
        title: t5("Nueva Clase","New Class","Nouvelle Classe","Neue Klasse","Nuova Classe"),
        fields: [
          { name: "asignatura", label: t5("Asignatura","Subject","Matière","Fach","Materia"), type: "text", required: true, placeholder: t5("Nombre de la asignatura","Subject name","Nom de la matière","Name des Fachs","Nome della materia") },
          { name: "curso_grupo", label: t5("Curso y Grupo","Grade and Group","Classe et Groupe","Klasse und Gruppe","Classe e Gruppo"), type: "text", required: true, placeholder: t5("Ej: 4° ESO-A","E.g.: 4° ESO-A","Ex : 4° ESO-A","Z.B.: 4° ESO-A","Es.: 4° ESO-A") },
          { name: "profesor", label: t5("Profesor","Teacher","Professeur","Lehrer","Professore"), type: "select", required: true, options: [
            { value: "garcia", label: "Prof. García Moreno" },
            { value: "hernandez", label: "Prof. Hernández Ruiz" },
            { value: "lopez", label: "Prof. López Vega" },
            { value: "diaz", label: "Prof. Díaz Torres" },
            { value: "martin", label: "Prof. Martín Soto" },
          ]},
          { name: "aula", label: t5("Aula","Classroom","Salle","Raum","Aula"), type: "text", required: true, placeholder: t5("Aula 201","Room 201","Salle 201","Raum 201","Aula 201") },
          { name: "horario", label: t5("Horario","Schedule","Horaire","Stundenplan","Orario"), type: "text", required: true, placeholder: t5("Lun-Mié-Vie 9:00","Mon-Wed-Fri 9:00","Lun-Mer-Ven 9h00","Mo-Mi-Fr 9:00","Lun-Mer-Ven 9:00") },
        ],
      },
    },
    {
      id: "grades",
      label: t5("Calificaciones","Grades","Notes","Noten","Voti"),
      icon: "chart",
      kpis: [
        { label: t5("Promedio General","Overall Average","Moyenne Générale","Gesamtdurchschnitt","Media Generale"), value: "7.6/10", change: "+0.2", trend: "up" },
        { label: t5("Sobresalientes","Outstanding","Excellents","Hervorragend","Eccellenti"), value: "18%", change: "+3%", trend: "up" },
        { label: t5("Aprobados","Passed","Admis","Bestanden","Promossi"), value: "82%", change: "+1%", trend: "up" },
        { label: t5("Evaluaciones Pendientes","Pending Evaluations","Évaluations en Attente","Ausstehende Bewertungen","Valutazioni in Sospeso"), value: "12", change: "-5", trend: "up" },
      ],
      table: {
        columns: [
          { key: "alumno", label: t5("Alumno","Student","Élève","Schüler","Alunno"), type: "text" },
          { key: "asignatura", label: t5("Asignatura","Subject","Matière","Fach","Materia"), type: "text" },
          { key: "evaluacion", label: t5("Evaluación","Evaluation","Évaluation","Bewertung","Valutazione"), type: "text" },
          { key: "nota", label: t5("Nota","Grade","Note","Note","Voto"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Aprobado": "green", "Suspenso": "red", "Notable": "blue", "Sobresaliente": "purple" } },
        ],
        rows: [
          { alumno: "Sofía Ramírez", asignatura: "Matemáticas", evaluacion: "2ª Evaluación", nota: "8.5", fecha: "2026-03-05", estado: "Notable" },
          { alumno: "Diego Martín", asignatura: "Física", evaluacion: "2ª Evaluación", nota: "6.2", fecha: "2026-03-05", estado: "Aprobado" },
          { alumno: "Lucía Fernández", asignatura: "Inglés", evaluacion: "2ª Evaluación", nota: "9.3", fecha: "2026-03-04", estado: "Sobresaliente" },
          { alumno: "Alejandro Ruiz", asignatura: "Historia", evaluacion: "2ª Evaluación", nota: "4.1", fecha: "2026-03-04", estado: "Suspenso" },
          { alumno: "Valentina Gómez", asignatura: "Química", evaluacion: "2ª Evaluación", nota: "8.9", fecha: "2026-03-03", estado: "Notable" },
        ],
        searchPlaceholder: t5("Buscar calificaciones...","Search grades...","Rechercher des notes...","Noten suchen...","Cerca voti..."),
      },
      modal: {
        title: t5("Registrar Calificación","Record Grade","Enregistrer une Note","Note Eintragen","Registra Voto"),
        fields: [
          { name: "alumno", label: t5("Alumno","Student","Élève","Schüler","Alunno"), type: "text", required: true, placeholder: t5("Nombre del alumno","Student name","Nom de l'élève","Name des Schülers","Nome dell'alunno") },
          { name: "asignatura", label: t5("Asignatura","Subject","Matière","Fach","Materia"), type: "select", required: true, options: [
            { value: "matematicas", label: t5("Matemáticas","Mathematics","Mathématiques","Mathematik","Matematica") },
            { value: "fisica", label: t5("Física","Physics","Physique","Physik","Fisica") },
            { value: "ingles", label: t5("Inglés","English","Anglais","Englisch","Inglese") },
            { value: "historia", label: t5("Historia","History","Histoire","Geschichte","Storia") },
            { value: "quimica", label: t5("Química","Chemistry","Chimie","Chemie","Chimica") },
          ]},
          { name: "evaluacion", label: t5("Evaluación","Evaluation","Évaluation","Bewertung","Valutazione"), type: "select", required: true, options: [
            { value: "1eval", label: t5("1ª Evaluación","1st Evaluation","1ère Évaluation","1. Bewertung","1ª Valutazione") },
            { value: "2eval", label: t5("2ª Evaluación","2nd Evaluation","2ème Évaluation","2. Bewertung","2ª Valutazione") },
            { value: "3eval", label: t5("3ª Evaluación","3rd Evaluation","3ème Évaluation","3. Bewertung","3ª Valutazione") },
            { value: "final", label: t5("Evaluación Final","Final Evaluation","Évaluation Finale","Abschlussbewertung","Valutazione Finale") },
          ]},
          { name: "nota", label: t5("Nota (0-10)","Grade (0-10)","Note (0-10)","Note (0-10)","Voto (0-10)"), type: "number", required: true, placeholder: "7.5" },
          { name: "observaciones", label: t5("Observaciones","Observations","Observations","Bemerkungen","Osservazioni"), type: "textarea", required: false, placeholder: t5("Comentarios sobre el alumno...","Comments about the student...","Commentaires sur l'élève...","Kommentare zum Schüler...","Commenti sull'alunno...") },
        ],
      },
    },
    {
      id: "attendance",
      label: t5("Asistencia","Attendance","Présence","Anwesenheit","Presenze"),
      icon: "clock",
      kpis: [
        { label: t5("Asistencia Hoy","Attendance Today","Présence Aujourd'hui","Anwesenheit Heute","Presenze Oggi"), value: "92%", change: "+1%", trend: "up" },
        { label: t5("Ausencias Hoy","Absences Today","Absences Aujourd'hui","Abwesenheiten Heute","Assenze Oggi"), value: "148", change: "-12", trend: "up" },
        { label: t5("Tardanzas Hoy","Late Arrivals Today","Retards Aujourd'hui","Verspätungen Heute","Ritardi Oggi"), value: "34", change: "-5", trend: "up" },
        { label: t5("Justificaciones Pendientes","Pending Justifications","Justifications en Attente","Ausstehende Entschuldigungen","Giustificazioni in Sospeso"), value: "23", change: "-8", trend: "up" },
      ],
      table: {
        columns: [
          { key: "alumno", label: t5("Alumno","Student","Élève","Schüler","Alunno"), type: "text" },
          { key: "curso", label: t5("Curso","Grade","Classe","Klasse","Classe"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "hora", label: t5("Hora","Time","Heure","Uhrzeit","Ora"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Presente": "green", "Ausente": "red", "Tardanza": "yellow", "Justificado": "blue" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { alumno: "Sofía Ramírez", curso: "3° ESO-B", fecha: "2026-03-07", hora: "08:00", estado: "Presente" },
          { alumno: "Diego Martín", curso: "4° ESO-A", fecha: "2026-03-07", hora: "08:00", estado: "Ausente" },
          { alumno: "Lucía Fernández", curso: "1° Bach-C", fecha: "2026-03-07", hora: "08:15", estado: "Tardanza" },
          { alumno: "Alejandro Ruiz", curso: "2° ESO-A", fecha: "2026-03-07", hora: "08:00", estado: "Justificado" },
          { alumno: "Valentina Gómez", curso: "2° Bach-B", fecha: "2026-03-07", hora: "08:00", estado: "Presente" },
          { alumno: "Marco Jiménez", curso: "4° ESO-A", fecha: "2026-03-07", hora: "08:22", estado: "Tardanza" },
        ],
        searchPlaceholder: t5("Buscar asistencia...","Search attendance...","Rechercher présence...","Anwesenheit suchen...","Cerca presenze..."),
      },
      modal: {
        title: t5("Registrar Asistencia","Record Attendance","Enregistrer la Présence","Anwesenheit Eintragen","Registra Presenza"),
        fields: [
          { name: "alumno", label: t5("Alumno","Student","Élève","Schüler","Alunno"), type: "text", required: true, placeholder: t5("Nombre del alumno","Student name","Nom de l'élève","Name des Schülers","Nome dell'alunno") },
          { name: "curso", label: t5("Curso","Grade","Classe","Klasse","Classe"), type: "text", required: true, placeholder: "3° ESO-B" },
          { name: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora de Entrada","Entry Time","Heure d'Entrée","Eingangszeit","Ora di Ingresso"), type: "time", required: true },
          { name: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "select", required: true, options: [
            { value: "presente", label: t5("Presente","Present","Présent","Anwesend","Presente") },
            { value: "ausente", label: t5("Ausente","Absent","Absent","Abwesend","Assente") },
            { value: "tardanza", label: t5("Tardanza","Late","Retard","Verspätung","Ritardo") },
            { value: "justificado", label: t5("Justificado","Justified","Justifié","Entschuldigt","Giustificato") },
          ]},
          { name: "observaciones", label: t5("Observaciones","Observations","Observations","Bemerkungen","Osservazioni"), type: "textarea", required: false, placeholder: t5("Motivo de ausencia o tardanza...","Reason for absence or lateness...","Motif d'absence ou de retard...","Grund für Abwesenheit oder Verspätung...","Motivo dell'assenza o del ritardo...") },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "estado", filterValue: "" },
        { id: "presentes", label: t5("Presentes","Present","Présents","Anwesend","Presenti"), filterField: "estado", filterValue: "Presente" },
        { id: "ausentes", label: t5("Ausentes","Absent","Absents","Abwesend","Assenti"), filterField: "estado", filterValue: "Ausente" },
        { id: "tardanzas", label: t5("Tardanzas","Late","Retards","Verspätungen","Ritardi"), filterField: "estado", filterValue: "Tardanza" },
        { id: "justificados", label: t5("Justificados","Justified","Justifiés","Entschuldigt","Giustificati"), filterField: "estado", filterValue: "Justificado" },
      ],
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Centros Educativos","Schools","Centres Éducatifs","Bildungseinrichtungen","Centri Educativi"),
        icon: "building",
        kpis: [
          { label: t5("Total Centros","Total Schools","Total Centres","Einrichtungen Gesamt","Centri Totali"), value: "18", change: "+2", trend: "up" },
          { label: t5("Activos","Active","Actifs","Aktiv","Attivi"), value: "16", change: "+2", trend: "up" },
          { label: t5("Alumnos Totales","Total Students","Total Élèves","Schüler Gesamt","Alunni Totali"), value: "33,300", change: "+2,160", trend: "up" },
          { label: "MRR", value: "€9,800", change: "+€800", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Centro Educativo","School","Centre Éducatif","Bildungseinrichtung","Centro Educativo"), type: "text" },
            { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Primaria": "blue", "Secundaria": "green", "Bachillerato": "purple", "Integrado": "indigo" } },
            { key: "alumnos", label: t5("Alumnos","Students","Élèves","Schüler","Alunni"), type: "text" },
            { key: "profesores", label: t5("Profesores","Teachers","Professeurs","Lehrer","Professori"), type: "text" },
            { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activo": "green", "Suspendido": "red", "Trial": "yellow" } },
            { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "Colegio San Patricio", tipo: "Integrado", alumnos: 2400, profesores: 120, estado: "Activo" },
            { nombre: "IES Cervantes", tipo: "Secundaria", alumnos: 1800, profesores: 94, estado: "Activo" },
            { nombre: "Colegio Montessori", tipo: "Primaria", alumnos: 600, profesores: 35, estado: "Activo" },
            { nombre: "Academia Europa", tipo: "Bachillerato", alumnos: 450, profesores: 28, estado: "Trial" },
            { nombre: "Colegio Internacional", tipo: "Integrado", alumnos: 3200, profesores: 160, estado: "Activo" },
          ],
          searchPlaceholder: t5("Buscar centros educativos...","Search schools...","Rechercher des centres éducatifs...","Bildungseinrichtungen suchen...","Cerca centri educativi..."),
        },
        modal: {
          title: t5("Nuevo Centro Educativo","New School","Nouveau Centre Éducatif","Neue Bildungseinrichtung","Nuovo Centro Educativo"),
          fields: [
            { name: "nombre", label: t5("Nombre del Centro","School Name","Nom du Centre","Name der Einrichtung","Nome del Centro"), type: "text", required: true, placeholder: t5("Nombre del colegio/instituto","School name","Nom de l'école/institut","Name der Schule/des Instituts","Nome della scuola/istituto") },
            { name: "email_admin", label: t5("Email Administrador","Admin Email","Email Administrateur","Admin E-Mail","Email Amministratore"), type: "email", required: true, placeholder: "admin@centro.edu" },
            { name: "tipo", label: t5("Tipo de Centro","School Type","Type de Centre","Art der Einrichtung","Tipo di Centro"), type: "select", required: true, options: [
              { value: "primaria", label: t5("Primaria","Primary","Primaire","Grundschule","Primaria") },
              { value: "secundaria", label: t5("Secundaria","Secondary","Secondaire","Sekundarstufe","Secondaria") },
              { value: "bachillerato", label: t5("Bachillerato","High School","Lycée","Oberstufe","Liceo") },
              { value: "integrado", label: t5("Integrado","Integrated","Intégré","Integriert","Integrato") },
            ]},
            { name: "max_alumnos", label: t5("Máx. Alumnos","Max. Students","Max. Élèves","Max. Schüler","Max. Alunni"), type: "number", required: true, placeholder: "500" },
            { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: true, placeholder: "+34 900 000 000" },
          ],
        },
      },
    ],
  },
};
