import type { SystemConfig } from "../types";
import { t5 } from "../types";

export const tutoring: SystemConfig = {
  name: "TutorConnect",
  subtitle: t5("Plataforma de Tutorias","Tutoring Platform","Plateforme de Tutorat","Nachhilfe-Plattform","Piattaforma di Tutoraggio"),
  brandColor: "#0d9488",
  icon: "📚",
  modules: [
    {
      id: "dashboard",
      label: t5("Panel Principal","Dashboard","Tableau de Bord","Dashboard","Pannello Principale"),
      icon: "dashboard",
      kpis: [
        { label: t5("Sesiones Este Mes","Sessions This Month","Sessions Ce Mois","Sitzungen Diesen Monat","Sessioni Questo Mese"), value: "342", change: "+28", trend: "up" },
        { label: t5("Tutores Activos","Active Tutors","Tuteurs Actifs","Aktive Tutoren","Tutor Attivi"), value: "56", change: "+4", trend: "up" },
        { label: t5("Estudiantes Activos","Active Students","Étudiants Actifs","Aktive Studenten","Studenti Attivi"), value: "480", change: "+35", trend: "up" },
        { label: t5("Ingresos del Mes","Monthly Revenue","Revenus du Mois","Monatsumsatz","Entrate del Mese"), value: "€24,600", change: "+15%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "actividad", label: t5("Actividad","Activity","Activité","Aktivität","Attività"), type: "text" },
          { key: "tutor", label: t5("Tutor","Tutor","Tuteur","Tutor","Tutor"), type: "text" },
          { key: "estudiante", label: t5("Estudiante","Student","Étudiant","Student","Studente"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Completada": "green", "Programada": "blue", "Cancelada": "red" } },
        ],
        rows: [
          { actividad: "Sesión de Matemáticas", tutor: "Prof. Álvarez", estudiante: "Carlos Mendoza", fecha: "2026-03-07", estado: "Completada" },
          { actividad: "Clase de Inglés", tutor: "Prof. Williams", estudiante: "Ana Pérez", fecha: "2026-03-07", estado: "Programada" },
          { actividad: "Tutoría de Física", tutor: "Prof. Serrano", estudiante: "Marta Ruiz", fecha: "2026-03-06", estado: "Completada" },
          { actividad: "Repaso Programación", tutor: "Prof. Castro", estudiante: "Luis García", fecha: "2026-03-06", estado: "Cancelada" },
          { actividad: "Clase de Arte", tutor: "Prof. Morales", estudiante: "Sofía Vega", fecha: "2026-03-05", estado: "Completada" },
        ],
        searchPlaceholder: t5("Buscar actividad reciente...","Search recent activity...","Rechercher activité récente...","Letzte Aktivität suchen...","Cerca attività recente..."),
      },
    },
    {
      id: "tutors",
      label: t5("Tutores","Tutors","Tuteurs","Tutoren","Tutor"),
      icon: "users",
      kpis: [
        { label: t5("Total Tutores","Total Tutors","Total Tuteurs","Tutoren Gesamt","Tutor Totali"), value: "56", change: "+4", trend: "up" },
        { label: t5("Disponibles Hoy","Available Today","Disponibles Aujourd'hui","Heute Verfügbar","Disponibili Oggi"), value: "38", change: "+2", trend: "up" },
        { label: t5("Valoración Media","Average Rating","Note Moyenne","Durchschnittsbewertung","Valutazione Media"), value: "4.7/5", change: "+0.1", trend: "up" },
        { label: t5("Horas Impartidas/Mes","Hours Taught/Month","Heures Enseignées/Mois","Unterrichtsstunden/Monat","Ore Impartite/Mese"), value: "1,680", change: "+120", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "avatar" },
          { key: "materias", label: t5("Materias","Subjects","Matières","Fächer","Materie"), type: "text" },
          { key: "tarifa", label: t5("Tarifa/Hora","Rate/Hour","Tarif/Heure","Tarif/Stunde","Tariffa/Ora"), type: "currency" },
          { key: "valoracion", label: t5("Valoración","Rating","Évaluation","Bewertung","Valutazione"), type: "text" },
          { key: "sesiones_mes", label: t5("Sesiones/Mes","Sessions/Month","Sessions/Mois","Sitzungen/Monat","Sessioni/Mese"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Disponible": "green", "Ocupado": "yellow", "Inactivo": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Prof. Álvarez Soto", materias: "Matemáticas, Estadística", tarifa: 35, valoracion: "4.9/5", sesiones_mes: 48, estado: "Disponible" },
          { nombre: "Prof. Williams Park", materias: "Inglés, Francés", tarifa: 30, valoracion: "4.8/5", sesiones_mes: 52, estado: "Ocupado" },
          { nombre: "Prof. Serrano Gil", materias: "Física, Química", tarifa: 32, valoracion: "4.6/5", sesiones_mes: 40, estado: "Disponible" },
          { nombre: "Prof. Castro Reyes", materias: "Programación, Robótica", tarifa: 40, valoracion: "4.7/5", sesiones_mes: 36, estado: "Disponible" },
          { nombre: "Prof. Morales Luna", materias: "Arte, Historia del Arte", tarifa: 28, valoracion: "4.5/5", sesiones_mes: 30, estado: "Inactivo" },
        ],
        searchPlaceholder: t5("Buscar tutores...","Search tutors...","Rechercher des tuteurs...","Tutoren suchen...","Cerca tutor..."),
      },
      modal: {
        title: t5("Nuevo Tutor","New Tutor","Nouveau Tuteur","Neuer Tutor","Nuovo Tutor"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo","Full Name","Nom Complet","Vollständiger Name","Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos","First and last name","Prénom et nom","Vor- und Nachname","Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: "tutor@email.com" },
          { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "materias", label: t5("Materia Principal","Main Subject","Matière Principale","Hauptfach","Materia Principale"), type: "select", required: true, options: [
            { value: "matematicas", label: t5("Matemáticas","Mathematics","Mathématiques","Mathematik","Matematica") },
            { value: "ciencias", label: t5("Ciencias","Sciences","Sciences","Naturwissenschaften","Scienze") },
            { value: "idiomas", label: t5("Idiomas","Languages","Langues","Sprachen","Lingue") },
            { value: "programacion", label: t5("Programación","Programming","Programmation","Programmierung","Programmazione") },
            { value: "arte", label: t5("Arte","Art","Art","Kunst","Arte") },
          ]},
          { name: "tarifa", label: t5("Tarifa por Hora (€)","Hourly Rate (€)","Tarif Horaire (€)","Stundensatz (€)","Tariffa Oraria (€)"), type: "number", required: true, placeholder: "35" },
          { name: "experiencia", label: t5("Años de Experiencia","Years of Experience","Années d'Expérience","Jahre Erfahrung","Anni di Esperienza"), type: "number", required: true, placeholder: "5" },
          { name: "biografia", label: t5("Biografía","Biography","Biographie","Biografie","Biografia"), type: "textarea", required: false, placeholder: t5("Descripción profesional del tutor...","Professional description of the tutor...","Description professionnelle du tuteur...","Professionelle Beschreibung des Tutors...","Descrizione professionale del tutor...") },
        ],
      },
    },
    {
      id: "students",
      label: t5("Estudiantes","Students","Étudiants","Studenten","Studenti"),
      icon: "book",
      kpis: [
        { label: t5("Total Estudiantes","Total Students","Total Étudiants","Studenten Gesamt","Studenti Totali"), value: "480", change: "+35", trend: "up" },
        { label: t5("Nuevos Este Mes","New This Month","Nouveaux Ce Mois","Neu Diesen Monat","Nuovi Questo Mese"), value: "28", change: "+8", trend: "up" },
        { label: t5("Sesiones Promedio","Average Sessions","Sessions Moyennes","Durchschnittliche Sitzungen","Sessioni Medie"), value: t5("4.2/mes","4.2/month","4.2/mois","4.2/Monat","4.2/mese"), change: "+0.3", trend: "up" },
        { label: t5("Retención","Retention","Rétention","Bindung","Ritenzione"), value: "91%", change: "+2%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "avatar" },
          { key: "email", label: "Email", type: "text" },
          { key: "materia", label: t5("Materia","Subject","Matière","Fach","Materia"), type: "text" },
          { key: "tutor_asignado", label: t5("Tutor Asignado","Assigned Tutor","Tuteur Assigné","Zugewiesener Tutor","Tutor Assegnato"), type: "text" },
          { key: "sesiones", label: t5("Sesiones Totales","Total Sessions","Sessions Totales","Sitzungen Gesamt","Sessioni Totali"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activo": "green", "Pausado": "yellow", "Inactivo": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { nombre: "Carlos Mendoza", email: "carlos.m@email.com", materia: "Matemáticas", tutor_asignado: "Prof. Álvarez", sesiones: 24, estado: "Activo" },
          { nombre: "Ana Pérez", email: "ana.p@email.com", materia: "Idiomas", tutor_asignado: "Prof. Williams", sesiones: 18, estado: "Activo" },
          { nombre: "Marta Ruiz", email: "marta.r@email.com", materia: "Ciencias", tutor_asignado: "Prof. Serrano", sesiones: 32, estado: "Activo" },
          { nombre: "Luis García", email: "luis.g@email.com", materia: "Programación", tutor_asignado: "Prof. Castro", sesiones: 12, estado: "Pausado" },
          { nombre: "Sofía Vega", email: "sofia.v@email.com", materia: "Arte", tutor_asignado: "Prof. Morales", sesiones: 8, estado: "Inactivo" },
          { nombre: "Pablo Torres", email: "pablo.t@email.com", materia: "Matemáticas", tutor_asignado: "Prof. Álvarez", sesiones: 40, estado: "Activo" },
        ],
        searchPlaceholder: t5("Buscar estudiantes...","Search students...","Rechercher des étudiants...","Studenten suchen...","Cerca studenti..."),
      },
      modal: {
        title: t5("Nuevo Estudiante","New Student","Nouvel Étudiant","Neuer Student","Nuovo Studente"),
        fields: [
          { name: "nombre", label: t5("Nombre Completo","Full Name","Nom Complet","Vollständiger Name","Nome Completo"), type: "text", required: true, placeholder: t5("Nombre y apellidos","First and last name","Prénom et nom","Vor- und Nachname","Nome e cognome") },
          { name: "email", label: "Email", type: "email", required: true, placeholder: t5("estudiante@email.com","student@email.com","etudiant@email.com","student@email.com","studente@email.com") },
          { name: "telefono", label: t5("Teléfono","Phone","Téléphone","Telefon","Telefono"), type: "tel", required: true, placeholder: "+34 600 000 000" },
          { name: "materia", label: t5("Materia de Interés","Subject of Interest","Matière d'Intérêt","Interessengebiet","Materia di Interesse"), type: "select", required: true, options: [
            { value: "matematicas", label: t5("Matemáticas","Mathematics","Mathématiques","Mathematik","Matematica") },
            { value: "ciencias", label: t5("Ciencias","Sciences","Sciences","Naturwissenschaften","Scienze") },
            { value: "idiomas", label: t5("Idiomas","Languages","Langues","Sprachen","Lingue") },
            { value: "programacion", label: t5("Programación","Programming","Programmation","Programmierung","Programmazione") },
            { value: "arte", label: t5("Arte","Art","Art","Kunst","Arte") },
          ]},
          { name: "nivel", label: t5("Nivel","Level","Niveau","Niveau","Livello"), type: "select", required: true, options: [
            { value: "primaria", label: t5("Primaria","Primary","Primaire","Grundschule","Primaria") },
            { value: "secundaria", label: t5("Secundaria","Secondary","Secondaire","Sekundarstufe","Secondaria") },
            { value: "bachillerato", label: t5("Bachillerato","High School","Lycée","Oberstufe","Liceo") },
            { value: "universidad", label: t5("Universidad","University","Université","Universität","Università") },
            { value: "adulto", label: t5("Adulto","Adult","Adulte","Erwachsener","Adulto") },
          ]},
          { name: "notas", label: t5("Notas Adicionales","Additional Notes","Notes Supplémentaires","Zusätzliche Anmerkungen","Note Aggiuntive"), type: "textarea", required: false, placeholder: t5("Objetivos, necesidades especiales...","Goals, special needs...","Objectifs, besoins spéciaux...","Ziele, besondere Bedürfnisse...","Obiettivi, esigenze speciali...") },
        ],
      },
    },
    {
      id: "sessions",
      label: t5("Sesiones","Sessions","Sessions","Sitzungen","Sessioni"),
      icon: "calendar",
      kpis: [
        { label: t5("Sesiones Hoy","Sessions Today","Sessions Aujourd'hui","Sitzungen Heute","Sessioni Oggi"), value: "18", change: "+3", trend: "up" },
        { label: t5("Completadas Esta Semana","Completed This Week","Terminées Cette Semaine","Diese Woche Abgeschlossen","Completate Questa Settimana"), value: "86", change: "+12", trend: "up" },
        { label: t5("Cancelaciones/Mes","Cancellations/Month","Annulations/Mois","Stornierungen/Monat","Cancellazioni/Mese"), value: "3.2%", change: "-0.5%", trend: "up" },
        { label: t5("Duración Media","Average Duration","Durée Moyenne","Durchschnittliche Dauer","Durata Media"), value: t5("55 min","55 min","55 min","55 Min","55 min"), change: "+2 min", trend: "up" },
      ],
      table: {
        columns: [
          { key: "tutor", label: t5("Tutor","Tutor","Tuteur","Tutor","Tutor"), type: "text" },
          { key: "estudiante", label: t5("Estudiante","Student","Étudiant","Student","Studente"), type: "text" },
          { key: "materia", label: t5("Materia","Subject","Matière","Fach","Materia"), type: "text" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "hora", label: t5("Hora","Time","Heure","Uhrzeit","Ora"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Programada": "blue", "En Curso": "yellow", "Completada": "green", "Cancelada": "red" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { tutor: "Prof. Álvarez", estudiante: "Carlos Mendoza", materia: "Matemáticas", fecha: "2026-03-07", hora: "10:00", estado: "Completada" },
          { tutor: "Prof. Williams", estudiante: "Ana Pérez", materia: "Inglés", fecha: "2026-03-07", hora: "14:00", estado: "Programada" },
          { tutor: "Prof. Serrano", estudiante: "Marta Ruiz", materia: "Física", fecha: "2026-03-07", hora: "16:00", estado: "En Curso" },
          { tutor: "Prof. Castro", estudiante: "Luis García", materia: "Programación", fecha: "2026-03-07", hora: "11:00", estado: "Cancelada" },
          { tutor: "Prof. Álvarez", estudiante: "Pablo Torres", materia: "Matemáticas", fecha: "2026-03-08", hora: "09:00", estado: "Programada" },
        ],
        searchPlaceholder: t5("Buscar sesiones...","Search sessions...","Rechercher des sessions...","Sitzungen suchen...","Cerca sessioni..."),
      },
      modal: {
        title: t5("Nueva Sesión","New Session","Nouvelle Session","Neue Sitzung","Nuova Sessione"),
        fields: [
          { name: "tutor", label: t5("Tutor","Tutor","Tuteur","Tutor","Tutor"), type: "select", required: true, options: [
            { value: "alvarez", label: "Prof. Álvarez Soto" },
            { value: "williams", label: "Prof. Williams Park" },
            { value: "serrano", label: "Prof. Serrano Gil" },
            { value: "castro", label: "Prof. Castro Reyes" },
            { value: "morales", label: "Prof. Morales Luna" },
          ]},
          { name: "estudiante", label: t5("Estudiante","Student","Étudiant","Student","Studente"), type: "text", required: true, placeholder: t5("Nombre del estudiante","Student name","Nom de l'étudiant","Name des Studenten","Nome dello studente") },
          { name: "materia", label: t5("Materia","Subject","Matière","Fach","Materia"), type: "select", required: true, options: [
            { value: "matematicas", label: t5("Matemáticas","Mathematics","Mathématiques","Mathematik","Matematica") },
            { value: "ciencias", label: t5("Ciencias","Sciences","Sciences","Naturwissenschaften","Scienze") },
            { value: "idiomas", label: t5("Idiomas","Languages","Langues","Sprachen","Lingue") },
            { value: "programacion", label: t5("Programación","Programming","Programmation","Programmierung","Programmazione") },
            { value: "arte", label: t5("Arte","Art","Art","Kunst","Arte") },
          ]},
          { name: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date", required: true },
          { name: "hora", label: t5("Hora","Time","Heure","Uhrzeit","Ora"), type: "time", required: true },
          { name: "duracion", label: t5("Duración (minutos)","Duration (minutes)","Durée (minutes)","Dauer (Minuten)","Durata (minuti)"), type: "number", required: true, placeholder: "60" },
          { name: "notas", label: t5("Notas","Notes","Notes","Notizen","Note"), type: "textarea", required: false, placeholder: t5("Temas a cubrir en la sesión...","Topics to cover in the session...","Sujets à couvrir dans la session...","Themen für die Sitzung...","Argomenti da trattare nella sessione...") },
        ],
      },
      tabs: [
        { id: "todas", label: t5("Todas","All","Toutes","Alle","Tutte"), filterField: "estado", filterValue: "" },
        { id: "programadas", label: t5("Programadas","Scheduled","Programmées","Geplant","Programmate"), filterField: "estado", filterValue: "Programada" },
        { id: "en_curso", label: t5("En Curso","In Progress","En Cours","Laufend","In Corso"), filterField: "estado", filterValue: "En Curso" },
        { id: "completadas", label: t5("Completadas","Completed","Terminées","Abgeschlossen","Completate"), filterField: "estado", filterValue: "Completada" },
        { id: "canceladas", label: t5("Canceladas","Cancelled","Annulées","Storniert","Cancellate"), filterField: "estado", filterValue: "Cancelada" },
      ],
    },
    {
      id: "scheduling",
      label: t5("Horarios","Schedules","Horaires","Stundenpläne","Orari"),
      icon: "clock",
      kpis: [
        { label: t5("Horas Programadas/Semana","Scheduled Hours/Week","Heures Programmées/Semaine","Geplante Stunden/Woche","Ore Programmate/Settimana"), value: "420", change: "+30", trend: "up" },
        { label: t5("Ocupación Tutores","Tutor Occupancy","Occupation des Tuteurs","Tutoren-Auslastung","Occupazione Tutor"), value: "78%", change: "+5%", trend: "up" },
        { label: t5("Slots Disponibles Hoy","Available Slots Today","Créneaux Disponibles Aujourd'hui","Heute Verfügbare Slots","Slot Disponibili Oggi"), value: "24", change: "-8", trend: "down" },
        { label: t5("Conflictos de Horario","Schedule Conflicts","Conflits d'Horaire","Terminkonflikt","Conflitti di Orario"), value: "2", change: "-1", trend: "up" },
      ],
      table: {
        columns: [
          { key: "tutor", label: t5("Tutor","Tutor","Tuteur","Tutor","Tutor"), type: "text" },
          { key: "dia", label: t5("Día","Day","Jour","Tag","Giorno"), type: "text" },
          { key: "hora_inicio", label: t5("Hora Inicio","Start Time","Heure Début","Startzeit","Ora Inizio"), type: "text" },
          { key: "hora_fin", label: t5("Hora Fin","End Time","Heure Fin","Endzeit","Ora Fine"), type: "text" },
          { key: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "badge", badgeColors: { "Regular": "green", "Puntual": "blue", "Bloqueo": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { tutor: "Prof. Álvarez", dia: "Lunes", hora_inicio: "09:00", hora_fin: "14:00", tipo: "Regular" },
          { tutor: "Prof. Williams", dia: "Martes", hora_inicio: "10:00", hora_fin: "18:00", tipo: "Regular" },
          { tutor: "Prof. Serrano", dia: "Miércoles", hora_inicio: "15:00", hora_fin: "20:00", tipo: "Regular" },
          { tutor: "Prof. Castro", dia: "Jueves", hora_inicio: "09:00", hora_fin: "13:00", tipo: "Regular" },
          { tutor: "Prof. Álvarez", dia: "Sábado", hora_inicio: "10:00", hora_fin: "13:00", tipo: "Puntual" },
        ],
        searchPlaceholder: t5("Buscar horarios...","Search schedules...","Rechercher des horaires...","Stundenpläne suchen...","Cerca orari..."),
      },
      modal: {
        title: t5("Nuevo Horario","New Schedule","Nouvel Horaire","Neuer Stundenplan","Nuovo Orario"),
        fields: [
          { name: "tutor", label: t5("Tutor","Tutor","Tuteur","Tutor","Tutor"), type: "select", required: true, options: [
            { value: "alvarez", label: "Prof. Álvarez Soto" },
            { value: "williams", label: "Prof. Williams Park" },
            { value: "serrano", label: "Prof. Serrano Gil" },
            { value: "castro", label: "Prof. Castro Reyes" },
            { value: "morales", label: "Prof. Morales Luna" },
          ]},
          { name: "dia", label: t5("Día de la Semana","Day of the Week","Jour de la Semaine","Wochentag","Giorno della Settimana"), type: "select", required: true, options: [
            { value: "lunes", label: t5("Lunes","Monday","Lundi","Montag","Lunedì") },
            { value: "martes", label: t5("Martes","Tuesday","Mardi","Dienstag","Martedì") },
            { value: "miercoles", label: t5("Miércoles","Wednesday","Mercredi","Mittwoch","Mercoledì") },
            { value: "jueves", label: t5("Jueves","Thursday","Jeudi","Donnerstag","Giovedì") },
            { value: "viernes", label: t5("Viernes","Friday","Vendredi","Freitag","Venerdì") },
            { value: "sabado", label: t5("Sábado","Saturday","Samedi","Samstag","Sabato") },
          ]},
          { name: "hora_inicio", label: t5("Hora de Inicio","Start Time","Heure de Début","Startzeit","Ora di Inizio"), type: "time", required: true },
          { name: "hora_fin", label: t5("Hora de Fin","End Time","Heure de Fin","Endzeit","Ora di Fine"), type: "time", required: true },
          { name: "tipo", label: t5("Tipo","Type","Type","Typ","Tipo"), type: "select", required: true, options: [
            { value: "regular", label: "Regular" },
            { value: "puntual", label: t5("Puntual","One-time","Ponctuel","Einmalig","Occasionale") },
            { value: "bloqueo", label: t5("Bloqueo","Block","Blocage","Blockierung","Blocco") },
          ]},
        ],
      },
    },
    {
      id: "payments",
      label: t5("Pagos","Payments","Paiements","Zahlungen","Pagamenti"),
      icon: "dollar",
      kpis: [
        { label: t5("Ingresos del Mes","Monthly Revenue","Revenus du Mois","Monatsumsatz","Entrate del Mese"), value: "€24,600", change: "+15%", trend: "up" },
        { label: t5("Pagos Pendientes","Pending Payments","Paiements en Attente","Ausstehende Zahlungen","Pagamenti in Sospeso"), value: "€3,200", change: "-€500", trend: "up" },
        { label: t5("Pagos a Tutores","Tutor Payments","Paiements aux Tuteurs","Zahlungen an Tutoren","Pagamenti ai Tutor"), value: "€16,800", change: "+€1,200", trend: "up" },
        { label: t5("Margen Neto","Net Margin","Marge Nette","Nettomarge","Margine Netto"), value: "31.7%", change: "+1.2%", trend: "up" },
      ],
      table: {
        columns: [
          { key: "estudiante", label: t5("Estudiante","Student","Étudiant","Student","Studente"), type: "text" },
          { key: "concepto", label: t5("Concepto","Concept","Concept","Konzept","Concetto"), type: "text" },
          { key: "monto", label: t5("Monto","Amount","Montant","Betrag","Importo"), type: "currency" },
          { key: "fecha", label: t5("Fecha","Date","Date","Datum","Data"), type: "date" },
          { key: "metodo", label: t5("Método","Method","Méthode","Methode","Metodo"), type: "text" },
          { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Pagado": "green", "Pendiente": "yellow", "Vencido": "red", "Reembolsado": "gray" } },
          { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
        ],
        rows: [
          { estudiante: "Carlos Mendoza", concepto: "Pack 8 sesiones - Matemáticas", monto: 280, fecha: "2026-03-05", metodo: "Tarjeta", estado: "Pagado" },
          { estudiante: "Ana Pérez", concepto: "Pack 4 sesiones - Inglés", monto: 120, fecha: "2026-03-04", metodo: "Transferencia", estado: "Pagado" },
          { estudiante: "Marta Ruiz", concepto: "Sesión individual - Física", monto: 32, fecha: "2026-03-07", metodo: "Tarjeta", estado: "Pendiente" },
          { estudiante: "Luis García", concepto: "Pack 8 sesiones - Programación", monto: 320, fecha: "2026-02-28", metodo: "Domiciliación", estado: "Vencido" },
          { estudiante: "Pablo Torres", concepto: "Pack 12 sesiones - Matemáticas", monto: 396, fecha: "2026-03-01", metodo: "Tarjeta", estado: "Pagado" },
        ],
        searchPlaceholder: t5("Buscar pagos...","Search payments...","Rechercher des paiements...","Zahlungen suchen...","Cerca pagamenti..."),
      },
      modal: {
        title: t5("Registrar Pago","Record Payment","Enregistrer un Paiement","Zahlung Erfassen","Registra Pagamento"),
        fields: [
          { name: "estudiante", label: t5("Estudiante","Student","Étudiant","Student","Studente"), type: "text", required: true, placeholder: t5("Nombre del estudiante","Student name","Nom de l'étudiant","Name des Studenten","Nome dello studente") },
          { name: "concepto", label: t5("Concepto","Concept","Concept","Konzept","Concetto"), type: "text", required: true, placeholder: t5("Pack 8 sesiones - Materia","8-session pack - Subject","Pack 8 sessions - Matière","8-Sitzungen-Paket - Fach","Pack 8 sessioni - Materia") },
          { name: "monto", label: t5("Monto (€)","Amount (€)","Montant (€)","Betrag (€)","Importo (€)"), type: "number", required: true, placeholder: "280" },
          { name: "metodo", label: t5("Método de Pago","Payment Method","Méthode de Paiement","Zahlungsmethode","Metodo di Pagamento"), type: "select", required: true, options: [
            { value: "tarjeta", label: t5("Tarjeta","Card","Carte","Karte","Carta") },
            { value: "transferencia", label: t5("Transferencia","Transfer","Virement","Überweisung","Bonifico") },
            { value: "domiciliacion", label: t5("Domiciliación","Direct Debit","Prélèvement","Lastschrift","Addebito Diretto") },
            { value: "efectivo", label: t5("Efectivo","Cash","Espèces","Bargeld","Contanti") },
          ]},
          { name: "fecha", label: t5("Fecha de Pago","Payment Date","Date de Paiement","Zahlungsdatum","Data di Pagamento"), type: "date", required: true },
        ],
      },
      tabs: [
        { id: "todos", label: t5("Todos","All","Tous","Alle","Tutti"), filterField: "estado", filterValue: "" },
        { id: "pagados", label: t5("Pagados","Paid","Payés","Bezahlt","Pagati"), filterField: "estado", filterValue: "Pagado" },
        { id: "pendientes", label: t5("Pendientes","Pending","En Attente","Ausstehend","In Sospeso"), filterField: "estado", filterValue: "Pendiente" },
        { id: "vencidos", label: t5("Vencidos","Overdue","Échus","Überfällig","Scaduti"), filterField: "estado", filterValue: "Vencido" },
      ],
    },
  ],
  superAdmin: {
    modules: [
      {
        id: "tenants",
        label: t5("Academias","Academies","Académies","Akademien","Accademie"),
        icon: "building",
        kpis: [
          { label: t5("Total Academias","Total Academies","Total Académies","Akademien Gesamt","Accademie Totali"), value: "32", change: "+5", trend: "up" },
          { label: t5("Activas","Active","Actives","Aktiv","Attive"), value: "28", change: "+4", trend: "up" },
          { label: t5("Tutores Totales","Total Tutors","Total Tuteurs","Tutoren Gesamt","Tutor Totali"), value: "1,792", change: "+224", trend: "up" },
          { label: "MRR", value: "€18,200", change: "+€2,400", trend: "up" },
        ],
        table: {
          columns: [
            { key: "nombre", label: t5("Academia","Academy","Académie","Akademie","Accademia"), type: "text" },
            { key: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "badge", badgeColors: { "Premium": "purple", "Estándar": "blue", "Básico": "gray" } },
            { key: "tutores", label: t5("Tutores","Tutors","Tuteurs","Tutoren","Tutor"), type: "text" },
            { key: "estudiantes", label: t5("Estudiantes","Students","Étudiants","Studenten","Studenti"), type: "text" },
            { key: "estado", label: t5("Estado","Status","Statut","Status","Stato"), type: "badge", badgeColors: { "Activa": "green", "Suspendida": "red", "Trial": "yellow" } },
            { key: "acciones", label: t5("Acciones","Actions","Actions","Aktionen","Azioni"), type: "actions" },
          ],
          rows: [
            { nombre: "Tutorías Excelencia", plan: "Premium", tutores: 120, estudiantes: 1800, estado: "Activa" },
            { nombre: "AcademiaPlus", plan: "Estándar", tutores: 45, estudiantes: 620, estado: "Activa" },
            { nombre: "SmartLearn", plan: "Estándar", tutores: 30, estudiantes: 380, estado: "Activa" },
            { nombre: "MiTutor Online", plan: "Básico", tutores: 12, estudiantes: 85, estado: "Trial" },
            { nombre: "EduConnect Pro", plan: "Premium", tutores: 80, estudiantes: 1200, estado: "Activa" },
          ],
          searchPlaceholder: t5("Buscar academias...","Search academies...","Rechercher des académies...","Akademien suchen...","Cerca accademie..."),
        },
        modal: {
          title: t5("Nueva Academia","New Academy","Nouvelle Académie","Neue Akademie","Nuova Accademia"),
          fields: [
            { name: "nombre", label: t5("Nombre","Name","Nom","Name","Nome"), type: "text", required: true, placeholder: t5("Nombre de la academia","Academy name","Nom de l'académie","Name der Akademie","Nome dell'accademia") },
            { name: "email_admin", label: "Email Admin", type: "email", required: true, placeholder: t5("admin@academia.com","admin@academy.com","admin@academie.com","admin@akademie.com","admin@accademia.com") },
            { name: "plan", label: t5("Plan","Plan","Plan","Plan","Piano"), type: "select", required: true, options: [
              { value: "basico", label: t5("Básico","Basic","Basique","Basis","Base") },
              { value: "estandar", label: t5("Estándar","Standard","Standard","Standard","Standard") },
              { value: "premium", label: "Premium" },
            ]},
            { name: "max_tutores", label: t5("Máx. Tutores","Max. Tutors","Max. Tuteurs","Max. Tutoren","Max. Tutor"), type: "number", required: true, placeholder: "50" },
          ],
        },
      },
    ],
  },
};
